---
sidebar: sidebar 
permalink: hu-aix-70.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap 
summary: 'Les utilitaires d"hôtes unifiés AIX vous aident à gérer le stockage NetApp ONTAP connecté à un hôte AIX.' 
---
= Installez AIX Host Utilities 7.0
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les utilitaires d'hôtes unifiés AIX vous aident à gérer le stockage NetApp ONTAP connecté à un hôte AIX.

Les utilitaires hôtes AIX prennent en charge les protocoles suivants :

* FC
* FCoE
* ISCSI


Les utilitaires hôtes AIX prennent en charge les environnements suivants :

* MPIO AIX (SYSTÈME D'EXPLOITATION NATIF)
* PowerVM
+
Pour plus d'informations sur PowerVM, consultez le livre rouge IBM PowerVM Live partition Mobility.



.Avant de commencer
* Pour un fonctionnement fiable, vérifiez que l'ensemble de votre configuration iSCSI, FC ou FCoE est pris en charge.
+
Vous pouvez utiliser le https://mysupport.netapp.com/matrix/imt.jsp?components=65623%3B64703%3B&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] pour vérifier votre configuration.

* Le suivi dynamique doit être activé pour tous les initiateurs FC et FCoE.



NOTE: Le progiciel Utilitaires hôtes AIX NetApp est disponible sur le link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["Site de support NetApp"^] dans un fichier tar.gz compressé. Vous devez installer le kit d'utilitaires hôtes AIX lors de l'utilisation de MPIO AIX avec le stockage NetApp ONTAP.

.Étapes
. Connectez-vous à votre hôte.
+
** Sur un hôte AIX, connectez-vous en tant que *root*.
** Sur un hôte PowerVM, connectez-vous en tant que *padmin*, puis entrez la `oem_setup_env` commande pour devenir un utilisateur root.


. Accédez au https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["Site de support NetApp"^] et téléchargez le fichier compressé contenant les utilitaires hôtes dans un répertoire de votre hôte.
. Accédez au répertoire contenant le téléchargement.
. Décompresser le fichier et extraire le progiciel SAN Toolkit :
+
`# tar -xvf ntap_aix_host_utilities_7.0.tar.gz`

+
Le répertoire suivant est créé lorsque vous décompressez le fichier : `ntap_aix_host_utilities_7.0`. Ce répertoire contient l'un des sous-répertoires suivants : MPIO, NON_MPIO ou SAN_Tool_Kit.

. Installez AIX MPIO :
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Installez le kit d'outils SAN :
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit`

. Redémarrez l'hôte.
. Vérifiez l'installation :
+
`# lslpp -l |grep -i netapp`

+
[listing]
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----
. Vérifiez la version du logiciel :
+
`# sanlun version`

+
[listing]
----
7.0.725.3521
----
. Vérifiez que le `lbp_enabled` paramètre SCSI UNMAP est ajouté au gestionnaire de données d'objet en exécutant les commandes suivantes :
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"`

+
[listing]
----
attribute = "lbp_enabled"
----
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`

+
[listing]
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----




== Kit D'outils SAN

Utilitaires hôtes AIX est un logiciel hôte NetApp qui fournit un kit d'outils de ligne de commande sur votre hôte IBM AIX. Le kit d'outils est installé lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les adaptateurs de bus hôte (HBA). Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

*Exemple*

Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
# sanlun lun show all
----
*Exemple de sortie*

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Ce kit d'outils est commun à toutes les configurations et tous les protocoles des utilitaires hôtes. En conséquence, une partie de son contenu s'applique à une configuration, mais pas à une autre. Le fait d'utiliser des composants non utilisés n'affecte pas les performances de votre système. Le kit SAN est pris en charge sur les versions AIX et PowerVM/VIOS.
