---
sidebar: sidebar 
permalink: hu-luhu-release-notes.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: Notes de publication pour les utilitaires hôtes Linux 
---
= Notes de publication des utilitaires hôtes Linux
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les notes de version décrivent les nouvelles fonctionnalités, les améliorations, les problèmes résolus, les problèmes connus, les limitations et les précautions importantes pour la configuration et la gestion de votre hôte spécifique avec votre système de stockage ONTAP .

Pour obtenir des informations spécifiques sur les versions et les mises à jour du système d'exploitation prises en charge par les utilitaires hôtes, reportez-vous au link:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^].



== Nouveautés de Linux Host Utilities 8.0

La version 8.0 de Linux Host Utilities contient les nouvelles fonctionnalités et améliorations suivantes

Linux Host Utilities 8.0 inclut la prise en charge des adaptateurs de bus hôte (HBA) QLogic et Emulex FC à vitesse 64 bits.

Les systèmes d’exploitation suivants sont pris en charge :

* Red Hat Enterprise Linux (RHEL) séries 9 et 8
* SUSE Linux Enterprise Server
* Oracle Linux séries 9 et 8
* Ubuntu




== Nouveautés de Linux Host Utilities 7.1

La version 7.1 de Linux Host Utilities contient les nouvelles fonctionnalités et améliorations suivantes :

* Les utilitaires d'hôtes Linux sont désormais appelés _utilitaires d'hôtes unifiés Linux_ car ils prennent en charge les systèmes de stockage NetApp E-Series exécutant SANtricity ainsi que les systèmes AFF, FAS et ASA exécutant ONTAP.
* Les systèmes d’exploitation suivants sont pris en charge :
+
** Citrix XenServer
** KVM et XEN, RHEV 6.5 et 6.4
** Oracle VM série 3.2
** Oracle Linux séries 7 et 6
** Séries RHEL 7 et 6
** SUSE Linux Enterprise Server série 15
** SUSE Linux Enterprise Server 11 SP4


* Sur les hôtes RHEL 6 et 7, un package optimisé pour la définition des profils de serveur est désormais pris en charge.  Vous pouvez utiliser le `tuned-adm` commande permettant de définir différents profils, en fonction de l'environnement.  Par exemple, vous pouvez utiliser le profil d'invité virtuel comme machine virtuelle invitée et le profil de stockage d'entreprise pour les configurations lorsque des LUN provenant de baies de stockage d'entreprise sont utilisés.  L’utilisation de ces packages optimisés peut entraîner une amélioration du débit et de la latence dans ONTAP.
* Linux Host Utilities 7.1 ajoute la prise en charge des adaptateurs FC 32 Go de Broadcom Emulex et Marvell Qlogic.



NOTE: NetApp continue de travailler avec les utilitaires hôtes Linux pour ajouter la prise en charge des fonctionnalités après la version initiale.  Pour obtenir les dernières informations sur les fonctionnalités prises en charge et les nouvelles fonctionnalités ajoutées, consultez lelink:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] .



== Problèmes résolus

Les problèmes suivants ont été résolus dans Linux Host Utilities.

[cols="20, 80"]
|===
| Corrigé dans la version | Description 


| 7.1 | Le problème de défaillance intermittente du système d'exploitation hôte qui se produit lors de l'exécution du `sanlun lun show -p` commande dans SUSE Linux Enterprise Server 12 SP1, Oracle Linux 7.2, RHEL 7.2 et RHEL 6.8. 
|===


== Problèmes connus et limitations

Vous devez être conscient des problèmes et limitations connus suivants qui pourraient avoir un impact sur les performances de votre hôte spécifique :

[cols="15, 15, 30, 40"]
|===
| ID de bug NetApp | Affecte la version | Titre | Description 


| 1457017 | 7.1 |  `sanlun` problèmes d'installation messages d'avertissement relatifs à `libdevmapper.so` et `libnl.so` bibliothèques. Ces avertissements n'affectent pas la fonctionnalité de `sanlun` kit. | Lorsque vous exécutez la commande CLI Linux Host Utilities - « sanlun fcp show adapter -v » sur un hôte SAN, la commande échoue avec un message d'erreur indiquant que les dépendances de bibliothèque requises pour la découverte d'un adaptateur de bus hôte HBA ne peuvent pas être localisées :
`[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded` Consultez les bugs NetApp en ligne -link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^] . 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp bogues en ligne"^] fournit des informations complètes pour la plupart des problèmes connus, y compris des solutions de contournement suggérées si possible.



== Quelle est la prochaine étape

link:hu-luhu-80.html["En savoir plus sur l'installation des utilitaires hôtes Linux"]
