---
sidebar: sidebar 
permalink: hu-ol-810.html 
keywords: host utilities, oracle, linux, 8.10, netapp, ontap 
summary: Décrit comment utiliser Oracle Linux 8.10 avec ONTAP 
---
= Utilisez Oracle Linux 8.10 avec ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser les paramètres de configuration de l'hôte SAN ONTAP pour configurer Oracle Linux 8.10 avec ONTAP comme cible.



== Installez Linux Unified Host Utilities

Vous pouvez télécharger le progiciel Utilitaires hôtes unifiés NetApp Linux sous la forme d'un fichier 64-bit.rpm à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^].

NetApp recommande vivement d'installer les utilitaires d'hôtes unifiés Linux, mais ce n'est pas obligatoire. Les utilitaires ne modifient aucun paramètre sur votre hôte Linux. Ces utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

.Étapes
. Téléchargez le pack logiciel Linux Unified Host Utilities 64 bits à partir du https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] à votre hôte.
. Installez le pack logiciel :
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== Kit SAN

Le kit d'outils est installé automatiquement lorsque vous installez le progiciel Utilitaires hôtes NetApp. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les adaptateurs de bus hôte (HBA). Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
# sanlun lun show all
----
.Exemple de résultat :
[listing]
----
controller(7mode/E-Series)/              device     host               lun
vserver(cDOT/FlashRay)  lun-pathname     filename   adapter  protocol  size   Product
-------------------------------------------------------------------------------------
data_vserver            /vol/vol1/lun1   /dev/sdb   host16   FCP       80.0g  cDOT
data_vserver            /vol/vol1/lun1   /dev/sdc   host15   FCP       80.0g  cDOT
data_vserver            /vol/vol2/lun2   /dev/sdd   host16   FCP       80.0g  cDOT
data_vserver            /vol/vol2/lun2   /dev/sde   host15   FCP       80.0g  cDOT
----


== Activez le démarrage SAN

Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration.

.Avant de commencer
Utilisez le link:https://mysupport.netapp.com/matrix/imt.jsp?components=91863;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] pour vérifier que votre système d'exploitation, votre adaptateur HBA, le micrologiciel de l'adaptateur HBA, le BIOS de démarrage de l'adaptateur HBA et la version de ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+

NOTE: Plusieurs chemins deviennent disponibles une fois que le système d'exploitation hôte est opérationnel sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage a réussi.




== Chemins d'accès multiples

Pour Oracle Linux 8.10, le `/etc/multipath.conf` fichier doit exister. Vous n'avez pas besoin d'apporter de modifications à ce fichier car Oracle Linux 8.10 est compilé avec les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP.

Pour toutes les configurations de baies SAN (ASA) et non-ASA, vous pouvez utiliser la `multipath -ll` commande pour vérifier les paramètres d'une LUN ONTAP, comme indiqué dans les exemples suivants.


NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. Plus de huit chemins peuvent entraîner des problèmes de chemin lors des défaillances du stockage.



=== Configurations ASA

Dans les configurations ASA, tous les chemins vers une LUN donnée sont actifs et optimisés. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

L'exemple suivant montre la sortie correcte pour une LUN ONTAP mappée à un rôle ASA :

[listing]
----
# multipath -ll
3600a098038314d79492b58306a727a6a dm-0 NETAPP,LUN C-Mode
size=180G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6  sdbz 68:208  active ready running
  |- 11:0:11:6 sddn 71:80   active ready running
  |- 11:0:15:6 sdfb 129:208 active ready running
  |- 12:0:1:6  sdgp 132:80  active ready running
----


=== Configurations non ASA

Pour les configurations non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont Active/Optimized (actif/optimisé), ce qui signifie que les services sont gérés par le contrôleur où se trouve l'agrégat. Les chemins aux priorités inférieures sont actifs, mais ne sont pas optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

L'exemple ci-dessous présente le résultat correct pour une LUN ONTAP avec deux chemins Active/Optimized et deux chemins Active/non optimisés mappés à un rôle non-ASA :

[listing]
----
# multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb	69:624	active ready running
| |- 16:0:5:35 sdun	66:752	active ready running
`-+- policy='service-time 0' prio=10 status=enabled
|- 15:0:0:35 sdaj	66:48	active ready running
|- 15:0:1:35 sdbx	68:176	active ready running
----


== Paramètres recommandés

Le système d'exploitation Oracle Linux 8.10 est compilé pour reconnaître les LUN ONTAP et définir automatiquement les paramètres de configuration corrects pour les configurations ASA et non ASA. En outre, vous pouvez utiliser les recommandations suivantes pour optimiser davantage les performances de votre configuration hôte :

Le `multipath.conf` fichier doit exister pour que le démon multichemin puisse démarrer. Si ce fichier n'existe pas, vous pouvez créer un fichier vide de zéro octet à l'aide de la `touch /etc/multipath.conf` commande.

Lors de la première création du `multipath.conf` fichier, vous devrez peut-être activer et démarrer les services multivoies en utilisant les commandes suivantes :

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
Vous n'avez pas besoin d'ajouter des éléments directement au `multipath.conf` fichier, sauf si vous avez des périphériques que vous ne souhaitez pas gérer le multipathing ou si vous avez des paramètres existants qui remplacent les paramètres par défaut. Pour exclure les périphériques indésirables, ajoutez la syntaxe suivante au `multipath.conf` fichier, en remplaçant <DevId> par la chaîne d'identifiant universel (WWID) du périphérique à exclure :

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
L'exemple suivant détermine le WWID d'un périphérique et l'ajoute au `multipath.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
/lib/udev/scsi_id -gud /dev/sda
----
+
360030057024d0730239134810c0cb833



[listing]
----
+
`sda` is the local SCSI disk that you want to add to the blacklist.

. Add the `WWID` to the blacklist stanza in `/etc/multipath.conf`:
[source,cli]
+
----
liste noire { wwid 3600a098038314c4a433f5774717a3046 devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*" devnode "^hd[a-z]" devnode "^cciss. }

[listing]
----

Always check your `/etc/multipath.conf` file, especially in the defaults section, for legacy settings that might be overriding default settings.

The following table demonstrates the critical `multipathd` parameters for ONTAP LUNs and the required values. If a host is connected to LUNs from other vendors and any of these parameters are overridden, they must be corrected by later stanzas in the `multipath.conf` file that apply specifically to ONTAP LUNs. Without this correction, the ONTAP LUNs might not work as expected. You should only override these defaults in consultation with NetApp, the OS vendor, or both, and only when the impact is fully understood.

//ONTAPDOC-2578 9-Dec-2024
//ONTAPDOC-2561 25-Nov-202

[cols=2*,options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | infinity
| failback | immediate
| fast_io_fail_tmo | 5
| features | 2 pg_init_retries 50
| flush_on_last_del | yes
| hardware_handler | 0
| no_path_retry | queue
| path_checker | tur
| path_grouping_policy | group_by_prio
| path_selector | service-time 0
| polling_interval | 5
| prio | ontap
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | uniform
| user_friendly_names | no
| vendor | NETAPP
|===

The following example demonstrates how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that aren't compatible with ONTAP LUNs. If they cannot be removed because other SAN arrays are still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

----
Valeurs par défaut { path_Checker readsector0 no_path_retry fail } périphériques { device { vendor "NetApp" produit "LUN.*" no_path_retry file path_Checker tur }

[listing]
----

NOTE: To configure Oracle Linux 8.10 RedHat Enterprise Kernel, use the link:hu_rhel_810.html#recommended-settings[recommended settings] for Red Hat Enterprise Linux (RHEL) 8.10.

== KVM settings
You can also use the <<recommended_settings_ol_810,recommended settings>> to configure a Kernel-based Virtual Machine (KVM). There are no changes required to configure a KVM because the LUN is mapped to the hypervisor.

== Known issues
There are no known issues for the Oracle Linux 8.10 with ONTAP release.
----