---
sidebar: sidebar 
permalink: hu-veritas-8x.html 
keywords: host utilities, veritas, infoscale, 8, netapp, ontap, sanhost, iscsi, red, hat linux, oracle, linux 
summary: Utilisez les utilitaires hôtes Linux avec Veritas Infoscale 8 pour les hôtes RHEL et Oracle Linux pour vous aider à gérer les opérations de protocole FC, FCoE et iSCSI avec les LUN ONTAP . 
---
= Configurer Veritas Infoscale 8 pour FC, FCoE et iSCSI avec stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le logiciel Linux Host Utilities fournit des outils de gestion et de diagnostic pour les hôtes Linux connectés au stockage ONTAP . Utilisez les utilitaires hôtes Linux avec Veritas Infoscale 8 pour les hôtes Oracle Linux (basé sur un noyau compatible Red Hat), Red Hat Enterprise Linux (RHEL) et SUSE Linux Enterprise Server pour prendre en charge la gestion des opérations de protocole FC, FCoE et iSCSI avec les LUN ONTAP .



== Étape 1 : activez éventuellement le démarrage SAN

Vous pouvez configurer votre hôte pour qu'il utilise le démarrage SAN afin de simplifier le déploiement et d'améliorer l'évolutivité.

.Avant de commencer
* Utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.
* Consultez le portail d'assistance Veritas (matrice des produits, recherche de plateforme et matrice HCL) pour vérifier la prise en charge de la configuration de démarrage SAN et les problèmes connus.


.Étapes
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Créez un LUN de démarrage SAN et mappez-le à l'hôte"^].
. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Vérifiez que la configuration a réussi en redémarrant l'hôte et en vérifiant que le système d'exploitation est opérationnel.




== Étape 2 : installez les utilitaires hôtes Linux

NetApp recommande fortement link:hu-luhu-release-notes.html["installation des utilitaires hôtes Linux"] pour assurer la gestion des LUN ONTAP et aider le support technique à collecter les données de configuration.


NOTE: L'installation des utilitaires d'hôtes Linux ne modifie aucun paramètre de délai d'expiration de l'hôte sur votre hôte Linux.



== Étape 3 : Vérifiez la configuration Veritas Dynamic Multipathing pour votre hôte

Utilisez Veritas Dynamic Multipathing (VxDMP) avec Veritas Infoscale 8 pour gérer les LUN ONTAP .

Pour garantir que VxDMP est correctement configuré pour votre hôte, vous devez vérifier la configuration de VxDMP et contrôler la configuration de la bibliothèque de support de baie (ASL) et du module de stratégie de baie (APM). Les packages ASL et APM pour les systèmes de stockage NetApp sont installés lors de l'installation du logiciel Veritas.


NOTE: Pour les environnements multipath hétérogènes, notamment Veritas Infoscale, Linux Native Device Mapper et LVM Volume Manager, reportez-vous à la documentation d'administration des produits Veritas pour connaître les paramètres de configuration.

.Avant de commencer
Assurez-vous que votre configuration répond aux exigences du système. Voir le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] et la matrice Veritas HCL.

.Étapes
. Vérifiez que la baie cible ONTAP est connectée au chemin multiple VxDMP :
+
[source, cli]
----
vxdmpadm
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
====
. Vérifiez la configuration des packages ASL et APM. NetApp vous recommande d'utiliser les derniers packages pris en charge répertoriés sur le portail de support Veritas.
+
.Afficher un exemple de configuration ASL et APM
[%collapsible]
====
[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so                  vm-8.0.0-rev-1   8.0

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----
====
. Pour une configuration système optimale lors des opérations de basculement de stockage, vérifiez que vous disposez des paramètres réglables Veritas VxDMP suivants :
+
[cols="2*"]
|===
| Paramètre | Réglage 


| dmp_lun_retry_timeout | 60 


| chemin_dmp_age | 120 


| intervalle_restauration_dmp | 60 
|===
. Configurez les paramètres DMP en ligne :
+
[source, cli]
----
# vxdmpadm settune dmp_tunable=value
----
. Vérifiez que les paramètres réglables sont correctement configurés :
+
[source, cli]
----
# vxdmpadm gettune
----
+
L'exemple suivant illustre les paramètres VxDMP effectifs sur un hôte SAN.

+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----
====
. Configurer les valeurs de délai d'expiration du protocole :
+
[role="tabbed-block"]
====
.FC/FCoE
--
Utilisez les valeurs de délai d'attente par défaut pour FC et FCoE.

--
.iSCSI
--
Réglez le `replacement_timeout` valeur du paramètre à 120.

iSCSI `replacement_timeout` Ce paramètre détermine combien de temps la couche iSCSI doit attendre qu'un chemin ou une session ayant expiré se rétablisse avant d'annuler toute commande qui lui est adressée. NetApp recommande de définir la valeur de `replacement_timeout` à 120 dans le fichier de configuration iSCSI.

.Exemple
[listing]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----
--
====
. Configurez les valeurs « udev rport » de l'hôte pour les hôtes des séries RHEL 8 et 9 afin de prendre en charge l'environnement Veritas Infoscale dans les scénarios de basculement de stockage.
+
Configurez les valeurs « udev rport » en créant le fichier `/etc/udev/rules.d/40-rport.rules` avec le contenu de fichier suivant :

+
[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----
+

NOTE: Pour tous les autres paramètres spécifiques à Veritas, veuillez vous référer à la documentation produit standard Veritas Infoscale.

. Vérifiez les paramètres et l'état du chemin de vos LUN ONTAP :
+
Dans les configurations AFF, FAS ou ASA , un seul LUN ONTAP ne devrait pas nécessiter plus de quatre chemins. Plus de quatre chemins d'accès peuvent engendrer des problèmes lors d'une panne de stockage.

+
Les exemples suivants montrent les paramètres corrects et l'état du chemin pour les LUN ONTAP dans une configuration ASA, AFF ou FAS .

+
[role="tabbed-block"]
====
.Configuration DE L'INFRASTRUCTURE ASA
--
Une configuration ASA optimise tous les chemins vers une LUN donnée en les gardant actifs. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

.Montrer l'exemple
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED (A)    Active/Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A) Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED (A)    Active/Optimized c14   SFRAC       sfrac0     -
----
=====
--
.Configuration AFF ou FAS
--
Une configuration AFF ou FAS doit comporter deux groupes de chemins ayant des priorités plus élevées et moins élevées. Les chemins actifs/optimisés à priorité supérieure sont servis par le contrôleur où se trouve l'agrégat. Les chemins de priorité inférieure sont actifs mais non optimisés, car ils sont gérés par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque des chemins optimisés ne sont pas disponibles.

L'exemple suivant présente la sortie d'une LUN ONTAP avec deux chemins Active/Optimized et deux chemins Active/non optimisés :

.Montrer l'exemple
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----
=====
--
====




== Étape 4 : Problèmes connus

Il n'y a pas de problème connu.



== Et la suite ?

* link:hu-luhu-command-reference.html["Découvrez comment utiliser l'outil Linux Host Utilities"] .

