---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Décrit comment utiliser IBM AIX 7.2 et/ou PowerVM VIOS 3.1 avec ONTAP 
---
= Utilitaires hôtes AIX 6.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


.Ce dont vous avez besoin
* Pour un fonctionnement fiable, vous devez vérifier que l'ensemble de votre configuration iSCSI, FC ou FCoE est prise en charge.
+
Vous pouvez utiliser le https://mysupport.netapp.com/matrix/imt.jsp?components=65623%3B64703%3B&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] pour vérifier votre configuration.





== Kit D'outils SAN

AIX Host Utilities est un logiciel hôte NetApp qui fournit un kit d'outils de ligne de commande sur votre hôte IBM AIX. Le kit d'outils est installé lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

*Exemple*

Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
#sanlun lun show all

controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Ce kit est commun à toutes les configurations et tous les protocoles des utilitaires hôtes. En conséquence, une partie de son contenu s'applique à une configuration, mais pas à une autre. Le fait d'utiliser des composants non utilisés n'affecte pas les performances de votre système.


NOTE: Le kit SAN est pris en charge sur les versions AIX et PowerVM/VIOS.



== Installez les utilitaires d'hôte AIX

Le pack logiciel NetApp AIX Host Utilities est disponible sur le https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host%2BUtilities%2B-%2BSAN&platform=Linux["Site de support NetApp"^] dans un fichier compressé tar.gz.

Vous devez installer AIX Host Utilities Kit lors de l'utilisation d'AIX MPIO avec stockage NetApp ONTAP.

Vous pouvez télécharger le fichier compressé contenant les packs logiciels d'utilitaires hôtes à partir du site de support NetApp. Après avoir téléchargé le fichier, vous devez le décompresser pour obtenir les deux packages logiciels dont vous avez besoin pour installer les utilitaires hôtes.

*Étapes*

. Connectez-vous à votre hôte.
+
** Sur un hôte AIX, connectez-vous en tant que *root*.
** Sur un hôte PowerVM, connectez-vous en tant que *padmin*, puis entrez la commande oem_setup_env pour devenir root.


. Téléchargez une copie du fichier compressé contenant les utilitaires hôtes du site de support NetApp dans un répertoire de votre hôte.
. Accédez au répertoire contenant le téléchargement.
. Décompresser le fichier et extraire le progiciel SAN Toolkit.
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
Le répertoire suivant est créé lors de la décompression du fichier : `ntap_aix_host_utilities_6.1`. Ce répertoire contient l'un des sous-répertoires suivants : MPIO, NON_MPIO ou SAN_Tool_Kit.

. Installez AIX MPIO :
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Installez le kit d'outils SAN :
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`

. Redémarrez l'hôte.
. Vérifiez l'installation :
+
`sanlun version`





== Exemple de référence de commande



=== Répertorie tous les initiateurs hôtes mappés sur l'hôte

[listing]
----
# sanlun fcp show adapter -v
bash-3.2# sanlun fcp show adapter -v
adapter name: fcs0
WWPN: 100000109b22e143
WWNN: 200000109b22e143
driver name: /usr/lib/drivers/pci/emfcdd
model: df1000e31410150
model description: FC Adapter
serial number: YA50HY79S117
hardware version: Not Available
driver version: 7.2.5.0
firmware version: 00012000040025700027
Number of ports: 1
port type: Fabric
port state: Operational
supported speed: 16 GBit/sec
negotiated speed: Unknown
OS device name: fcs0
adapter name: fcs1
WWPN: 100000109b22e144
WWNN: 200000109b22e144
driver name: /usr/lib/drivers/pci/emfcdd
model: df1000e31410150
model description: FC Adapter
serial number: YA50HY79S117
hardware version: Not Available
driver version: 7.2.5.0
firmware version: 00012000040025700027
Number of ports: 1
port type: Fabric
port state: Operational
supported speed: 16 GBit/sec
negotiated speed: Unknown
OS device name: fcs1
bash-3.2#
----


=== Répertorie toutes les LUN mappées à l'hôte

[listing]
----
# sanlun lun show -p -v all
ONTAP Path: vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
LUN: 88
LUN Size: 15g
Host Device: hdisk9
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host    vserver  AIX   AIX MPIO
path    path     MPIO  host      vserver      path
state   type     path  adapter   LIF          priority
-----------------------------------------------------
up     primary   path0   fcs0    fc_aix_1     1
up     primary   path1   fcs1    fc_aix_2     1
up     secondary path2   fcs0    fc_aix_3     1
up     secondary path3   fcs1    fc_aix_4     1
----


=== Répertorie toutes les LUN mappées à l'hôte à partir d'un SVM donné

[listing]
----
# sanlun lun show -p -v sanboot_unix

ONTAP Path: sanboot_unix:/vol/aix_205p2_boot_0/boot_205p2_lun
LUN: 0
LUN Size: 80.0g
Host Device: hdisk85
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host    vserver    AIX   AIX MPIO
path    path       MPIO  host    vserver    path
state   type       path  adapter LIF        priority
-------------------------------------------------
up      primary    path0 fcs0    sanboot_1   1
up      primary    path1 fcs1    sanboot_2   1
up      secondary  path2 fcs0    sanboot_3   1
up      secondary  path3 fcs1    sanboot_4   1
----


=== Répertorie tous les attributs d'une LUN donnée mappée sur l'hôte

[listing]
----
# sanlun lun show -p -v vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
ONTAP Path: vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
LUN: 88
LUN Size: 15g
Host Device: hdisk9
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host     vserver   AIX   AIX MPIO
path     path      MPIO  host     vserver   path
state    type      path  adapter  LIF       priority
---------------------------------------------------------
up       primary   path0 fcs0    fc_aix_1   1
up       primary   path1 fcs1    fc_aix_2   1
up       secondary path2 fcs0    fc_aix_3   1
up       secondary path3 fcs1    fc_aix_4   1
----


=== Répertorie les attributs de LUN ONTAP par nom de fichier de périphérique hôte

[listing]
----
#sanlun lun show -d /dev/hdisk1
controller(7mode)/
device host lun
vserver(Cmode)     lun-pathname
-----------------------------------------------------------------------------
vs_aix_clus       /vol/gpfs_205p2_207p1_vol_0_0/aix_205p2_207p1_lun

filename adapter protocol size mode
-----------------------------------
hdisk1    fcs0    FCP     15g  C
----


=== Lister tous les WWPN des LIF cibles des SVM liés à l'hôte

[listing]
----
# sanlun lun show -wwpn
controller(7mode)/
target device host lun
vserver(Cmode)          wwpn            lun-pathname
--------------------------------------------------------------------------------

vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_0_0/aix_205p2_207p1_lun
vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_0_9/aix_205p2_207p1_lun
vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_en_0_0/aix_205p2_207p1_lun_en
vs_aix_clus          202f00a098ba7afe  /vol/gpfs_205p2_207p1_vol_en_0_1/aix_205p2_207p1_lun_en

filename     adapter    size  mode
-----------------------------------
hdisk1       fcs0       15g    C
hdisk10      fcs0       15g    C
hdisk11      fcs0       15g    C
hdisk12      fcs0       15g    C
----