---
sidebar: sidebar 
permalink: hu_aix_72.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Décrit comment utiliser IBM AIX 7.2 et/ou PowerVM VIOS 3.1 avec ONTAP 
---
= Utilisez IBM AIX 7.2 et/ou PowerVM (VIOS 3.1) avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser les paramètres de configuration de l'hôte SAN ONTAP pour configurer IBM AIX 7.2 et/ou PowerVM (VIOS 3.1) avec ONTAP comme cible.



== Installez les utilitaires hôtes AIX/VIOS

Vous devez installer le kit d'utilitaires hôtes AIX lors de l'utilisation d'AIX MPIO avec un système de stockage NetApp ONTAP.

Vous pouvez télécharger le fichier compressé contenant les packs logiciels Host Utilities à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["Site de support NetApp"^]. Une fois le fichier créé, vous devez le décompresser pour obtenir les deux logiciels dont vous avez besoin pour installer les utilitaires hôtes.

NetApp AIX Host Utilities 6.1 est la dernière version. Cette version résout le problème de fuite de mémoire signalé dans les versions précédentes. Reportez-vous à la section des notes de version pour plus d'informations.

.Étapes
. Connectez-vous à votre hôte.
+
** Sur un hôte AIX, connectez-vous en tant que *root*.
** Sur un hôte PowerVM, connectez-vous en tant que *padmin*, puis entrez le `oem_setup_env` commande pour devenir root.


. Téléchargez une copie du fichier compressé contenant les utilitaires hôtes du site de support NetApp dans un répertoire de votre hôte.
. Accédez au répertoire contenant le téléchargement.
. Décompressez le fichier et extrayez le pack logiciel SAN Toolkit.
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
Le répertoire suivant est créé lors de la décompression du fichier : `ntap_aix_host_utilities_6.1`. Ce répertoire contient l'un des sous-répertoires suivants : MPIO, NON_MPIO ou SAN_Tool_Kit.

. Installez AIX MPIO :
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Installez le kit d'outils SAN :
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`
. Redémarrez l'hôte.




== Kit SAN

L'installation du package des utilitaires hôtes NetApp installe automatiquement le kit d'outils. Ce kit fournit l' `sanlun`utilitaire qui vous aide à gérer les LUN et les adaptateurs de bus hôte (HBA).  `sanlun`La commande renvoie des informations sur les LUN mappées sur votre hôte, les chemins d'accès multiples et les informations nécessaires à la création des groupes initiateurs.

.Exemple
Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
#sanlun lun show

controller(7mode)/                  device      host       lun
vserver(Cmode)    lun-pathname     filename    adapter   protocol   size   mode
--------------------------------------------------------------------------------
data_vserver      /vol/vol1/lun1    hdisk0      fcs0       FCP       60g    C
data_vserver      /vol/vol2/lun2    hdisk0      fcs0       FCP       20g    C
data_vserver      /vol/vol3/lun3    hdisk11     fcs0       FCP       20g    C
data_vserver      /vol/vol4/lun4    hdisk14     fcs0       FCP       20g    C

----


== Démarrage SAN

.Ce dont vous avez besoin
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser le link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] Pour vérifier que votre système d'exploitation, votre adaptateur de bus hôte, votre micrologiciel HBA, votre BIOS de démarrage HBA et votre version de ONTAP sont pris en charge.

LE démarrage SAN est le processus de configuration d'un disque connecté au SAN (un LUN) en tant que périphérique d'amorçage pour un hôte AIX/PowerVM. Vous pouvez configurer une LUN de démarrage SAN pour qu'elle fonctionne dans un environnement AIX MPIO qui exécute les utilitaires hôtes AIX avec le protocole FC ou FCoE. La méthode que vous utilisez pour créer une LUN de démarrage SAN et installer une nouvelle image OS sur celle-ci dans un environnement MPIO AIX peut varier en fonction du protocole utilisé.



== Chemins d'accès multiples

Les chemins d'accès multiples vous permettent de configurer plusieurs chemins réseau entre l'hôte et le système de stockage. En cas de défaillance d'un chemin, le trafic continue sur les chemins restants. Les environnements AIX et PowerVM des utilitaires hôtes utilisent la solution MPIO (native multipathing) d'AIX.

Pour AIX, le module de contrôle de chemin (PCM) est chargé de contrôler plusieurs chemins. PCM est un code fourni par un fournisseur de stockage qui gère la gestion des chemins. Cette option est installée et activée dans le cadre de l'installation des utilitaires hôtes.



=== Configurations non ASA

Pour les configurations non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont Active/Optimized (actif/optimisé), ce qui signifie que les services sont gérés par le contrôleur où se trouve l'agrégat. Les chemins aux priorités inférieures sont actifs, mais ne sont pas optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés.

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1

----


=== Configurations All SAN Array

Toutes les configurations de baie SAN (ASA) optimisent tous les chemins d'accès à une LUN donnée en les gardant actives. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

.Exemple
L'exemple suivant illustre la sortie correcte d'une LUN ONTAP.


NOTE: Toutes les configurations de baies SAN (ASA) sont prises en charge à partir de ONTAP 9.8 pour les hôtes AIX.

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----


== Paramètres recommandés

Voici quelques paramètres recommandés pour les LUN ONTAP.  Les paramètres critiques des LUN ONTAP sont définis automatiquement après l'installation du kit d'utilitaires d'hôtes NetApp.

[cols="4*"]
|===
| Paramètre | De production | Valeur pour AIX | Remarque 


| algorithme | MPIO | round_robin | Défini par les utilitaires hôtes 


| hcheck_cmd | MPIO | question | Défini par les utilitaires hôtes 


| hcheck_interval | MPIO | 30 | Défini par les utilitaires hôtes 


| hcheck_mode | MPIO | non actif | Défini par les utilitaires hôtes 


| lun_reset_spt | MPIO / non MPIO | oui | Défini par les utilitaires hôtes 


| transfert max | MPIO / non MPIO | LUN FC : 0x100000 octets | Défini par les utilitaires hôtes 


| qfull_dly | MPIO / non MPIO | délai de 2 secondes | Défini par les utilitaires hôtes 


| queue_deted | MPIO / non MPIO | 64 | Défini par les utilitaires hôtes 


| reserve_policy | MPIO / non MPIO | no_reserve | Défini par les utilitaires hôtes 


| rw_timeout (disque) | MPIO / non MPIO | 30 secondes | Utilise les valeurs par défaut du système d'exploitation 


| dystrk | MPIO / non MPIO | Oui. | Utilise les valeurs par défaut du système d'exploitation 


| fc_err_recov | MPIO / non MPIO | Fast_fail | Utilise les valeurs par défaut du système d'exploitation 


| q_type | MPIO / non MPIO | simplicité | Utilise les valeurs par défaut du système d'exploitation 


| num_cmd_elems | MPIO / non MPIO | 1024 pour AIX 3072 pour VIOS | FC EN1B, FC EN1C 


| num_cmd_elems | MPIO / non MPIO | 1024 pour AIX | FC EN0G 
|===


== Paramètres recommandés pour MetroCluster

Par défaut, le système d'exploitation AIX applique un délai d'expiration d'E/S plus court lorsqu'aucun chemin vers une LUN n'est disponible. Ce phénomène peut survenir dans les configurations, notamment avec une structure SAN à commutateur unique et des configurations MetroCluster qui présentent des basculements non planifiés. Pour plus d'informations et pour connaître les modifications recommandées aux paramètres par défaut, reportez-vous à la section link:https://kb.netapp.com/app/answers/answer_view/a_id/1001318["NetApp KB1001318"^]



== Prise en charge d'AIX avec SnapMirror Active Sync

À partir de ONTAP 9.11.1, AIX est pris en charge avec la synchronisation active SnapMirror. Dans le cas d'une configuration AIX, le cluster principal est le cluster « actif ».

Dans une configuration AIX, les basculements sont disruptifs. Chaque basculement nécessite une nouvelle analyse de l'hôte pour que les opérations d'E/S reprennent.

Pour configurer AIX pour la synchronisation active SnapMirror, reportez-vous à l'article de la base de connaissances link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_configure_an_AIX_host_for_SnapMirror_Business_Continuity_(SM-BC)["Comment configurer un hôte AIX pour la synchronisation active SnapMirror"^].



== Problèmes connus

IBM AIX 7.2 et/ou PowerVM (VIOS 3.1) avec la version ONTAP présente les problèmes connus suivants :

[cols="4*"]
|===
| ID de bug NetApp | Titre | Description | ID de partenaire 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1416221["1416221"^] | AIX 7200-05-01 a rencontré une interruption des E/S sur les disques iSCSI virtuels (VIOS 3.1.1.x) lors du basculement du stockage | Des perturbations d'E/S peuvent survenir pendant les opérations de basculement de stockage sur les hôtes AIX 7.2 TL5 sur les disques iSCSI virtuels mappés via le système VIOS 3.1.1.x. Par défaut, le `rw_timeout` La valeur des disques iSCSI virtuels (hdisk) sur VIOC sera de 45 secondes. Un retard d'E/S supérieur à 45 secondes peut se produire lors du basculement du système de stockage. Pour éviter ce problème, reportez-vous à la solution de contournement mentionnée dans BURT. Comme pour IBM, après avoir appliqué APAR - IJ34739 (prochaine version), nous pouvons modifier dynamiquement la valeur rw_timeout à l'aide de l' `chdev` commande. | NA 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1414700["1414700"^] | AIX 7.2 TL04 a rencontré une interruption des E/S sur les disques iSCSI virtuels (VIOS 3.1.1.x) lors du basculement du stockage | Des perturbations d'E/S peuvent survenir pendant les opérations de basculement de stockage sur les hôtes AIX 7.2 TL4 sur les disques iSCSI virtuels mappés via le système VIOS 3.1.1.x. Par défaut, le `rw_timeout` La valeur de la carte vSCSI sur VIOC est de 45 secondes. Un retard d'E/S de plus de 45 secondes peut se produire lors d'un basculement de stockage, une défaillance d'E/S. Pour éviter ce problème, reportez-vous à la solution de contournement mentionnée dans BURT. | NA 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1307653["1307653"^] | Voir les problèmes d'E/S sur le système VIOS 3.1.1.10 pendant les pannes SFO et les E/S droites | Les défaillances d'E/S du système VIOS 3.1.1 peuvent être vues sur le disque client NPIV qui est pris en charge par les adaptateurs FC 16 Gb. Aussi, a `vfchost` Le pilote peut atteindre un état dans lequel il arrête le traitement des demandes d'E/S du client. L'application d'IBM APAR IJ22290 IBM APAR IJ23222 corrigera le problème. | NA 
|===