---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Décrit comment utiliser IBM AIX 7.2 et/ou PowerVM VIOS 3.1 avec ONTAP 
---
= Utilitaires hôtes AIX 6.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Les utilitaires d'hôtes unifiés AIX vous aident à gérer le stockage NetApp ONTAP connecté à un hôte AIX.



== Kit D'outils SAN

AIX Host Utilities est un logiciel hôte NetApp qui fournit un kit d'outils de ligne de commande sur votre hôte IBM AIX. Le kit d'outils est installé lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

*Exemple*

Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
#sanlun lun show all

controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Ce kit est commun à toutes les configurations et tous les protocoles des utilitaires hôtes. En conséquence, une partie de son contenu s'applique à une configuration, mais pas à une autre. Le fait d'utiliser des composants non utilisés n'affecte pas les performances de votre système.


NOTE: Le kit SAN est pris en charge sur les versions AIX et PowerVM/VIOS.



== Installez les utilitaires d'hôte AIX

Le pack logiciel NetApp AIX Host Utilities est disponible sur le https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host%2BUtilities%2B-%2BSAN&platform=Linux["Site de support NetApp"^] dans un fichier compressé tar.gz.

Vous devez installer AIX Host Utilities Kit lors de l'utilisation d'AIX MPIO avec stockage NetApp ONTAP.

Vous pouvez télécharger le fichier compressé contenant les packs logiciels d'utilitaires hôtes à partir du site de support NetApp. Après avoir téléchargé le fichier, vous devez le décompresser pour obtenir les deux packages logiciels dont vous avez besoin pour installer les utilitaires hôtes.

*Étapes*

. Connectez-vous à votre hôte.
+
** Sur un hôte AIX, connectez-vous en tant que *root*.
** Sur un hôte PowerVM, connectez-vous en tant que *padmin*, puis entrez la commande oem_setup_env pour devenir root.


. Téléchargez une copie du fichier compressé contenant les utilitaires hôtes du site de support NetApp dans un répertoire de votre hôte.
. Accédez au répertoire contenant le téléchargement.
. Décompresser le fichier et extraire le progiciel SAN Toolkit.
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
Le répertoire suivant est créé lors de la décompression du fichier : `ntap_aix_host_utilities_6.1`. Ce répertoire contient l'un des sous-répertoires suivants : MPIO, NON_MPIO ou SAN_Tool_Kit.

. Installez AIX MPIO :
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Installez le kit d'outils SAN :
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`

. Redémarrez l'hôte.
. Vérifiez l'installation :
+
`sanlun version`


