---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_aix.html 
keywords: host utilities, aix, netapp, ontap, configure, discover, configuring, discovering 
summary: Décrit la découverte et la configuration DES LUN sous AIX 
---
= (AIX MPIO sans PowerVM) Découvrez et configurez les LUN avec AIX
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous utilisez AIX sans PowerVM, vous pouvez exécuter `cfgmgr` la commande pour permettre à l'hôte de détecter les LUN. Il n'est pas nécessaire de redémarrer l'hôte pour détecter les LUN. Pour confirmer que l'hôte a découvert les LUN, vous pouvez utiliser l'utilitaire sanlun.


NOTE: Les étapes suivantes ne s'appliquent pas à un hôte qui exécute un environnement PowerVM.

.Étapes
. Connectez-vous en tant que root sur l'hôte.
. Sur l'hôte AIX, entrez la commande suivante pour détecter les LUN nouvellement créés :
+
`cfgmgr`

+
Le `cfgmgr` la commande permet de :

+
** Les initiateurs pour se connecter à la structure.
** Le système pour rechercher de nouveaux dispositifs.
** Le système pour créer de nouvelles entrées de périphérique.


. Afficher tous les disques AIX, y compris les LUN NetApp :
+
`lsdev -Cc disk`

+
Les LUN apparaissent sur l'hôte sous forme de disques. Vous pouvez utiliser ces disques de la même manière que vous utilisez des disques locaux sur l'hôte. Le fichier ODM de paramètres hôte installé dans le cadre des utilitaires hôtes provoque l'affichage des LUN en tant que disques NetApp FCP.

+
Notez les numéros d'instance hdisk. Vous les utilisez lorsque vous effectuez la configuration du chemin.

+
L'exemple suivant montre la `lsdev -Cc disk` sortie de la commande dans un environnement FC.

+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
# lsdev -Cc disk
hdisk0 Available 08-08-00-5,0 16 Bit LVD SCSI Disk Drive
hdisk1 Available 08-08-00-8,0 16 Bit LVD SCSI Disk Drive
hdisk2 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk3 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk4 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk5 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
----
====
. Récupérer des informations sur votre configuration :
+
`lsattr -El hdisk_name`

+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
# lsattr -El hdisk65
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistant Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
====
. Si votre configuration prend en charge ALUA, vous pouvez l'utiliser pour définir la priorité des chemins d'accès. Vérifiez que ALUA est activé :
+
`lun igroup show -instance igroup_name`

+
.. Si ALUA n'est pas activé, activez-le :
+
`igroup set igroup_name alua yes`



. Si votre configuration ne prend pas en charge ALUA, vous devez utiliser l'utilitaire dotpaths pour définir les priorités de chemin. L'utilitaire dotpaths est installé lors de l'installation des utilitaires hôtes. N'utilisez pas l'utilitaire dotpaths si le protocole ALUA est activé.
+
.. Définissez la priorité de toutes les LUN ONTAP :
+
`dotpaths`

.. Définir la priorité d'un jeu spécifique de disques :
+
`dotpaths [-hqv] [hdiskN ...]`

+
Utilisez `-v` l'option pour activer le mode détaillé et afficher toutes les priorités. Utilisez `-q` l'option pour interroger toutes les priorités de disque ou les priorités individuelles.



. Vérifiez que l'hôte a détecté les LUN :
+
`# sanlun lun show`

+
L'exemple suivant montre la sortie type de la `sanlun lun show` commande dans un environnement multi-chemins d'accès E/S (MPIO) Microsoft :

+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ---------------------------------------------- ----------
host      controller  AIX            controller                                     AIX MPIO
path      path        MPIO   host    target                                         path
state     type        path   adapter port                                           priority
--------- ----------- ------ ------- ---------------------------------------------- ----------
up        secondary   path0  fcs0    3b                                             1
up        primary     path1  fcs0    3a                                             1
up        secondary   path2  fcs0    3a                                             1
up        primary     path3  fcs0    3b                                             1
up        secondary   path4  fcs0    4b                                             1
up        secondary   path5  fcs0    4a                                             1
up        primary     path6  fcs0    4b                                             1
up        primary     path7  fcs0    4a                                             1
up        secondary   path8  fcs1    3b                                             1
up        primary     path9  fcs1    3a                                             1
up        secondary   path10 fcs1    3a                                             1
up        primary     path11 fcs1    3b                                             1
up        secondary   path12 fcs1    4b                                             1
up        secondary   path13 fcs1    4a                                             1
up        primary     path14 fcs1    4b                                             1
up        primary     path15 fcs1    4a                                             1
----
====

