---
sidebar: sidebar 
permalink: hu_citrix_7x.html 
keywords: host utilities, citrix, XenServer, 7 series, netapp, ontap, san, boot 
summary: 'Décrit l"utilisation de Citrix XenServer 7.x avec ONTAP' 
---
= Utilisez Citrix XenServer avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez configurer les paramètres de configuration d'hôte SAN ONTAP pour les versions du système d'exploitation Citrix XenServer 7 avec les protocoles FC, FCoE et iSCSI.



== SAN Booting

.Ce dont vous avez besoin
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser le link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] Pour vérifier que votre système d'exploitation, votre adaptateur de bus hôte, votre micrologiciel HBA, votre BIOS de démarrage HBA et votre version de ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+

NOTE: Plusieurs chemins deviennent disponibles une fois que le système d'exploitation hôte est opérationnel sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage a réussi.




== Chemins d'accès multiples

La prise en charge des chemins d'accès multiples dans Citrix XenServer repose sur les composants Device Mapper Multipathd. Les nœuds de mappage de périphériques ne sont pas automatiquement créés pour toutes les LUN présentées à XenServer et sont uniquement provisionnés lorsque les LUN sont activement utilisées par la couche de gestion du stockage (API). Le plug-in API Citrix XenServer Storage Manager gère automatiquement l'activation et la désactivation des nœuds multichemins.

En raison des incompatibilités avec l'architecture intégrée de gestion des chemins d'accès multiples, Citrix vous recommande d'utiliser l'application Citrix XenCenter pour gérer la configuration du stockage. S'il est nécessaire d'interroger manuellement l'état des tables Device Mapper ou de répertorier les nœuds multipathing actifs du mappeur de périphériques sur le système, vous pouvez utiliser le `/sbin/mpathutil status` Commande pour vérifier les paramètres des LUN ONTAP. Pour en savoir plus, consultez la documentation standard fournie par les fournisseurs pour Citrix XenServer.



=== Configurations non ASA

Pour les configurations non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont Active/Optimized (actif/optimisé), ce qui signifie que les services sont gérés par le contrôleur où se trouve l'agrégat. Les chemins aux priorités inférieures sont actifs, mais ne sont pas optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés.

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
|-+- policy='service-time 0' prio=10 status=enabled
  |- 2:0:0:0   sda   8:0     active ready running
  |- 2:0:1:0   sdb   8:16    active ready running
  |- 12:0:3:0  sd1   8:176   active ready running
  `-12:0:6:0   sdo   8:224   active ready running
[root@sanhost ~]#
----

NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. La présence de plus de quatre chemins peut entraîner des problèmes de chemin pendant les pannes de stockage.



=== Configuration de la baie SAN

Dans toutes les configurations ASA (SAN Array), tous les chemins d'accès à une LUN donnée sont actifs et optimisés. Autrement dit, les E/S peuvent être servies par tous les chemins simultanément, ce qui assure de meilleures performances.

.Exemple
L'exemple suivant montre la sortie correcte d'une LUN ONTAP avec les quatre chemins actifs/optimisés :

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
[root@sanhost ~]#
----

NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. La présence de plus de quatre chemins peut entraîner des problèmes de chemin pendant les pannes de stockage.



=== Paramètres recommandés

Le système d'exploitation Citrix XenServer 7.x est compilé avec tous les paramètres requis afin de reconnaître et de gérer correctement les LUN ONTAP. Pour Citrix XenServer 7.x, un zerobyte vide `/etc/multipath.conf` le fichier doit exister, mais il n'est pas nécessaire d'apporter des modifications spécifiques au fichier.

Activez le service de chemins d'accès multiples de l'hôte à partir du portail de gestion XenCenter* et vérifiez que le service de chemins d'accès multiples est activé et exécuté.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
Il n'est pas nécessaire d'ajouter du contenu au `/etc/multipath.conf` fichier, sauf si vous disposez de périphériques que vous ne souhaitez pas gérer les chemins d'accès multiples ou si vous disposez de paramètres existants qui remplacent les paramètres par défaut. Vous pouvez ajouter la syntaxe suivante au `multipath.conf` fichier pour exclure les périphériques indésirables.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: Remplacez le *<DevID>* par la chaîne WWID du périphérique que vous souhaitez exclure.

.Exemple
Dans l'exemple suivant pour Citrix XenServer 7.x, `sda` est le disque SCSI local que vous souhaitez ajouter à la liste noire.

. Exécutez la commande suivante pour déterminer l'identifiant WWID :
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. Ajoutez cet identifiant WWID à la strophe de la liste noire dans le `/etc/multipath.conf`:
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


Reportez-vous à la configuration de l'exécution des paramètres de chemins d'accès multiples à l'aide du `$multipathd show config` commande. Vous devez toujours vérifier la configuration de votre exécution pour les anciens paramètres qui peuvent remplacer les paramètres par défaut, en particulier dans la section par défaut.

Le tableau suivant présente les paramètres *multipathd* critiques pour les LUN ONTAP et les valeurs requises. Si un hôte est connecté à des LUN d'autres fournisseurs et que l'un de ces paramètres est remplacé, ils doivent être corrigés par des strophes ultérieurs dans *multipath.conf* qui s'appliquent spécifiquement aux LUN ONTAP. Si ce n'est pas le cas, les LUN de ONTAP risquent de ne pas fonctionner comme prévu. Les valeurs par défaut suivantes doivent être remplacées uniquement en consultation avec NetApp et/ou le fournisseur du système d'exploitation, et uniquement lorsque l'impact est parfaitement compris.

[cols="2*"]
|===
| Paramètre | Réglage 


| `detect_prio` | oui 


| `dev_loss_tmo` | « infini » 


| `failback` | immédiate 


| `fast_io_fail_tmo` | 5 


| `features` | "3 queue_if_no_path pg_init_retries 50" 


| `flush_on_last_del` | « oui » 


| `hardware_handler` | « 0 » 


| `path_checker` | « tur » 


| `path_grouping_policy` | « group_by_prio » 


| `path_selector` | « temps-service 0 » 


| `polling_interval` | 5 


| `prio` | « ONTAP » 


| `product` | LUN.* 


| `retain_attached_hw_handler` | oui 


| `rr_weight` | « uniforme » 


| `user_friendly_names` | non 


| `vendor` | NETAPP 
|===
.Exemple
L'exemple suivant illustre comment corriger une valeur par défaut remplacée. Dans ce cas, le fichier *multipath.conf* définit les valeurs pour *path_Checker* et *Detect_prio* qui ne sont pas compatibles avec les LUN ONTAP. S'ils ne peuvent pas être supprimés en raison d'autres baies SAN connectées à l'hôte, ces paramètres peuvent être corrigés spécifiquement pour les LUN ONTAP avec une strophe de périphérique.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: Citrix XenServer recommande l'utilisation des outils Citrix VM pour toutes les machines virtuelles invitées Linux et Windows pour une configuration prise en charge.



== Problèmes connus

Il n'y a aucun problème connu pour Citrix XenServer avec la version ONTAP.
