---
sidebar: sidebar 
permalink: hu_citrix_8x.html 
keywords: host utilities, citrix, hypervisor, 8.0, 8.1, 8.2, netapp, ontap, sanhost 
summary: 'Décrit l"utilisation de l"hyperviseur Citrix 8.x avec ONTAP' 
---
= Avec l'hyperviseur Citrix avec NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Introduction

Ce document décrit les paramètres de configuration des hôtes SAN ONTAP pour les versions des systèmes d'exploitation d'hyperviseur Citrix série 8 avec protocoles FC, FCoE et iSCSI.



== SAN Booting

.Ce dont vous avez besoin
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser le link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] Pour vérifier que votre système d'exploitation, votre adaptateur de bus hôte, votre micrologiciel HBA, votre BIOS de démarrage HBA et votre version de ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+
N'oubliez pas que plusieurs chemins ne seront disponibles qu'après la mise en service et l'exécution du système d'exploitation hôte sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage est réussi.




== Chemins d'accès multiples

Pour Citrix Hypervisor (CH) 8.x `/etc/multipath.conf` le fichier doit exister, mais il n'est pas nécessaire d'apporter des modifications spécifiques au fichier. CH 8.x est compilé avec tous les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP. Vous pouvez utiliser le `/sbin/mpathutil` Commande status pour vérifier les paramètres de vos LUN ONTAP. Les sections suivantes fournissent un exemple de résultat de chemins d'accès multiples pour une LUN mappée aux rôles ASA.



=== Configuration de baie 100 % SAN (ASA)

Pour la configuration des baies SAN (ASA), il doit y avoir un groupe de chemins avec des priorités uniques. Tous les chemins sont actifs/optimisés, ce qui signifie qu'ils sont gérés par le contrôleur et que les E/S sont envoyées sur tous les chemins actifs.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec quatre chemins actifs/optimisés :

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
....

NOTE: N'utilisez pas un nombre excessif de chemins pour une seule LUN. Pas plus de 4 chemins ne devraient être nécessaires. Plus de 8 chemins peuvent entraîner des problèmes de chemin pendant les défaillances du stockage.



=== Configuration non ASA

Pour la configuration non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant les priorités les plus élevées sont actifs/optimisés, ce qui signifie qu'ils sont gérés par le contrôleur où se trouve l'agrégat. Les chemins avec les priorités les plus basses sont actifs, mais ne sont pas optimisés car ils sont servis à partir d'un autre contrôleur. Les chemins non optimisés sont utilisés uniquement lorsqu'aucun chemin optimisé n'est disponible.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
 |- 1:0:0:11   sde   8:64    active ready running
`- 12:0:8:11  sdua  66:544  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
   |- 1:0:9:11   sddo  71:96   active ready running
   `- 12:0:26:11 sdyt  129:720 active ready running
....

NOTE: N'utilisez pas un nombre excessif de chemins pour une seule LUN. Pas plus de 4 chemins ne devraient être nécessaires. Plus de 8 chemins peuvent entraîner des problèmes de chemin pendant les défaillances du stockage.



== Paramètres recommandés

Le système d'exploitation Citrix Hypervisor 8.x est compilé avec tous les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP. Pour l'hyperviseur Citrix 8.x, un zerobyte vide `/etc/multipath.conf` le fichier doit exister, mais il n'est pas nécessaire d'apporter des modifications spécifiques au fichier.

Activez le service de chemins d'accès multiples de l'hôte à partir du portail de gestion XenCenter* et vérifiez que le service de chemins d'accès multiples est activé et exécuté.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
Il n'est pas obligatoire d'ajouter du contenu à `/etc/multipath.conf` fichier, sauf si vous disposez de périphériques que vous ne voulez pas être gérés par multipath ou si vous avez des paramètres existants qui remplacent les paramètres par défaut. Vous pouvez ajouter la syntaxe suivante au fichier multipath.conf pour exclure les périphériques indésirables.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: Remplacez le *<DevID>* par la chaîne WWID du périphérique que vous souhaitez exclure.

.Exemple
Dans cet exemple pour Citrix Hypervisor 8.x, `sda` Est le disque SCSI local que nous devons ajouter à la liste noire.

. Exécutez la commande suivante pour déterminer l'identifiant WWID :
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. Ajoutez cet identifiant WWID à la strophe de la liste noire dans le `/etc/multipath.conf`:
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


Reportez-vous à la configuration de l'exécution des paramètres de chemins d'accès multiples à l'aide du `$multipathd show config` commande. Vous devez toujours vérifier la configuration de votre exécution pour les anciens paramètres qui peuvent remplacer les paramètres par défaut, en particulier dans la section par défaut.

Le tableau suivant présente les paramètres *multipathd* critiques pour les LUN ONTAP et les valeurs requises. Si un hôte est connecté à des LUN d'autres fournisseurs et que l'un de ces paramètres est remplacé, ils doivent être corrigés par des strophes ultérieurs dans *multipath.conf* qui s'appliquent spécifiquement aux LUN ONTAP. Si ce n'est pas le cas, les LUN de ONTAP risquent de ne pas fonctionner comme prévu. Les valeurs par défaut suivantes doivent être remplacées uniquement en consultation avec NetApp et/ou le fournisseur du système d'exploitation, et uniquement lorsque l'impact est parfaitement compris.

[cols="2*"]
|===
| Paramètre | Réglage 


| `detect_prio` | oui 


| `dev_loss_tmo` | « infini » 


| `failback` | immédiate 


| `fast_io_fail_tmo` | 5 


| `features` | "3 queue_if_no_path pg_init_retries 50" 


| `flush_on_last_del` | « oui » 


| `hardware_handler` | « 0 » 


| `path_checker` | « tur » 


| `path_grouping_policy` | « group_by_prio » 


| `path_selector` | « temps-service 0 » 


| `polling_interval` | 5 


| `prio` | « ONTAP » 


| `product` | LUN.* 


| `retain_attached_hw_handler` | oui 


| `rr_weight` | « uniforme » 


| `user_friendly_names` | non 


| `vendor` | NETAPP 
|===
.Exemple
L'exemple suivant illustre comment corriger une valeur par défaut remplacée. Dans ce cas, le fichier *multipath.conf* définit les valeurs pour *path_Checker* et *Detect_prio* qui ne sont pas compatibles avec les LUN ONTAP. S'ils ne peuvent pas être supprimés en raison d'autres baies SAN connectées à l'hôte, ces paramètres peuvent être corrigés spécifiquement pour les LUN ONTAP avec une strophe de périphérique.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: L'hyperviseur Citrix recommande d'utiliser les outils de machine virtuelle Citrix pour toutes les machines virtuelles invitées Linux et Windows pour une configuration prise en charge.



== Problèmes connus et limites

[cols="4*"]
|===
| ID de bug NetApp | Titre | Description | ID du Citrix Tracker 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1242343["1242343"^] | Perturbation du noyau sur l'hyperviseur Citrix 8.0 avec QLogic QLE2742 32 Go FC pendant les opérations de basculement du stockage | Une interruption du noyau peut survenir pendant les opérations de basculement du stockage sur un noyau de l'hyperviseur Citrix 8.0 (4.19.0+1) avec le HBA QLogic QLE2742 32 Go. Ce problème entraîne un redémarrage du système d'exploitation et une interruption des applications. Si kdump est configuré, l'interruption du noyau génère un fichier vmcore sous le répertoire /var/crash/. Vous pouvez utiliser le fichier vmcore pour comprendre la cause de l'échec. Après la perturbation du noyau, vous pouvez restaurer le système d'exploitation en redémarrant le système d'exploitation hôte et en redémarrant l'application. | link:https://tracker.citrix.com/browse/NETAPP-98["NETAPP-98"^] 
|===