---
sidebar: sidebar 
permalink: hu_citrix_84.html 
keywords: host utilities, citrix, Xenserver, 8 series, netapp, ontap, san, boot 
summary: Configurez Citrix Xenserver 8.4 pour le multivoie et avec des paramètres et paramètres spécifiques pour les opérations de protocole FCP et iSCSI avec le stockage ONTAP . 
---
= Configurer Citrix Xenserver 8.4 pour FCP et iSCSI avec stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configurez Citrix Xenserver 8.4 pour le multivoie et avec des paramètres et paramètres spécifiques pour les opérations de protocole FCP et iSCSI avec le stockage ONTAP .

[NOTE]
====
Le progiciel Linux Host Utilities ne prend pas en charge les systèmes d'exploitation Citrix Xenserver.

====


[[step-1-optionally-enable-san-booting]]
== Étape 1 : activez éventuellement le démarrage SAN

Vous pouvez configurer votre hôte pour qu'il utilise le démarrage SAN afin de simplifier le déploiement et d'améliorer l'évolutivité.

.Avant de commencer
Utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.

.Étapes
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Créez un LUN de démarrage SAN et mappez-le à l'hôte"^].
. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Vérifiez que la configuration a réussi en redémarrant l'hôte et en vérifiant que le système d'exploitation est opérationnel.




[[step-2-confirm-the-multipath-configuration-for-your-host]]
== Étape 2 : Confirmez la configuration multi-chemins pour votre hôte

Vous pouvez utiliser le multipathing avec Citrix Xenserver 8.4 pour gérer les LUN ONTAP .

Pour vous assurer que les chemins d'accès multiples sont correctement configurés pour votre hôte, vérifiez que le `/etc/multipath.conf` fichier est défini et que vous disposez des paramètres recommandés par NetApp pour vos LUN ONTAP.

.Étapes
. Localisez le  `/etc/multipath.conf` fichier.
+
Si le fichier de référence `/etc/multipath.conf` ne contient pas les paramètres de configuration spécifiques à l'appareil NetApp, ajoutez ces paramètres à l'aide du fichier personnalisé suivant `.conf drop-in`. Vous trouverez ce fichier sous `/etc/multipath/conf.d/` :

+

NOTE: Ne modifiez pas le  `/etc/multipath.conf` fichier, car le contenu du fichier pourrait être écrasé lors d'une mise à jour du système.

+
.Afficher le contenu du fichier
[%collapsible]
====
[source, cli]
----
$sudo tee -a /etc/multipath/conf.d/custom.conf >/dev/null <<'EOF'

defaults {
    polling_interval 5
}

blacklist {
    wwid <Insert_LUN_wwid_string>
    devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
    devnode "^hd[a-z]"
    devnode "^cciss.*"
}

devices {
    device {
    vendor "NETAPP"
    product "LUN.*"
    user_friendly_names no
    path_checker "tur"
    prio "ontap"
    detect_prio yes
    path_grouping_policy "group_by_prio"
    path_selector "service-time 0"
    failback immediate
    fast_io_fail_tmo 5
    dev_loss_tmo infinity
    no_path_retry queue
    features "3 queue_if_no_path pg_init_retries 50"
    flush_on_last_del yes
    hardware_handler "0"
    retain_attached_hw_handler yes
    rr_weight uniform
  }
}

EOF
----
====
. Lors de la première configuration du multipath, vous devrez peut-être activer et démarrer les services multipath pour charger les paramètres recommandés :
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. À chaque démarrage de l'hôte, le fichier  `/etc/multipath/conf.d/custom.conf` charge automatiquement les paramètres multipath recommandés par NetApp comme paramètres par défaut.
+
Le tableau suivant présente les paramètres de chemins d'accès multiples compilés par le système d'exploitation Linux natif pour les LUN ONTAP.

+
.Affiche les paramètres
[%collapsible]
====
[[multipath-parameter-settings]]
[cols="2"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
====
. Vérifiez les paramètres et l'état du chemin de vos LUN ONTAP :
+
[source, cli]
----
/sbin/mpathutil status
----
+
Les paramètres multi-trajets par défaut prennent en charge les configurations ASA, AFF et FAS . Dans ces configurations, un seul LUN ONTAP ne devrait pas nécessiter plus de quatre chemins. Le fait d'avoir plus de quatre chemins d'accès peut engendrer des problèmes en cas de panne de stockage.

+
Les résultats des exemples suivants montrent les paramètres et l'état de chemin corrects pour les LUN ONTAP dans une configuration ASA, AFF ou FAS.

+
[role="tabbed-block"]
====
.Configuration DE L'INFRASTRUCTURE ASA
--
Une configuration ASA optimise tous les chemins vers une LUN donnée en les gardant actifs. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

.Montrer l'exemple
[%collapsible]
=====
[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  |- 15:0:1:0  sdc  8:32    active ready running
  |- 16:0:0:0  sdcf 69:48   active ready running
  `- 16:0:1:0  sdcg 69:64   active ready running
----
=====
--
.Configuration AFF ou FAS
--
Une configuration AFF ou FAS doit comporter deux groupes de chemins ayant des priorités plus élevées et moins élevées. Les chemins actifs/optimisés à priorité supérieure sont servis par le contrôleur où se trouve l'agrégat. Les chemins de priorité inférieure sont actifs mais non optimisés, car ils sont gérés par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque des chemins optimisés ne sont pas disponibles.

L'exemple suivant présente la sortie d'une LUN ONTAP avec deux chemins Active/Optimized et deux chemins Active/non optimisés :

.Montrer l'exemple
[%collapsible]
=====
[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  `- 15:0:1:0  sdc  8:32    active ready running
`-+- policy='service-time 0' prio=50 status=active
     |- 16:0:0:0  sdcf 69:48   active ready running
     `- 16:0:1:0  sdcg 69:64   active ready running
----
=====
--
====




[[step-3-optionally-exclude-a-device-from-multipathing]]
== Étape 3 : exclure éventuellement un périphérique du multivoie

Si nécessaire, vous pouvez exclure un périphérique du routage multiple en ajoutant le WWID du périphérique indésirable à la section « blacklist » pour le  `/etc/multipath/conf.d/custom.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" est le disque SCSI local que vous souhaitez ajouter à la liste noire.

+
Un exemple de WWID est `360030057024d0730239134810c0cb833`.

. Ajoutez le WWID à la strophe « blacklist » :
+
[source, cli]
----
blacklist {
        wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




[[step-4-customize-multipath-parameters-for-ontap-luns]]
== Étape 4 : Personnaliser les paramètres multi-chemins pour les LUN ONTAP

Si votre hôte est connecté à des LUN d'autres fournisseurs et que certains paramètres de multipath sont remplacés, vous devez les corriger en modifiant les sections du fichier  `/etc/multipath/conf.d/custom.conf` qui s'appliquent spécifiquement aux LUN ONTAP. Faites défiler le fichier vers le bas pour ajouter ces sections. Si vous ne corrigez pas les paramètres, les LUN ONTAP pourraient ne pas fonctionner comme prévu.


CAUTION: Vous ne devez pas remplacer les paramètres recommandés pour les LUN ONTAP. Ces paramètres sont requis pour optimiser les performances de votre configuration hôte. Pour plus d'informations, contactez le support NetApp, le fournisseur de votre système d'exploitation ou les deux.

L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans cet exemple, le `custom.conf drop-in` fichier définit des valeurs pour `path_checker` et `no_path_retry` qui ne sont pas compatibles avec les LUNs ONTAP, et vous ne pouvez pas supprimer ces paramètres car les baies de stockage ONTAP sont toujours attachées à l'hôte. À la place, vous corrigez les valeurs pour `path_checker` et `no_path_retry` en ajoutant une section de périphérique dans le fichier `custom.conf drop-in` qui s'applique spécifiquement aux LUNs ONTAP.

.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


[[step-5-review-the-known-issues]]
== Étape 5 : Examiner les problèmes connus

Il n'y a pas de problème connu.
