---
sidebar: sidebar 
permalink: hu_hpux_60_cmd.html 
keywords: host utilities, unified, oracle, hp-ux, 6.0, netapp, ontap 
summary: Ce document explique comment utiliser les utilitaires hôtes HP-UX 6.0 avec ONTAP. 
---
= Utilisez les commandes des utilitaires hôtes HP-UX pour vérifier la configuration du stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez l'exemple de référence de commande HP-UX Host Utilities 6.0 pour une validation de bout en bout de la configuration de stockage ONTAP à l'aide de l'outil Host Utilities.



== Répertorie tous les initiateurs hôtes mappés sur l'hôte

Récupérer une liste de tous les initiateurs d’hôte mappés à un hôte.

[source, cli]
----
sanlun fcp show adapter -v
----
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
adapter name:      fclp2
WWPN:              10000000c985ef92
WWNN:              20000000c985ef92
driver name:       fclp
model:             AJ763-63001
model description: HP 8Gb Dual Channel PCI-e 2.0 FC HBA
serial number:     MY19034N9U
hardware version:  3
driver version:    @(#) FCLP: PCIe Fibre Channel driver (FibrChanl-02), B.11.31.1805, Feb  5 2018, FCLP_IFC (3,2)
firmware version:  2.02X2 SLI-3 (U3D2.02X2)
Number of ports:   1 of 2
port type:         Unknown
port state:        Link Down
supported speed:   8 GBit/sec
negotiated speed:  Speed not established
OS device name:    /dev/fclp2

adapter name:      fclp3
WWPN:              10000000c985ef93
WWNN:              20000000c985ef93
driver name:       fclp
model:             AJ763-63001
model description: HP 8Gb Dual Channel PCI-e 2.0 FC HBA
serial number:     MY19034N9U
hardware version:  3
driver version:    @(#) FCLP: PCIe Fibre Channel driver (FibrChanl-02), B.11.31.1805, Feb  5 2018, FCLP_IFC (3,2)
firmware version:  2.02X2 SLI-3 (U3D2.02X2)
Number of ports:   2 of 2
port type:         Unknown
port state:        Link Down
supported speed:   8 GBit/sec
negotiated speed:  Speed not established
OS device name:    /dev/fclp3
----
====


== Répertorie toutes les LUN mappées à l'hôte

Récupérer une liste de tous les LUN mappés à un hôte.

[source, cli]
----
sanlun lun show -p -v all
----
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
\
                    ONTAP Path: vs_hp_cluster:/vol/chathpux_217_vol_en_1_10/hp_en_217_lun
                           LUN: 55
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk718
                          Mode: C
                            VG: /dev/vg_data
              Multipath Policy: A/A
            Multipath Provider: Native
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
host     vserver    /dev/dsk                                                                    HP A/A
path     path       filename             host    vserver                                        path failover
state    type       or hardware path     adapter LIF                                            priority
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
up       primary    /dev/dsk/c37t6d7     fclp0   hpux_7                                         0
up       primary    /dev/dsk/c22t6d7     fclp1   hpux_8                                         0
up       secondary  /dev/dsk/c36t6d7     fclp0   hpux_5                                         1
up       secondary  /dev/dsk/c44t6d7     fclp1   hpux_6                                         1
----
====


== Répertorie toutes les LUN mappées à l'hôte à partir d'un SVM donné

Récupérer une liste de tous les LUN mappés à un hôte à partir d'un SVM spécifique.

[source, cli]
----
sanlun lun show -p -v vs_hp_cluster
----
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
                    ONTAP Path: vs_hp_cluster:/vol/chathpux_217_vol_en_1_10/hp_en_217_lun
                           LUN: 55
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk718
                          Mode: C
                            VG: /dev/vg_data
              Multipath Policy: A/A
            Multipath Provider: Native
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
host     vserver    /dev/dsk                                                                    HP A/A
path     path       filename             host    vserver                                        path failover
state    type       or hardware path     adapter LIF                                            priority
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
up       primary    /dev/dsk/c37t6d7     fclp0   hpux_7                                         0
up       primary    /dev/dsk/c22t6d7     fclp1   hpux_8                                         0
up       secondary  /dev/dsk/c36t6d7     fclp0   hpux_5                                         1
up       secondary  /dev/dsk/c44t6d7     fclp1   hpux_6                                         1
----
====


== Répertorie tous les attributs d'une LUN donnée mappée sur l'hôte

Récupérer une liste de tous les attributs d'un LUN spécifié mappé à un hôte.

[source, cli]
----
sanlun lun show -p -v vs_hp_cluster:/vol/chathpux_217_vol_en_1_5/hp_en_217_lun
----
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----

                    ONTAP Path: vs_hp_cluster:/vol/chathpux_217_vol_en_1_5/hp_en_217_lun
                           LUN: 49
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk712
                          Mode: C
                            VG: /dev/vg_data
              Multipath Policy: A/A
            Multipath Provider: Native
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
host     vserver    /dev/dsk                                                                    HP A/A
path     path       filename             host    vserver                                        path failover
state    type       or hardware path     adapter LIF                                            priority
-------- ---------- -------------------- ------- ---------------------------------------------- -------------
up       primary    /dev/dsk/c37t6d1     fclp0   hpux_7                                         0
up       primary    /dev/dsk/c22t6d1     fclp1   hpux_8                                         0
up       secondary  /dev/dsk/c36t6d1     fclp0   hpux_5                                         1
up       secondary  /dev/dsk/c44t6d1     fclp1   hpux_6                                         1
----
====


== Répertorie les attributs de LUN ONTAP par nom de fichier de périphérique hôte

Récupérer une liste d'attributs ONTAP LUN par un nom de fichier de périphérique hôte spécifié.

[source, cli]
----
sanlun lun show -dv /dev/rdisk/disk716
----
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
                                                                 device             host                  lun
vserver              lun-pathname                                filename           adapter    protocol   size    mode
----------------------------------------------------------------------------------------------------------------------
vs_hp_cluster        /vol/chathpux_217_vol_en_1_14/hp_en_217_lun /dev/rdisk/disk716 0          FCP        15g     C
             LUN Serial number: 80D7l?NiNP5U
         Controller Model Name: AFF-A800
          Vserver FCP nodename: 208400a098ba7afe
          Vserver FCP portname: 207e00a098ba7afe
              Vserver LIF name: hpux_5
            Vserver IP address: 10.141.54.30
                                10.141.54.35
                                10.141.54.37
                                10.141.54.33
                                10.141.54.31
           Vserver volume name: chathpux_217_vol_en_1_14        MSID::0x00000000000000000000000080915935
         Vserver snapshot name:
----
====


== Lister tous les WWPN des LIF cibles des SVM liés à l'hôte

Récupérer une liste de tous les WWPN LIF cibles SVM attachés à un hôte.

[source, cli]
----
sanlun lun show -wwpn
----
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----

controller(7mode)/
vserver(Cmode)       target wwpn        lun-pathname                                  device filename
--------------------------------------------------------------------------------------------------------
vs_hp_cluster        208300a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c22t6d7
vs_hp_cluster        208100a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c44t6d7
vs_hp_cluster        208200a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c37t6d7
vs_hp_cluster        207e00a098ba7afe   /vol/chathpux_217_vol_en_1_10/hp_en_217_lun   /dev/rdsk/c36t6d7
vs_hp_cluster        207d00a098ba7afe   /vol/chathpux_217_os/hp_217_os                /dev/rdsk/c18t7d4
vs_hp_cluster        207f00a098ba7afe   /vol/chathpux_217_os/hp_217_os                /dev/rdsk/c42t7d4

host adapter    lun size    mode
---------------------------------
fclp1           15g         C
fclp1           15g         C
fclp0           15g         C
fclp0           15g         C
fclp1           30g         C
fclp0           30g         C
----
====