---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 'Décrit l"utilisation de Linux Unified Host Utilities 7.1 avec ONTAP' 
---
= Utilitaires hôtes HP-UX 6.0
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Les utilitaires d'hôtes unifiés HP-UX vous aident à gérer le stockage NetApp ONTAP connecté à un hôte HP-UX.



== Kit D'outils SAN

HP-UX Host Utilities est un logiciel hôte NetApp qui fournit un kit d'outils de ligne de commande sur votre hôte HP-UX. Le kit d'outils est installé lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

.Exemple
Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----

NOTE: Ce kit est commun à toutes les configurations et tous les protocoles des utilitaires hôtes. En conséquence, une partie de son contenu s'applique à une configuration, mais pas à une autre. Le fait d'utiliser des composants non utilisés n'affecte pas les performances de votre système.



== Installation des utilitaires hôtes HP-UX

Le pack logiciel NetApp HP-UX Host Utilities est disponible sur le link:https://mysupport.netapp.com/site/["Site de support NetApp"^] dans un fichier compressé.

Vous pouvez télécharger le fichier compressé contenant les packs logiciels Host Utilities à partir du link:https://mysupport.netapp.com/site/["Site de support NetApp"^]. Après avoir téléchargé le fichier, vous devez le décompresser avant son installation.

.Étapes
. Connectez-vous à votre hôte.
. Téléchargez le fichier HP-UX Host Utilities `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` à partir du link:https://mysupport.netapp.com/site/["Site de support NetApp"^] Sur votre hôte HP-UX.
. Décompresser le `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` en entrant la commande suivante :
+
`# gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

+
Le système place le logiciel extrait dans le répertoire dans lequel vous avez décompressé le fichier de dépôt.

. Installez le logiciel en entrant la commande suivante :
+
`# swinstall -s /depot_path`

+
`depot_path` fournit le chemin et le nom du fichier de dépôt.

+
Le `swinstall` Commande exécute un script d'installation qui vérifie l'état de votre installation HP-UX. Si votre système répond à la configuration requise, ce script installe le `sanlun` scripts d'utilitaire et de diagnostic dans le `/opt/NetApp/santools/bin` répertoire.

. Vérifiez l'installation :
+
`sanlun version`


