---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Décrit comment utiliser les utilitaires hôtes HP-UX 6.0 avec le stockage ONTAP 
---
= Installez les utilitaires hôtes HP-UX 6.0 pour le stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les utilitaires hôtes HP-UX vous aident à gérer le stockage ONTAP connecté à un hôte HP-UX.  NetApp recommande fortement d'installer les utilitaires hôtes HP-UX, mais ce n'est pas obligatoire.  Les utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

Les utilitaires hôtes HP-UX prennent en charge les environnements suivants :

* E/S multivoies (MPIO) Microsoft natives
* Veritas Dynamic Multipathing (DMP)


.Avant de commencer
Pour un fonctionnement fiable, utilisez le https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre configuration iSCSI, FC ou FCoE est prise en charge.

.Étapes
. Connectez-vous à votre hôte hôte HP-UX.
. Téléchargez le fichier HP-UX Host Utilities `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` à partir du link:https://mysupport.netapp.com/site/["Site de support NetApp"^] Sur votre hôte HP-UX.
. Décompresser le `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` fichier :
+
[source, cli]
----
gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz
----
+
Le système place le logiciel extrait dans le répertoire dans lequel vous avez décompressé le fichier de dépôt.

. Installez le logiciel :
+
[source, cli]
----
swinstall -s /depot_path
----
+
`depot_path` fournit le chemin et le nom du fichier de dépôt.

+
Le `swinstall` Commande exécute un script d'installation qui vérifie l'état de votre installation HP-UX. Si votre système répond à la configuration requise, ce script installe le `sanlun` scripts d'utilitaire et de diagnostic dans le `/opt/NetApp/santools/bin` répertoire.

. Vérifiez l'installation :
+
[source, cli]
----
sanlun version
----




== Et la suite ?

link:hu-hpux-sanlun-toolkit.html["En savoir plus sur la boîte à outils SAN"] .
