---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: Installez Linux Host Utilities sur un hôte HP-UX 11i v3 pour gérer les opérations de protocole FCP et iSCSI avec les LUN ONTAP . 
---
= Configurer HP-UX 11i v3 pour FCP et iSCSI avec le stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le logiciel HP-UX Host Utilities fournit des outils de gestion et de diagnostic pour les hôtes HP-UX connectés au stockage ONTAP .  Lorsque vous installez les utilitaires hôte HP-UX sur un hôte HP-UX 11i v3, vous pouvez utiliser les utilitaires hôte pour vous aider à gérer les opérations de protocole FCP et iSCSI avec les LUN ONTAP .



== Étape 1 : activez éventuellement le démarrage SAN

Configurez votre hôte pour utiliser le démarrage SAN afin de simplifier le déploiement et d’améliorer l’évolutivité.  Le démarrage SAN est le processus de configuration d'un disque connecté au SAN (un LUN) en tant que périphérique de démarrage pour un hôte HP-UX.  Les utilitaires hôtes prennent en charge le démarrage SAN avec les protocoles FC et FCoE dans les environnements HP-UX.

.Étapes
. Utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.
. Suivez les meilleures pratiques pour configurer un démarrage SAN dans la documentation du fournisseur HP-UX.




== Étape 2 : installer les utilitaires hôtes HP-UX

NetApp recommande fortement d'installer les utilitaires hôtes HP-UX pour prendre en charge la gestion des LUN ONTAP et aider le support technique à collecter les données de configuration.

link:hu_hpux_60.html["Installez les utilitaires d'hôte HP-UX 6.0"]



== Étape 3 : confirmez la configuration des chemins d'accès multiples pour votre hôte

Utilisez le multipathing avec HP-UX 11i v3 pour gérer les LUN ONTAP .  Le multi-accès vous permet de configurer plusieurs chemins réseau entre l'hôte et le système de stockage.  Si un chemin échoue, le trafic continue sur les chemins restants.

Après avoir installé les utilitaires hôtes HP-UX, vérifiez que les paramètres recommandés par NetApp sont configurés pour vos LUN ONTAP .

.Description de la tâche
Les utilitaires hôtes HP-UX prennent en charge les E/S multi-chemins Microsoft natives (MPIO) et le multi-chemin dynamique Veritas.  Les étapes suivantes concernent la solution MPIO native.

.Étapes
. Lorsque vous installez les utilitaires hôtes HP-UX, les paramètres par défaut recommandés suivants sont automatiquement chargés pour les LUN ONTAP .
+
.Affiche les paramètres
[%collapsible]
====
[cols="2*"]
|===
| Paramètre | Utilise la valeur par défaut 


| secondes_transitoires | 120 


| leg_mpath_enable | VRAI 


| max_q_detene | 8 


| path_fail_sec | 120 


| load_bal_policy | Round_Robin 


| lua_enabled | VRAI 


| esd_secondes | 30 
|===
====
. Vérifiez les paramètres et l'état du chemin de vos LUN ONTAP :
+
[source, cli]
----
sanlun lun show
----
+
Les paramètres multi-trajets par défaut prennent en charge les configurations ASA, AFF et FAS .  Les exemples de sortie suivants affichent les paramètres corrects et l'état du chemin pour les LUN ONTAP dans une configuration ASA, AFF ou FAS .

+
[role="tabbed-block"]
====
.Configuration DE L'INFRASTRUCTURE ASA
--
Une configuration ASA optimise tous les chemins vers une LUN donnée en les gardant actifs. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----
--
.Configuration AFF ou FAS
--
Une configuration AFF ou FAS doit comporter deux groupes de chemins ayant des priorités plus élevées et moins élevées. Les chemins actifs/optimisés à priorité supérieure sont servis par le contrôleur où se trouve l'agrégat. Les chemins de priorité inférieure sont actifs mais non optimisés, car ils sont gérés par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque des chemins optimisés ne sont pas disponibles.

L'exemple suivant présente la sortie d'une LUN ONTAP avec deux chemins Active/Optimized et deux chemins Active/non optimisés :

[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----
--
====




== Étape 4 : Examiner les problèmes connus

La version HP-UX 11i v3 avec stockage ONTAP présente les problèmes connus suivants :

[cols="4*"]
|===
| ID de bug NetApp | Titre | Description | ID de partenaire 


| 1447287 | L'événement AUFO sur le cluster maître isolé dans la configuration de synchronisation active SnapMirror provoque une interruption temporaire sur l'hôte HP-UX | Ce problème survient lorsqu'un événement de basculement automatique non planifié (AUFO) est présent sur le cluster maître isolé dans la configuration de synchronisation active SnapMirror. La reprise des E/S sur l'hôte HP-UX peut prendre plus de 120 secondes, mais cela risque d'entraîner une interruption d'E/S ou des messages d'erreur. Ce problème provoque une défaillance de double événement, car la connexion entre le cluster principal et le cluster secondaire est perdue et la connexion entre le cluster principal et le médiateur est également perdue. Ce phénomène est considéré comme un événement rare, contrairement à d'autres événements AUFO. | NA 


| 1344935 | L'hôte HP-UX 11.31 signale par intermittence que le chemin d'accès n'est pas correctement signalé lors de la configuration de ASA. | Création de rapports sur les problèmes de chemin avec la configuration ASA. | NA 


| 1306354 | La création HP-UX LVM envoie des E/S d'une taille de bloc supérieure à 1 Mo | La longueur maximale de transfert SCSI de 1 Mo est appliquée dans ONTAP All SAN Array. Pour limiter la longueur maximale de transfert depuis les hôtes HP-UX lorsqu'ils sont connectés à la matrice SAN ONTAP, il est nécessaire de définir la taille maximale d'E/S autorisée par le sous-système SCSI HP-UX sur 1 Mo. Pour plus de détails, reportez-vous à la documentation du fournisseur HP-UX. | NA 
|===


== Quelle est la prochaine étape

link:hu_hpux_60_cmd.html["En savoir plus sur l'utilisation de l'outil Utilitaires hôte HP-UX"] .
