---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: Décrit comment utiliser IBM AIX 7.2 et/ou PowerVM VIOS 3.1 avec ONTAP 
---
= Utilisez HP-UX 11i v3 avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser les paramètres de configuration de l'hôte SAN ONTAP pour configurer HP-UX 11i v3 avec ONTAP comme cible.



== Installez les utilitaires hôtes HP-UX

Vous pouvez télécharger le fichier compressé contenant les packs logiciels Host Utilities à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.0/downloads["Site de support NetApp"^]. Une fois le fichier installé, vous devez le décompresser pour obtenir les packs logiciels dont vous avez besoin pour installer les utilitaires hôtes.

.Étapes
. Téléchargez une copie du fichier compressé contenant les utilitaires d'hôte à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.0/downloads["Site de support NetApp"^] vers un répertoire de votre hôte.
. Accédez au répertoire contenant le téléchargement.
. Décompressez le fichier.
+
`gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

. Entrez la commande suivante pour installer le logiciel :
+
`swinstall -s /netapp_hpux_host_utilities_6.0_ia_pa.depot NetApp_santoolkit`

. Redémarrez l'hôte.




== Kit D'outils SAN

Le kit d'outils est installé automatiquement lorsque vous installez le progiciel Utilitaires hôtes NetApp. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

.Exemple
Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
#sanlun lun show

controller(7mode)/                            device                         host     lun
vserver(Cmode)    lun-pathname               filename                       adapter protocol  size  mode
--------------------------------------------------------------------------------
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c11t0d0 fcd0   FCP      150g   C
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c24t0d0 fcd1   FCP      150g   C
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c21t0d0 fcd1   FCP      150g   C
sanboot_unix      /vol/hpux_215_boot_en_0/goot_hpux_215_lun /dev/rdsk/c12t0d0 fcd0   FCP      150g   C
----


== SAN Booting

.Ce dont vous avez besoin
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser le link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] Pour vérifier que votre système d'exploitation, votre adaptateur de bus hôte, votre micrologiciel HBA, votre BIOS de démarrage HBA et votre version de ONTAP sont pris en charge.

LE démarrage SAN est le processus de configuration d'un disque connecté au SAN (un LUN) en tant que périphérique d'amorçage pour un hôte HP-UX. Les utilitaires hôtes prennent en charge le démarrage SAN avec les protocoles FC et FCoE dans les environnements HP-UX.



== Chemins d'accès multiples

Les chemins d'accès multiples vous permettent de configurer plusieurs chemins réseau entre l'hôte et le système de stockage. En cas de défaillance d'un chemin, le trafic continue sur les chemins restants. Pour qu'un hôte puisse avoir plusieurs chemins d'accès à une LUN, les chemins d'accès multiples doivent être activés. Les utilitaires hôtes HP-UX prennent en charge différentes solutions de chemins d'accès multiples en fonction de votre configuration. Les éléments suivants sont destinés à la solution native de chemins d'accès multiples.



=== Configurations non ASA

Pour les configurations non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant les priorités les plus élevées sont actifs/optimisés, ce qui signifie qu'ils sont gérés par le contrôleur où se trouve l'agrégat. Les chemins avec les priorités les plus basses sont actifs, mais ne sont pas optimisés car ils sont servis à partir d'un autre contrôleur. Les chemins non optimisés sont utilisés uniquement lorsqu'aucun chemin optimisé n'est disponible.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----


=== Configurations All SAN Array

Dans les configurations ASA (All SAN Array), tous les chemins d'accès à une LUN donnée sont actifs et optimisés. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP :


NOTE: Toutes les configurations de matrice SAN (ASA) sont prises en charge à partir de ONTAP 9.8 pour HP-UX 11iv3

[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----


== Paramètres recommandés

Voici certains paramètres recommandés pour les LUN HPUX 11i v3 et NetApp ONTAP. NetApp utilise les paramètres par défaut pour HP-UX.

[cols="2*"]
|===
| Paramètre | Utilise la valeur par défaut 


| secondes_transitoires | 120 


| leg_mpath_enable | VRAI 


| max_q_detene | 8 


| path_fail_sec | 120 


| load_bal_policy | Round_Robin 


| lua_enabled | VRAI 


| esd_secondes | 30 
|===


== Problèmes connus

La version HP-UX 11i v3 avec ONTAP présente les problèmes connus suivants :

[cols="4*"]
|===
| ID de bug NetApp | Titre | Description | ID de partenaire 


| 1447287 | L'événement AUFO sur le cluster maître isolé dans la configuration de synchronisation active SnapMirror provoque une interruption temporaire sur l'hôte HP-UX | Ce problème survient lorsqu'un événement de basculement automatique non planifié (AUFO) est présent sur le cluster maître isolé dans la configuration de synchronisation active SnapMirror. La reprise des E/S sur l'hôte HP-UX peut prendre plus de 120 secondes, mais cela risque d'entraîner une interruption d'E/S ou des messages d'erreur. Ce problème provoque une défaillance de double événement, car la connexion entre le cluster principal et le cluster secondaire est perdue et la connexion entre le cluster principal et le médiateur est également perdue. Ce phénomène est considéré comme un événement rare, contrairement à d'autres événements AUFO. | NA 


| 1344935 | L'hôte HP-UX 11.31 signale par intermittence que le chemin d'accès n'est pas correctement signalé lors de la configuration de ASA. | Création de rapports sur les problèmes de chemin avec la configuration ASA. | NA 


| 1306354 | La création HP-UX LVM envoie des E/S d'une taille de bloc supérieure à 1 Mo | La longueur maximale de transfert SCSI de 1 Mo est appliquée dans ONTAP All SAN Array. Pour limiter la longueur maximale de transfert depuis les hôtes HP-UX lorsqu'ils sont connectés à la matrice SAN ONTAP, il est nécessaire de définir la taille maximale d'E/S autorisée par le sous-système SCSI HP-UX sur 1 Mo. Pour plus de détails, reportez-vous à la documentation du fournisseur HP-UX. | NA 
|===