---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: Notes de version pour Linux Host Utilities 7.1 
---
= Linux Host Utilities 7.1 - Notes de version
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les notes de version décrivent les nouvelles fonctionnalités et améliorations, les problèmes connus et les limites, ainsi que les mises en garde importantes pour la configuration et la gestion de votre hôte spécifique avec votre système de stockage ONTAP.

Pour obtenir des informations spécifiques sur les versions et les mises à jour du système d'exploitation prises en charge par les utilitaires hôtes, reportez-vous au link:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^].



== Nouveautés

La version 7.1 de Linux Host Utilities contient les nouvelles fonctionnalités et améliorations suivantes :

* Les utilitaires d'hôtes Linux sont désormais appelés _utilitaires d'hôtes unifiés Linux_ car ils prennent en charge les systèmes de stockage NetApp E-Series exécutant SANtricity ainsi que les systèmes AFF, FAS et ASA exécutant ONTAP.
+

NOTE: Toute mention d'Host Utilities ou d'Host Utilities Linux dans ce document fait référence à Linux Unified Host Utilities.

* Les systèmes d'exploitation suivants sont désormais pris en charge :
+
** SUSE Linux Enterprise Server série 15
** Oracle VM série 3.2
** Oracle Linux 6 et 7
** Red Hat Enterprise Linux 6 et 7
** SUSE Linux Enterprise Server 11 SP4
** KVM et XEN, RHEV 6.4 et 6.5
** Citrix XenServer


* Sur les hôtes Red Hat Enterprise Linux (RHEL) 6 et RHEL 7, un package optimisé pour la définition des profils de serveur est désormais pris en charge. Vous pouvez utiliser le `tuned-adm` pour définir différents profils, en fonction de l'environnement. Par exemple, vous pouvez également utiliser le profil invité virtuel en tant que machine virtuelle invitée et le profil de stockage d'entreprise pour les configurations dans lesquelles les LUN des baies de stockage d'entreprise sont utilisées. L'utilisation de ces packages optimisés peut améliorer le débit et la latence des ONTAP.
* Ajoute la prise en charge des cartes FC 32 Gb de Broadcom Emulex et Marvell Qlogic.



NOTE: NetApp continue de fonctionner avec les utilitaires hôtes afin d'ajouter la prise en charge des fonctionnalités après la version initiale. Pour obtenir les dernières informations sur les fonctions prises en charge et les nouvelles fonctionnalités ajoutées, reportez-vous à la section link:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^].



== Corrigé dans cette version

Le problème de défaillance intermittente du système d'exploitation de l'hôte qui se produit lors de l'exécution de la `sanlun lun show -p` commande dans SUSE Linux Enterprise Server 12 SP1, OL 7.2, RHEL 7.2 et RHEL 6.8 est corrigé dans cette version.



== Problèmes et limites connus

La version 7.1 de Linux Host Utilities présente les problèmes et limitations connus suivants.

[cols="10, 30, 30"]
|===
| ID de bug NetApp | Titre | Description 


| 1457017 |  `sanlun` problèmes d'installation messages d'avertissement relatifs à `libdevmapper.so` et `libnl.so` bibliothèques. Ces avertissements n'affectent pas la fonctionnalité de `sanlun` kit. | Lorsque vous exécutez la commande CLI des utilitaires d'hôtes Linux - « sanlun fcp show adapter -v » sur un hôte SAN, la commande échoue et un message d'erreur s'affiche indiquant que les dépendances de bibliothèque requises pour la découverte d'un adaptateur de bus hôte (HBA) ne peuvent pas être localisées : 
`[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded` reportez-vous à NetApp Bugs Online - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^]. 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp bogues en ligne"^] fournit des informations complètes pour la plupart des problèmes connus, y compris des solutions de contournement suggérées si possible.
