---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 'Décrit l"utilisation de Linux Unified Host Utilities 7.1 avec ONTAP' 
---
= Installez Linux Unified Host Utilities 7.1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les utilitaires d'hôtes unifiés Linux vous aident à gérer le stockage NetApp ONTAP connecté à un hôte Linux. NetApp recommande vivement d'installer les utilitaires d'hôtes unifiés Linux, mais ce n'est pas obligatoire. Les utilitaires ne modifient aucun paramètre sur votre hôte Linux. Ces utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

Les distributions Linux suivantes sont prises en charge :

* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
* Oracle Linux
* VM Oracle
* Citrix XenServer


.Ce dont vous avez besoin
Le pack logiciel NetApp Linux Unified Host Utilities est disponible sur le link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] dans un fichier .rpm 32 bits ou 64 bits.

* Pour un fonctionnement fiable, vous devez vérifier que l'ensemble de votre configuration iSCSI, FC ou FCoE est prise en charge.
+
Vous pouvez utiliser le https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] pour vérifier votre configuration.

* Vous devez installer les packages de gestion HBA (Host bus adapter) disponibles sur le site de support du fournisseur.
+
Le logiciel de gestion permet aux commandes du kit SAN de collecter des informations sur les HBA FC, telles que leurs WWPN. Pour le `sanlun fcp show adapter` pour fonctionner, vérifiez que les packages suivants sont correctement installés :

+
** HBA QLogic Marvell – CLI QConvergeConsole
** Broadcom Emulex HBA - interface de ligne de commande de l'application principale OneCommand Manager
** HBA Brocade Marvell – CLI de l'utilitaire de commande Brocade


* LES paquets RPM "libhbaapi" et "libhbalinux" disponibles pour chaque distribution Linux doivent être installés sur le système d'exploitation hôte.



NOTE: Les utilitaires d'hôtes unifiés Linux ne prennent pas en charge les protocoles hôtes NVMe over Fibre Channel (NVMe/FC) et NVMe over TCP (NVMe/TCP).

.Étapes
. Si une version de Linux Unified Host Utilities est déjà installée, utilisez la commande suivante pour la supprimer :
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
Pour les anciennes versions des utilitaires hôtes Linux, accédez au répertoire dans lequel le logiciel de l'utilitaire hôte est installé et entrez la commande de désinstallation pour supprimer le package installé.

. Téléchargez le pack logiciel Linux Unified Host Utilities 32 bits ou 64 bits à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] à votre hôte.
. Accédez au répertoire dans lequel vous avez téléchargé le pack logiciel et utilisez la commande suivante pour l'installer :
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
*Exemple de sortie*

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. Vérifiez l'installation :
+
[source, cli]
----
sanlun version
----
+
*Exemple de sortie*

+
[listing]
----
sanlun version 7.1.386.1644
----




== Paramètres de pilote recommandés avec le noyau Linux

Lorsque vous configurez un environnement FC qui utilise des pilotes de boîte de réception natifs fournis avec le noyau Linux, vous pouvez utiliser les valeurs par défaut des pilotes.



== Kit D'outils SAN

Linux Unified Host Utilities est un logiciel hôte NetApp qui fournit un kit d'outils de ligne de commandes sur votre hôte Linux.

Le kit d'outils est installé automatiquement lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

.Exemple
Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[source, cli]
----
# sanlun lun show all
----
Exemple de résultat :

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----
[NOTE]
====
* Ce kit est commun à toutes les configurations et tous les protocoles des utilitaires hôtes. En conséquence, une partie de son contenu s'applique à une configuration, mais pas à une autre. Le fait d'utiliser des composants non utilisés n'affecte pas les performances de votre système.
* Le kit SAN n'est pas pris en charge sur Citrix XenServer, Oracle VM et l'hyperviseur Red Hat Enterprise Virtualization.


====