---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: Notes de version pour Linux Unified Host Utilities 7.1 
---
= Notes de version de Linux Unified Host Utilities 7.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Les notes de version décrivent les nouvelles fonctionnalités et améliorations, les problèmes connus et les limites, ainsi que les mises en garde importantes pour la configuration et la gestion de votre hôte spécifique avec votre système de stockage ONTAP.

Pour des informations spécifiques sur les versions et mises à jour du système d'exploitation prises en charge par les utilitaires hôtes, consultez le link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^].



== Nouveautés

La version 7.1 de Linux Host Utilities contient les nouvelles fonctionnalités et améliorations suivantes :

* Les utilitaires d'hôtes Linux sont désormais appelés _utilitaires d'hôtes unifiés Linux_ car ils prennent en charge les systèmes de stockage NetApp E-Series exécutant SANtricity ainsi que les systèmes AFF, FAS et ASA exécutant ONTAP.
+

NOTE: Toute mention d'Host Utilities ou d'Host Utilities Linux dans ce document fait référence à Linux Unified Host Utilities.

* Les systèmes d'exploitation suivants sont désormais pris en charge :
+
** SUSE Linux Enterprise Server série 15
** Oracle VM série 3.2
** Oracle Linux 6 et 7
** Red Hat Enterprise Linux 6 et 7
** SUSE Linux Enterprise Server 11 SP4
** KVM et XEN, RHEV 6.4 et 6.5
** Citrix XenServer


* Sur les hôtes Red Hat Enterprise Linux (RHEL) 6 et RHEL 7, un package optimisé pour la définition des profils de serveur est désormais pris en charge. Vous pouvez utiliser le `tuned-adm` pour définir différents profils, en fonction de l'environnement. Par exemple, vous pouvez également utiliser le profil invité virtuel en tant que machine virtuelle invitée et le profil de stockage d'entreprise pour les configurations dans lesquelles les LUN des baies de stockage d'entreprise sont utilisées. L'utilisation de ces packages optimisés peut améliorer le débit et la latence des ONTAP.
* Ajoute la prise en charge des cartes FC 32 Gb de Broadcom Emulex et Marvell Qlogic.



NOTE: NetApp continue de fonctionner avec les utilitaires hôtes afin d'ajouter la prise en charge des fonctionnalités après la version initiale. Pour obtenir les dernières informations sur les fonctionnalités prises en charge et les nouvelles fonctionnalités ajoutées, reportez-vous au link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^].



== Corrigé dans cette version

Problème intermittent de défaillance du système d'exploitation de l'hôte qui se produit lors de l'exécution du `sanlun lun show -p` La commande dans SLES12SP1, OL7.2, RHEL7.2 et RHEL 6.8 est corrigée dans cette version.



== Problèmes et limites connus

La version 7.1 de Linux Host Utilities présente les problèmes et limitations connus suivants.

[cols="10, 30, 30"]
|===
| ID de bug NetApp | Titre | Description 


| 1457017 |  `sanlun` problèmes d'installation messages d'avertissement relatifs à `libdevmapper.so` et `libnl.so` bibliothèques. Ces avertissements n'affectent pas la fonctionnalité de `sanlun` kit. | Lorsque vous exécutez la commande CLI Linux Unified Host Utilities - « sanlun fcp show adapter -v » sur un hôte SAN, la commande échoue et un message d'erreur indique que les dépendances de bibliothèque requises pour la découverte d'un adaptateur de bus hôte (HBA) ne peuvent pas être
emplacement :

[root@hostname ~]# sanlun fcp show adapter -v
Impossible de localiser la bibliothèque /usr/lib64/libHBAAPI.so
Assurez-vous que le package d'installation de la bibliothèque est installé et chargé
Voir le rapport public 1508554. 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp bogues en ligne"^] fournit des informations complètes pour la plupart des problèmes connus, y compris des solutions de contournement suggérées si possible.
