---
sidebar: sidebar 
permalink: hu_ol_77.html 
keywords: host utilities, oracle, linux, 7.7, netapp, ontap 
summary: 'Décrit l"utilisation d"Oracle Linux 7.7 avec ONTAP' 
---
= Utilisez Oracle Linux 7.7 avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser les paramètres de configuration de l'hôte SAN ONTAP pour configurer Oracle Linux 7.7 avec ONTAP comme cible.



== Installez Linux Unified Host Utilities

Le pack logiciel NetApp Linux Unified Host Utilities est disponible sur le link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] dans un fichier .rpm 32 bits et 64 bits. Si vous ne savez pas quel fichier est adapté à votre configuration, utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp"^] pour vérifier celui dont vous avez besoin.

NetApp recommande vivement d'installer les utilitaires d'hôtes unifiés Linux, mais ce n'est pas obligatoire. Les utilitaires ne modifient aucun paramètre sur votre hôte Linux. Ces utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

Si une version de Linux Unified Host Utilities est actuellement installée, vous devez la mettre à niveau ou la supprimer et suivre ces étapes pour installer la dernière version.

.Étapes
. Téléchargez le pack logiciel Linux Unified Host Utilities 32 bits ou 64 bits à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] Sur votre hôte.
. Utilisez la commande suivante pour installer le pack logiciel :
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Vous pouvez utiliser les paramètres de configuration fournis dans ce document pour configurer les clients Cloud connectés à link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] et link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX pour ONTAP"^].



== Kit D'outils SAN

Le kit d'outils est installé automatiquement lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

.Exemple
Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[source, cli]
----
# sanlun lun show all
----
Exemple de résultat :

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN Booting

.Ce dont vous avez besoin
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser le link:https://mysupport.netapp.com/matrix/imt.jsp?components=90144;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] Pour vérifier que votre système d'exploitation, votre adaptateur de bus hôte, votre micrologiciel HBA, votre BIOS de démarrage HBA et votre version de ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+

NOTE: Plusieurs chemins deviennent disponibles une fois que le système d'exploitation hôte est en cours d'exécution sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage a réussi.




== Chemins d'accès multiples

Pour Oracle Linux 7.7, le fichier /etc/multipath.conf doit exister, mais vous n'avez pas besoin d'apporter de modifications spécifiques au fichier. Oracle Linux 7.7 est compilé avec tous les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP.

Vous pouvez utiliser `multipath -ll` la commande pour vérifier les paramètres de vos LUN ONTAP. Il devrait y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont Active/Optimized (actif/optimisé), ce qui signifie qu'ils sont gérés par le contrôleur où se trouve l'agrégat. Les chemins aux priorités inférieures sont actifs, mais ne sont pas optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. Plus de huit chemins peuvent entraîner des problèmes de chemin lors des défaillances du stockage.



== Paramètres recommandés

Le système d'exploitation Oracle Linux 7.7 est compilé pour reconnaître les LUN ONTAP et définir automatiquement tous les paramètres de configuration correctement. Le `multipath.conf` fichier doit exister pour que le démon multichemin puisse démarrer. Si ce fichier n'existe pas, vous pouvez créer un fichier vide à zéro octet en utilisant la commande suivante :

`touch /etc/multipath.conf`

Lors de la première création du `multipath.conf` fichier, vous devrez peut-être activer et démarrer les services multivoies en utilisant les commandes suivantes :

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
Il n'est pas nécessaire d'ajouter quelque chose directement au `multipath.conf` fichier, sauf si vous disposez de périphériques que vous ne souhaitez pas gérer le multipathing ou si vous avez des paramètres existants qui remplacent les paramètres par défaut. Pour exclure les périphériques indésirables, ajoutez la syntaxe suivante au `multipath.conf` fichier, en remplaçant <DevId> par la chaîne WWID du périphérique à exclure :

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
.Exemple
L'exemple suivant détermine le WWID d'un périphérique et l'ajoute au `multipath.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` Est le disque SCSI local que vous souhaitez ajouter à la liste noire.

. Ajoutez le `WWID` à la strophe de liste noire dans `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Vous devez toujours vérifier votre `/etc/multipath.conf` fichier pour les paramètres hérités, en particulier dans la section valeurs par défaut, qui peut remplacer les paramètres par défaut.

Le tableau suivant présente `multipathd` les paramètres critiques pour les LUN ONTAP et les valeurs requises. Si un hôte est connecté à des LUN d'autres fournisseurs et que l'un de ces paramètres est remplacé, il faut les corriger par les strophes ultérieures du `multipath.conf` fichier qui s'appliquent spécifiquement aux LUN ONTAP. Sans cette correction, les LUN ONTAP risquent de ne pas fonctionner comme prévu. Vous ne devez remplacer ces valeurs par défaut qu'en concertation avec NetApp, le fournisseur du système d'exploitation ou les deux, et uniquement lorsque l'impact est pleinement compris.

[cols="2*"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN.* 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
.Exemple
L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans ce cas, le `multipath.conf` fichier définit les valeurs pour `path_checker` et `detect_prio` Non compatible avec les LUN ONTAP. S'ils ne peuvent pas être supprimés en raison d'autres baies SAN toujours connectées à l'hôte, ces paramètres peuvent être corrigés spécifiquement pour les LUN ONTAP avec une strophe de périphérique.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Pour configurer Oracle Linux 7.7 Red Hat Enterprise Kernel (RHCK), utilisez link:hu_rhel_77.html#recommended-settings["paramètres recommandés"]pour Red Hat Enterprise Linux (RHEL) 7.7.



== Problèmes connus

La version Oracle Linux 7.7 avec ONTAP présente les problèmes connus suivants :

[cols="3*"]
|===
| ID de bug NetApp | Titre | Description 


| 1440718 | Si vous annulez le mappage d'une LUN ou si vous la mappez sans effectuer de nouvelle analyse SCSI, elle risque de corrompre les données de l'hôte. | Lorsque vous définissez le paramètre de configuration multivoie 'disable_changed_wwid' sur YES, il désactive l'accès au périphérique chemin d'accès en cas de modification de l'identifiant WWID. Les chemins d'accès multiples désactivent l'accès au périphérique de chemin d'accès jusqu'à ce que le WWID du chemin soit restauré vers le WWID du périphérique multichemin. Pour en savoir plus, voir link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["Base de connaissances NetApp : corruption du système de fichiers sur le LUN iSCSI sur Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1311575["1311575"^] | Retards d'E/S observés en raison des opérations de lecture/écriture qui ne sont pas parvenus à basculer sur des chemins secondaires lors du basculement du stockage avec Qlogic QLE2672 (16 Gbit/s) | Les opérations d'E/S peuvent ne pas reprendre les chemins secondaires pendant les opérations de basculement de stockage sur le noyau Oracle Linux 7.7 (5.4.17-2011.0.7.el7uek.x86_6) avec l'adaptateur de bus hôte QLogic QLE2672 16 Gbit/s. Si la progression des E/S est interrompue en raison de chemins primaires bloqués pendant le basculement de stockage, l'opération d'E/S peut ne pas reprendre via les chemins secondaires, entraînant ainsi un retard d'E/S. L'opération d'E/S est reprise uniquement après la mise en ligne des chemins primaires après l'exécution de l'opération de rétablissement du basculement du stockage. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1311576["1311576"^] | Retards d'E/S constatés suite à l'échec des opérations de lecture/écriture sur les chemins secondaires pendant le basculement du stockage avec Emulex LPe16002 (16 Gbit/s) | Les opérations d'E/S peuvent ne pas reprendre les chemins secondaires pendant les opérations de basculement de stockage sur le noyau Oracle Linux 7.7 (5.4.17-2011.0.7.el7uek.x86_6) avec l'adaptateur de bus hôte Emulex LPe16002 16G. Si la progression des E/S est interrompue en raison de chemins primaires bloqués pendant le basculement de stockage, l'opération d'E/S peut ne pas reprendre via les chemins secondaires, entraînant ainsi un retard d'E/S. L'opération d'E/S est reprise uniquement après la mise en ligne des chemins primaires après l'exécution de l'opération de rétablissement du basculement du stockage. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["1246134"^] | Retards d'E/S observés et déplacement des rapports vers un état bloqué et NON PRÉSENT lors du basculement de stockage avec Emulex LPe16002(16 Gbit/s) | Lors des opérations de basculement de stockage sur Oracle Linux 7.6 avec le noyau UEK5U2 s'exécutant avec un adaptateur de bus hôte (HBA) Fibre Channel (FC) Emulex LPe16002B-M6 16 Gbit/s, la progression des E/S peut s'arrêter en raison du blocage des rapports. Le basculement du stockage passe de l'état « en ligne » à l'état « bloqué », entraînant un retard dans les opérations de lecture et d'écriture. Une fois l'opération terminée avec succès, les rapports ne parviennent pas à revenir à l'état « en ligne » et continuent de rester à l'état « bloqué ». 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | Retards d'E/S observés et déplacement des ports Rés vers un état bloqué ET NON PRÉSENT lors du basculement du stockage avec Qlogic QLE2672(16G) et QLE2742(32G) | Les ports distants Fibre Channel (FC) peuvent être bloqués sur Red Hat Enterprise Linux (RHEL) 7.6 avec un hôte QLogic QLE2672 16 Gbit/s lors des opérations de basculement de stockage. Étant donné que les interfaces logiques sont arrêtées lorsqu'un nœud de stockage est en panne, les ports distants définissent l'état du nœud de stockage sur bloqués. L'avancement des E/S peut s'arrêter en raison des ports bloqués si vous exécutez à la fois un hôte QLogic QLE2672 16 Gbit/s et un adaptateur de bus hôte (FC) Fibre Channel 32 Gbit/s QLE2742. Lorsque le nœud de stockage revient à son état optimal, les interfaces logiques s'allument également et les ports distants doivent être en ligne. Cependant, il se peut que les ports distants soient toujours bloqués. Cet état bloqué s'enregistre comme étant défectueux pour LES LUN au niveau de la couche multivoie. Vous pouvez vérifier l'état des ports distants à l'aide de la commande suivante : # Cat /sys/class/fc_remote_ports/rport-*/port_stat vous devriez voir la sortie suivante : bloqué en ligne bloqué 
|===