---
sidebar: sidebar 
permalink: hu_ol_76.html 
keywords: host utilities, oracle, linux, 7.6, netapp, ontap 
summary: Installez Linux Host Utilities sur un hôte Oracle Linux 7.6 pour gérer les opérations de protocole FCP et iSCSI avec les LUN ONTAP. 
---
= Configurer Oracle Linux 7.6 pour FCP et iSCSI avec le stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le logiciel Linux Host Utilities fournit des outils de gestion et de diagnostic pour les hôtes Linux connectés au stockage ONTAP. Lorsque vous installez les utilitaires d'hôte Linux sur un hôte Oracle Linux 7.6, vous pouvez utiliser les utilitaires d'hôte pour vous aider à gérer les opérations de protocole FCP et iSCSI avec les LUN ONTAP.


NOTE: Vous n’avez pas besoin de configurer manuellement les paramètres de la machine virtuelle basée sur le noyau (KVM) car les LUN ONTAP sont automatiquement mappés à l’hyperviseur.



== Étape 1 : activez éventuellement le démarrage SAN

Vous pouvez configurer votre hôte pour qu'il utilise le démarrage SAN afin de simplifier le déploiement et d'améliorer l'évolutivité.

.Avant de commencer
Utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.

.Étapes
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Créez un LUN de démarrage SAN et mappez-le à l'hôte"^].
. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Vérifiez que la configuration a réussi en redémarrant l'hôte et en vérifiant que le système d'exploitation est opérationnel.




== Étape 2 : installez les utilitaires hôtes Linux

NetApp recommande vivement d'installer les utilitaires hôtes Linux pour prendre en charge la gestion des LUN ONTAP et aider le support technique à collecter les données de configuration.

link:hu_luhu_71.html["Installez Linux Host Utilities 7.1"].


NOTE: L'installation des utilitaires d'hôtes Linux ne modifie aucun paramètre de délai d'expiration de l'hôte sur votre hôte Linux.



== Étape 3 : confirmez la configuration des chemins d'accès multiples pour votre hôte

Vous pouvez utiliser les chemins d'accès multiples avec Oracle Linux 7.6 pour gérer les LUN ONTAP.


NOTE: Vous pouvez utiliser le link:hu_rhel_76.html#rhel-rhck["paramètres recommandés pour Red Hat Enterprise Linux (RHEL) 7.6"] pour configurer le noyau compatible Red Hat pour Oracle Linux 7.6.

Pour vous assurer que les chemins d'accès multiples sont correctement configurés pour votre hôte, vérifiez que le `/etc/multipath.conf` fichier est défini et que vous disposez des paramètres recommandés par NetApp pour vos LUN ONTAP.

.Étapes
. Vérifiez que le `/etc/multipath.conf` fichier se ferme. Si le fichier n'existe pas, créez un fichier vide à zéro octet :
+
[source, cli]
----
touch /etc/multipath.conf
----
. Lors de la première `multipath.conf` création du fichier, vous devrez peut-être activer et démarrer les services multivoies pour charger les paramètres recommandés :
+
[source, cli]
----
chkconfig multipathd on
----
+
[source, cli]
----
/etc/init.d/multipathd start
----
. Chaque fois que vous démarrez l'hôte, le fichier vide `/etc/multipath.conf` à zéro octet charge automatiquement les paramètres de chemins d'accès multiples recommandés par NetApp comme paramètres par défaut. Vous ne devriez pas avoir besoin d'apporter de modifications au `/etc/multipath.conf` fichier de votre hôte car le système d'exploitation est compilé avec les paramètres multivoies qui reconnaissent et gèrent correctement les LUN ONTAP.
+
Le tableau suivant présente les paramètres de chemins d'accès multiples compilés natifs du système d'exploitation Linux pour les LUN ONTAP.

+
.Affiche les paramètres
[%collapsible]
====
[cols="2"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | « 2 pg_init_retries 50 » 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
====
. Vérifiez les paramètres et l'état du chemin de vos LUN ONTAP :
+
[source, cli]
----
multipath -ll
----
+
Les paramètres multipath par défaut prennent en charge les configurations AFF et FAS . Dans ces configurations, un seul LUN ONTAP ne devrait pas nécessiter plus de quatre chemins. Le fait d'avoir plus de quatre chemins d'accès peut engendrer des problèmes en cas de panne de stockage.

+
Une configuration AFF ou FAS doit comporter deux groupes de chemins ayant des priorités plus élevées et moins élevées. Les chemins actifs/optimisés à priorité supérieure sont servis par le contrôleur où se trouve l'agrégat. Les chemins de priorité inférieure sont actifs mais non optimisés, car ils sont gérés par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque des chemins optimisés ne sont pas disponibles.

+
Les exemples de sortie suivants montrent les paramètres corrects et l'état du chemin pour les LUN ONTAP dans une configuration AFF ou FAS avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
====




== Étape 4 : si vous le souhaitez, excluez un périphérique du multipathing

Si nécessaire, vous pouvez exclure un périphérique du multipathing en ajoutant le WWID du périphérique indésirable à la strophe « blacklist » du `multipath.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" est le disque SCSI local que vous souhaitez ajouter à la liste noire.

+
Un exemple de WWID est `360030057024d0730239134810c0cb833`.

. Ajoutez le WWID à la strophe « blacklist » :
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Étape 5 : personnalisez les paramètres des chemins d'accès multiples pour les LUN ONTAP

Si votre hôte est connecté à des LUN d'autres fournisseurs et que l'un des paramètres de chemins d'accès multiples est remplacé, vous devez les corriger en ajoutant la strophe plus loin dans `multipath.conf` le fichier qui s'applique spécifiquement aux LUN ONTAP. Si vous ne le faites pas, les LUN ONTAP risquent de ne pas fonctionner comme prévu.

Vérifiez votre `/etc/multipath.conf` fichier, en particulier dans la section valeurs par défaut, pour les paramètres qui peuvent remplacer <<multipath-parameter-settings,paramètres par défaut pour les paramètres multivoies>>.


CAUTION: Vous ne devez pas remplacer les paramètres recommandés pour les LUN ONTAP. Ces paramètres sont requis pour optimiser les performances de votre configuration hôte. Pour plus d'informations, contactez le support NetApp, le fournisseur de votre système d'exploitation ou les deux.

L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans cet exemple, le `multipath.conf` fichier définit des valeurs pour `path_checker` et `no_path_retry` qui ne sont pas compatibles avec les LUN ONTAP, et vous ne pouvez pas supprimer ces paramètres car les baies de stockage ONTAP sont toujours connectées à l'hôte. Vous corrigez plutôt les valeurs de `path_checker` et `no_path_retry` en ajoutant une strophe de périphérique au `multipath.conf` fichier qui s'applique spécifiquement aux LUN ONTAP.

.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Étape 6 : passez en revue les problèmes connus

L'hôte Oracle Linux 7.6 avec stockage ONTAP présente les problèmes connus suivants :

[cols="3*"]
|===
| ID de bug NetApp | Titre | Description 


| 1440718 | Si vous annulez le mappage d'une LUN ou si vous la mappez sans effectuer de nouvelle analyse SCSI, elle risque de corrompre les données de l'hôte. | Lorsque vous définissez le paramètre de configuration multivoie 'disable_changed_wwid' sur YES, il désactive l'accès au périphérique chemin d'accès en cas de modification de l'identifiant WWID. Les chemins d'accès multiples désactivent l'accès au périphérique de chemin d'accès jusqu'à ce que le WWID du chemin soit restauré vers le WWID du périphérique multichemin. Pour en savoir plus, voir link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["Base de connaissances NetApp : corruption du système de fichiers sur le LUN iSCSI sur Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1202736["1202736"^] | Il est possible que les LUN ne soient pas disponibles lors de la découverte de l'hôte en raison de l'état « non présent » des ports distants sur un hôte OL7U6 équipé d'un adaptateur QLogic QLE2742 | Lors de la découverte de l'hôte, l'état des ports distants Fibre Channel (FC) d'un hôte OL7U6 avec un adaptateur QLogic QLE2742 peut devenir « non présent ». Les ports distants équipés d'un état « non présent » peuvent entraîner l'indisponibilité des chemins vers les LUN. Lors du basculement du stockage, la redondance des chemins peut être réduite et entraîner une panne d'E/S. Vous pouvez vérifier l'état du port distant en entrant la commande suivante : # Cat /sys/class/fc_remote_ports/rport-*/port_state. Voici un exemple de sortie qui s'affiche : Online non présent en ligne 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204078["1204078"^] | L'interruption du noyau se produit sur Oracle Linux 7.6 exécuté avec un adaptateur HBA FC 16 Go Qlogic (QLE2672) pendant les opérations de basculement du stockage | Lors des opérations de basculement de stockage sur Oracle Linux 7.6 avec un adaptateur de bus hôte Qlogic QLE2672 Fibre Channel (FC), une perturbation du noyau se produit en raison d'une panique dans le noyau. Le problème du noyau provoque le redémarrage d'Oracle Linux 7.6, ce qui entraîne une interruption des applications. Si le mécanisme kdump est activé, le kernel Panic génère un fichier vmcore situé dans le répertoire /var/crash/. Vous pouvez analyser le fichier vmcore pour déterminer la cause de l'incident. Après une interruption du noyau, vous pouvez redémarrer le système d'exploitation hôte et restaurer le système d'exploitation, puis redémarrer les applications selon vos besoins. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204351["1204351"^] | Une interruption du noyau peut se produire sur Oracle Linux 7.6 exécuté avec la carte HBA FC 32 Gb Qlogic (QLE2742) pendant les opérations de basculement du stockage | Lors des opérations de basculement de stockage sur Oracle Linux 7.6 avec un adaptateur de bus hôte Qlogic QLE2742 (FC), une perturbation du noyau peut avoir lieu en raison d'un incident dans le noyau. Le problème du noyau provoque le redémarrage d'Oracle Linux 7.6, ce qui entraîne une interruption des applications. Si le mécanisme kdump est activé, le kernel Panic génère un fichier vmcore situé dans le répertoire /var/crash/. Vous pouvez analyser le fichier vmcore pour déterminer la cause de l'incident. Après une interruption du noyau, vous pouvez redémarrer le système d'exploitation hôte et restaurer le système d'exploitation, puis redémarrer les applications selon vos besoins. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204352["1204352"^] | Une interruption du noyau peut se produire sur Oracle Linux 7.6 exécuté avec un HBA FC 32 Gb (LPe32002-M2)32 Gb lors des opérations de basculement de stockage | Lors des opérations de basculement de stockage sur Oracle Linux 7.6 avec un adaptateur de bus hôte (HBA) Fibre Channel (FC) Emulex LPe32002-M2, une perturbation du noyau peut se produire en raison d'un incident au niveau du noyau. Le problème du noyau provoque le redémarrage d'Oracle Linux 7.6, ce qui entraîne une interruption des applications. Si le mécanisme kdump est activé, le kernel Panic génère un fichier vmcore situé dans le répertoire /var/crash/. Vous pouvez analyser le fichier vmcore pour déterminer la cause de l'incident. Après une interruption du noyau, vous pouvez redémarrer le système d'exploitation hôte et restaurer le système d'exploitation, puis redémarrer les applications selon vos besoins. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["11246134"^] | Pas de progression d'E/S sur Oracle Linux 7.6 avec le noyau UEK5U2, qui fonctionne avec un HBA Emulex LPe16002B-M6 Fibre Channel 16 Gbit/s lors des opérations de basculement du stockage | Lors des opérations de basculement de stockage sur Oracle Linux 7.6 avec le noyau UEK5U2 s'exécutant avec un adaptateur de bus hôte (HBA) Fibre Channel (FC) Emulex LPe16002B-M6 16 Gbit/s, la progression des E/S peut s'arrêter en raison du blocage des rapports. Le basculement de stockage signale un passage d'un état « en ligne » à un état « bloqué », entraînant un retard dans les opérations de lecture et d'écriture. Une fois l'opération terminée avec succès, les rapports ne parviennent pas à revenir à l'état « en ligne » et continuent de rester dans un état « bloqué ». 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | État du port distant sur l'hôte QLogic QLE2672 16 Gbit/s bloqué lors des opérations de basculement de stockage | Les ports distants Fibre Channel (FC) peuvent être bloqués sur Red Hat Enterprise Linux (RHEL) 7.6 avec un hôte QLogic QLE2672 16 Gbit/s lors des opérations de basculement de stockage. Étant donné que les interfaces logiques sont arrêtées lorsqu'un nœud de stockage est en panne, les ports distants définissent l'état du nœud de stockage sur bloqués. La progression des E/S peut s'arrêter en raison de ports bloqués si vous utilisez à la fois un hôte QLogic QLE2672 16G et un adaptateur de bus hôte (HBA) QLE2742 32 Gb Fibre Channel (FC). Lorsque le nœud de stockage revient à son état optimal, les interfaces logiques s'allument également et les ports distants doivent être en ligne. Cependant, il se peut que les ports distants soient toujours bloqués. Cet état bloqué s'enregistre comme étant défectueux pour LES LUN au niveau de la couche multivoie. Vous pouvez vérifier l'état des ports distants à l'aide de la commande suivante : # Cat /sys/class/fc_remote_ports/rport-*/port_stat vous devriez voir la sortie suivante : bloqué en ligne bloqué 
|===


== Et la suite ?

* link:hu-luhu-command-reference.html["Découvrez comment utiliser l'outil Linux Host Utilities"] .
* Découvrez la mise en miroir ASM
+
La mise en miroir de gestion automatique du stockage (ASM) peut nécessiter des modifications des paramètres de chemins d'accès multiples Linux pour permettre à ASM de reconnaître un problème et de basculer vers un autre groupe de pannes. La plupart des configurations ASM sur ONTAP utilisent une redondance externe, ce qui signifie que la protection des données est assurée par la baie externe et qu'ASM ne met pas en miroir les données. Certains sites utilisent ASM avec redondance normale pour fournir une mise en miroir bidirectionnelle, généralement entre différents sites. Voir link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bases de données Oracle sur ONTAP"^] pour plus d'informations.


