---
sidebar: sidebar 
permalink: hu_ol_81.html 
keywords: host utilities, oracle, linux, 8.1, netapp, ontap 
summary: 'Décrit l"utilisation d"Oracle Linux 8.1 avec ONTAP' 
---
= Utilisez Oracle Linux 8.1 avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser les paramètres de configuration de l'hôte SAN ONTAP pour configurer Oracle Linux 8.1 avec ONTAP comme cible.



== Installez les utilitaires hôtes Linux

Vous pouvez télécharger le progiciel Utilitaires hôtes NetApp Linux sous la forme d'un fichier 64-bit.rpm à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^].

NetApp recommande fortement d'installer les utilitaires hôtes Linux, mais ce n'est pas obligatoire. Les utilitaires ne modifient aucun paramètre sur votre hôte Linux. Ces utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

.Étapes
. Téléchargez le progiciel Linux Host Utilities 64 bits du https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] sur votre hôte.
. Installez le pack logiciel :
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Vous pouvez utiliser les paramètres de configuration fournis dans cette procédure pour configurer les clients cloud connectés à link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] et link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX pour ONTAP"^].



== Kit D'outils SAN

Le kit d'outils est installé automatiquement lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

.Exemple
Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[source, cli]
----
# sanlun lun show all
----
Exemple de résultat :

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN Booting

.Avant de commencer
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser link:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^]pour vérifier que votre se, votre HBA, le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+

NOTE: Plusieurs chemins deviennent disponibles une fois que le système d'exploitation hôte est en cours d'exécution sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage a réussi.




== Chemins d'accès multiples

Pour Oracle Linux 8.1, le fichier /etc/multipath.conf doit exister, mais vous n'avez pas besoin d'apporter de modifications spécifiques au fichier. Oracle Linux 8.1 est compilé avec tous les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP.

Vous pouvez utiliser `multipath -ll` la commande pour vérifier les paramètres de vos LUN ONTAP. Il devrait y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont actifs/optimisés. Cela signifie qu'ils sont gérés par le contrôleur où se trouve l'agrégat. Les chemins avec des priorités inférieures sont actifs mais non optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb 69:624 active ready running
| |- 16:0:5:35 sdun 66:752 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 15:0:0:35 sdaj 66:48 active ready running
|- 15:0:1:35 sdbx 68:176 active ready running
----

NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. La présence de plus de quatre chemins peut entraîner des problèmes de chemin pendant les pannes de stockage.



== Paramètres recommandés

Oracle Linux 8.1 OS est compilé pour reconnaître les LUN ONTAP et définir automatiquement tous les paramètres de configuration correctement.

Le `multipath.conf` fichier doit exister pour que le démon multichemin puisse démarrer. Si ce fichier n'existe pas, vous pouvez créer un fichier vide de zéro octet à l'aide de la `touch /etc/multipath.conf` commande.

Lors de la première création du `multipath.conf` fichier, vous devrez peut-être activer et démarrer les services multivoies en utilisant les commandes suivantes :

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
Vous n'avez pas besoin d'ajouter des éléments directement au `multipath.conf` fichier, sauf si vous avez des périphériques que vous ne souhaitez pas gérer le multipathing ou si vous avez des paramètres existants qui remplacent les paramètres par défaut. Pour exclure les périphériques indésirables, ajoutez la syntaxe suivante au `multipath.conf` fichier, en remplaçant <DevId> par la chaîne d'identifiant universel (WWID) du périphérique à exclure :

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
L'exemple suivant détermine le WWID d'un périphérique et l'ajoute au `multipath.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
----
+
`sda` Est le disque SCSI local que vous souhaitez ajouter à la liste noire.

. Ajoutez le `WWID` à la strophe de liste noire dans `/etc/multipath.conf`:
+
[source, cli]
----
blacklist {
     wwid   3600a098038314c4a433f5774717a3046
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Vérifiez toujours votre `/etc/multipath.conf` fichier, en particulier dans la section valeurs par défaut, pour les paramètres hérités qui peuvent remplacer les paramètres par défaut.

Le tableau suivant présente `multipathd` les paramètres critiques pour les LUN ONTAP et les valeurs requises. Si un hôte est connecté à des LUN d'autres fournisseurs et que l'un de ces paramètres est remplacé, il faut les corriger par les strophes ultérieures du `multipath.conf` fichier qui s'appliquent spécifiquement aux LUN ONTAP. Sans cette correction, les LUN ONTAP risquent de ne pas fonctionner comme prévu. Vous ne devez remplacer ces valeurs par défaut qu'en concertation avec NetApp, le fournisseur du système d'exploitation ou les deux, et uniquement lorsque l'impact est pleinement compris.

[cols="2*"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | « 2 pg_init_retries 50 » 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN.* 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
.Exemple
L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans ce cas, le `multipath.conf` fichier définit les valeurs pour `path_checker` et `no_path_retry` Non compatible avec les LUN ONTAP. S'ils ne peuvent pas être supprimés en raison d'autres baies SAN toujours connectées à l'hôte, ces paramètres peuvent être corrigés spécifiquement pour les LUN ONTAP avec une strophe de périphérique.

[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 no_path_retry queue
 path_checker tur
 }
}
----

NOTE: Pour configurer Oracle Linux 8.1 Red Hat compatible Kernel (RHCK), utilisez link:hu_rhel_81.html#recommended-settings["paramètres recommandés"]pour Red Hat Enterprise Linux (RHEL) 8.1.



== Problèmes connus

Il n'y a aucun problème connu pour Oracle Linux 8.1 avec la version ONTAP.


NOTE: Pour connaître les problèmes connus liés à Oracle Linux RHCK, consultez le link:hu_rhel_81.html#known-problems-and-limitations["problèmes connus"] pour RHEL 8.1.
