---
sidebar: sidebar 
permalink: hu_ol_76.html 
keywords: host utilities, oracle, linux, 7.6, netapp, ontap 
summary: 'Décrit l"utilisation d"Oracle Linux 7.6 avec ONTAP' 
---
= Utilisation d'Oracle Linux 7.6 avec NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Installation de Linux Unified Host Utilities

Le pack logiciel NetApp Linux Unified Host Utilities est disponible sur le link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["Site de support NetApp"^] dans un fichier .rpm 32 bits et 64 bits. Si vous ne savez pas quel fichier est adapté à votre configuration, utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp"^] pour vérifier celui dont vous avez besoin.

L'installation de Linux Unified Host Utilities est fortement recommandée, mais n'est pas obligatoire. Les utilitaires ne modifient aucun paramètre sur votre hôte Linux. Ces utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

.Ce dont vous avez besoin
Si une version de Linux Unified Host Utilities est actuellement installée, vous devez la mettre à niveau ou la supprimer et utiliser les étapes suivantes pour installer la dernière version.

. Téléchargez le pack logiciel Linux Unified Host Utilities 32 bits ou 64 bits à partir du link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["Site de support NetApp"^] Sur votre hôte.
. Utilisez la commande suivante pour installer le pack logiciel :
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Vous pouvez utiliser les paramètres de configuration fournis dans cette rubrique pour configurer les clients Cloud connectés à link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] et link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX pour ONTAP"^].



== Kit D'outils SAN

Le kit d'outils est installé automatiquement lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

.Exemple
Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
# sanlun lun show all
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN Booting

.Ce dont vous avez besoin
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser le link:https://mysupport.netapp.com/matrix/imt.jsp?components=86309;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] Pour vérifier que votre système d'exploitation, votre adaptateur de bus hôte, votre micrologiciel HBA, votre BIOS de démarrage HBA et votre version de ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+
N'oubliez pas que plusieurs chemins ne seront disponibles qu'après la mise en service et l'exécution du système d'exploitation hôte sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage est réussi.




== Chemins d'accès multiples

Pour Oracle Linux 7.6, le fichier /etc/multipath.conf doit exister, mais vous n'avez pas besoin d'apporter de modifications spécifiques au fichier. Oracle Linux 7.6 est compilé avec tous les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP.

Vous pouvez utiliser le `multipath -ll` Commande pour vérifier les paramètres des LUN ONTAP. Il devrait y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant les priorités les plus élevées sont actifs/optimisés, ce qui signifie qu'ils sont gérés par le contrôleur où se trouve l'agrégat. Les chemins avec les priorités les plus basses sont actifs, mais ne sont pas optimisés car ils sont servis à partir d'un autre contrôleur. Les chemins non optimisés sont utilisés uniquement lorsqu'aucun chemin optimisé n'est disponible.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: N'utilisez pas un nombre excessif de chemins pour une seule LUN. Pas plus de 4 chemins ne devraient être nécessaires. Plus de 8 chemins peuvent entraîner des problèmes de chemin pendant les défaillances du stockage.



== Paramètres recommandés

Oracle Linux 7.6 OS est compilé pour reconnaître les LUN ONTAP et définir automatiquement tous les paramètres de configuration correctement. Le `multipath.conf` le fichier doit exister pour que le démon multivoie démarre, mais vous pouvez créer un fichier vide de zéro octet à l'aide de la commande :
`touch /etc/multipath.conf`

Lors de la première création de ce fichier, vous devrez peut-être activer et démarrer les services multipathing.

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
Il n'y a aucune exigence d'ajouter directement quoi que ce soit au `multipath.conf` fichier, sauf si vous disposez de périphériques que vous ne voulez pas être gérés par multipath ou si vous avez des paramètres existants qui remplacent les paramètres par défaut.

Vous pouvez ajouter la syntaxe suivante à la `multipath.conf` fichier pour exclure les périphériques indésirables.

Remplacer l' `<DevId>` Avec la chaîne WWID du périphérique que vous souhaitez exclure. Utilisez la commande suivante pour déterminer l'identifiant WWID :

....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
.Exemple
Dans cet exemple, `sda` Est le disque SCSI local que nous devons ajouter à la liste noire.

.Étapes
. Exécutez la commande suivante pour déterminer l'identifiant WWID :
+
....
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
....
. Ajoutez cet identifiant WWID à la strophe de la liste noire dans le `/etc/multipath.conf`:
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


Vous devez toujours vérifier votre `/etc/multipath.conf` fichier pour les paramètres hérités, notamment dans la section par défaut, qui peut remplacer les paramètres par défaut.

Le tableau suivant indique le niveau critique `multipathd` Paramètres des LUN ONTAP et des valeurs requises. Si un hôte est connecté à des LUN d'autres fournisseurs et que l'un de ces paramètres est remplacé, il doit être corrigé par des strophes ultérieurs dans le `multipath.conf` Fichier qui s'applique spécifiquement aux LUN ONTAP. Si ce n'est pas le cas, les LUN de ONTAP peuvent ne pas fonctionner comme prévu. Ces valeurs par défaut ne doivent être remplacées qu'en consultation avec les fournisseurs de NetApp et/ou du système d'exploitation, et uniquement lorsque l'impact est totalement compris.

[cols="2*"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN.* 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
.Exemple
L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans ce cas, le `multipath.conf` fichier définit les valeurs pour `path_checker` et `detect_prio` Non compatible avec les LUN ONTAP. S'ils ne peuvent pas être supprimés en raison d'autres baies SAN toujours connectées à l'hôte, ces paramètres peuvent être corrigés spécifiquement pour les LUN ONTAP avec une strophe de périphérique.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Pour configurer Oracle Linux 7.6 RedHat Enterprise Kernel (RHCK), utilisez le link:hu_rhel_76.html#recommended-settings["paramètres recommandés"] Pour Red Hat Enterprise Linux (RHEL) 7.6.



== Problèmes connus et limites

[cols="4*"]
|===
| ID de bug NetApp | Titre | Description | ID Bugzilla 


| 1440718 | Si vous annulez le mappage d'une LUN ou si vous la mappez sans effectuer de nouvelle analyse SCSI, elle risque de corrompre les données de l'hôte. | Lorsque vous définissez le paramètre de configuration multivoie 'disable_changed_wwid' sur YES, il désactive l'accès au périphérique chemin d'accès en cas de modification de l'identifiant WWID. Les chemins d'accès multiples désactivent l'accès au périphérique de chemin d'accès jusqu'à ce que le WWID du chemin soit restauré vers le WWID du périphérique multichemin. Pour en savoir plus, voir link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["Base de connaissances NetApp : corruption du système de fichiers sur le LUN iSCSI sur Oracle Linux 7"^]. | S/O 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1202736["1202736"^] | Il est possible que les LUN ne soient pas disponibles lors de la découverte de l'hôte en raison de l'état « non présent » des ports distants sur un hôte OL7U6 équipé d'un adaptateur QLogic QLE2742 | Lors de la découverte de l'hôte, l'état des ports distants Fibre Channel (FC) d'un hôte OL7U6 avec un adaptateur QLogic QLE2742 peut devenir « non présent ». Les ports distants équipés d'un état « non présent » peuvent entraîner l'indisponibilité des chemins vers les LUN. Lors du basculement du stockage, la redondance des chemins peut être réduite et entraîner une panne d'E/S. Vous pouvez vérifier l'état du port distant en entrant la commande suivante : # Cat /sys/class/fc_remote_ports/rport-*/port_state. Voici un exemple de sortie qui s'affiche : Online non présent en ligne | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=16613["16613"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204078["1204078"^] | L'interruption du noyau se produit sur Oracle Linux 7.6 exécuté avec un adaptateur HBA FC 16 Go Qlogic (QLE2672) pendant les opérations de basculement du stockage | Lors des opérations de basculement de stockage sur Oracle Linux 7.6 avec un adaptateur de bus hôte Qlogic QLE2672 Fibre Channel (FC), une perturbation du noyau se produit en raison d'une panique dans le noyau. Le problème du noyau provoque le redémarrage d'Oracle Linux 7.6, ce qui entraîne une interruption des applications. Si le mécanisme kdump est activé, le kernel Panic génère un fichier vmcore situé dans le répertoire /var/crash/. Vous pouvez analyser le fichier vmcore pour déterminer la cause de l'incident. Après une interruption du noyau, vous pouvez redémarrer le système d'exploitation hôte et restaurer le système d'exploitation, puis redémarrer les applications selon vos besoins. | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=16606["16606"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204351["1204351"^] | Une interruption du noyau peut se produire sur Oracle Linux 7.6 exécuté avec la carte HBA FC 32 Gb Qlogic (QLE2742) pendant les opérations de basculement du stockage | Lors des opérations de basculement de stockage sur Oracle Linux 7.6 avec un adaptateur de bus hôte Qlogic QLE2742 (FC), une perturbation du noyau peut avoir lieu en raison d'un incident dans le noyau. Le problème du noyau provoque le redémarrage d'Oracle Linux 7.6, ce qui entraîne une interruption des applications. Si le mécanisme kdump est activé, le kernel Panic génère un fichier vmcore situé dans le répertoire /var/crash/. Vous pouvez analyser le fichier vmcore pour déterminer la cause de l'incident. Après une interruption du noyau, vous pouvez redémarrer le système d'exploitation hôte et restaurer le système d'exploitation, puis redémarrer les applications selon vos besoins. | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=16605["16605"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204352["1204352"^] | Une interruption du noyau peut se produire sur Oracle Linux 7.6 exécuté avec un HBA FC 32 Gb (LPe32002-M2)32 Gb lors des opérations de basculement de stockage | Lors des opérations de basculement de stockage sur Oracle Linux 7.6 avec un adaptateur de bus hôte (HBA) Fibre Channel (FC) Emulex LPe32002-M2, une perturbation du noyau peut se produire en raison d'un incident au niveau du noyau. Le problème du noyau provoque le redémarrage d'Oracle Linux 7.6, ce qui entraîne une interruption des applications. Si le mécanisme kdump est activé, le kernel Panic génère un fichier vmcore situé dans le répertoire /var/crash/. Vous pouvez analyser le fichier vmcore pour déterminer la cause de l'incident. Après une interruption du noyau, vous pouvez redémarrer le système d'exploitation hôte et restaurer le système d'exploitation, puis redémarrer les applications selon vos besoins. | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=16607["16607"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["11246134"^] | Pas de progression d'E/S sur Oracle Linux 7.6 avec le noyau UEK5U2, qui fonctionne avec un HBA Emulex LPe16002B-M6 Fibre Channel 16 Gbit/s lors des opérations de basculement du stockage | Lors des opérations de basculement de stockage sur Oracle Linux 7.6 avec le noyau UEK5U2 s'exécutant avec un adaptateur de bus hôte (HBA) Fibre Channel (FC) Emulex LPe16002B-M6 16 Gbit/s, la progression des E/S peut s'arrêter en raison du blocage des rapports. Le basculement de stockage signale un passage d'un état « en ligne » à un état « bloqué », entraînant un retard dans les opérations de lecture et d'écriture. Une fois l'opération terminée avec succès, les rapports ne parviennent pas à revenir à l'état « en ligne » et continuent de rester dans un état « bloqué ». | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=16852["16852"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | État du port distant sur l'hôte QLogic QLE2672 16 Gbit/s bloqué lors des opérations de basculement de stockage | Les ports distants Fibre Channel (FC) peuvent être bloqués sur Red Hat Enterprise Linux (RHEL) 7.6 avec un hôte QLogic QLE2672 16 Gbit/s lors des opérations de basculement de stockage. Étant donné que les interfaces logiques sont arrêtées lorsqu'un nœud de stockage est en panne, les ports distants définissent l'état du nœud de stockage sur bloqués. L'avancement des E/S peut s'arrêter en raison des ports bloqués si vous exécutez à la fois un hôte QLogic QLE2672 16 Gbit/s et un adaptateur de bus hôte (FC) Fibre Channel 32 Gbit/s QLE2742. Lorsque le nœud de stockage revient à son état optimal, les interfaces logiques s'allument également et les ports distants doivent être en ligne. Cependant, il se peut que les ports distants soient toujours bloqués. Cet état bloqué s'enregistre comme étant défectueux pour LES LUN au niveau de la couche multivoie. Vous pouvez vérifier l'état des ports distants à l'aide de la commande suivante : # Cat /sys/class/fc_remote_ports/rport-*/port_stat vous devriez voir la sortie suivante : bloqué en ligne bloqué | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=16853["16853"^] 
|===


== Notes de version



=== Mise en miroir ASM

La mise en miroir ASM peut nécessiter des modifications des paramètres de chemins d'accès multiples Linux pour permettre à ASM de reconnaître un problème et de basculer vers un autre groupe de défaillances. La plupart des configurations ASM sur ONTAP reposent sur une redondance externe. La protection des données est assurée par la baie externe et ASM ne met pas en miroir les données. Certains sites utilisent ASM avec redondance normale pour fournir une mise en miroir bidirectionnelle, généralement entre différents sites. Voir link:https://www.netapp.com/us/media/tr-3633.pdf["Les bases de données Oracle sur ONTAP"^] pour plus d'informations.
