---
sidebar: sidebar 
permalink: hu_ol_71.html 
keywords: Host Utilities, oracle, linux, 7.1, netapp, ontap 
summary: Installez Linux Host Utilities sur un hôte Oracle Linux 7.1 pour gérer les opérations de protocole FCP et iSCSI avec les LUN ONTAP. 
---
= Configurer Oracle Linux 7.1 pour FCP et iSCSI avec le stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le logiciel Linux Host Utilities fournit des outils de gestion et de diagnostic pour les hôtes Linux connectés au stockage ONTAP. Lorsque vous installez les utilitaires d'hôte Linux sur un hôte Oracle Linux 7.1, vous pouvez utiliser les utilitaires d'hôte pour vous aider à gérer les opérations de protocole FCP et iSCSI avec les LUN ONTAP.


NOTE: Vous n’avez pas besoin de configurer manuellement les paramètres de la machine virtuelle basée sur le noyau (KVM) car les LUN ONTAP sont automatiquement mappés à l’hyperviseur.



== Étape 1 : activez éventuellement le démarrage SAN

Vous pouvez configurer votre hôte pour qu'il utilise le démarrage SAN afin de simplifier le déploiement et d'améliorer l'évolutivité.

.Avant de commencer
Utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.

.Étapes
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Créez un LUN de démarrage SAN et mappez-le à l'hôte"^].
. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Vérifiez que la configuration a réussi en redémarrant l'hôte et en vérifiant que le système d'exploitation est opérationnel.




== Étape 2 : installez les utilitaires hôtes Linux

NetApp recommande vivement d'installer les utilitaires hôtes Linux pour prendre en charge la gestion des LUN ONTAP et aider le support technique à collecter les données de configuration.

link:hu_luhu_71.html["Installez Linux Host Utilities 7.1"].


NOTE: L'installation des utilitaires d'hôtes Linux ne modifie aucun paramètre de délai d'expiration de l'hôte sur votre hôte Linux.



== Étape 3 : confirmez la configuration des chemins d'accès multiples pour votre hôte

Vous pouvez utiliser les chemins d'accès multiples avec Oracle Linux 7.1 pour gérer les LUN ONTAP. Oracle Linux 7.1 prend en charge Unbreakable Enterprise Kernel (UEK) R3 et UEK R4. Par défaut, le système d'exploitation démarre avec le noyau UEK R3.


NOTE: Vous pouvez utiliser le link:hu_rhel_71.html#rhel-rhck["paramètres recommandés pour Red Hat Enterprise Linux (RHEL) 7.1"] pour configurer le noyau compatible Red Hat pour Oracle Linux 7.1.

.Étapes
Selon votre configuration, sélectionnez l'onglet UEK 3 ou UEK 4.

[role="tabbed-block"]
====
.UEK 3
--
Les paramètres d'Oracle Linux UEK 3 avec et sans ALUA se mettent à jour automatiquement. Après la mise à jour, vous devez activer le gestionnaire ALUA :

. Créez une sauvegarde de l'image initrd.
. Ajoutez la valeur de paramètre suivante au noyau pour ALUA et non-ALUA à fonctionner :
+
[source, cli]
----
rdloaddriver=scsi_dh_alua
----
+
.Exemple de sortie
[listing]
----
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
----
. Recréer l'image initrd :
+
[source, cli]
----
dracut -f
----
. Redémarrez l'hôte.
. Examiner la sortie de la  `cat /proc/cmdline` commande pour vérifier que le réglage est terminé.


--
.UEK 4
--
Pour Oracle Linux UEK 4, vérifiez que le  `/etc/multipath.conf` le fichier est défini et que les paramètres recommandés par NetApp sont configurés pour vos LUN ONTAP.

. Vérifiez que le `/etc/multipath.conf` fichier se ferme. Si le fichier n'existe pas, créez un fichier vide à zéro octet :
+
[source, cli]
----
touch /etc/multipath.conf
----
. Lors de la première `multipath.conf` création du fichier, vous devrez peut-être activer et démarrer les services multivoies pour charger les paramètres recommandés :
+
[source, cli]
----
chkconfig multipathd on
----
+
[source, cli]
----
/etc/init.d/multipathd start
----
. Chaque fois que vous démarrez l'hôte, le fichier vide `/etc/multipath.conf` à zéro octet charge automatiquement les paramètres de chemins d'accès multiples recommandés par NetApp comme paramètres par défaut. Vous ne devriez pas avoir besoin d'apporter de modifications au `/etc/multipath.conf` fichier de votre hôte car le système d'exploitation est compilé avec les paramètres multivoies qui reconnaissent et gèrent correctement les LUN ONTAP.
+
.Affiche les paramètres
[%collapsible]
=====
[cols="2"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | « 2 pg_init_retries 50 » 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
=====
. Vérifiez les paramètres et l'état du chemin de vos LUN ONTAP :
+
[source, cli]
----
multipath -ll
----
+
Les paramètres multi-trajets par défaut prennent en charge les configurations AFF et FAS. Dans ces configurations, une seule LUN ONTAP ne doit pas nécessiter plus de quatre chemins. S'il y a plus de quatre chemins, cela peut causer des problèmes avec les chemins en cas de panne de stockage.

+
Une configuration AFF ou FAS doit comporter deux groupes de chemins ayant des priorités plus élevées et moins élevées. Les chemins actifs/optimisés à priorité supérieure sont servis par le contrôleur où se trouve l'agrégat. Les chemins de priorité inférieure sont actifs mais non optimisés, car ils sont gérés par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque des chemins optimisés ne sont pas disponibles.

+
Les exemples de sortie suivants montrent les paramètres corrects et l'état du chemin pour les LUN ONTAP dans une configuration AFF ou FAS avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

+
.Montrer l'exemple
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
=====


--
====


== Étape 4 : si vous le souhaitez, excluez un périphérique du multipathing

Si nécessaire, vous pouvez exclure un périphérique du multipathing en ajoutant le WWID du périphérique indésirable à la strophe « blacklist » du `multipath.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" est le disque SCSI local que vous souhaitez ajouter à la liste noire.

+
Un exemple de WWID est `360030057024d0730239134810c0cb833`.

. Ajoutez le WWID à la strophe « blacklist » :
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Étape 5 : personnalisez les paramètres des chemins d'accès multiples pour les LUN ONTAP

Si votre hôte est connecté à des LUN d'autres fournisseurs et que l'un des paramètres de chemins d'accès multiples est remplacé, vous devez les corriger en ajoutant la strophe plus loin dans `multipath.conf` le fichier qui s'applique spécifiquement aux LUN ONTAP. Si vous ne le faites pas, les LUN ONTAP risquent de ne pas fonctionner comme prévu.

Vérifiez votre `/etc/multipath.conf` fichier, en particulier dans la section valeurs par défaut, pour les paramètres qui peuvent remplacer <<multipath-parameter-settings,paramètres par défaut pour les paramètres multivoies>>.


CAUTION: Vous ne devez pas remplacer les paramètres recommandés pour les LUN ONTAP. Ces paramètres sont requis pour optimiser les performances de votre configuration hôte. Pour plus d'informations, contactez le support NetApp, le fournisseur de votre système d'exploitation ou les deux.

L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans cet exemple, le `multipath.conf` fichier définit des valeurs pour `path_checker` et `no_path_retry` qui ne sont pas compatibles avec les LUN ONTAP, et vous ne pouvez pas supprimer ces paramètres car les baies de stockage ONTAP sont toujours connectées à l'hôte. Vous corrigez plutôt les valeurs de `path_checker` et `no_path_retry` en ajoutant une strophe de périphérique au `multipath.conf` fichier qui s'applique spécifiquement aux LUN ONTAP.

.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Étape 6 : passez en revue les problèmes connus

Il n'y a pas de problème connu.



== Et la suite ?

* link:hu-luhu-command-reference.html["Découvrez comment utiliser l'outil Linux Host Utilities"] .
* En savoir plus sur la mise en miroir ASM.
+
La mise en miroir de gestion automatique du stockage (ASM) peut nécessiter des modifications des paramètres de chemins d'accès multiples Linux pour permettre à ASM de reconnaître un problème et de basculer vers un autre groupe de pannes. La plupart des configurations ASM sur ONTAP utilisent une redondance externe, ce qui signifie que la protection des données est assurée par la baie externe et qu'ASM ne met pas en miroir les données. Certains sites utilisent ASM avec redondance normale pour fournir une mise en miroir bidirectionnelle, généralement entre différents sites. Voir link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bases de données Oracle sur ONTAP"^] pour plus d'informations.


