---
sidebar: sidebar 
permalink: hu_rhel_70.html 
keywords: host utilities, red hat, rhel, linux, 7.0, netapp, ontap 
summary: Décrit comment utiliser Red Hat Enterprise Linux 7.0 avec ONTAP 
---
= Utilisez Red Hat Enterprise Linux 7.0 avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser les paramètres de configuration de l'hôte SAN ONTAP pour configurer Red Hat Enterprise Linux 7.0 avec ONTAP comme cible.



== Installez Linux Unified Host Utilities

Le pack logiciel NetApp Linux Unified Host Utilities est disponible sur le link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] dans un fichier .rpm 32 bits et 64 bits. Si vous ne savez pas quel fichier est adapté à votre configuration, utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp"^] pour vérifier celui dont vous avez besoin.

NetApp recommande vivement d'installer les utilitaires d'hôtes unifiés Linux, mais ce n'est pas obligatoire. Les utilitaires ne modifient aucun paramètre sur votre hôte Linux. Ces utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

Si une version de Linux Unified Host Utilities est actuellement installée, vous devez la mettre à niveau ou la supprimer et suivre ces étapes pour installer la dernière version.

.Étapes
. Téléchargez le pack logiciel Linux Unified Host Utilities 32 bits ou 64 bits à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] Sur votre hôte.
. Utilisez la commande suivante pour installer le pack logiciel :
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Vous pouvez utiliser les paramètres de configuration fournis dans ce document pour configurer les clients Cloud connectés à link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] et link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX pour ONTAP"^].



== Kit D'outils SAN

Le kit d'outils est installé automatiquement lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

.Exemple
Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[source, cli]
----
# sanlun lun show all
----
Exemple de résultat :

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN Booting

.Ce dont vous avez besoin
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser le link:https://mysupport.netapp.com/matrix/imt.jsp?components=68128;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] Pour vérifier que votre système d'exploitation, votre adaptateur de bus hôte, votre micrologiciel HBA, votre BIOS de démarrage HBA et votre version de ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+

NOTE: Plusieurs chemins deviennent disponibles une fois que le système d'exploitation hôte est en cours d'exécution sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage a réussi.




== Chemins d'accès multiples

Pour Red Hat Enterprise Linux (RHEL) 7.0, le fichier /etc/multipath.conf doit exister, mais vous n'avez pas besoin d'apporter de modifications spécifiques au fichier. RHEL 7.0 est compilé avec tous les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP.

Vous pouvez utiliser le `multipath -ll` Commande pour vérifier les paramètres des LUN ONTAP.

Les sections suivantes fournissent des exemples de sorties multivoies pour une LUN mappée sur des rôles ASA et non ASA.



=== Configurations All SAN Array

Dans les configurations ASA (All SAN Array), tous les chemins d'accès à une LUN donnée sont actifs et optimisés. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP :

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G  features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. Plus de huit chemins peuvent entraîner des problèmes de chemin lors des défaillances du stockage.



=== Configurations non ASA

Pour les configurations non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont Active/Optimized (actif/optimisé), ce qui signifie que les services sont gérés par le contrôleur où se trouve l'agrégat. Les chemins aux priorités inférieures sont actifs, mais ne sont pas optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle’ hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj  8:144  active ready running
| |- 11:0:2:0 sdr  65:16  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 11:0:0:0 sdb  8:i6   active ready running
  |- 12:0:0:0 sdz  65:144 active ready running
----

NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. Plus de huit chemins peuvent entraîner des problèmes de chemin lors des défaillances du stockage.



== Paramètres recommandés

Le système d'exploitation RHEL 7.0 est compilé pour reconnaître les LUN ONTAP et définir automatiquement tous les paramètres de configuration pour les configurations ASA et non ASA.

Le `multipath.conf` fichier doit exister pour que le démon multichemin puisse démarrer. Si ce fichier n'existe pas, vous pouvez créer un fichier vide à zéro octet en utilisant la commande suivante :

`touch /etc/multipath.conf`

Lors de la première création du `multipath.conf` fichier, vous devrez peut-être activer et démarrer les services multivoies en utilisant les commandes suivantes :

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
Il n'est pas nécessaire d'ajouter quelque chose directement au `multipath.conf` fichier, sauf si vous disposez de périphériques que vous ne souhaitez pas gérer le multipathing ou si vous avez des paramètres existants qui remplacent les paramètres par défaut. Pour exclure les périphériques indésirables, ajoutez la syntaxe suivante au `multipath.conf` fichier, en remplaçant <DevId> par la chaîne WWID du périphérique à exclure :

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
.Exemple
L'exemple suivant détermine le WWID d'un périphérique et l'ajoute au `multipath.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` Est le disque SCSI local que vous souhaitez ajouter à la liste noire.

. Ajoutez le `WWID` à la strophe de liste noire dans `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Vous devez toujours vérifier votre `/etc/multipath.conf` fichier pour les paramètres hérités, en particulier dans la section valeurs par défaut, qui peut remplacer les paramètres par défaut.

Le tableau suivant présente `multipathd` les paramètres critiques pour les LUN ONTAP et les valeurs requises. Si un hôte est connecté à des LUN d'autres fournisseurs et que l'un de ces paramètres est remplacé, il faut les corriger par les strophes ultérieures du `multipath.conf` fichier qui s'appliquent spécifiquement aux LUN ONTAP. Sans cette correction, les LUN ONTAP risquent de ne pas fonctionner comme prévu. Vous ne devez remplacer ces valeurs par défaut qu'en concertation avec NetApp, le fournisseur du système d'exploitation ou les deux, et uniquement lorsque l'impact est pleinement compris.

[cols="2*"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN.* 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
.Exemple
L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans ce cas, le `multipath.conf` fichier définit les valeurs pour `path_checker` et `no_path_retry` Non compatible avec les LUN ONTAP. S'ils ne peuvent pas être supprimés en raison d'autres baies SAN toujours connectées à l'hôte, ces paramètres peuvent être corrigés spécifiquement pour les LUN ONTAP avec une strophe de périphérique.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== Paramètres KVM

Vous pouvez également utiliser les paramètres recommandés pour configurer la machine virtuelle basée sur le noyau (KVM). Aucune modification n'est nécessaire pour configurer KVM car le LUN est mappé à l'hyperviseur.



== Problèmes connus

La version RHEL 7.0 avec ONTAP présente les problèmes connus suivants :

[cols="3*"]
|===
| ID de bug NetApp | Titre | Description 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=844417["844417"^] | Lors d'une panne d'E/S impliquant un basculement du stockage, la carte hôte FC 16 Gbit/s d'Emulex (LPe16002B-M6) tombe en panne | Lors des opérations de basculement du stockage, il est possible d'observer une panne d'hôte Emulex (LPe16002B-M6) FC 16 Gbit/s 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=811587["811587"^] | Lors d'une panne d'E/S impliquant un basculement du stockage, la carte hôte FC 16 Gbit/s d'Emulex (LPe16002B-M6) tombe en panne | Lors des opérations de basculement du stockage, il est possible d'observer une panne d'hôte Emulex (LPe16002B-M6) FC 16 Gbit/s 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=803071["803071"^] | Lors d'une panne d'E/S impliquant un basculement du stockage, la carte hôte FC 16 Gbit/s d'Emulex (LPe16002B-M6) tombe en panne | Lors des opérations de basculement du stockage, il est possible d'observer une panne d'hôte Emulex (LPe16002B-M6) FC 16 Gbit/s 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=820163["820163"^] | Pannes de chemin ou d'accrochage d'hôte QLogic observées lors des E/S avec les opérations de basculement du stockage | Lors des opérations de basculement du stockage, il est possible que les hôtes soient suspendus ou défaillants sur un chemin hôte QLogic. Dans de tels scénarios, le message suivant peut s'afficher : « expiration du délai cmd de la boîte aux lettres, cmd=0x54, mb[0]=0x54 et vidage du micrologiciel enregistré dans le tampon temporaire », ce qui entraîne une interruption du chemin/de l'hôte. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=799323["799323"^] | Pannes de chemin ou de blocage de l'hôte FCoE d'Emulex (OCe10102-FX-D) observées lors des E/S avec les opérations de basculement de stockage | Lors des opérations d'E/S associées au basculement de stockage, il peut être possible que des pannes de chemin ou de blocage de l'hôte sur l'hôte Emulex 10G FCoE (OCe10102-FX-D) Dans de tels scénarios, le message suivant peut s'afficher : « le pool de mémoire tampon du pilote est vide, les bus d'E/S et l'état de la requête d'abandon de couche SCSI », ce qui entraîne des pannes de chemin/blocage de l'hôte. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=849212["849212"^] | Lors des opérations d'E/S par basculement du stockage, des pannes d'hôte ou de chemin FC 16 Gbit/s d'Emulex (LPe16002B-M6) sont observées | Lors des opérations de basculement de stockage, il est possible d'observer des défaillances sur un hôte ou sur un chemin d'accès bloqué (LPe16002B-M6) Emulex lors des E/S. Dans de tels scénarios, le message suivant peut s'afficher : « RSCN timeout Data and iotag x1301 is out of range: max iotag » messages qui entraîne des échecs de blocage/chemin de l'hôte. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836800["836800"^] | Anaconda affiche un message d'échec de connexion iSCSI bien que les connexions aient réussi lors de l'installation de RHEL 7.0 OS | Lorsque vous installez la racine(/) sur une LUN iSCSI multipath, l’adresse IP des interfaces Ethernet est spécifiée dans la ligne de commande du noyau afin que les adresses IP soient attribuées avant le démarrage du service iSCSI. Cependant, la fonction dracut ne peut pas attribuer d'adresses IP à tous les ports Ethernet pendant le démarrage, avant le démarrage du service iSCSI. La connexion iSCSI échoue alors sur les interfaces sans adresses IP. Vous verrez que le service iSCSI tente de se connecter plusieurs fois, ce qui entraînera un retard dans le délai de démarrage du système d'exploitation. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836875["836875"^] | Les adresses IP ne sont pas toujours attribuées lors du démarrage d'un système d'exploitation RHEL 7.0 installé sur une LUN iSCSI à chemins d'accès multiples | Lorsque vous installez RHEL 7.0, l'écran d'installation d'anaconda affiche que la connexion iSCSI à plusieurs adresses IP cibles a échoué bien que les connexions iSCSI aient réussi. Anaconda affiche le message d'erreur suivant : "Echec de la connexion au nœud" cette erreur n'est détectée que lorsque vous sélectionnez plusieurs adresses IP cibles pour la connexion iSCSI. Vous pouvez poursuivre l'installation du système d'exploitation en cliquant sur le bouton « ok ». Ce bug n'entrave pas l'installation d'iSCSI ou de RHEL 7.0 OS. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836657["836657"^] | Anaconda n'ajoute pas d'argument bootdev dans la ligne cmd du noyau pour définir l'adresse IP de RHEL 7.0 OS installée sur le LUN iSCSI multipath | Anaconda n'ajoute pas d'argument bootdev dans la ligne de commande du noyau où vous définissez l'adresse IPv4 pendant l'installation de RHEL 7.0 OS sur une LUN iSCSI multipath. Cela empêche l'attribution d'adresses IP à l'une des interfaces Ethernet configurées pour établir des sessions iSCSI avec le sous-système de stockage lors du démarrage de RHEL 7.0. Les sessions iSCSI ne étant pas établies, la LUN racine n'est pas détectée au démarrage du système d'exploitation, ce qui provoque l'échec du démarrage du système d'exploitation. 
|===