---
sidebar: sidebar 
permalink: hu_rhel_80.html 
keywords: host utilities, red hat, rhel, linux, 8.0, netapp, ontap 
summary: Décrit comment utiliser Red Hat Enterprise Linux 8.0 avec ONTAP 
---
= Utilisation de Red Hat Enterprise Linux 8.0 avec NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Installation de Linux Unified Host Utilities

Le pack logiciel NetApp Linux Unified Host Utilities est disponible sur le link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["Site de support NetApp"^] dans un fichier .rpm 64 bits.

L'installation de Linux Unified Host Utilities est fortement recommandée, mais n'est pas obligatoire. Les utilitaires ne modifient aucun paramètre sur votre hôte Linux. Ces utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

Si une version de Linux Unified Host Utilities est actuellement installée, vous devez la mettre à niveau ou la supprimer et utiliser les étapes suivantes pour installer la dernière version.

.Étapes
. Téléchargez le pack logiciel Linux Unified Host Utilities 64 bits à partir du https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["Site de support NetApp"^] à votre hôte.
. Utilisez la commande suivante pour installer le pack logiciel :
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Vous pouvez utiliser les paramètres de configuration fournis dans ce contenu pour configurer les clients cloud connectés à link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] et link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX pour ONTAP"^].



== Kit D'outils SAN

Le kit d'outils est installé automatiquement lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire, qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
# sanlun lun show all
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN Booting

Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser le link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] Pour vérifier que votre système d'exploitation, votre adaptateur de bus hôte, votre micrologiciel HBA, votre BIOS de démarrage HBA et votre version de ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+
N'oubliez pas que plusieurs chemins ne seront disponibles qu'après la mise en service et l'exécution du système d'exploitation hôte sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage est réussi.




== Chemins d'accès multiples

Pour Red Hat Enterprise Linux (RHEL) 8.0, le fichier /etc/multipath.conf doit exister, mais vous n'avez pas besoin d'apporter de modifications spécifiques au fichier. RHEL 8.0 est compilé avec tous les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP.

Vous pouvez utiliser le `multipath -ll` Commande pour vérifier les paramètres des LUN ONTAP. Les sections suivantes fournissent un exemple de résultat de chemins d'accès multiples pour une LUN mappée aux rôles ASA et non ASA.



=== Configuration de la baie SAN

Dans toutes les configurations ASA (SAN Array), tous les chemins d'accès à une LUN donnée sont actifs et optimisés. Autrement dit, les E/S peuvent être servies par tous les chemins simultanément, ce qui assure de meilleures performances.

L'exemple suivant montre la sortie correcte pour une LUN ONTAP :

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: N'utilisez pas un nombre excessif de chemins pour une seule LUN. Pas plus de 4 chemins ne devraient être nécessaires. Plus de 8 chemins peuvent entraîner des problèmes de chemin pendant les défaillances du stockage.



=== Configuration non ASA

Pour la configuration non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant les priorités les plus élevées sont actifs/optimisés, ce qui signifie qu'ils sont gérés par le contrôleur où se trouve l'agrégat. Les chemins avec les priorités les plus basses sont actifs, mais ne sont pas optimisés car ils sont servis à partir d'un autre contrôleur. Les chemins non optimisés sont utilisés uniquement lorsqu'aucun chemin optimisé n'est disponible.

L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: N'utilisez pas un nombre excessif de chemins pour une seule LUN. Pas plus de 4 chemins ne devraient être nécessaires. Plus de 8 chemins peuvent entraîner des problèmes de chemin pendant les défaillances du stockage.



== Paramètres recommandés

Le système d'exploitation RHEL 8.0 est compilé pour reconnaître les LUN ONTAP et définir automatiquement tous les paramètres de configuration pour les configurations ASA et non ASA.

Le `multipath.conf` le fichier doit exister pour que le démon multivoie démarre, mais vous pouvez créer un fichier vide de zéro octet à l'aide de la commande :
`touch /etc/multipath.conf`

Lors de la première création de ce fichier, vous devrez peut-être activer et démarrer les services multipathing.

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
Il n'est pas nécessaire d'ajouter directement quoi que ce soit `multipath.conf` fichier, sauf si vous disposez de périphériques que vous ne voulez pas être gérés par multipath ou si vous avez des paramètres existants qui remplacent les paramètres par défaut.

Vous pouvez ajouter la syntaxe suivante à la `multipath.conf` fichier pour exclure les périphériques indésirables.

Remplacer l' `<DevId>` Avec la chaîne WWID du périphérique que vous souhaitez exclure. Utilisez la commande suivante pour déterminer l'identifiant WWID :

....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
Dans cet exemple, `sda` Est le disque SCSI local que nous devons ajouter à la liste noire.

.Étapes
. Exécutez la commande suivante pour déterminer l'identifiant WWID :
+
....
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
....
. Ajoutez cet identifiant WWID à la strophe de la liste noire dans le `/etc/multipath.conf`:
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


Vous devez toujours vérifier votre `/etc/multipath.conf` fichier pour les paramètres hérités, notamment dans la section par défaut, qui peut remplacer les paramètres par défaut.

Le tableau ci-dessous indique la critique `multipathd` Paramètres des LUN ONTAP et des valeurs requises. Si un hôte est connecté à des LUN d'autres fournisseurs et que l'un de ces paramètres est remplacé, il doit être corrigé par des strophes ultérieurs dans `multipath.conf` Qui s'appliquent spécifiquement aux LUN ONTAP. Si ce n'est pas le cas, les LUN de ONTAP peuvent ne pas fonctionner comme prévu. Ces valeurs par défaut ne doivent être remplacées qu'en consultation avec les fournisseurs de NetApp et/ou du système d'exploitation, et uniquement lorsque l'impact est totalement compris.

[cols="2*"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | « 2 pg_init_retries 50 » 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN.* 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans ce cas, le `multipath.conf` fichier définit les valeurs pour `path_checker` et `no_path_retry` Non compatible avec les LUN ONTAP. S'ils ne peuvent pas être supprimés en raison d'autres baies SAN toujours connectées à l'hôte, ces paramètres peuvent être corrigés spécifiquement pour les LUN ONTAP avec une strophe de périphérique.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== Paramètres KVM

Vous pouvez également utiliser les paramètres recommandés pour configurer la machine virtuelle basée sur le noyau (KVM). Aucune modification n'est nécessaire pour configurer KVM car le LUN est mappé à l'hyperviseur.



== Problèmes connus et limites

[cols="4*"]
|===
| ID de bug NetApp | Titre | Description | ID Bugzilla 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1238719["1238719"^] | Perturbation du noyau sur RHEL8 avec QLogic QLE2672 16 Go FC pendant les opérations de basculement du stockage | Une interruption du noyau peut se produire lors des opérations de basculement du stockage sur un noyau Red Hat Enterprise Linux (RHEL) 8 avec un adaptateur de bus hôte QLE2672 QLogic. L'interruption du noyau entraîne le redémarrage du système d'exploitation. Le redémarrage entraîne une interruption de l'application et génère le fichier vmcore sous /var/crash/Directory si kdump est configuré. Utilisez le fichier vmcore pour identifier la cause de l'échec. Dans ce cas, l’interruption se situe dans le module “kmem_cache_alloc+160”. Il est connecté dans le fichier vmcore avec la chaîne suivante : « [exception RIP: Kmem_cache_alloc+160] ». Redémarrez le système d'exploitation hôte pour restaurer le système d'exploitation, puis redémarrez l'application. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1710009["1710009"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1226783["1226783"^] | RHEL8 OS démarre jusqu'au « mode d'urgence » lorsque plus de 204 périphériques SCSI sont mappés sur tous les adaptateurs de bus hôte (HBA) Fibre Channel (FC) | Si un hôte est mappé avec plus de 204 périphériques SCSI lors d'un processus de redémarrage du système d'exploitation, le système d'exploitation RHEL8 ne parvient pas à démarrer jusqu'au « mode normal » et passe en « mode d'urgence ». La plupart des services hôtes deviennent alors indisponibles. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1690356["1690356"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1230882["1230882"^] | Il est impossible de créer une partition sur un périphérique iSCSI à chemins d'accès multiples lors de l'installation de RHEL8. | Les périphériques iSCSI SAN LUN multichemin ne sont pas répertoriés dans la sélection de disque lors de l'installation de RHEL 8. Par conséquent, le service multichemin n'est pas activé sur le périphérique de démarrage SAN. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1709995["1709995"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1235998["1235998"^] | La commande « rescan-scsi-bus.sh -a » ne numérise pas plus de 328 périphériques | Si un hôte Red Hat Enterprise Linux 8 est mappé avec plus de 328 périphériques SCSI, la commande rescan-scsi-bus.sh -a du système d'exploitation hôte ne recherche que 328 périphériques. L'hôte ne détecte aucun périphérique mappé restant. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1709995["1709995"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1231087["1231087"^] | Les ports distants sont en transit vers un état bloqué sur RHEL8 avec Emulex LPe16002 16 Go FC pendant les opérations de basculement du stockage | Les ports distants sont en transit vers un état bloqué sur RHEL8 avec Emulex LPe16002 16 Go Fibre Channel (FC) pendant les opérations de basculement du stockage. Lorsque le nœud de stockage revient à un état optimal, les LIF sont également active et l'état du port distant doit lire « en ligne ». Il arrive que l'état du port distant continue à être « bloqué » ou « absent ». Cet état peut entraîner un chemin « défectueux » vers les LUN au niveau de la couche multivoie | link:https://bugzilla.redhat.com/show_bug.cgi?id=1702005["1702005"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1231098["1231098"^] | Les ports distants sont en transit vers l'état bloqué sur RHEL8 avec Emulex LPe32002 32 Go FC pendant les opérations de basculement du stockage | Les ports distants sont en transit vers un état bloqué sur RHEL8 avec Emulex LPe32002 32GBFibre Channel (FC) pendant les opérations de basculement de stockage. Lorsque le nœud de stockage revient à un état optimal, les LIF sont également active et l'état du port distant doit lire « en ligne ». Il arrive que l'état du port distant continue à être « bloqué » ou « absent ». Cet état peut entraîner un chemin « défectueux » vers les LUN au niveau de la couche multivoie. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1705573["1705573"^] 
|===


== Notes de version



=== Mise en miroir ASM

La mise en miroir ASM peut nécessiter des modifications des paramètres de chemins d'accès multiples Linux pour permettre à ASM de reconnaître un problème et de basculer vers un autre groupe de défaillances. La plupart des configurations ASM sur ONTAP reposent sur une redondance externe. La protection des données est assurée par la baie externe et ASM ne met pas en miroir les données. Certains sites utilisent ASM avec redondance normale pour fournir une mise en miroir bidirectionnelle, généralement entre différents sites. Voir link:https://www.netapp.com/us/media/tr-3633.pdf["Les bases de données Oracle sur ONTAP"^] pour plus d'informations.
