---
sidebar: sidebar 
permalink: hu_rhel_93.html 
keywords: host utilities, red hat, rhel, linux, 9.3, netapp, ontap, rhel 
summary: Décrit comment utiliser Red Hat Enterprise Linux 9.3 avec ONTAP 
---
= Utilisez Red Hat Enterprise Linux 9.3 avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser les paramètres de configuration de l'hôte SAN ONTAP pour configurer Red Hat Enterprise Linux 9.3 avec ONTAP comme cible.



== Installez les utilitaires hôtes Linux

Vous pouvez télécharger le progiciel Utilitaires hôtes NetApp Linux sous la forme d'un fichier 64-bit.rpm à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^].

NetApp recommande fortement d'installer les utilitaires hôtes Linux, mais ce n'est pas obligatoire. Les utilitaires ne modifient aucun paramètre sur votre hôte Linux. Ces utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

.Étapes
. Téléchargez le progiciel Linux Host Utilities 64 bits du https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] sur votre hôte.
. Installez le pack logiciel :
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== Kit D'outils SAN

L'installation du package des utilitaires hôtes NetApp installe automatiquement le kit d'outils. Ce kit fournit l' `sanlun`utilitaire qui vous aide à gérer les LUN et les adaptateurs de bus hôte (HBA).  `sanlun`La commande renvoie des informations sur les LUN mappées sur votre hôte, les chemins d'accès multiples et les informations nécessaires à la création des groupes initiateurs.

Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[source, cli]
----
# sanlun lun show all
----
*Exemple de sortie :*

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
vs_147_32glpe	         /vol/vol1/lun	 /dev/sdb	Host11  FCP        10g	cDOT
vs_147_32glpe	         /vol/vol1/lun	 /dev/sdx	Host11  FCP        10g	cDOT
vs_147_32glpe	         /vol/vol2/lun	 /dev/sdbt  host12 FCP        10g	cDOT
vs_147_32glpe	         /vol/vol2/lun	 /dev/sdax	host12  FCP        10g	cDOT
----


== Démarrage SAN

.Avant de commencer
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser le link:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre se, votre HBA, le micrologiciel HBA et le BIOS de démarrage de l'adaptateur HBA, ainsi que la version de ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+

NOTE: Plusieurs chemins deviennent disponibles une fois que le système d'exploitation hôte est en cours d'exécution sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage a réussi.




== Chemins d'accès multiples

Pour Red Hat Enterprise Linux (RHEL) 9.3, le `/etc/multipath.conf` le fichier doit exister, mais il n'est pas nécessaire d'apporter des modifications spécifiques au fichier. RHEL 9.3 est compilé avec tous les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP.

Vous pouvez utiliser le `multipath -ll` Commande pour vérifier les paramètres des LUN ONTAP.

Les sections suivantes fournissent des exemples de sorties multivoies pour une LUN mappée sur des rôles ASA et non ASA.



=== Configurations All SAN Array

Toutes les configurations de baie SAN (ASA) optimisent tous les chemins d'accès à une LUN donnée en les gardant actives. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

.Exemple
L'exemple suivant illustre la sortie correcte d'une LUN ONTAP.

[listing]
----
# multipath -ll
3600a098038314359725d516c69733471 dm-22 NETAPP,LUN C-Mode
size=160G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:3:0  sdau 66:224 active ready running
  |- 12:0:4:0  sdco 69:192 active ready running
  |- 12:0:0:0  sdav 66:240 active ready running
  `- 11:0:2:0  sdat 66:208 active ready running
----

NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. La présence de plus de quatre chemins peut entraîner des problèmes de chemin pendant les pannes de stockage.



=== Configurations non ASA

Pour les configurations non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont actifs/optimisés. Cela signifie qu'ils sont gérés par le contrôleur où se trouve l'agrégat. Les chemins avec des priorités inférieures sont actifs mais non optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés.

[listing]
----
# multipath -ll
3600a0980383149783224544d334a644d dm-10 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 12:0:0:18 sdbj 67:208 active ready running
| `- 11:0:1:18 sdan 66:112 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 11:0:0:18 sdt  65:48  active ready running
  `- 12:0:3:18 sdcf 69:48  active ready running

----

NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. La présence de plus de quatre chemins peut entraîner des problèmes de chemin pendant les pannes de stockage.



== Paramètres recommandés

Le système d'exploitation RHEL 9.3 est compilé pour reconnaître les LUN ONTAP et définir automatiquement tous les paramètres de configuration correctement pour les configurations ASA et non ASA. Les paramètres recommandés suivants vous permettent d'optimiser davantage les performances de votre configuration hôte.

Le `multipath.conf` fichier doit exister pour que le démon multichemin puisse démarrer. Si ce fichier n'existe pas, vous pouvez créer un fichier vide de zéro octet à l'aide de la `touch /etc/multipath.conf` commande.

Lors de la première création du `multipath.conf` fichier, vous devrez peut-être activer et démarrer les services multivoies en utilisant les commandes suivantes :

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
Il n'est pas nécessaire d'ajouter des périphériques directement au `multipath.conf` fichier, sauf si vous disposez de périphériques que vous ne souhaitez pas gérer les chemins d'accès multiples ou si vous avez des paramètres existants qui remplacent les paramètres par défaut. Vous pouvez exclure les périphériques indésirables en ajoutant la syntaxe suivante au `multipath.conf` fichier, en remplaçant <DevId> par la chaîne WWID du périphérique que vous souhaitez exclure :

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
Dans l'exemple suivant, vous déterminez le WWID d'un périphérique et ajoutez-le au `multipath.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
360030057024d0730239134810c0cb833
----
+
`sda` Est le disque SCSI local que vous souhaitez ajouter à la liste noire.

. Ajoutez le `WWID` à la strophe de liste noire dans `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Vous devez toujours vérifier votre `/etc/multipath.conf` fichier, en particulier dans la section valeurs par défaut, pour les paramètres hérités qui peuvent remplacer les paramètres par défaut.

Le tableau suivant présente `multipathd` les paramètres critiques pour les LUN ONTAP et les valeurs requises. Si un hôte est connecté à des LUN d'autres fournisseurs et que l'un de ces paramètres est remplacé, il faudra les corriger par les strophes ultérieures du `multipath.conf` fichier qui s'appliquent spécifiquement aux LUN ONTAP. Si ce n'est pas le cas, les LUN de ONTAP risquent de ne pas fonctionner comme prévu. Vous ne devez remplacer ces valeurs par défaut que si vous en avez connaissance avec NetApp et/ou un fournisseur de système d'exploitation, et ce uniquement lorsque vous en avez pleinement conscience.

[cols="2*"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | « 2 pg_init_retries 50 » 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN.* 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
.Exemple
L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans ce cas, le `multipath.conf` fichier définit les valeurs pour `path_checker` et `no_path_retry` Non compatible avec les LUN ONTAP. S'ils ne peuvent pas être supprimés parce que d'autres baies SAN sont toujours connectées à l'hôte, ces paramètres peuvent être corrigés spécifiquement pour les LUN ONTAP avec une strophe de périphérique.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry     fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry    queue
      path_checker     tur
   }
}
----


== Configurer les paramètres KVM

Il n'est pas nécessaire de configurer les paramètres d'une machine virtuelle basée sur kernel, car la LUN est mappée sur l'hyperviseur.



== Problèmes connus

La version RHEL 9.3 avec ONTAP présente les problèmes connus suivants :

[cols="20, 20, 50,20"]
|===
| ID de bug NetApp | Titre | Description | ID JIRA 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^] | L'interface de ligne de commande des utilitaires d'hôtes Linux de NetApp nécessite des dépendances de package de bibliothèque supplémentaires pour prendre en charge la détection des adaptateurs HBA (HBA) d'Emulex | Dans RHEL 9.x, l'interface de ligne de commande des utilitaires d'hôtes SAN NetApp Linux `sanlun fcp show adapter -v` échoue car les dépendances du package de bibliothèque prenant en charge la détection des adaptateurs de bus hôte (HBA) Emulex sont introuvables. | Sans objet 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1593771["1593771"^] | Un hôte SAN QLogic Red Hat Enterprise Linux 9.3 rencontre la perte de chemins multiples partiels lors des opérations de mobilité du stockage | Lors du basculement du contrôleur de stockage ONTAP, la moitié des chemins d'accès multiples devrait tomber en panne ou passer en mode de basculement, puis revenir au nombre complet de chemins pendant le workflow de rétablissement. Cependant, avec un hôte QLogic Red Hat Enterprise Linux (RHEL) 9.3, seuls les chemins multipaths partiels sont récupérés après un rétablissement de basculement de stockage. | RHEL 17811 
|===