---
sidebar: sidebar 
permalink: hu_solaris_62_rn.html 
keywords: host utilities, solaris, 6.2 netapp, ontap 
summary: Notes de version pour Solaris Host Utilities 6.2 
---
= Notes de mise à jour de Solaris Host Utilities 6.2
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Les notes de mise à jour décrivent les nouvelles fonctionnalités et améliorations, les problèmes résolus dans la version actuelle, les problèmes et limitations connus, ainsi que les mises en garde importantes relatives à la configuration et à la gestion de votre hôte Solaris spécifique avec votre système de stockage ONTAP.

Pour des informations spécifiques sur les versions et mises à jour du système d'exploitation prises en charge par les utilitaires hôtes, consultez le link:https://mysupport.netapp.com/matrix/imt.jsp?components=85803;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^].



== Problèmes et limites connus

Vous devez connaître les problèmes et limitations connus suivants susceptibles d'affecter les performances de votre hôte spécifique.

[cols="3"]
|===
| ID de bug | Titre | Description 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1385189["1385189"^] | Modifications de liaison du pilote FC Solaris 11.4 requises dans HUK 6.2 | Recommandations Solaris 11.4 et HUK :
La liaison du pilote FC est modifiée de `ssd(4D)` à `sd(4D)`. Déplacez la configuration dans laquelle vous vous êtes `ssd.conf` à `sd.conf` Comme indiqué dans Oracle (Doc ID 2595926.1). Le comportement varie entre les systèmes Solaris 11.4 nouvellement installés et les systèmes mis à niveau à partir de versions 11.3 ou inférieures. 
|===
link:https://mysupport.netapp.com/site/["NetApp bogues en ligne"^] fournit des informations complètes pour la plupart des problèmes connus, y compris des solutions de contournement suggérées si possible. Voici quelques combinaisons de mots-clés et types de bogue que vous pouvez utiliser :

* FCP General : affiche les bogues FC et HBA (Host bus adapter) qui ne sont pas associés à un hôte spécifique.
* FCP - Solaris

