---
sidebar: sidebar 
permalink: hu_sles_12SP3.html 
keywords: host utilities, suse linux enterprise server 12 SP3, suse, linux, 12 SP3, netapp, ontap 
summary: Installez Linux Host Utilities sur un SUSE Linux Enterprise Server 12 SP3 pour gérer les opérations de protocole FCP et iSCSI avec les LUN ONTAP. 
---
= Configurez SUSE Linux Enterprise Server 12 SP3 pour FCP et iSCSI avec stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le logiciel Linux Host Utilities fournit des outils de gestion et de diagnostic pour les hôtes Linux connectés au stockage ONTAP. Lorsque vous installez les utilitaires hôtes Linux sur un hôte SUSE Linux Enterprise Server 12 SP3, vous pouvez utiliser les utilitaires hôtes pour vous aider à gérer les opérations de protocole FCP et iSCSI avec les LUN ONTAP.



== Étape 1 : activez éventuellement le démarrage SAN

Vous pouvez configurer votre hôte pour qu'il utilise le démarrage SAN afin de simplifier le déploiement et d'améliorer l'évolutivité.

.Avant de commencer
Utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.

.Étapes
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Créez un LUN de démarrage SAN et mappez-le à l'hôte"^].
. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Vérifiez que la configuration a réussi en redémarrant l'hôte et en vérifiant que le système d'exploitation est opérationnel.




== Étape 2 : installez les utilitaires hôtes Linux

NetApp recommande vivement d'installer les utilitaires hôtes Linux pour prendre en charge la gestion des LUN ONTAP et aider le support technique à collecter les données de configuration.

link:hu_luhu_71.html["Installez Linux Host Utilities 7.1"].


NOTE: L'installation des utilitaires d'hôtes Linux ne modifie aucun paramètre de délai d'expiration de l'hôte sur votre hôte Linux.



== Étape 3 : confirmez la configuration des chemins d'accès multiples pour votre hôte

Vous pouvez utiliser les chemins d'accès multiples avec SUSE Linux Enterprise Server 12 SP3 pour gérer les LUN ONTAP.

Pour vous assurer que les chemins d'accès multiples sont correctement configurés pour votre hôte, vérifiez que le `/etc/multipath.conf` fichier est défini et que vous disposez des paramètres recommandés par NetApp pour vos LUN ONTAP.

.Étapes
. Vérifiez que le `/etc/multipath.conf` fichier existe :
+
[source, cli]
----
ls /etc/multipath.conf
----
+
Si le fichier n'existe pas, créez un fichier vide à zéro octet :

+
[source, cli]
----
touch /etc/multipath.conf
----
. Lors de la première `multipath.conf` création du fichier, vous devrez peut-être activer et démarrer les services multivoies pour charger les paramètres recommandés :
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Chaque fois que vous démarrez l'hôte, le fichier vide `/etc/multipath.conf` à zéro octet charge automatiquement les paramètres de chemins d'accès multiples recommandés par NetApp comme paramètres par défaut. Vous ne devriez pas avoir besoin d'apporter de modifications au `/etc/multipath.conf` fichier de votre hôte car le système d'exploitation hôte est compilé avec les paramètres multivoies qui reconnaissent et gèrent correctement les LUN ONTAP.
+
Le tableau suivant présente les paramètres de chemins d'accès multiples compilés par le système d'exploitation Linux natif pour les LUN ONTAP.

+
.Affiche les paramètres
[%collapsible]
====
[cols="2"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | « 2 pg_init_retries 50 » 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
====
. Vérifiez les paramètres et l'état du chemin de vos LUN ONTAP :
+
[source, cli]
----
multipath -ll
----
+
Les paramètres multi-trajets par défaut prennent en charge les configurations ASA, AFF et FAS . Dans ces configurations, un seul LUN ONTAP ne devrait pas nécessiter plus de quatre chemins. Le fait d'avoir plus de quatre chemins d'accès peut engendrer des problèmes en cas de panne de stockage.

+
Les résultats des exemples suivants montrent les paramètres et l'état de chemin corrects pour les LUN ONTAP dans une configuration ASA, AFF ou FAS.

+
[role="tabbed-block"]
====
.Configuration DE L'INFRASTRUCTURE ASA
--
Une configuration ASA optimise tous les chemins vers une LUN donnée en les gardant actifs. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----
--
.Configuration AFF ou FAS
--
Une configuration AFF ou FAS doit comporter deux groupes de chemins ayant des priorités plus élevées et moins élevées. Les chemins actifs/optimisés à priorité supérieure sont servis par le contrôleur où se trouve l'agrégat. Les chemins de priorité inférieure sont actifs mais non optimisés, car ils sont gérés par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque des chemins optimisés ne sont pas disponibles.

L'exemple suivant présente la sortie d'une LUN ONTAP avec deux chemins Active/Optimized et deux chemins Active/non optimisés :

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----
--
====




== Étape 4 : si vous le souhaitez, excluez un périphérique du multipathing

Si nécessaire, vous pouvez exclure un périphérique du multipathing en ajoutant le WWID du périphérique indésirable à la strophe « blacklist » du `multipath.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" est le disque SCSI local que vous souhaitez ajouter à la liste noire.

+
Un exemple de WWID est `360030057024d0730239134810c0cb833`.

. Ajoutez le WWID à la strophe « blacklist » :
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Étape 5 : personnalisez les paramètres des chemins d'accès multiples pour les LUN ONTAP

Si votre hôte est connecté à des LUN d'autres fournisseurs et que l'un des paramètres de chemins d'accès multiples est remplacé, vous devez les corriger en ajoutant la strophe plus loin dans `multipath.conf` le fichier qui s'applique spécifiquement aux LUN ONTAP. Si vous ne le faites pas, les LUN ONTAP risquent de ne pas fonctionner comme prévu.

Vérifiez votre `/etc/multipath.conf` fichier, en particulier dans la section valeurs par défaut, pour les paramètres qui peuvent remplacer <<multipath-parameter-settings,paramètres par défaut pour les paramètres multivoies>>.


CAUTION: Vous ne devez pas remplacer les paramètres recommandés pour les LUN ONTAP. Ces paramètres sont requis pour optimiser les performances de votre configuration hôte. Pour plus d'informations, contactez le support NetApp, le fournisseur de votre système d'exploitation ou les deux.

L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans cet exemple, le `multipath.conf` fichier définit des valeurs pour `path_checker` et `no_path_retry` qui ne sont pas compatibles avec les LUN ONTAP, et vous ne pouvez pas supprimer ces paramètres car les baies de stockage ONTAP sont toujours connectées à l'hôte. Vous corrigez plutôt les valeurs de `path_checker` et `no_path_retry` en ajoutant une strophe de périphérique au `multipath.conf` fichier qui s'applique spécifiquement aux LUN ONTAP.

.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Étape 6 : passez en revue les problèmes connus

La version SUSE Linux Enterprise Server 12 SP3 avec stockage ONTAP présente les problèmes connus suivants :

[cols="3*"]
|===
| ID de bug NetApp | Titre | Description 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089555["1089555"^] | Perturbation du noyau observée sur la version du noyau SLES12 SP3 avec Emulex LPe16002 16 Go FC lors du basculement du stockage | Une interruption du noyau peut se produire lors des opérations de basculement du stockage sur la version du noyau SLES12 SP3 avec HBA Emulex LPe16002. L'interruption du noyau entraîne un redémarrage du système d'exploitation, qui entraîne à son tour une interruption des applications. Si le kdump est configuré, l'interruption du noyau génère un fichier vmcore sous /var/crash/Directory. Vous pouvez étudier la cause de l'échec dans le fichier vmcore. Exemple : dans le cas observé, la perturbation du noyau a été observée dans le module “lpfc_sli_ringtxcmpl_put+51” et est consigné dans le fichier vmcore – exception RIP : lpfc_sli_ringtxcmpl_put+51. Restaurez le système d'exploitation après l'interruption du noyau en redémarrant le système d'exploitation hôte et en redémarrant l'application. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089561["1089561"^] | Perturbation du noyau observée sur la version du noyau SLES12 SP3 avec Emulex LPe32002 32 Go FC lors des opérations de basculement du stockage | Une interruption du noyau peut se produire lors des opérations de basculement du stockage sur la version du noyau SLES12 SP3 avec HBA Emulex LPe32002. L'interruption du noyau entraîne un redémarrage du système d'exploitation, qui entraîne à son tour une interruption des applications. Si le kdump est configuré, l'interruption du noyau génère un fichier vmcore sous /var/crash/Directory. Vous pouvez étudier la cause de l'échec dans le fichier vmcore. Exemple : dans le cas observé, la perturbation du noyau a été observée dans le module “lpfc_sli_free_hbq+76” et est consignée dans le fichier vmcore – exception RIP : lpfc_sli_free_hbq+76. Restaurez le système d'exploitation après l'interruption du noyau en redémarrant le système d'exploitation hôte et en redémarrant l'application. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117248["1117248"^] | Perturbation du noyau observée sur SLES12SP3 avec QLogic QLE2562 8 Go FC lors des opérations de basculement du stockage | Lors des opérations de basculement de stockage sur le noyau Sles12sp3 (kernel-default-4.4.82-6.3.1) avec l'adaptateur HBA QLogic QLE2562, la perturbation du noyau a été observée en raison d'un incident dans le noyau. Le noyau de panique a entraîné le redémarrage du système d'exploitation, entraînant une interruption des applications. Le incident du noyau génère le fichier vmcore sous le répertoire /var/crash/ si kdump est configuré. En cas de problème du noyau, le fichier vmcore peut être utilisé pour comprendre la cause de la défaillance. Exemple : dans ce cas, la panique a été observée dans le module "blk_Finish_request+289". Il est connecté dans le fichier vmcore avec la chaîne suivante : « exception RIP: blk_Finish_request+289 » après l'interruption du noyau, vous pouvez restaurer le système d'exploitation en redémarrant le système d'exploitation hôte. Vous pouvez redémarrer l'application si nécessaire. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117261["1117261"^] | Perturbation du noyau observée sur SLES12SP3 avec Qlogic QLE2662 16 Go FC lors des opérations de basculement du stockage | Lors des opérations de basculement de stockage sur le noyau Sles12sp3 (kernel-default-4.4.82-6.3.1) avec Qlogic QLE2662 HBA, vous pouvez observer les perturbations du noyau. Cette invite entraîne le redémarrage du système d'exploitation, qui entraîne une interruption des applications. L'interruption du noyau génère un fichier vmcore sous /var/crash/ Directory si kdump est configuré. Le fichier vmcore peut être utilisé pour comprendre la cause de la défaillance. Exemple : dans ce cas, l'interruption du noyau a été observée dans le module « adresse inconnue ou non valide » et est consignée dans le fichier vmcore avec la chaîne suivante - exception RIP : adresse inconnue ou non valide. Après une interruption du noyau, le système d'exploitation peut être restauré en redémarrant le système d'exploitation hôte et en redémarrant l'application selon les besoins. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117274["1117274"^] | Perturbation du noyau observée sur SLES12SP3 avec Emulex LPe16002 16 Go FC lors des opérations de basculement du stockage | Lors des opérations de basculement de stockage sur noyau Sles12sp3 (kernel-default-4.4.87-3.1) avec HBA Emulex LPe16002, vous pouvez observer une interruption du noyau. Cette invite entraîne le redémarrage du système d'exploitation, qui entraîne une interruption des applications. L'interruption du noyau génère un fichier vmcore sous le répertoire /var/crash/ si kdump est configuré. Le fichier vmcore peut être utilisé pour comprendre la cause de la défaillance. Exemple : dans ce cas, une perturbation du noyau a été observée dans le module “RAW_spin_lock_irqsave+30” et est consignée dans le fichier vmcore avec la chaîne suivante : – exception RIP : _RAW_spin_lock_irqsave+30. Après une interruption du noyau, le système d'exploitation peut être restauré en redémarrant le système d'exploitation hôte et en redémarrant l'application selon les besoins. 
|===


== Et la suite ?

* link:hu-luhu-command-reference.html["Découvrez comment utiliser l'outil Linux Host Utilities"] .
* Découvrez la mise en miroir ASM
+
La mise en miroir de gestion automatique du stockage (ASM) peut nécessiter des modifications des paramètres de chemins d'accès multiples Linux pour permettre à ASM de reconnaître un problème et de basculer vers un autre groupe de pannes. La plupart des configurations ASM sur ONTAP utilisent une redondance externe, ce qui signifie que la protection des données est assurée par la baie externe et qu'ASM ne met pas en miroir les données. Certains sites utilisent ASM avec redondance normale pour fournir une mise en miroir bidirectionnelle, généralement entre différents sites. Voir link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bases de données Oracle sur ONTAP"^] pour plus d'informations.

* Découvrez la virtualisation SUSE Linux (KVM)
+
SUSE Linux peut servir d'hôte KVM. Cela vous permet d'exécuter plusieurs machines virtuelles sur un seul serveur physique grâce à la technologie de machine virtuelle basée sur le noyau Linux (KVM). L'hôte KVM ne nécessite pas de paramètres de configuration hôte explicites pour les LUN ONTAP .


