---
sidebar: sidebar 
permalink: hu_solaris_62_cmd.html 
keywords: host utilities, unified, solaris, 6.2, netapp, ontap 
summary: Décrit comment utiliser Solaris Host Utilities 6.2 avec ONTAP 
---
= Référence de la commande Solaris Host Utilities 6.2
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser l'exemple de référence de commande Solaris Host Utilities 6.2 pour valider de bout en bout la configuration de stockage NetApp à l'aide de l'outil Utilitaires hôtes.



== Répertorie tous les initiateurs hôtes mappés sur l'hôte

Vous pouvez récupérer la liste de tous les initiateurs hôtes mappés sur un hôte.

[source, cli]
----
# sanlun fcp show adapter -v
----
*Exemple de sortie*

[listing]
----
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----


== Répertorie toutes les LUN mappées à l'hôte

Vous pouvez récupérer la liste de toutes les LUN mappées sur un hôte.

[source, cli]
----
# sanlun lun show -p -v all
----
*Exemple de sortie*

[listing]
----

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----


== Répertorie toutes les LUN mappées à l'hôte à partir d'un SVM donné/ répertorie tous les attributs d'une LUN mappée à l'hôte

Vous pouvez récupérer la liste de toutes les LUN mappées sur un hôte à partir d'un SVM spécifique.

[source, cli]
----
# sanlun lun show -p -v sanboot_unix`
----
*Exemple de sortie*

[listing]
----
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----


== Répertorie les attributs de LUN ONTAP par nom de fichier de périphérique hôte

Vous pouvez récupérer une liste de tous les attributs de LUN ONTAP en spécifiant un nom de fichier de périphérique hôte.

[source, cli]
----
# sanlun lun show all
----
*Exemple de sortie*

[listing]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                 /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc3            FCP      180.0g     cDOT
----