---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 'Décrit l"utilisation de Linux Unified Host Utilities 7.1 avec ONTAP' 
---
= Solaris Host Utilities 6.2
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


.Ce dont vous avez besoin, 8217;ll
* Pour un fonctionnement fiable, vous devez vérifier que l'ensemble de votre configuration iSCSI, FC ou FCoE est pris en charge.


Vous pouvez utiliser le link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["Matrice d'interopérabilité NetApp"^] pour vérifier votre configuration.



== Kit D'outils SAN

Solaris Host Utilities est un logiciel hôte NetApp qui fournit un kit d'outils de ligne de commande sur votre hôte Oracle Solaris. Le kit d'outils est installé lorsque vous installez le pack NetApp Host Utilities. Ce kit contient le `sanlun` Utilitaire qui vous aide à gérer les LUN et les HBA. Le `sanlun` La commande renvoie les informations relatives aux LUN mappées sur votre hôte, aux chemins d'accès multiples et aux informations nécessaires à la création des groupes initiateurs.

Dans l'exemple suivant, le `sanlun lun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
#sanlun lun show all
controller(7mode)/ device host lun
vserver(Cmode)                     lun-pathname       filename                                       adapter protocol size mode
-----------------------------------------------------------------------------------------------------------------------------------
data_vserver                     /vol/vol1/lun1     /dev/rdsk/c0t600A098038304437522B4E694E49792Dd0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol0/lun2     /dev/rdsk/c0t600A098038304437522B4E694E497938d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol2/lun3     /dev/rdsk/c0t600A098038304437522B4E694E497939d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol3/lun4     /dev/rdsk/c0t600A098038304437522B4E694E497941d0s2 qlc3   FCP       10g cDOT


----

NOTE: Ce kit est commun à toutes les configurations et tous les protocoles des utilitaires hôtes. En conséquence, une partie de son contenu s'applique à une configuration, mais pas à une autre. Le fait d'utiliser des composants non utilisés n'affecte pas les performances de votre système.



== Installation de Solaris Host Utilities

Solaris Host Utilities 6.2 prend en charge plusieurs environnements Solaris et plusieurs protocoles. Les environnements d'utilitaires hôtes principaux sont les suivants :

* Système d'exploitation natif avec MPxIO avec protocole Fibre Channel (FC) ou iSCSI sur un système utilisant un processeur SPARC ou x86/64.
* Veritas Dynamic Multipathing (DMP) avec le protocole FC ou iSCSI sur un système utilisant un processeur SPARC et avec le protocole iSCSI sur le système utilisant un processeur x86/64.



NOTE: Le pack logiciel NetApp Solaris Host Utilities est disponible sur le link:https://mysupport.netapp.com/site/["Site de support NetApp"^] dans un format de fichier compressé pour votre processeur. Vous pouvez télécharger le pack logiciel Host Utilities pour votre environnement sur le site de support.

.Étapes
. Connectez-vous à votre hôte en tant que root.
. Téléchargez une copie du fichier compressé contenant les utilitaires d'hôte à partir de link:https://mysupport.netapp.com/site/["Site de support NetApp"^] vers un répertoire de votre hôte.
+
Au moment de la préparation de cette documentation, les fichiers compressés étaient appelés :

+
** PROCESSEUR SPARC : `netapp_solaris_host_utilities_6_2_sparc.tar.gz`
** Processeur x86/x64 : `netapp_solaris_host_utilities_6_2_amd.tar.gz`


. Accédez au répertoire contenant le téléchargement.
. Décompressez le fichier à l'aide de la commande gunzip
+
`# gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz`

. Décompressez le fichier. Vous pouvez utiliser le `tar xvf` commande pour faire ça.
+
`# tar xvf netapp_solaris_host_utilities_6_2_sparc.tar`

. Ajoutez les paquets que vous avez extraits du fichier tar à votre hôte. Vous pouvez utiliser le `pkgadd` commande pour faire ça.
+
Les packages sont ajoutés à `/opt/NTAP/SANToolkit/bin` répertoire. L'exemple suivant utilise le `pkgadd` Pour installer le package d'installation Solaris :

+
`# pkgadd -d ./NTAPSANTool.pkg`

. Vérifiez que la boîte à outils a été installée avec succès à l'aide de l' `pkginfo` commande ou le `ls - al` commande.
+
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
. Une fois que vous avez terminé, vous devez configurer les paramètres de l'hôte pour votre environnement à l'aide de `/opt/NTAP/SANToolkit/bin/host_config` commande :
+
** Mpxio
** DMP Veritas


. Vérifiez l'installation :
+
`sanlun version`





== Exemple de référence de commande



=== Répertorie tous les initiateurs hôtes mappés sur l'hôte

[listing]
----
# sanlun fcp show adapter -v
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----


=== Répertorie toutes les LUN mappées à l'hôte

[listing]
----
# sanlun lun show -p -v all

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----


=== Répertorie toutes les LUN mappées à l'hôte à partir d'un SVM donné/ répertorie tous les attributs d'une LUN mappée à l'hôte

[listing]
----
# sanlun lun show -p -v sanboot_unix`
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----


=== Répertorie les attributs de LUN ONTAP par nom de fichier de périphérique hôte

[listing]
----
# sanlun lun show all

controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                 /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc3            FCP      180.0g     cDOT
----