---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Décrit comment utiliser Solaris Host Utilities 6.2 avec ONTAP 
---
= Installez Solaris Host Utilities 6.2 pour le stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les utilitaires d'hôte Solaris vous aident à gérer le stockage ONTAP attaché à un hôte Solaris et aident le support technique à collecter les données de configuration.

Les utilitaires hôtes Solaris prennent en charge plusieurs environnements Solaris et plusieurs protocoles de transport.  Voici les principaux environnements Solaris Host Utilities :

* Le système d'exploitation natif avec MPxIO et le protocole Fibre Channel (FC) ou iSCSI sur un système utilisant un processeur SPARC ou un processeur x86/64.
* Veritas Dynamic Multipathing (DMP) avec le protocole FC ou iSCSI sur un système utilisant un processeur SPARC, ou le protocole iSCSI sur un système utilisant un processeur x86/64.


Les utilitaires hôtes Solaris 6.2 prennent en charge les séries Solaris suivantes :

* Solaris 11.x
* Solaris 10.x


.Avant de commencer
Vérifiez que votre configuration iSCSI, FC ou FCoE est prise en charge.  Vous pouvez utiliser lelink:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier votre configuration.

.Étapes
. Connectez-vous à votre hôte en tant que root.
. Téléchargez une copie du fichier compressé contenant les utilitaires hôtes à partir dulink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["Site de support NetApp"^] vers un répertoire sur votre hôte Solaris :
+
[role="tabbed-block"]
====
.Processeur SPARC
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.processeur x86/x64
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. Accédez au répertoire de votre hôte Solaris contenant le téléchargement.
. Décompressez le fichier à l'aide du `gunzip` commande :
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
. Extraire le fichier en utilisant le `tar xvf` commande:
+
[source, cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----
. Ajoutez les packages que vous avez extraits du fichier tar à votre hôte
+
[source, cli]
----
pkgadd
----
+
Les packages sont ajoutés à `/opt/NTAP/SANToolkit/bin` répertoire.

+
L'exemple suivant utilise `pkgadd` la commande pour installer le progiciel d'installation Solaris :

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. Confirmez que la boîte à outils a été installée avec succès en utilisant l’une des commandes suivantes :
+
[source, cli]
----
pkginfo
----
+
[source, cli]
----
ls - al
----
+
.Afficher des exemples de sorties
[%collapsible]
====
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====
. Configurez les paramètres de l'hôte pour votre environnement MPxIO ou Veritas DMP :
+
[source, cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----
. Vérifiez l'installation :
+
[source, cli]
----
sanlun version
----




== Et la suite ?

link:hu-solaris-san-toolkit.html["En savoir plus sur la boîte à outils SAN"] .
