---
sidebar: sidebar 
permalink: hu_ubuntu_2404.html 
keywords: host utilities, red hat, rhel, linux, 20.04, netapp, ontap, ubuntu 
summary: Décrit comment utiliser Ubuntu 24.04 avec ONTAP 
---
= Utilisez Ubuntu 24.04 avec ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Vous pouvez utiliser les paramètres de configuration de l'hôte SAN ONTAP pour configurer Ubuntu 24.04 avec ONTAP comme cible.


NOTE: Le progiciel des utilitaires hôtes Linux de NetApp n'est pas disponible pour le système d'exploitation Ubuntu 24.04.



== Démarrage SAN

Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration.

.Avant de commencer
Utilisez le link:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation, votre adaptateur HBA, le micrologiciel de l'adaptateur HBA, le BIOS de démarrage de l'adaptateur HBA et la version de ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+

NOTE: Plusieurs chemins deviennent disponibles une fois que le système d'exploitation hôte est en cours d'exécution sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage a réussi.




== Chemins d'accès multiples

Pour Ubuntu 24.04, le `/etc/multipath.conf` fichier doit exister, mais vous n'avez pas besoin d'apporter des modifications au fichier car Ubuntu 24.04 est compilé avec les paramètres requis pour reconnaître et gérer correctement les LUN ONTAP.

Pour toutes les configurations de baies SAN (ASA) et non-ASA, vous pouvez utiliser la `multipath -ll` commande pour vérifier les paramètres d'une LUN ONTAP, comme indiqué dans les exemples suivants.


NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. Plus de quatre chemins peuvent entraîner des problèmes de chemin pendant des pannes de stockage.



=== Configurations ASA

Dans les configurations ASA, tous les chemins vers une LUN donnée sont actifs et optimisés. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

L'exemple suivant montre la sortie correcte pour une LUN ONTAP mappée à un rôle ASA :

[listing]
----
# # multipath -ll
3600a098038314559533f524d6c652f62 dm-24 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:1:13 sdm  8:192  active ready running
  |- 11:0:3:13 sdah 66:16  active ready running
  |- 12:0:1:13 sdbc 67:96  active ready running
  `- 12:0:3:13 sdbx 68:176 active ready running
----


=== Configurations non ASA

Pour les configurations non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont Active/Optimized (actif/optimisé), ce qui signifie que les services sont gérés par le contrôleur où se trouve l'agrégat. Les chemins aux priorités inférieures sont actifs, mais ne sont pas optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

L'exemple ci-dessous présente le résultat correct pour une LUN ONTAP avec deux chemins Active/Optimized et deux chemins Active/non optimisés mappés à un rôle non-ASA :

[listing]
----
# multipath -ll
3600a098038314837352453694b542f4a dm-0 NETAPP,LUN C-Mode
size=160G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 14:0:3:0 sdbk 67:224 active ready running
| `- 15:0:2:0 sdbl 67:240 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:0:0 sda  8:0    active ready running
  `- 15:0:1:0 sdv  65:80  active ready running
----


== Paramètres recommandés

Le système d'exploitation Ubuntu 24.04 est compilé pour reconnaître les LUN ONTAP et définir automatiquement tous les paramètres de configuration correctement pour les configurations ASA et non ASA. En outre, vous pouvez utiliser les paramètres recommandés suivants pour optimiser davantage les performances de votre configuration hôte.

Le `multipath.conf` fichier doit exister pour que le démon multichemin puisse démarrer. Si ce fichier n'existe pas, vous pouvez créer un fichier vide de zéro octet à l'aide de la `touch /etc/multipath.conf` commande.

Lors de la première création du `multipath.conf` fichier, vous devrez peut-être activer et démarrer les services multivoies en utilisant les commandes suivantes :

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
Il n'est pas nécessaire d'ajouter des périphériques directement au `multipath.conf` fichier, sauf si vous disposez de périphériques que vous ne souhaitez pas gérer les chemins d'accès multiples ou si vous avez des paramètres existants qui remplacent les paramètres par défaut. Vous pouvez exclure les périphériques indésirables en ajoutant la syntaxe suivante au `multipath.conf` fichier, en remplaçant <DevId> par la chaîne WWID du périphérique que vous souhaitez exclure :

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
Dans l'exemple suivant, vous déterminez le WWID d'un périphérique et ajoutez-le au `multipath.conf` fichier.

.Étapes
. Déterminez le WWID :
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
360030057024d0730239134810c0cb833
----
+
`sda` Est le disque SCSI local que vous souhaitez ajouter à la liste noire.

. Ajoutez le `WWID` à la strophe de liste noire dans `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Vous devez toujours vérifier votre `/etc/multipath.conf` fichier, en particulier dans la section valeurs par défaut, pour les paramètres hérités qui peuvent remplacer les paramètres par défaut.

Le tableau suivant présente `multipathd` les paramètres critiques pour les LUN ONTAP et les valeurs requises. Si un hôte est connecté à des LUN d'autres fournisseurs et que l'un de ces paramètres est remplacé, il faudra les corriger par les strophes ultérieures du `multipath.conf` fichier qui s'appliquent spécifiquement aux LUN ONTAP. Si ce n'est pas le cas, les LUN de ONTAP risquent de ne pas fonctionner comme prévu. Vous ne devez remplacer ces valeurs par défaut que si vous en avez connaissance avec NetApp et/ou un fournisseur de système d'exploitation, et ce uniquement lorsque vous en avez pleinement conscience.

[cols="2*"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | « 2 pg_init_retries 50 » 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN.* 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
L'exemple suivant montre comment corriger une valeur par défaut remplacée. Dans ce cas, le `multipath.conf` fichier définit des valeurs pour `path_checker` et `no_path_retry` qui ne sont pas compatibles avec les LUN ONTAP. S'ils ne peuvent pas être supprimés parce que d'autres baies SAN sont toujours connectées à l'hôte, ces paramètres peuvent être corrigés spécifiquement pour les LUN ONTAP avec une strophe de périphérique.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry     fail
}

devices {
   device {
      vendor         "NETAPP"
      product         "LUN"
      no_path_retry    queue
      path_checker     tur
   }
}
----


== Configurer les paramètres KVM

Il n'est pas nécessaire de configurer les paramètres d'une machine virtuelle basée sur kernel, car la LUN est mappée sur l'hyperviseur.



== Problèmes connus

Il n'y a pas de problèmes connus pour Ubuntu 24.04 avec la version ONTAP.
