---
sidebar: sidebar 
permalink: hu_vsphere_8.html 
keywords: host utilities, veritas, infoscale, 8.x, netapp, ontap, vmware, vspehere 
summary: 'Vous pouvez configurer les paramètres d"hôte SAN ONTAP pour la version VMware vSphere 8.x avec les protocoles FC, FCoE et iSCSI.' 
---
= Utilisez VMware vSphere 8.x avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez configurer les paramètres d'hôte SAN ONTAP pour la version VMware vSphere 8.x avec les protocoles FC, FCoE et iSCSI.



== Démarrage du SAN de l'hyperviseur

.Avant de commencer
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser link:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^]pour vérifier que votre se, votre HBA, le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP sont pris en charge.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+

NOTE: Plusieurs chemins deviennent disponibles une fois que le système d'exploitation hôte est en cours d'exécution sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage a réussi.




== Chemins d'accès multiples

ESXi fournit un module de chemins d'accès multiples extensible appelé Native Multipathing Plug-in (NMP) qui gère les sous-plug-ins, les Storage Array Type Plugins (SATPS) et les Path Selection Plugins (PSP). Par défaut, ces règles SATP sont disponibles dans ESXi.

Pour le stockage ONTAP, le plug-in « VMW_SATP_ALUA » est utilisé par défaut avec « VMW_PSP_RR » comme règle de sélection de chemin (PSP). Vous pouvez exécuter la commande suivante pour confirmer la PSP :

[listing]
----
`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`
----
Exemple de résultat :

[listing]
----
Name           Device  Vendor    Model         Driver  Transport  Options
---------------------------------------------------------------------------------
VMW_SATP_ALUA          LSI       INF-01-00                        reset_on_attempted_reserve  system
VMW_SATP_ALUA          NETAPP                                     reset_on_attempted_reserve  system

Rule Group  Claim Options  Default PSP  PSP Options     Description
------------------------------------------------------------------
tpgs_on        VMW_PSP_MRU                  NetApp E-Series arrays with ALUA support
tpgs_on        VMW_PSP_RR                   NetApp arrays with ALUA support
----


=== Configurations non ASA

Pour les configurations non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont actifs/optimisés. Cela signifie qu'ils sont gérés par le contrôleur où se trouve l'agrégat. Les chemins avec des priorités inférieures sont actifs mais non optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés.

[listing]
----
# esxcli storage nmp device list -d naa.600a0980383148693724545244395855
----
Exemple de résultat :

[listing]
----
naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=1: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L11, vmhba3:C0:T0:L11
   Is USB: false
----
[listing]
----
# esxcli storage nmp path list -d naa.600a0980383148693724545244395855
----
Exemple de résultat :

[listing, subs="+quotes"]
----
fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2003d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2002d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2001d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2000d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


=== Configurations All SAN Array

Toutes les configurations de baie SAN (ASA) optimisent tous les chemins d'accès à une LUN donnée en les gardant actives. Ce qui améliore les performances en assurant le service des opérations d'E/S sur tous les chemins en même temps.

.Exemple
L'exemple suivant illustre la sortie correcte d'une LUN ONTAP.

[listing]
----
esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453
----
Exemple de résultat :

[listing]
----
naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1001,TPG_state=AO}{TPG_id=1000,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=3: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L14, vmhba4:C0:T1:L14, vmhba3:C0:T0:L14, vmhba3:C0:T1:L14
   Is USB: false

----
[listing]
----
# esxcli storage nmp path list -d naa.600a098038314962485d543078486c7a
----
Exemple de résultat :

[listing, subs="+quotes"]
----
fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2015d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2017d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2014d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2016d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


== Vol

Les volumes virtuels (vVols) sont un type d'objet VMware qui correspond à un disque de machine virtuelle, à ses snapshots et à ses clones rapides.

Les outils ONTAP pour VMware vSphere incluent VASA Provider pour ONTAP, qui fournit le point d'intégration à VMware vCenter pour exploiter le stockage basé sur vvols. Lorsque vous déployez ONTAP Tools Open Virtualization Appliance (OVA), il est automatiquement enregistré auprès du serveur vCenter et active le fournisseur VASA.

Lorsque vous créez un datastore vVols à l'aide de l'interface utilisateur vCenter, il vous guide à créer des volumes FlexVol en tant que stockage de sauvegarde pour le datastore. Les hôtes ESXi accèdent aux vVols des datastores vVols à l'aide d'un terminal de protocole (PE). Dans les environnements SAN, une LUN de 4 Mo est créée sur chaque FlexVol du datastore pour une utilisation en tant que PE. Un SAN PE est une unité logique administrative (ALU). Les vVols sont des unités logiques secondaires (SLU).

Les exigences standard et les meilleures pratiques pour les environnements SAN s'appliquent lors de l'utilisation de vVvols, y compris (mais non limité à) les éléments suivants :

* Créer au moins une LIF SAN sur chaque nœud par SVM que vous prévoyez d'utiliser. Il est recommandé de créer au moins deux par nœud, mais pas plus que nécessaire.
* Éliminez tout point de défaillance unique. Utilisez plusieurs interfaces réseau VMkernel sur différents sous-réseaux réseau réseau qui utilisent le regroupement de cartes réseau lorsque plusieurs commutateurs virtuels sont utilisés, ou utilisez plusieurs cartes réseau physiques connectées à plusieurs commutateurs physiques pour fournir une haute disponibilité et un débit supérieur.
* Configurez le zoning, les VLAN ou les deux selon les besoins de la connectivité hôte.
* Vérifier que tous les initiateurs requis sont connectés aux LIFs cibles sur le SVM souhaité.



NOTE: Vous devez déployer des outils ONTAP pour VMware vSphere afin d'activer VASA Provider. Le fournisseur VASA gère tous vos paramètres iGroup. Il n'est donc pas nécessaire de créer ou de gérer les iGroups dans un environnement vVols.

NetApp ne recommande pas pour le moment de modifier les paramètres vVvols des valeurs par défaut.

Reportez-vous au https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour connaître les versions spécifiques des outils ONTAP ou du fournisseur VASA hérité pour vos versions spécifiques de vSphere et ONTAP.

Pour plus d'informations sur le provisionnement et la gestion des vVols, reportez-vous à la documentation relative aux outils ONTAP pour VMware vSphere. link:https://docs.netapp.com/us-en/netapp-solutions/hybrid-cloud/vsphere_ontap_ontap_for_vsphere.html["TR-4597"^], et link:https://www.netapp.com/pdf.html?item=/media/13555-tr4400pdf.pdf["TR-4400"^].



== Paramètres recommandés



=== Verrouillage ATS

Le verrouillage ATS est *obligatoire* pour le stockage compatible VAAI et la mise à niveau du VMFS5. Il est nécessaire pour une interopérabilité correcte et des performances optimales en E/S de stockage partagé VMFS avec des LUN ONTAP. Pour plus d'informations sur l'activation du verrouillage ATS, reportez-vous à la documentation VMware.

[cols="4*"]
|===
| Paramètres | Valeur par défaut | ONTAP recommandé | Description 


| HardwareAccélérationde localisation | 1 | 1 | Permet d'activer l'utilisation du verrouillage du test atomique et du réglage (ATS) 


| IOPS du disque | 1000 | 1 | Limite d'IOPS : la valeur par défaut de Round Robin PSP est de 1000 IOPS. Dans ce cas par défaut, un nouveau chemin est utilisé après l'émission des opérations d'E/S 1000. 


| Disk/QFullSampleSize | 0 | 32 | Nombre de FILES D'ATTENTE PLEINES ou OCCUPÉES qu'il faut avant que ESXi ne commence à limiter. 
|===

NOTE: Activer `Space-alloc` Paramètre de toutes les LUN mappées à VMware vSphere for `UNMAP` au travail. Pour plus d'informations, reportez-vous à la documentation ONTAP.



=== Délais d'expiration du système d'exploitation invité

Vous pouvez configurer manuellement les machines virtuelles à l'aide des réglages de système d'exploitation invités recommandés. Après avoir effectué les mises à jour, vous devez redémarrer l'invité pour que les mises à jour prennent effet.

*Valeurs de temporisation GOS :*

[cols="2*"]
|===
| Type de système d'exploitation invité | Délais d'attente 


| Variantes Linux | expiration du délai du disque = 60 


| Répertoires de base | expiration du délai du disque = 60 


| Solaris | expiration du délai du disque = 60 tentatives d'essai en cours = 300 tentatives d'essai non prêtes = 300 tentatives de réinitialisation = 30 accélération max. = 32 min. d'accélérateur = 8 
|===


=== Validez le réglage vSphere

Vous pouvez utiliser la commande suivante pour vérifier le `HardwareAcceleratedLocking` réglage.

`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`

[listing, subs="+quotes"]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: *1*
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== Validez le paramètre IOPS du disque

Vous pouvez utiliser la commande suivante pour vérifier le paramètre IOPS.

`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`

[listing, subs="+quotes"]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,*iops=1*,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== Valider la QFullSampleSize

Vous pouvez utiliser la commande suivante pour vérifier QFullSampleSize.

`esxcli system settings  advanced list --option /Disk/QFullSampleSize`

[listing, subs="+quotes"]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: *32*
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== Problèmes connus

La version VMware vSphere 8.x avec ONTAP présente les problèmes connus suivants :

[cols="10,30,30"]
|===
| ID de bug NetApp | Titre | Description 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1543660["1543660"^] | Une erreur d'E/S se produit lorsque les machines virtuelles Linux utilisant des adaptateurs vNVMe rencontrent une fenêtre long All paths Down (APD)  a| 
Les machines virtuelles Linux exécutant vSphere 8.x et versions ultérieures et utilisant des adaptateurs virtuels NVMe (vNVME) rencontrent une erreur d'E/S, car l'opération de nouvelle tentative vNVMe est désactivée par défaut. Pour éviter une interruption sur les machines virtuelles Linux exécutant des noyaux plus anciens lors d'une panne de tous les chemins (APD) ou d'une charge d'E/S importante, VMware a introduit un « VSCSIDisableNvmeRetry » ajustable pour désactiver l'opération de nouvelle tentative vNVMe.

|===
.Informations associées
* link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["Tr-4597-VMware vSphere avec ONTAP"^]
* link:https://kb.vmware.com/s/article/2031038["Prise en charge de VMware vSphere 5.x, 6.x et 7.x avec NetApp MetroCluster (2031038)"^]
* link:https://kb.vmware.com/s/article/83370["NetApp ONTAP avec synchronisation active NetApp SnapMirror avec VMware vSphere Metro Storage Cluster (vMSC)"^]

