---
sidebar: sidebar 
permalink: hu_veritas_6x.html 
keywords: host utilities, veritas, infoscale, 6.x, netapp, ontap, san, lun, multipathing, iscsi 
summary: Fournit des conseils sur les paramètres de configuration hôte SAN de ONTAP pour la version Veritas Infoscale 6 
---
= Utilisez Veritas Storage Foundation 6 pour Linux avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser les paramètres de configuration des hôtes SAN ONTAP pour la version 6 de Veritas Storage Foundation pour les plateformes Red Hat Enterprise Linux et Oracle Linux (basées sur le noyau compatible Red Hat) avec les protocoles FC, FCoE et iSCSI.



== Installez les utilitaires hôtes Linux

Vous pouvez télécharger le progiciel Utilitaires hôtes NetApp Linux sous la forme d'un fichier 64-bit.rpm à partir du link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^].

NetApp recommande fortement d'installer les utilitaires hôtes Linux, mais ce n'est pas obligatoire. Les utilitaires ne modifient aucun paramètre sur votre hôte Linux. Ces utilitaires améliorent la gestion et aident le support client NetApp à collecter des informations sur votre configuration.

.Étapes
. Téléchargez le progiciel Linux Host Utilities 64 bits du https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^] sur votre hôte.
. Installez le pack logiciel :
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== Kit D'outils SAN

L'installation du package des utilitaires hôtes NetApp installe automatiquement le kit d'outils. Ce kit fournit l' `sanlun`utilitaire qui vous aide à gérer les LUN et les adaptateurs de bus hôte (HBA).  `sanlun`La commande renvoie des informations sur les LUN mappées sur votre hôte, les chemins d'accès multiples et les informations nécessaires à la création des groupes initiateurs.

.Exemple
Dans l'illustration suivante, le `sanlun show` La commande renvoie les informations relatives à la LUN.

[listing]
----
# sanlun show -p -v SFRAC:/vol/fen1/lun1

              ONTAP Path: SFRAC:/vol/fen1/lun1
                     LUN: 0
                LUN Size: 10g
                 Product: cDOT
                DMP NODE: sfrac0_47
      Multipath Provider: Veritas
----------  ------  ---------  ------  -------------------------------------
Veritas     host    vserver    host:
path        path    path     /dev/   chan:     vserver           major:
state       state   type     node    id:lun    LIF                   minor
----------  ------  ---------  ------  -------------------------------------
enabled     up      active/non-optimized sdea   14:0:1:0   lif_10    128:32
enabled (a) up      active/optimized     sdcj   14:0:0:0   lif_2      69:112
enabled (a) up      active/optimized     sdb    13:0:0:0   lif_1       8:16
enabled     up      active/non-optimized sdas   13:0:1:0   lif_9      66:192
----


== SAN Booting

.Avant de commencer
Si vous décidez d'utiliser le démarrage SAN, celui-ci doit être pris en charge par votre configuration. Vous pouvez utiliser link:https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^]pour vérifier que votre se, votre HBA, le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP sont pris en charge.

Consultez le portail de support Veritas (matrice de produits, recherche de plateforme, matrice HCL) pour vérifier la prise en charge de la configuration de démarrage SAN et les mises en garde connues.

.Étapes
. Mappez la LUN de démarrage SAN sur l'hôte.
. Vérifiez que plusieurs chemins sont disponibles.
+

NOTE: Plusieurs chemins deviennent disponibles une fois que le système d'exploitation hôte est opérationnel sur les chemins.

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l'hôte pour vérifier que le démarrage a réussi.




== Chemins d'accès multiples

Vous devez vérifier que votre configuration répond à la configuration système requise. Pour plus d'informations, reportez-vous à https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] la et à la matrice Veritas HCL.

.Exemple
Dans l'exemple suivant, la `vxdmpadm` commande est utilisée pour vérifier que le chemin d'accès multiple VxDMP est associé à la baie cible ONTAP.

[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
----
[listing]
----
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
Avec Veritas Dynamic Multipathing (VxDMP), vous devez effectuer des tâches de configuration afin de réclamer des LUN NetApp comme périphériques Veritas Multipath. Vous devez disposer de l'ASL (Array support Library) et des packages APM (Array Policy module) installés par Veritas pour les systèmes de stockage NetApp. Pendant que l'installation du logiciel Veritas charge les packages ASL APM par défaut avec le produit, il est recommandé d'utiliser les derniers packages pris en charge répertoriés sur le portail d'assistance Veritas.

.Exemple
L'exemple suivant montre la configuration de Veritas support Library (ASL) et de Array Policy module (APM).

[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
----
[listing]
----
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so              vm-7.4-rev-1    6.1

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
----
[listing]
----
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----


=== Configurations non ASA

Pour les configurations non ASA, il doit y avoir deux groupes de chemins avec des priorités différentes. Les chemins ayant des priorités plus élevées sont Active/Optimized (actif/optimisé), ce qui signifie que les services sont gérés par le contrôleur où se trouve l'agrégat. Les chemins aux priorités inférieures sont actifs, mais ne sont pas optimisés, car ils sont desservis par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque les chemins optimisés ne sont pas disponibles.

.Exemple
L'exemple suivant montre la sortie correcte pour une LUN ONTAP avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés.

[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----

NOTE: Une seule LUN ne doit pas nécessiter plus de quatre chemins. La présence de plus de quatre chemins peut entraîner des problèmes de chemin pendant les pannes de stockage.



=== Paramètres recommandés



==== Paramètres pour Veritas Multipath

Pour une configuration système optimale dans les opérations de basculement du stockage, NetApp recommande les tunables VxDMP suivants.

[cols="2*"]
|===
| Paramètre | Réglage 


| dmp_lun_retry_timeout | 60 


| chemin_dmp_age | 120 


| intervalle_restauration_dmp | 60 
|===
Les tunables DMP sont définis en ligne à l'aide du `vxdmpadm` commande comme suit :

`# vxdmpadm settune dmp_tunable=value`

Les valeurs de ces données réglables peuvent être vérifiées de façon dynamique à l'aide de `#vxdmpadm gettune`.

.Exemple
L'exemple suivant montre les tunables DMP effectifs VxRables sur l'hôte SAN.

[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----


==== Paramètres par protocole

* Pour FC/FCoE uniquement : utilisez les valeurs de délai par défaut.
* Pour iSCSI uniquement : permet de définir le `replacement_timeout` valeur du paramètre à 120.
+
ISCSI `replacement_timeout` Paramètre contrôle la durée pendant laquelle la couche iSCSI doit attendre qu'un chemin ou une session ait expiré pour se rétablir avant d'échouer toute commande sur celle-ci. Réglage de la valeur de `replacement_timeout` Dans le fichier de configuration iSCSI, 120 est recommandé.



.Exemple
[listing]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----


==== Paramètres par plate-forme de système d'exploitation

Pour les séries Red Hat Enterprise Linux 7 et 8, vous devez configurer `udev rport` Valeurs pour prendre en charge l'environnement Veritas Infoscale dans les scénarios de basculement du stockage. Créez le fichier `/etc/udev/rules.d/40-rport.rules` avec le contenu du fichier suivant :

[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----

NOTE: Pour tous les autres paramètres spécifiques à Veritas, reportez-vous à la documentation standard du produit Veritas Infoscale.



== Coexistence de chemins d'accès multiples

Si vous disposez d'un environnement multi-chemins hétérogène, notamment Veritas InfoScale, Linux Native Device Mapper et le gestionnaire de volumes LVM, consultez la documentation d'administration des produits Veritas pour connaître les paramètres de configuration.



== Problèmes connus

Il n'existe aucun problème connu pour Veritas Storage Foundation 6 pour Linux avec la version ONTAP.
