---
sidebar: sidebar 
permalink: hu_wuhu_71.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: 'Windows Host Utilities inclut un programme d"installation qui définit les paramètres de registre et de HBA Windows requis afin que l"hôte Windows gère correctement le comportement du système de stockage pour les plateformes ONTAP et E-Series.' 
---
= Installer Windows Host Utilities 7.1 pour le stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les utilitaires hôtes Windows vous permettent de connecter un ordinateur hôte Windows à des systèmes de stockage NetApp.

Windows Host Utilities prend en charge les versions suivantes de Windows :

* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Windows Host Utilities inclut un programme d'installation qui définit les paramètres de registre Windows et d'adaptateur de bus hôte (HBA) requis afin qu'un hôte Windows puisse gérer correctement les comportements du système de stockage pour les plateformes ONTAP et E-Series.

Lorsque vous installez le logiciel Host Utilities, le programme d'installation définit le registre Windows et les paramètres HBA requis.

Les programmes et fichiers suivants sont installés sur l'ordinateur hôte Windows. Le répertoire par défaut est `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programme | Objectif 


| `emulexhba.reg` | Programme de dépannage ; exécutez ce programme uniquement si le personnel du support technique vous y invite. 


| `\NetAppQCLI\fcconfig.exe` | Utilisé par le programme d'installation pour définir les paramètres HBA. 


| `\NetAppQCLI\fcconfig.ini` | Utilisé par le programme d'installation pour définir les paramètres HBA. 


| `\NetAppQCLI\*.*` | Utilisé par le programme d'installation pour définir les paramètres HBA FC QLogic. 


| `san_version.exe` | Affiche la version des utilitaires hôtes et des HBA FC. 
|===
Les utilitaires hôtes prennent en charge différentes configurations d'hôtes Windows, différents protocoles et différentes options de chemins d'accès multiples. Pour obtenir la liste actuelle des configurations prises en charge, reportez-vous au https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].



== Étape 1 : Vérifiez les configurations de votre hôte et de votre système de stockage

Vérifiez que la configuration de l'hôte et du système de stockage est prise en charge avant d'installer Windows Host Utilities pour le <<supported-windows-versions-71,Version de Windows prise en charge>>.

.Étapes
. Vérifiez la configuration prise en charge dans le http://mysupport.netapp.com/matrix["Matrice d'interopérabilité"^].
. Vérifiez les correctifs requis pour votre version d'hôte Windows Server dans lelink:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentation Windows de l'hôte SAN"] .
+
Par exemple, lelink:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Configurer Windows Server 2022 pour le stockage ONTAP"] la documentation fournit les instructions pour l'installation des correctifs Windows pour Windows Server 2022.

. link:https://docs.netapp.com/us-en/ontap/san-admin/verify-license-fc-iscsi-task.html["Ajouter la licence iSCSI ou FCP"^] .
+

NOTE: Les protocoles FC et iSCSI ne nécessitent pas de licences sur les systèmes de stockage de la série E utilisant SANtricity Storage Manager.

. Démarrer le service cible.
. Vérifiez votre câblage.
+
Se référer à la https://docs.netapp.com/us-en/ontap/san-config/index.html["Référence de configuration SAN"^] pour des informations détaillées sur le câblage et la configuration.





== Étape 2 : Configurer les HBA et les commutateurs FC

Installez et configurez un ou plusieurs adaptateurs de bus hôte FC pris en charge pour les connexions FC au système de stockage.

Le programme d'installation de Windows Host Utilities définit les paramètres de carte HBA FC requis.


CAUTION: Vous devez uniquement autoriser le programme d’installation de Windows Host Utilities à définir les paramètres HBA.  Cela garantit que l'hôte Windows peut gérer correctement les comportements du système de stockage pour les plates-formes ONTAP .

.Étapes
. Installez une ou plusieurs cartes HBA FC prises en charge conformément aux instructions fournies par le fournisseur de cartes HBA.
. Obtenez les pilotes HBA et les utilitaires de gestion pris en charge et installez-les conformément aux instructions fournies par le fournisseur de l'adaptateur HBA.
. https://docs.netapp.com/us-en/ontap/san-management/index.html["Connectez les HBA à vos commutateurs FC ou directement au système de stockage"^] .
. https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["Créez des zones sur le commutateur FC conformément à la documentation de votre commutateur FC"^] .
. Pour ONTAP, zonez le commutateur par le WWPN.  Assurez-vous d’utiliser le WWPN des interfaces logiques (LIF) et non le WWPN des ports physiques sur les contrôleurs de stockage. Se référer à la  https://docs.netapp.com/us-en/ontap/san-config/index.html["Référence de configuration SAN"^] pour plus d'informations.




== Étape 3 : installer les utilitaires hôtes Windows

Le programme d'installation installe le package Windows Host Utilities et définit les paramètres du registre Windows et du HBA.

.Description de la tâche
En option, vous pouvez inclure la prise en charge du multivoie lorsque vous installez le package logiciel Windows Host Utilities.  Le programme d’installation vous propose les options suivantes :

* Choisissez `MPIO` Si vous disposez de plusieurs chemins entre l'hôte Windows ou la machine virtuelle et le système de stockage.
* Choisir `no MPIO` uniquement si vous utilisez un chemin unique vers le système de stockage.


Vous pouvez également choisir la prise en charge du multivoie à l’aide d’une invite de ligne de commande Windows.

Pour les invités Hyper-V, les disques bruts (pass-through) n'apparaissent pas dans le système d'exploitation invité si vous choisissez la prise en charge du multivoie.  Vous pouvez utiliser des disques bruts ou MPIO, mais vous ne pouvez pas utiliser les deux dans le système d'exploitation invité.


CAUTION: Si vous n'installez pas le logiciel MPIO, le système d'exploitation Windows peut voir chaque chemin comme un disque distinct. Cela peut entraîner une corruption des données.


NOTE: Windows XP ou Windows Vista exécuté sur une machine virtuelle Hyper-V ne prend pas en charge MPIO.

.Étapes
Vous pouvez installer les utilitaires hôtes de manière interactive ou en utilisant la ligne de commande Windows.  Le nouveau package d’installation des utilitaires hôtes doit se trouver dans un chemin accessible à l’hôte Windows.

[role="tabbed-block"]
====
.Installer de manière interactive
--
Installez le progiciel Host Utilities de manière interactive en exécutant le programme d'installation Host Utilities et en suivant les invites.

. Téléchargez le fichier exécutable à partir du https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^].
. Accédez au répertoire à partir duquel vous avez téléchargé le fichier exécutable.
. Exécutez le `netapp_windows_host_utilities_7.1_x64` classez et suivez les instructions à l'écran.
. Redémarrez l'hôte Windows lorsque vous y êtes invité.


--
.Installer de manière non interactive
--
Effectuez une installation non interactive des utilitaires hôtes à l’aide de la ligne de commande Windows.  Le système redémarre automatiquement lorsque l'installation est terminée.

. Entrez la commande suivante à l'invite de commande Windows :
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` est le nom du `.msi` Pour votre architecture de processeur
** MULTIPATHING indique si la prise en charge de MPIO est installée. Les valeurs autorisées sont « 0 » pour non, « 1 » pour oui
** `inst_path` Est le chemin d'installation des fichiers Host Utilities. Le chemin par défaut est `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Pour voir les options Microsoft installer (MSI) standard pour la journalisation et d'autres fonctions, entrez `msiexec /help` À l'invite de commande Windows. Par exemple, la commande `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` affiche les informations de journalisation.

--
====


== Et la suite ?

link:hu_wuhu_hba_settings.html["Configurer les paramètres de registre pour Windows Host Utilities"] .
