---
sidebar: sidebar 
permalink: hu_wuhu_repair_remove.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: 'Windows Host Utilities inclut un programme d"installation qui définit les paramètres de registre et de HBA Windows requis afin que l"hôte Windows gère correctement le comportement du système de stockage pour les plateformes ONTAP et E-Series.' 
---
= Réparer et supprimer les utilitaires hôtes Windows pour le stockage ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Utilisez l'option *Réparer* dans le programme d'installation des utilitaires hôtes pour mettre à jour l'adaptateur de bus hôte (HBA) et les paramètres du registre Windows.  Vous pouvez également supprimer entièrement les utilitaires hôtes, soit de manière interactive, soit à partir de la ligne de commande Windows.

[role="tabbed-block"]
====
.Réparez ou supprimez de manière interactive
--
L'option *Repair* met à jour le registre Windows et les HBA FC avec les paramètres requis. Vous pouvez également supprimer entièrement les utilitaires hôtes.

.Étapes
. Ouvrez Windows *programmes et fonctionnalités* (Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 et Windows 2022).
. Sélectionnez *Utilitaires hôtes Windows NetApp*.
. Sélectionnez *Modifier*.
. Sélectionnez *réparer* ou *Supprimer*, selon les besoins.
. Suivez les instructions à l'écran.


--
.Réparer ou supprimer de manière non interactive
--
L'option *Repair* met à jour le registre Windows et les HBA FC avec les paramètres requis. Vous pouvez également supprimer entièrement les utilitaires hôtes d'une ligne de commande Windows.

.Étapes
. Réparer les utilitaires hôtes Windows :
+
[source, cli]
----
msiexec /f installer.msi [/quiet]
----
+
** `/f` répare l'installation.
** `installer.msi` Est le nom du programme d'installation de Windows Host Utilities sur votre système.
** `/quiet` supprime tous les commentaires et redémarre automatiquement le système sans message d'invite à la fin de la commande.




--
====