---
sidebar: sidebar 
permalink: hu_wuhu_72.html 
keywords: wuhu, 7.2, host utilities, SAN, windows, unified 
summary: 'Les utilitaires d"hôte unifié Windows incluent un programme d"installation qui définit les paramètres de registre Windows et d"adaptateur de bus hôte requis afin que l"hôte Windows gère correctement le comportement du système de stockage pour les plateformes NetApp ONTAP et E-Series.' 
---
= Utilitaires d'hôtes unifiés Windows 7.2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




== A propos des utilitaires d'hôtes Windows

Les utilitaires d'hôte unifié Windows incluent un programme d'installation qui définit les paramètres de registre Windows et d'adaptateur de bus hôte requis afin que l'hôte Windows gère correctement le comportement du système de stockage pour les plateformes NetApp ONTAP et E-Series.

Lorsque vous installez le logiciel des utilitaires hôtes, le programme d'installation définit les paramètres requis du registre Windows et du HBA.

Les programmes et fichiers suivants sont installés sur l'ordinateur hôte Windows. Le répertoire par défaut est `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programme | Objectif 


| `emulexhba.reg` | Programme de dépannage ; exécutez ce programme uniquement si le personnel du support technique vous y invite. 


| `\NetAppQCLI\fcconfig.exe` | Utilisé par le programme d'installation pour définir les paramètres HBA. 


| `\NetAppQCLI\fcconfig.ini` | Utilisé par le programme d'installation pour définir les paramètres HBA. 


| `\NetAppQCLI\*.*` | Utilisé par le programme d'installation pour définir les paramètres QLogic FC HBA. 


| `san_version.exe` | Affiche la version des utilitaires hôtes et des HBA FC. 
|===


== Configurations prises en charge par les utilitaires hôtes

Les utilitaires hôtes prennent en charge différentes configurations d'hôtes Windows, différents protocoles et différentes options de chemins d'accès multiples. Pour plus d'informations, reportez-vous à la section https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^].



== Vérifiez la configuration de l'hôte et du système de stockage

Avant d'installer les utilitaires hôtes, vous devez vérifier que la version des utilitaires hôtes prend en charge la configuration de votre hôte et de votre système de stockage afin que le logiciel s'installe correctement.

.Étapes
. Vérifiez la configuration prise en charge dans le http://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^].
. Vérifiez les correctifs requis pour l'hôte respectif dans le link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentation Windows de l'hôte SAN"].
+

NOTE: link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Utilisation de Windows Server 2022 avec ONTAP"] fournit des instructions sur link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Installation des correctifs Windows"] Pour Windows Server 2022. Reportez-vous aux documents Windows de la catégorie configurations hôte pour trouver les informations de correctif appropriées pour les versions antérieures de Windows Server.

. Ajoutez la licence iSCSI, FCP ou NVMe-of et démarrez le service cible.
+
Les protocoles FC et iSCSI ne nécessitent pas de licence sur les systèmes de stockage E-Series utilisant SANtricity Storage Manager.

. Vérifiez votre câblage.
+
Voir la https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7["Guide de configuration SAN"^] Pour votre version ONTAP ou https://mysupport.netapp.com/ecm/ecm_get_file/ECMLP2773533["Guide du câblage matériel E-Series"^] pour des informations détaillées sur le câblage et la configuration.





== Configuration des HBA FC et des commutateurs

Installez et configurez un ou plusieurs adaptateurs de bus hôte FC pris en charge pour les connexions FC au système de stockage.

Le programme d'installation de Windows Host Utilities définit les paramètres de carte HBA FC requis.


CAUTION: Ne modifiez pas les paramètres HBA manuellement.

.Étapes
. Installez une ou plusieurs cartes HBA FC prises en charge conformément aux instructions fournies par le fournisseur de cartes HBA.
. Obtenez les pilotes HBA et les utilitaires de gestion pris en charge et installez-les conformément aux instructions fournies par le fournisseur de l'adaptateur HBA.
. Connectez les HBA à vos commutateurs FC ou directement au système de stockage.
. Créez des zones sur le commutateur FC conformément à la documentation de votre commutateur FC.
. Pour ONTAP, zone le commutateur par WWPN. Veillez à utiliser le WWPN des interfaces logiques (LIF) et non le WWPN des ports physiques des contrôleurs de stockage. Pour plus d'informations, voir https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7["Guide de configuration SAN"^].




== Installez les utilitaires hôtes

Le programme d'installation installe le package des utilitaires hôtes et définit le registre Windows et les paramètres HBA.

Vous devez indiquer si vous souhaitez inclure la prise en charge des chemins d'accès multiples lors de l'installation du pack logiciel Windows Unified Host Utilities. Le programme d'installation vous demande les options suivantes. Vous pouvez également exécuter une installation silencieuse (sans surveillance) à partir d'une invite de commande Windows.

.Prise en charge des chemins d'accès
* Choisissez `MPIO` Si vous disposez de plusieurs chemins entre l'hôte Windows ou la machine virtuelle et le système de stockage.
* Choisissez `no MPIO` uniquement si vous utilisez un chemin unique vers le système de stockage.


La sélection MPIO n'est pas disponible sur les systèmes Windows XP et Windows Vista ; les E/S multivoies ne sont pas prises en charge sur ces systèmes d'exploitation invités. Pour les invités Hyper-V, les disques bruts (pass-through) n'apparaissent pas dans le système d'exploitation invité si vous choisissez la prise en charge des chemins d'accès multiples. Vous pouvez utiliser des disques bruts ou MPIO, mais vous ne pouvez pas les utiliser les deux dans le système d'exploitation invité.

[role="tabbed-block"]
====
.Installez les utilitaires hôtes de manière interactive
--
Pour installer le progiciel des utilitaires hôtes de manière interactive, vous devez exécuter le programme d'installation des utilitaires hôtes et suivre les invites.

.Étapes
. Téléchargez le fichier exécutable à partir du https://mysupport.netapp.com/site/["Site de support NetApp"^].
. Accédez au répertoire dans lequel vous avez téléchargé le fichier exécutable.
. Exécutez le `netapp_windows_host_utilities_7.2_x64` classez et suivez les instructions à l'écran.
. Redémarrez l'hôte Windows lorsque vous y êtes invité.


--
.Installez les utilitaires hôtes à partir d'une ligne de commande
--
Vous pouvez effectuer une installation silencieuse (sans surveillance) des utilitaires hôtes en entrant les commandes appropriées à l'invite de commande Windows. Le package d'installation des utilitaires hôtes doit se trouver dans un chemin accessible par l'hôte Windows.

Suivez les instructions pour installer les utilitaires hôtes de manière interactive afin d'obtenir le package d'installation. Le système redémarre automatiquement lorsque l'installation est terminée.

.Étapes
. Entrez la commande suivante à l'invite de commande Windows :
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` est le nom du `.msi` Fichier pour votre architecture CPU.
** MULTIPATHING indique si la prise en charge de MPIO est installée. Les valeurs autorisées sont « 0 » pour non et « 1 » pour oui.
** `inst_path` est le chemin d'accès où les fichiers des utilitaires hôtes sont installés. Le chemin par défaut est `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Pour voir les options Microsoft installer (MSI) standard pour la journalisation et d'autres fonctions, entrez `msiexec /help` À l'invite de commande Windows. Par exemple, le `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` commande affiche les informations de journalisation.

--
====


== Mettez à niveau les utilitaires hôtes

Le nouveau package d'installation des utilitaires hôtes doit se trouver dans un chemin accessible par l'hôte Windows. Suivez les instructions pour installer les utilitaires hôtes de manière interactive afin de mettre à niveau le package d'installation.

[role="tabbed-block"]
====
.Mettez à niveau les utilitaires hôtes de manière interactive
--
Pour mettre à niveau le progiciel des utilitaires hôtes de manière interactive, vous devez exécuter le programme d'installation des utilitaires hôtes et suivre les invites.

.Étapes
. Accédez au répertoire dans lequel vous avez téléchargé le fichier exécutable.
. Exécutez le fichier exécutable et suivez les instructions à l'écran.
. Redémarrez l'hôte Windows lorsque vous y êtes invité.
. Une fois le redémarrage terminé, vérifiez la version de l'utilitaire hôte :
+
.. Ouvrez *panneau de configuration*.
.. Accédez à *Programme et fonctionnalités* et vérifiez la version de l'utilitaire hôte.




--
.Mettez à niveau les utilitaires hôtes à partir d'une ligne de commande
--
Vous pouvez effectuer une mise à niveau silencieuse (sans surveillance) des nouveaux utilitaires hôtes en entrant les commandes appropriées à l'invite de commande Windows.

Le nouveau package d'installation des utilitaires hôtes doit se trouver dans un chemin accessible par l'hôte Windows. Suivez les instructions pour installer les utilitaires hôtes de manière interactive afin de mettre à niveau le package d'installation.

.Étapes
. Entrez la commande suivante à l'invite de commande Windows :
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` est le nom du `.msi` Fichier pour votre architecture CPU.
** MULTIPATHING indique si la prise en charge de MPIO est installée. Les valeurs autorisées sont « 0 » pour non et « 1 » pour oui.
** `inst_path` est le chemin d'accès où les fichiers des utilitaires hôtes sont installés. Le chemin par défaut est `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Pour voir les options Microsoft installer (MSI) standard pour la journalisation et d'autres fonctions, entrez `msiexec /help` À l'invite de commande Windows. Par exemple, le `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` commande affiche les informations de journalisation.

Le système redémarre automatiquement lorsque l'installation est terminée.

--
====


== Réparez et supprimez les utilitaires d'hôtes Windows

Vous pouvez utiliser l'option *Repair* du programme d'installation des utilitaires hôtes pour mettre à jour les paramètres du registre HBA et Windows. Vous pouvez supprimer entièrement les utilitaires hôtes, de manière interactive ou à partir de la ligne de commande Windows.

[role="tabbed-block"]
====
.Réparez ou supprimez les utilitaires hôtes Windows de manière interactive
--
L'option *Repair* met à jour le registre Windows et les HBA FC avec les paramètres requis. Vous pouvez également supprimer entièrement les utilitaires hôtes.

.Étapes
. Ouvrez Windows *programmes et fonctionnalités* (Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 et Windows 2022).
. Sélectionnez *NetApp Windows Unified Host Utilities*.
. Sélectionnez *Modifier*.
. Sélectionnez *réparer* ou *Supprimer*, selon les besoins.
. Suivez les instructions à l'écran.


--
.Réparez ou supprimez les utilitaires hôtes Windows de la ligne de commande
--
L'option *Repair* met à jour le registre Windows et les HBA FC avec les paramètres requis. Vous pouvez également supprimer entièrement les utilitaires hôtes d'une ligne de commande Windows.

.Étapes
. Entrez la commande suivante sur la ligne de commande Windows pour réparer les utilitaires hôtes Windows :
+
`msiexec /f installer.msi [/quiet]`

+
** `/f` répare l'installation.
** `installer.msi` Est le nom du programme d'installation de Windows Host Utilities sur votre système.
** `/quiet` supprime tous les commentaires et redémarre automatiquement le système sans message d'invite à la fin de la commande.




--
====


== Présentation des paramètres utilisés par les utilitaires hôtes

Les utilitaires hôtes requièrent certains paramètres de registre et de paramètres pour vérifier que l'hôte Windows gère correctement le comportement du système de stockage.

Les utilitaires d'hôtes Windows définissent les paramètres qui affectent la façon dont l'hôte Windows répond à un retard ou une perte de données. Les valeurs spécifiques ont été sélectionnées pour vérifier que l'hôte Windows gère correctement les événements tels que le basculement d'un contrôleur du système de stockage vers son contrôleur partenaire.

Toutes les valeurs ne s'appliquent pas au gestionnaire de stockage DSM pour SANtricity ; cependant, tout chevauchement des valeurs définies par les utilitaires hôtes et celles définies par le gestionnaire de stockage DSM pour SANtricity n'entraîne pas de conflits.

Les HBA FC, NVMe/FC et iSCSI possèdent également des paramètres que vous devez définir pour garantir des performances optimales et gérer correctement les événements du système de stockage.

Le programme d'installation fourni avec les utilitaires d'hôtes unifiés Windows définit les paramètres des HBA Windows, FC et NVMe/FC sur les valeurs prises en charge.

Vous devez définir manuellement les paramètres du HBA iSCSI.

Le programme d'installation définit des valeurs différentes selon que vous spécifiez la prise en charge MPIO (Multipath I/O) lors de l'exécution du programme d'installation.

Vous ne devez pas modifier ces valeurs à moins d'en être dirigé par le support technique.



== Valeurs de registre définies par les utilitaires d'hôtes unifiés Windows

Le programme d'installation de Windows Unified Host Utilities définit automatiquement les valeurs de registre en fonction des choix que vous faites au cours de l'installation. Vous devez connaître ces valeurs de registre et la version du système d'exploitation.

Les valeurs suivantes sont définies par le programme d'installation de Windows Unified Host Utilities. Toutes les valeurs sont décimales, sauf indication contraire.


NOTE: HKLM est l'abréviation de `HKEY_LOCAL_MACHINE`.

[cols="20,20,30"]
|===
| Clé de registre | Valeur | Une fois réglé 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters \dsmMaximumRetryTimeDuringStatetransition | 120 | Lorsque le support MPIO est spécifié et que votre serveur est Windows Server 2012 R2, Windows Server 2016 et Windows 2019 ou Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet \Services\msdsm\Parameters \dsmMaximumStateTransitionTime | 120 | Lorsque le support MPIO est spécifié et que votre serveur est Windows Server 2012 R2, ou Windows Server 2016, Windows 2019 ou Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters\DsSupportedDeviceList | « NetApp LUN », « NETAPP LUN C- mode » « NVMe NetApp ONTAO con » | Lorsque la prise en charge de MPIO est spécifiée 


| HKLM\SYSTEM\CurrentControlSet\Control \Class\ {iSCSI_driver_GUID}\ instance_ID \Parameters \IPSecConfigTimeout | 60 | Toujours 


| HKLM\SYSTEM\CurrentControlSet\Control \Class\ {iSCSI_driver_GUID}\ instance_ID \Parameters \LinkDownTime | 10 | Toujours 


| HKLM\SYSTEM\CurrentControlSet\Services \ClusDisk \Parameters\ManageDisksOnSystemBuses | 1 | Toujours 


| HKLM\SYSTEM\CurrentControlSet\Control \Class\ {iSCSI_driver_GUID}\ instance_ID \Parameters \MaxRequestHoldTime | 120 | Lorsqu'aucun support MPIO n'est sélectionné 


| HKLM\SYSTEM\CurrentControlSet\Control \Class\ {iSCSI_driver_GUID}\ instance_ID \Parameters \MaxRequestHoldTime | 30 | Toujours 


| HKLM\SYSTEM\CurrentControlSet\Control \MPDEV\MPIOSupportedDeviceList | « NetApp LUN », « NETAPP LUN C- mode », « NVMe NetApp ONTAO con » | Lorsque la prise en charge de MPIO est spécifiée 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\PathRecovery yInterval | 30 | Lorsque votre serveur est Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 ou Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\PathVerifyEnabled | 1 | Lorsque la prise en charge de MPIO est spécifiée 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters\PathVerifyEnabled | 1 | Lorsque le support MPIO est spécifié et que votre serveur est Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 ou Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services \vnetapp\Parameters\PathVerifyEnabled | 0 | Lorsque la prise en charge de MPIO est spécifiée 


| HKLM\SYSTEM\CurrentControlSet\Services \mpio\Parameters\PDORemovePeriod | 130 | Lorsque la prise en charge de MPIO est spécifiée 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\PDORemovePeriod | 130 | Lorsque le support MPIO est spécifié et que votre serveur est Windows Server 2012 R2, Windows Server 2016 , Windows Server 2019 ou Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services\vnetapp \Parameters\PDORemovePeriod | 130 | Lorsque la prise en charge de MPIO est spécifiée, sauf si Data ONTAP DSM est détecté 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\RetryCount | 6 | Lorsque la prise en charge de MPIO est spécifiée 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\RetyCount | 6 | Lorsque le support MPIO est spécifié et que votre serveur est Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 ou Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\RetryInterval | 1 | Lorsque la prise en charge de MPIO est spécifiée 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\RetryInterval | 1 | Lorsque le support MPIO est spécifié et que votre serveur est Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 ou Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services\vnetapp \Parameters\RetryInterval | 1 | Lorsque la prise en charge de MPIO est spécifiée 


| HKLM\SYSTEM\CurrentControlSet\Services \disk\TimeOutValue | 120 | Lorsqu'aucun support MPIO n'est sélectionné 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\UseCustomPathRecovery yInterval | 1 | Lorsque le support MPIO est spécifié et que votre serveur est Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 ou Windows Server 2022 
|===
.Informations associées
Reportez-vous aux documents Microsoft pour plus de détails sur les paramètres de registre.



== Les paramètres NVMe

Les paramètres suivants du pilote Emulex NVMe sont mis à jour lors de l'installation DE WUHU 7.2 :

* EnableNVMe = 1
* NVMEMode = 0
* LimTransferSize=1




== Valeurs de HBA FC définies par les utilitaires hôtes Windows

Sur les systèmes utilisant FC, le programme d'installation des utilitaires hôtes définit les valeurs de délai requises pour les HBA Emulex et QLogic FC.

Pour les HBA FC Emulex, le programme d'installation définit les paramètres suivants :

[role="tabbed-block"]
====
.Lorsque MPIO est sélectionné
--
|===
| Type de propriété | Valeur de propriété 


| LinkTimeOut | 1 


| NodeTimeOut | 10 
|===
--
.Lorsque MPIO n'est pas sélectionné
--
|===
| Type de propriété | Valeur de propriété 


| LinkTimeOut | 30 


| NodeTimeOut | 120 
|===
--
====
Pour les HBA QLogic FC, le programme d'installation définit les paramètres suivants :

[role="tabbed-block"]
====
.Lorsque MPIO est sélectionné
--
|===
| Type de propriété | Valeur de propriété 


| LinkDownTimeOut | 1 


| PortDownloyCount | 10 
|===
--
.Lorsque MPIO n'est pas sélectionné
--
|===
| Type de propriété | Valeur de propriété 


| LinkDownTimeOut | 30 


| PortDownloyCount | 120 
|===
--
====

NOTE: Les noms des paramètres peuvent varier légèrement selon le programme. Par exemple, dans le programme QConvergeConsole de QLogic, le paramètre s'affiche comme `Link Down Timeout`. Les utilitaires hôtes `fcconfig.ini` fichier affiche ce paramètre comme l'un ou l'autre `LinkDownTimeOut` ou `MpioLinkDownTimeOut`, Selon que MPIO est spécifié ou non. Cependant, tous ces noms font référence au même paramètre HBA.

.Informations associées
Consultez le site Emulex ou QLogic pour en savoir plus sur les paramètres de temporisation.



== Dépannage

Vous pouvez utiliser les techniques de dépannage générales pour les utilitaires d'hôtes Windows. Assurez-vous de consulter les dernières notes de mise à jour pour connaître les problèmes connus et les solutions.



=== Différents domaines pour identifier les problèmes d'interopérabilité possibles

* Pour identifier les problèmes d'interopérabilité potentiels, vous devez vous assurer que les utilitaires hôtes prennent en charge votre combinaison de logiciel de système d'exploitation hôte, de matériel hôte, de logiciel ONTAP et de matériel de système de stockage.
* Vous devez vérifier le http://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^].
* Vous devez vérifier que vous disposez de la bonne configuration iSCSI.
* Si les LUN iSCSI ne sont pas disponibles après un redémarrage, vous devez vérifier que la cible est répertoriée comme étant persistante dans l'onglet *cibles persistantes* de l'interface utilisateur de l'initiateur Microsoft iSCSI.
* Si les applications utilisant les LUN affichent des erreurs au démarrage, vous devez vérifier que les applications sont configurées pour dépendre du service iSCSI.
* Pour les chemins FC vers les contrôleurs de stockage exécutant ONTAP, vous devez vérifier que les switchs FC sont zonés en utilisant les WWPN des LIF cibles, pas les WWPN des ports physiques sur le nœud.
* Vous devez vérifier le link:hu_wuhu_71_rn.html["Notes de version"] Pour que les utilitaires hôtes Windows vérifient les problèmes connus. Les notes de mise à jour incluent une liste des problèmes connus et des limites.
* Vous devez consulter les informations de dépannage du Guide d'administration SAN de votre version de ONTAP.
* Vous devez effectuer une recherche https://mysupport.netapp.com/site/bugs-online/product["NetApp bogues en ligne"^] pour les problèmes récemment découverts.
+
** Dans le champ Type de bogue sous recherche avancée, sélectionnez *iSCSI - Windows*, puis *Go*. Vous devez répéter la recherche pour Bug Type *FCP -Windows*.


* Vous devez collecter des informations sur votre système.
* Enregistrez tous les messages d'erreur affichés sur l'hôte ou la console du système de stockage.
* Collectez les fichiers journaux de l'hôte et du système de stockage.
* Notez les symptômes du problème et toutes les modifications apportées à l'hôte ou au système de stockage juste avant l'apparition du problème.
* Si vous ne parvenez pas à résoudre le problème, contactez le support technique NetApp pour obtenir de l'aide.




=== Présentation des modifications apportées aux paramètres du pilote de carte HBA FC aux utilitaires hôtes

Lors de l'installation des pilotes Emulex ou QLogic HBA requis sur un système FC, plusieurs paramètres sont vérifiés et, dans certains cas, modifiés.

Les utilitaires hôtes définissent les valeurs des paramètres suivants :

* LinkTimeOut : définit la durée en secondes pendant laquelle le port hôte attend avant de reprendre les opérations d'E/S après la défaillance d'une liaison physique.
* NodeTimeOut – définit la durée en secondes avant que le port hôte ne reconnaisse qu'une connexion au périphérique cible soit interrompue.


Lors du dépannage des problèmes de HBA, vérifiez que ces paramètres ont les valeurs correctes. Les valeurs correctes dépendent de deux facteurs :

* Fournisseur du HBA
* Que vous utilisiez MPIO


Vous pouvez corriger les paramètres HBA en exécutant l'option *Repair* du programme d'installation de Windows Host Utilities.

[role="tabbed-block"]
====
.Vérifiez les paramètres du pilote HBA Emulex sur les systèmes FC
--
Si vous disposez d'un système FC, vous devez vérifier les paramètres du pilote HBA Emulex. Ces paramètres doivent exister pour chaque port de l'adaptateur HBA.

.Étapes
. Ouvrez OnCommand Manager.
. Sélectionnez l'adaptateur HBA approprié dans la liste et sélectionnez l'onglet *Paramètres du pilote*.
+
Les paramètres du pilote s'affichent.

. Si vous utilisez le logiciel MPIO, vérifiez que vous disposez des paramètres de pilote suivants :
+
** LinkTimeOut - 1
** NodeTimeOut - 10


. Si vous n'utilisez pas le logiciel MPIO, vérifiez que vous disposez des paramètres de pilote suivants :
+
** LinkTimeOut - 30
** NodeTimeOut - 120




--
.Vérifiez les paramètres du pilote HBA QLogic sur les systèmes FC
--
Sur les systèmes FC, vous devez vérifier les paramètres du pilote QLogic HBA. Ces paramètres doivent exister pour chaque port de l'adaptateur HBA.

.Étapes
. Ouvrez QConvergeConsole, puis sélectionnez *Connect* dans la barre d'outils.
+
La boîte de dialogue *se connecter à l'hôte* s'affiche.

. Sélectionnez l'hôte approprié dans la liste, puis sélectionnez *Connect*.
+
La liste des HBA s'affiche dans le volet HBA FC.

. Sélectionnez le port HBA approprié dans la liste, puis sélectionnez l'onglet *Paramètres*.
. Sélectionnez *Paramètres avancés de port HBA* dans la section *Sélectionner les paramètres*.
. Si vous utilisez le logiciel MPIO, vérifiez que vous disposez des paramètres de pilote suivants :
+
** Délai d'attente de la liaison descendante (linkdwnto) - 1
** Nombre de tentatives de port en panne (portdwnrc) - 10


. Si vous n'utilisez pas le logiciel MPIO, vérifiez que vous disposez des paramètres de pilote suivants :
+
** Délai d'attente de la liaison descendante (linkdwnto) - 30
** Nombre de tentatives de port en panne (portdwnrc) - 120




--
====