---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: 'Windows Host Utilities inclut un programme d"installation qui définit les paramètres de registre et de HBA Windows requis afin que l"hôte Windows gère correctement le comportement du système de stockage pour les plateformes ONTAP et E-Series.' 
---
= Mettre à niveau les utilitaires hôtes Windows pour le stockage ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Vous pouvez mettre à niveau le logiciel Windows Host Utilities dans votre configuration de stockage ONTAP en suivant les instructions d'installation de manière interactive ou en utilisant la ligne de commande Windows.  Vous devez installer le nouveau logiciel d’installation de Windows Host Utilities sur un chemin accessible à l’hôte Windows.

[role="tabbed-block"]
====
.Mise à niveau interactive
--
Mettez à niveau le logiciel Windows Host Utilities de manière interactive en exécutant le programme d’installation Host Utilities et en suivant les invites.

.Étapes
. Accédez au répertoire dans lequel vous avez téléchargé le fichier exécutable.
. Exécutez le fichier exécutable et suivez les instructions à l'écran.
. Redémarrez l'hôte Windows lorsque vous y êtes invité.
. Une fois le redémarrage terminé, vérifiez la version de l'utilitaire hôte :
+
.. Ouvrez *panneau de configuration*.
.. Accédez à *Programme et fonctionnalités* et vérifiez la version de l'utilitaire hôte.




--
.Mise à niveau non interactive
--
Effectuez une mise à niveau du logiciel Windows Host Utilities non interactif à l’aide de la ligne de commande Windows.

.Étapes
. Entrez la commande suivante à l'invite de commande Windows :
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` est le nom du `.msi` Fichier pour votre architecture CPU.
** MULTIPATHING indique si la prise en charge MPIO (Microsoft Multipath I/O) est installée. Les valeurs autorisées sont « 0 » pour non et « 1 » pour oui.
** `inst_path` Est le chemin d'installation des fichiers Host Utilities. Le chemin par défaut est `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Pour voir les options Microsoft installer (MSI) standard pour la journalisation et d'autres fonctions, entrez `msiexec /help` À l'invite de commande Windows. Par exemple, le `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` commande affiche les informations de journalisation.

Le système redémarre automatiquement lorsque l'installation est terminée.

--
====