---
sidebar: sidebar 
permalink: hu_wuhu_71.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: 'Windows Unified Host Utilities comprend un programme d"installation qui définit les paramètres d"enregistrement et d"adaptateur HBA Windows requis. L"hôte Windows gère ainsi correctement les comportements du système de stockage pour les plateformes NetApp ONTAP et E-Series.' 
---
= Installez Windows Unified Host Utilities 7.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Les utilitaires d'hôtes unifiés Windows (WUHU) vous permettent de connecter un ordinateur hôte Windows à des systèmes de stockage NetApp.

Windows Unified Host Utilities prend en charge les versions suivantes de Windows :

* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Windows Unified Host Utilities inclut un programme d'installation qui définit les paramètres de registre Windows et d'adaptateur de bus hôte (HBA) requis afin qu'un hôte Windows puisse gérer correctement les comportements du système de stockage pour les plateformes NetApp ONTAP et E-Series.

Lorsque vous installez le logiciel Host Utilities, le programme d'installation définit les paramètres requis du registre Windows et de l'adaptateur de bus hôte (HBA).

Les programmes et fichiers suivants sont installés sur l'ordinateur hôte Windows. Le répertoire par défaut est `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programme | Objectif 


| `emulexhba.reg` | Programme de dépannage ; exécutez ce programme uniquement si le personnel du support technique vous y invite. 


| `\NetAppQCLI\fcconfig.exe` | Utilisé par le programme d'installation pour définir les paramètres HBA. 


| `\NetAppQCLI\fcconfig.ini` | Utilisé par le programme d'installation pour définir les paramètres HBA. 


| `\NetAppQCLI\*.*` | Utilisé par le programme d'installation pour définir les paramètres HBA FC QLogic. 


| `san_version.exe` | Affiche la version des utilitaires hôtes et des HBA FC. 
|===
Les utilitaires hôtes prennent en charge différentes configurations d'hôtes Windows, différents protocoles et différentes options de chemins d'accès multiples. Voir la https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^] pour obtenir la liste la plus récente des configurations prises en charge.



== Vérifiez les configurations de votre hôte et de votre système de stockage

Avant d'installer les utilitaires hôtes, vérifiez que la version des utilitaires hôtes prend en charge la configuration de l'hôte et du système de stockage afin que le logiciel s'installe correctement.

.Étapes
. Vérifiez la configuration prise en charge dans le http://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^].
. Vérifier les correctifs requis pour l'hôte respectif sur le link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentation Windows de l'hôte SAN"].
+

NOTE: Le link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Utilisation de Windows Server 2022 avec ONTAP"] le document fournit des instructions sur link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Installation des correctifs Windows"] Pour Windows Server 2022. Reportez-vous aux documents Windows de la catégorie configurations hôte pour trouver les informations de correctif appropriées pour les versions antérieures de Windows Server.

. Ajoutez la licence iSCSI ou FCP et démarrez le service cible.
+

NOTE: Les protocoles FC et iSCSI ne nécessitent pas de licence sur les systèmes de stockage E-Series utilisant le gestionnaire de stockage SANtricity.

. Vérifiez le câblage
+
Voir la https://docs.netapp.com/us-en/ontap/san-config/index.html["Référence de configuration SAN"^] Documentation de votre version de ONTAP ou https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html["Câblage matériel E-Series"^] pour des informations détaillées sur le câblage et la configuration.





== Configuration des HBA FC et des commutateurs

Installez et configurez un ou plusieurs adaptateurs de bus hôte FC pris en charge pour les connexions FC à un système de stockage.

Le programme d'installation de Windows Host Utilities définit les paramètres de carte HBA FC requis.


NOTE: Ne modifiez pas les paramètres HBA manuellement.

.Étapes
. Installez une ou plusieurs cartes HBA FC prises en charge conformément aux instructions fournies par le fournisseur de cartes HBA.
. Obtenez les pilotes HBA et les utilitaires de gestion pris en charge et installez-les conformément aux instructions fournies par le fournisseur de l'adaptateur HBA.
. Connectez les HBA à vos commutateurs FC ou directement au système de stockage.
. Créez des zones sur le commutateur FC conformément à la documentation de votre commutateur FC.
. Pour les ONTAP, zone le commutateur par nom de port mondial (WWPN). Veillez à utiliser le WWPN des LIFs et non des ports physiques des contrôleurs de stockage. Voir la https://docs.netapp.com/us-en/ontap/san-config/index.html["Référence de configuration SAN"^] pour plus d'informations.




== Installez les utilitaires hôtes

Le programme d'installation installe le package Host Utilities et définit les paramètres du registre Windows et HBA.

Vous devez indiquer si vous souhaitez inclure la prise en charge des chemins d'accès multiples lors de l'installation du pack logiciel Windows Unified Host Utilities. Le programme d'installation vous demande le choix suivant. Vous pouvez également exécuter une installation silencieuse (sans surveillance) à partir d'une invite de commande Windows.

.Prise en charge des chemins d'accès
* Choisissez `MPIO` Si vous disposez de plusieurs chemins entre l'hôte Windows ou la machine virtuelle et le système de stockage.
* Choisissez `no MPIO` uniquement si vous utilisez un chemin unique vers le système de stockage.


La sélection MPIO n'est pas disponible sur les systèmes Windows XP et Windows Vista ; les E/S multivoies ne sont pas prises en charge sur ces systèmes d'exploitation invités. Pour les invités Hyper-V, les disques bruts (pass-through) n'apparaissent pas dans le système d'exploitation invité si vous choisissez la prise en charge des chemins d'accès multiples. Vous pouvez utiliser des disques bruts ou MPIO, mais vous ne pouvez pas les utiliser les deux dans le système d'exploitation invité.

Vous pouvez installer les utilitaires hôtes de manière interactive ou à l'aide de la ligne de commande. Le nouveau package d'installation Host Utilities doit se trouver dans un chemin accessible par l'hôte Windows. Suivez les instructions d'installation interactive des utilitaires hôtes ou à partir de la ligne de commande Windows.

[role="tabbed-block"]
====
.Installer de manière interactive
--
.Étapes
Pour installer le progiciel Host Utilities de manière interactive, vous devez exécuter le programme d'installation Host Utilities et suivre les invites.

.Étapes
. Téléchargez le fichier exécutable à partir du https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de support NetApp"^].
. Accédez au répertoire à partir duquel vous avez téléchargé le fichier exécutable.
. Exécutez le `netapp_windows_host_utilities_7.1_x64` classez et suivez les instructions à l'écran.
. Redémarrez l'hôte Windows lorsque vous y êtes invité.


--
.Installer à partir d'une ligne de commande
--
Vous pouvez effectuer une installation silencieuse (sans surveillance) des utilitaires hôtes en entrant les commandes appropriées à l'invite de commande de Windows. Le système redémarre automatiquement lorsque l'installation est terminée.

.Étapes
. Entrez la commande suivante à l'invite de commande Windows :
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` est le nom du `.msi` Pour votre architecture de processeur
** MULTIPATHING indique si la prise en charge de MPIO est installée. Les valeurs autorisées sont « 0 » pour non, « 1 » pour oui
** `inst_path` Est le chemin d'installation des fichiers Host Utilities. Le chemin par défaut est `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Pour voir les options Microsoft installer (MSI) standard pour la journalisation et d'autres fonctions, entrez `msiexec /help` À l'invite de commande Windows. Par exemple, la commande `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` affiche les informations de journalisation.

--
====