---
permalink: legal_notices.html 
sidebar: sidebar 
keywords: legal, notices, copyright, trademarks, patents 
summary: Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc. 
---
= Mentions légales
:allow-uri-read: 


[role="lead"]
Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc.



== Droits d'auteur

http://www.netapp.com/us/legal/copyright.aspx[]



== Marques déposées

NetApp, le logo NETAPP et les marques mentionnées sur la page des marques commerciales NetApp sont des marques commerciales de NetApp, Inc. Les autres noms de sociétés et de produits peuvent être des marques commerciales de leurs propriétaires respectifs.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Brevets

Vous trouverez une liste actuelle des brevets appartenant à NetApp à l'adresse suivante :

https://www.netapp.com/us/media/patents-page.pdf[]



== Politique de confidentialité

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Source ouverte

Fournit des informations sur les droits d'auteur tiers et les licences utilisées dans ce produit.

* link:./media/Notices-AIX61-2023.pdf["Avis pour AIX"^]
* link:./media/Linux_Unified_Host_Utilities.pdf["Avis pour Linux"^]
* link:./media/Solaris_Host_Utilities-2017.09.12-01.25.35.pdf["Avis pour Solaris"^]
* link:./media/Windows_Unified_Host_Utilities_(WUHU)Notice.pdf["Remarque pour Windows"^]

