---
permalink: legal-notices.html 
sidebar: sidebar 
keywords: legal, notices, copyright, trademarks, patents 
summary: Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc. 
---
= Mentions légales
:allow-uri-read: 


[role="lead lead"]
Les mentions légales donnent accès aux déclarations de copyright, aux marques, aux brevets, etc.



== Droits d'auteur

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marques déposées

NetApp, le logo NETAPP et les marques mentionnées sur la page des marques commerciales NetApp sont des marques commerciales de NetApp, Inc. Les autres noms de sociétés et de produits peuvent être des marques commerciales de leurs propriétaires respectifs.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Brevets

Vous trouverez une liste actuelle des brevets appartenant à NetApp à l'adresse suivante :

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Politique de confidentialité

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]

* link:./media/Notices-AIX61-2023.pdf["Avis pour AIX"^]
* link:./media/Linux_Unified_Host_Utilities.pdf["Avis pour Linux"^]
* link:./media/Solaris_Host_Utilities-2017.09.12-01.25.35.pdf["Avis pour Solaris"^]
* link:./media/Windows_Unified_Host_Utilities_(WUHU)Notice.pdf["Remarque pour Windows"^]

