---
sidebar: sidebar 
permalink: nvme-windows-2012r2.html 
keywords: nvme, windows, enterprise 
summary: 'Vous pouvez configurer NVMe over Fibre Channel (NVMe/FC) sur des hôtes qui exécutent Windows Server 2012 R2 en vue d"une utilisation avec des LUN ONTAP.' 
---
= Configuration de Windows Server 2012 R2 avec NVMe/FC pour ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez configurer NVMe over Fibre Channel (NVMe/FC) sur des hôtes qui exécutent Windows Server 2012 R2 en vue d'une utilisation avec des LUN ONTAP.

.Description de la tâche
Vous pouvez utiliser la prise en charge suivante avec la configuration hôte NVMe/FC pour Windows 2012 R2. Vous devez également vérifier les limites connues avant de commencer le processus de configuration.


NOTE: Vous pouvez utiliser les paramètres de configuration fournis dans cette procédure pour configurer les clients cloud connectés à link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] et link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX pour ONTAP"^].

* Support disponible :
+
Depuis la version ONTAP 9.7, NVMe/FC est pris en charge pour Windows Server 2012 R2.

+
Pour obtenir la liste des adaptateurs et contrôleurs FC pris en charge, reportez-vous au link:https://hwu.netapp.com/Home/Index["Hardware Universe"^]. Pour obtenir la liste actuelle des configurations et versions prises en charge, reportez-vous au link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].

* Limitations connues :
+
Le cluster de basculement Windows n'est pas pris en charge avec le protocole NVMe/FC, car ONTAP ne prend pas actuellement en charge les réservations persistantes avec le protocole NVMe/FC.

+

NOTE: Broadcom expédie un pilote externe pour Windows NVMe/FC qui est un pilote NVMe ⇄ en translation et non un véritable pilote NVMe/FC. La surcharge en translation n'a pas forcément d'impact sur les performances, mais elle annule les avantages de la technologie NVMe/FC en matière de performance. Par conséquent, les performances de NVMe/FC et FCP sont identiques sur les serveurs Windows, contrairement aux autres systèmes d'exploitation tels que Linux, où les performances de NVMe/FC sont nettement supérieures à celles de FCP.





== Activation de NVMe/FC

Activez FC/NVMe sur l'hôte initiateur Windows.

.Étapes
. Installez l'utilitaire Emulex HBA Manager sur l'hôte Windows.
. Sur chacun des ports d'initiateur HBA, définissez les paramètres suivants du pilote HBA :
+
** EnableNVMe = 1
** NVMEMode = 0


. Redémarrez l'hôte.




== Configuration de la carte FC Broadcom

L'initiateur Broadcom peut traiter le trafic NVMe/FC et FCP via les mêmes ports d'adaptateur FC 32 Gbit/s. Pour FCP et FC/NVMe, vous devez utiliser le module DSM (Device-Specific module) Microsft en tant qu'option MPIO (Microsoft Multipath I/O).

Un `+hostnqn+` est associé à chaque port de carte bus hôte (HBA) de la carte Broadcom avec FC/NVMe dans un environnement Windows. Le `+hostnqn+` est formaté comme indiqué dans l'exemple suivant :

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== Activez MPIO pour les périphériques NVMe

Vous devez activer MPIO pour les périphériques NVMe afin d'effectuer la configuration NVMe sur l'hôte Windows.

.Étapes
. Installer link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Kit utilitaire hôte Windows 7.1"] Pour définir les paramètres du pilote communs à FC et NVMe.
. Ouvrez les propriétés MPIO.
. Dans l'onglet *Discover Multi-Paths*, ajoutez l'ID de périphérique répertorié pour NVMe.
+
MPIO connaît les périphériques NVMe, visibles au niveau de la gestion des disques.

. Ouvrez *Disk Management* et accédez à *Disk Properties*.
. Dans l'onglet *MPIO*, sélectionnez *Détails*.
. Définissez les paramètres Microsoft DSM suivants :
+
** PathVerifiedPeriod: *10*
** PathVerifyEnabled : *Activer*
** RetryCount: *6*
** Intervalle de rérémanence : *1*
** PDODOedRemiod: *130*


. Sélectionnez la stratégie MPIO *Round Robin with Subset*.
. Modifiez les valeurs du registre :
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. Redémarrez l'hôte.




== Validation de la spécification NVMe/FC

Vérifiez que les sous-systèmes NVMe ont été découverts et que les namespaces ONTAP sont corrects pour la configuration NVMe-of.

.Étapes
. Vérifiez que « Type de port » est `+FC+NVMe+`:
+
`listhba`

+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
*Port Type*      : *FC+NVMe*
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
====
. Vérifier que les sous-systèmes NVMe/FC ont été détectés :
+
** `+nvme-list+`
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
====
** `nvme-list`
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
====


. Vérifiez que les espaces de noms ont été créés :
+
`+nvme-list-ns+`

+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----
====

