---
sidebar: sidebar 
permalink: nvme_ol_93.html 
keywords: nvme, oracle linux, 9.3, host configuration 
summary: 'Configuration d"hôte NVMe-of pour Oracle Linux 9.3 avec ONTAP' 
---
= Configuration d'hôte NVMe-of pour Oracle Linux 9.3 avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NVMe over Fabrics (NVMe-of), y compris NVMe over Fibre Channel (NVMe/FC) et d'autres moyens de transport, est pris en charge par Oracle Linux (OL) 9.3 avec ANA (Asymmetric Namespace Access). Dans les environnements NVMe-of, ANA est l'équivalent des chemins d'accès multiples ALUA dans les environnements iSCSI et FC. Il est implémenté avec les chemins d'accès multiples NVMe intégrés au noyau.

La prise en charge suivante est disponible pour la configuration hôte NVMe-of pour OL 9.3 avec ONTAP :

* Prise en charge de NVMe over TCP (NVMe/TCP) en plus de NVMe/FC. Le plug-in NetApp du package nvme-cli natif affiche les détails des ONTAP pour les namespaces NVMe/FC et NVMe/TCP.
* Utilisation du trafic existant NVMe et SCSI sur le même hôte sur un adaptateur de bus hôte (HBA) donné, sans les paramètres dm-multipathing explicites pour empêcher la demande d'espaces de noms NVMe.


Pour plus d'informations sur les configurations prises en charge, reportez-vous au link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^].



== Caractéristiques

Par défaut, Oracle Linux 9.3 a activé le multipathing NVMe dans le noyau pour les namespaces NVMe. Par conséquent, il n'est pas nécessaire de définir des paramètres explicites.



== Limites connues

Le démarrage SAN à l'aide du protocole NVMe-of n'est pas pris en charge pour le moment.



== Validation des versions logicielles

Vous pouvez utiliser la procédure suivante pour valider les versions minimales de OL 9.3 prises en charge.

.Étapes
. Installez OL 9.3 GA sur le serveur. Une fois l'installation terminée, vérifiez que vous exécutez le noyau OL 9.3 GA spécifié.
+
[listing]
----
# uname -r
----
+
*Exemple de sortie :*

+
[listing]
----
5.15.0-200.131.27.el9uek.x86_64
----
. Installer le `nvme-cli` groupe :
+
[listing]
----
# rpm -qa|grep nvme-cli
----
+
*Exemple de sortie :*

+
[listing]
----
nvme-cli-2.4-10.el9.x86_64
----
. Installer le `libnvme` groupe :
+
[listing]
----
#rpm -qa|grep libnvme
----
+
*Exemple de sortie*

+
[listing]
----
libnvme-1.4-7.el9.x86_64
----
. Sur l'hôte Oracle Linux 9.3, vérifiez la `hostnqn` chaîne à `/etc/nvme/hostnqn`:
+
[listing]
----
# cat /etc/nvme/hostnqn
----
+
*Exemple de sortie :*

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:2831093d-fa7f-4714-a6bf-548796e82053
----
. Vérifiez que le `hostnqn` la chaîne correspond au `hostnqn` Chaîne du sous-système correspondant sur la baie ONTAP :
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_ol_nvme
----
+
*Exemple de sortie :*

+
[listing]
----
Vserver     Subsystem          Host NQN
----------- --------------- ----------------------------------------------------------
vs_ol_nvme   nvme              nqn.2014-08.org.nvmexpress:uuid:2831093d-fa7f-4714-a6bf-548796e82053
----
+

NOTE: Si le `hostnqn` les chaînes ne correspondent pas, vous pouvez utiliser le `vserver modify` commande pour mettre à jour le `hostnqn` Chaîne sur le sous-système de matrice ONTAP correspondant à `hostnqn` chaîne de `/etc/nvme/hostnqn` sur l'hôte.





== Configurez NVMe/FC

Vous pouvez configurer NVMe/FC pour les cartes Broadcom/Emulex ou Marvell/Qlogic.

[role="tabbed-block"]
====
.Broadcom/Emulex
--
.Étapes
. Vérifiez que vous utilisez le modèle d'adaptateur pris en charge :
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
----
+
*Exemple de sortie :*

+
[listing]
----
LPe36002-M2
LPe36002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
----
+
*Exemple de sortie :*

+
[listing]
----
Emulex LightPulse LPe36002-M2 2-Port 64Gb Fibre Channel Adapter
Emulex LightPulse LPe36002-M2 2-Port 64Gb Fibre Channel Adapter
----
. Vérifiez que vous utilisez la carte Broadcom recommandée `lpfc` micrologiciel et pilote de boîte de réception :
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
14.2.673.40, sli-4:2:c
14.2.673.40, sli-4:2:c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:14.2.0.13
----
+
Pour obtenir la liste la plus récente des versions de pilote de carte et de micrologiciel prises en charge, reportez-vous à la section link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^].

. Vérifiez-le `lpfc_enable_fc4_type` est défini sur `3`:
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Vérifier que les ports initiateurs sont opérationnels et que les LIFs cibles sont visibles :
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000620b3c089c
0x100000620b3c089d

----
+
[listing]
----

# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
.Affiche un exemple de résultat
[%collapsible]
=====
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000620b3c089c WWNN x200000620b3c089c DID x062f00 ONLINE
NVME RPORT       WWPN x2019d039ea9ea480 WWNN x2018d039ea9ea480 DID x061b06 TARGET DISCSRVC ONLINE
NVME RPORT       WWPN x201cd039ea9ea480 WWNN x2018d039ea9ea480 DID x062706 TARGET DISCSRVC ONLINE

NVME Statistics
LS: Xmt 0000000f03 Cmpl 0000000efa Abort 0000004a
LS XMIT: Err 00000009  CMPL: xb 0000004a Err 0000004a
Total FCP Cmpl 00000000b9b3486a Issue 00000000b97ba0d2 OutIO ffffffffffc85868
abort 00000afc noxri 00000000 nondlp 00002e34 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 0000138c Err 00014750

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000620b3c089d WWNN x200000620b3c089d DID x062400 ONLINE
NVME RPORT       WWPN x201ad039ea9ea480 WWNN x2018d039ea9ea480 DID x060206 TARGET DISCSRVC ONLINE
NVME RPORT       WWPN x201dd039ea9ea480 WWNN x2018d039ea9ea480 DID x061305 TARGET DISCSRVC ONLINE

NVME Statistics
LS: Xmt 0000000b40 Cmpl 0000000b40 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 00000000b9a9f03f Issue 00000000b96e622e OutIO ffffffffffc471ef
abort 0000090d noxri 00000000 nondlp 00003b3f qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000010a5 Err 000147e4
----
=====


--
.Adaptateur FC Marvell/QLogic pour NVMe/FC
--
Le pilote natif de la boîte de réception qla2xxx inclus dans le noyau OL 9.3 GA possède les derniers correctifs en amont. Ces correctifs sont essentiels à la prise en charge de ONTAP.

.Étapes
. Vérifiez que vous exécutez les versions du pilote de carte et du micrologiciel prises en charge :
+
[listing]
----
# cat /sys/class/fc_host/host*/symbolic_name
QLE2872 FW:v9.14.02 DVR:v 10.02.09.100-k
QLE2872 FW:v9.14.02 DVR:v 10.02.09.100-k
----
. Vérifiez-le `ql2xnvmeenable` est défini. L'adaptateur Marvell peut ainsi fonctionner en tant qu'initiateur NVMe/FC :
+
[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----


--
====


=== Activation d'une taille d'E/S de 1 Mo (en option)

ONTAP signale une taille de transfert MAX Data (MDT) de 8 dans les données Identify Controller. La taille maximale des demandes d'E/S peut donc atteindre 1 Mo. Pour émettre des demandes d'E/S d'une taille de 1 Mo pour un hôte Broadcom NVMe/FC, augmentez la `lpfc` valeur du `lpfc_sg_seg_cnt` paramètre à 256 par rapport à la valeur par défaut 64.


NOTE: Ces étapes ne s'appliquent pas aux hôtes NVMe/FC Qlogic.

.Étapes
. Réglez le `lpfc_sg_seg_cnt` paramètre sur 256 :
+
[listing]
----
cat /etc/modprobe.d/lpfc.conf
----
+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Exécutez `dracut -f` la commande et redémarrez l'hôte.
. Vérifier que la valeur attendue de `lpfc_sg_seg_cnt` est 256 :
+
[listing]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== Configurez NVMe/TCP

NVMe/TCP ne dispose pas de la fonctionnalité de connexion automatique. Par conséquent, vous devez exécuter manuellement les fonctionnalités de connexion NVMe/TCP ou de connexion pour découvrir les sous-systèmes et les espaces de noms NVMe/TCP. Vous pouvez utiliser la procédure suivante pour configurer NVMe/TCP.

.Étapes
. Vérifiez que le port initiateur peut récupérer les données de la page de journal de découverte sur les LIF NVMe/TCP prises en charge :
+
[listing]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
# nvme discover -t tcp -w 192.168.166.4 -a 192.168.166.56

Discovery Log Number of Records 4, Generation counter 10
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: current discovery subsystem
treq:    not specified
portid:  2
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.337a0392d58011ee9764d039eab0dadd:discovery
traddr:  192.168.165.56
eflags:  explicit discovery connections, duplicate discovery information
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: current discovery subsystem
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.337a0392d58011ee9764d039eab0dadd:discovery
traddr:  192.168.166.56
eflags:  explicit discovery connections, duplicate discovery information
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  2
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.337a0392d58011ee9764d039eab0dadd:subsystem.rhel_95
traddr:  192.168.165.56
eflags:  none
sectype: none
..........
----
====
. Vérifier que les autres combinaisons de LIF cible-initiateur NVMe/TCP peuvent récupérer les données de la page du journal de détection :
+
[listing]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
*Exemple de sortie :*

+
[listing]
----
# nvme discover -t tcp -w 192.168.166.4 -a 192.168.166.56
# nvme discover -t tcp -w 192.168.165.3 -a 192.168.165.56
----
. Exécutez le `nvme connect-all` Commande sur toutes les LIF cible-initiateur NVMe/TCP prises en charge sur l'ensemble des nœuds :
+
[listing]
----
nvme connect-all -t tcp -w host-traddr -a traddr -l <ctrl_loss_timeout_in_seconds>
----
+
*Exemple de sortie :*

+
[listing]
----
# nvme connect-all -t tcp -w 192.168.166.4 -a 192.168.166.56 -l -1
# nvme connect-all -t tcp -w 192.168.165.3 -a 192.168.165.56 -l -1
----
+

NOTE: NetApp recommande de configurer le `ctrl-loss-tmo` option à `-1` De sorte que l'initiateur NVMe/TCP tente de se reconnecter indéfiniment en cas de perte de chemin.





== Validez la spécification NVMe-of

La procédure suivante permet de valider NVMe-of.

.Étapes
. Vérifiez les paramètres NVMe/FC suivants sur l'hôte OL 9.3 :
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. Vérifiez que les espaces de noms sont créés et correctement découverts sur l'hôte :
+
[listing]
----
# nvme list
----
+
*Exemple de sortie :*

+
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme0n1 814vWBNRwf9HAAAAAAAB NetApp ONTAP Controller
/dev/nvme0n2 814vWBNRwf9HAAAAAAAB NetApp ONTAP Controller
/dev/nvme0n3 814vWBNRwf9HAAAAAAAB NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB  4 KiB + 0 B   FFFFFFFF
2                 21.47 GB / 21.47 GB  4 KiB + 0 B  FFFFFFFF
3	                21.47 GB/ 21.47 GB 4 KiB + 0 B   FFFFFFFF

----
. Vérifiez que l'état du contrôleur de chaque chemin est actif et que l'état ANA est correct :
+
[role="tabbed-block"]
====
.NVMe/FC
--
[listing]
----
# nvme list-subsys /dev/nvme0n1
----
*Exemple de sortie :*

[listing]
----
nvme-subsys5 - NQN=nqn.1992-08.com.netapp:sn.4aa0fa76c92c11eeb301d039eab0dadd:subsystem.rhel_213
\
 +- nvme3 fc traddr=nn-0x2018d039ea9ea480:pn-0x201dd039ea9ea480,host_traddr=nn-0x200000620b3c089d:pn-0x100000620b3c089d live non-optimized
 +- nvme4 fc traddr=nn-0x2018d039ea9ea480:pn-0x201cd039ea9ea480,host_traddr=nn-0x200000620b3c089c:pn-0x100000620b3c089c live non-optimized
 +- nvme6 fc traddr=nn-0x2018d039ea9ea480:pn-0x2019d039ea9ea480,host_traddr=nn-0x200000620b3c089c:pn-0x100000620b3c089c live optimized
 +- nvme7 fc traddr=nn-0x2018d039ea9ea480:pn-0x201ad039ea9ea480,host_traddr=nn-0x200000620b3c089d:pn-0x100000620b3c089d live optimized
----
--
.NVMe/TCP
--
[listing]
----
nvme list-subsys /dev/nvme1n22
----
*Exemple de sortie*

[listing]
----
nvme-subsys1 - NQN=nqn.1992-08.com.netapp:sn.337a0392d58011ee9764d039eab0dadd:subsystem.rhel_95
\
 +- nvme2 tcp traddr=192.168.166.56,trsvcid=4420,host_traddr=192.168.166.4,src_addr=192.168.166.4 live optimized
 +- nvme3 tcp traddr=192.168.165.56,trsvcid=4420,host_traddr=192.168.165.3,src_addr=192.168.165.3 live non-optimized


----
--
====
. Vérifier que le plug-in NetApp affiche les valeurs correctes pour chaque périphérique d'espace de noms ONTAP :
+
[role="tabbed-block"]
====
.Colonne
--
[listing]
----
# nvme netapp ontapdevices -o column
----
*Exemple de sortie :*

[listing]
----
Device        Vserver   Namespace Path
----------------------- ------------------------------
/dev/nvme5n6     vs_nvme175                /vol/vol6/ns
/dev/nvme5n7     vs_nvme175                /vol/vol7/ns
/dev/nvme5n8     vs_nvme175                /vol/vol8/ns




NSID       UUID                                   Size
------------------------------------------------------------
6          72b887b1-5fb6-47b8-be0b-33326e2542e2   21.47GB
7          04bf9f6e-9031-40ea-99c7-a1a61b2d7d08   21.47GB
8          264823b1-8e03-4155-80dd-e904237014a4   21.47GB


----
--
.JSON
--
[listing]
----
# nvme netapp ontapdevices -o json
----
*Exemple de sortie*

[listing]
----
{
  "ONTAPdevices":[
    {
      "Device":"/dev/nvme5n1",
      "Vserver":"vs_nvme175",
      "Namespace_Path":"/vol/vol1/ns",
      "NSID":1,
      "UUID":"d4791955-07c9-44fc-b41c-d1c39d3d9b5b",
      "Size":"21.47GB",
      "LBA_Data_Size":4096,
      "Namespace_Size":5242880
    },
    {
      "Device":"/dev/nvme5n10",
      "Vserver":"vs_nvme175",
      "Namespace_Path":"/vol/vol10/ns",
      "NSID":10,
      "UUID":"f3a4ce94-bcc5-4ff0-9e52-e59030bbc97f",
      "Size":"21.47GB",
      "LBA_Data_Size":4096,
      "Namespace_Size":5242880
    },
    {
      "Device":"/dev/nvme5n11",
      "Vserver":"vs_nvme175",
      "Namespace_Path":"/vol/vol11/ns",
      "NSID":11,
      "UUID":"0bf171d2-51f7-4a00-8f6a-0ea2190885a2",
      "Size":"21.47GB",
      "LBA_Data_Size":4096,
      "Namespace_Size":5242880
    },
  ]
}

----
--
====




== Problèmes connus

Il n'y a aucun problème connu pour Oracle Linux 9.3 avec la version ONTAP.
