---
sidebar: sidebar 
permalink: nvme_sles15_sp7.html 
keywords: nvme, linux, suse, sles, 15, SP7, server, enterprise 
summary: Décrit comment configurer NVMe/FC pour SUSE Linux Enterprise Server 15 SP7 avec ONTAP. 
---
= Configuration hôte NVMe-of pour SUSE Linux Enterprise Server 15 SP7 avec ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Les hôtes Red Hat Enterprise Linux (RHEL) prennent en charge les protocoles NVMe over Fibre Channel (NVMe/FC) et NVMe over TCP (NVMe/TCP) avec Asymmetric Namespace Access (ANA).  ANA fournit une fonctionnalité de multi-accès équivalente à l'accès aux unités logiques asymétriques (ALUA) dans les environnements iSCSI et FCP.

.Description de la tâche
Vous pouvez utiliser la prise en charge et les fonctionnalités suivantes avec la configuration d'hôte NVMe-oF pour SUSE Linux Enterprise Server 15 SP7 (SLES15 SP7). Vous devez également vérifier les limites connues avant de commencer le processus de configuration.

* Support disponible :
+
** Prise en charge de NVMe over TCP (NVMe/TCP) et de NVMe over Fibre Channel (NVMe/FC). Le plug-in NetApp du pack natif `nvme-cli` affiche les détails des ONTAP pour les namespaces NVMe/FC et NVMe/TCP.
** Exécution du trafic NVMe et SCSI sur le même hôte Par exemple, vous pouvez configurer dm-multipath pour les périphériques SCSI mpath pour les LUN SCSI, et utiliser le protocole NVMe multipath pour configurer les périphériques d'espace de noms NVMe-of sur l'hôte.
** Prise en charge du démarrage SAN à l'aide du protocole NVMe/FC.
** À partir d' ONTAP 9.12.1, la prise en charge de l'authentification sécurisée en bande est introduite pour NVMe/TCP et NVMe/FC. Vous pouvez utiliser l'authentification sécurisée en bande pour NVMe/TCP et NVMe/FC avec SLES15 SP7.
** Prise en charge des contrôleurs de découverte persistants (PDC) à l'aide d'un NQN de découverte unique.
** Prise en charge du cryptage TLS 1.3 pour NVMe/TCP.
** NetApp  `sanlun` la prise en charge de l'utilitaire hôte n'est pas disponible pour NVMe-oF sur un hôte SLES15 SP7. Vous pouvez plutôt vous appuyer sur le plug-in NetApp inclus dans le pack natif `nvme-cli` pour tous les transports NVMe-of.
+
Pour plus de détails sur les configurations prises en charge, consultez le link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].



* Fonctionnalités disponibles :
+
** Aucune nouvelle fonctionnalité n'est disponible.


* Limites connues
+
** Évitez d'émettre le  `nvme disconnect-all` commande sur les systèmes démarrant à partir du SAN sur les espaces de noms NVMe-TCP ou NVMe-FC car elle déconnecte les systèmes de fichiers racine et de données et peut entraîner une instabilité du système.






== Étape 1 : activez éventuellement le démarrage SAN

Vous pouvez configurer votre hôte pour qu'il utilise le démarrage SAN afin de simplifier le déploiement et d'améliorer l'évolutivité.

.Avant de commencer
Utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.

.Étapes
. Créez un espace de noms de démarrage SAN et mappez-le à l'hôte.
+
Voir https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["Provisionner le stockage NVMe"^].

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels l'espace de noms de démarrage SAN est mappé.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Vérifiez que la configuration a réussi en redémarrant l'hôte et en vérifiant que le système d'exploitation est opérationnel.




== Étape 2 : Valider les versions du logiciel

Utilisez la procédure suivante pour valider les versions minimales du logiciel SLES15 SP7 prises en charge.

.Étapes
. Installez SLES15 SP7 sur le serveur. Une fois l'installation terminée, vérifiez que vous utilisez le noyau SLES15 SP7 spécifié :
+
[source, cli]
----
uname -r
----
+
L'exemple suivant montre une version du noyau SLES :

+
[listing]
----
6.4.0-150700.53.3-default
----
. Installer le `nvme-cli` groupe :
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
L'exemple suivant montre un  `nvme-cli` version du paquet :

+
[listing]
----
nvme-cli-2.11+22.gd31b1a01-150700.3.3.2.x86_64
----
. Installer le `libnvme` groupe :
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
L'exemple suivant montre un  `libnvme` version du paquet :

+
[listing]
----
libnvme1-1.11+4.ge68a91ae-150700.4.3.2.x86_64
----
. Sur l'hôte, vérifiez la chaîne hostnqn à  `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
L'exemple suivant montre un  `hostnqn` version:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:f6517cae-3133-11e8-bbff-7ed30aef123f
----
. Vérifiez que le `hostnqn` la chaîne correspond au `hostnqn` Chaîne du sous-système correspondant sur la baie ONTAP :
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_coexistence_LPE36002
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ------------------------------------------------
vs_coexistence_LPE36002
        nvme
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
        nvme_1
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
        nvme_2
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
        nvme_3
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
4 entries were displayed.
----
====
+

NOTE: Si le `hostnqn` les chaînes ne correspondent pas, utilisez le `vserver modify` commande pour mettre à jour le `hostnqn` Chaîne sur le sous-système de matrice ONTAP correspondant à `hostnqn` chaîne de `/etc/nvme/hostnqn` sur l'hôte.





== Étape 3 : Configurer NVMe/FC

Vous pouvez configurer NVMe/FC avec les adaptateurs FC Broadcom/Emulex ou Marvell/Qlogic. Vous devez également découvrir manuellement les sous-systèmes et espaces de noms NVMe/TCP.

[role="tabbed-block"]
====
.Broadcom/Emulex
--
Configuration de NVMe/FC pour une carte FC Broadcom/Emulex

.Étapes
. Vérifiez que vous utilisez le modèle d'adaptateur pris en charge :
+
.. Afficher les noms des modèles :
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
LPe36002-M64
LPe36002-M64
----
.. Afficher les descriptions des modèles :
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Vous devriez voir une sortie similaire à l’exemple suivant :

+
[listing]
----
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
----


. Vérifiez que vous utilisez la carte Broadcom recommandée `lpfc` micrologiciel et pilote de boîte de réception :
+
.. Afficher la version du firmware :
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
L'exemple suivant montre les versions du firmware :

+
[listing]
----
14.4.393.25, sli-4:2:c
14.4.393.25, sli-4:2:c
----
.. Afficher la version du pilote de la boîte de réception :
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
L'exemple suivant montre une version de pilote :

+
[listing]
----
0:14.4.0.8
----


+
Pour obtenir la liste actuelle des versions de pilotes et de micrologiciels de carte prises en charge, consultez le link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].

. Vérifiez que la sortie attendue de `lpfc_enable_fc4_type` est définie sur `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Vérifiez que vous pouvez afficher vos ports initiateurs :
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
L'exemple suivant montre les identités de port :

+
[listing]
----
0x10000090fae0ec88
0x10000090fae0ec89
----
. Vérifiez que vos ports initiateurs sont en ligne :
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
Online
Online
----
. Vérifiez que les ports initiateurs NVMe/FC sont activés et que les ports cibles sont visibles :
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Affiche un exemple de résultat
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec88 WWNN x20000090fae0ec88 DID x0a1300 *ONLINE*
NVME RPORT       WWPN x23b1d039ea359e4a WWNN x23aed039ea359e4a DID x0a1c01 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x22bbd039ea359e4a WWNN x22b8d039ea359e4a DID x0a1c0b *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2362d039ea359e4a WWNN x234ed039ea359e4a DID x0a1c10 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x23afd039ea359e4a WWNN x23aed039ea359e4a DID x0a1a02 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x22b9d039ea359e4a WWNN x22b8d039ea359e4a DID x0a1a0b *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2360d039ea359e4a WWNN x234ed039ea359e4a DID x0a1a11 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000004ea0 Cmpl 0000004ea0 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000000102c35 Issue 0000000000102c2d OutIO fffffffffffffff8
        abort 00000175 noxri 00000000 nondlp 0000021d qdepth 00000000 wqerr 00000007 err 00000000
FCP CMPL: xb 00000175 Err 0000058b

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x10000090fae0ec89 WWNN x20000090fae0ec89 DID x0a1200 *ONLINE*
NVME RPORT       WWPN x23b2d039ea359e4a WWNN x23aed039ea359e4a DID x0a1d01 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x22bcd039ea359e4a WWNN x22b8d039ea359e4a DID x0a1d0b *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2363d039ea359e4a WWNN x234ed039ea359e4a DID x0a1d10 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x23b0d039ea359e4a WWNN x23aed039ea359e4a DID x0a1b02 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x22bad039ea359e4a WWNN x22b8d039ea359e4a DID x0a1b0b *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2361d039ea359e4a WWNN x234ed039ea359e4a DID x0a1b11 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000004e31 Cmpl 0000004e31 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 00000000001017f2 Issue 00000000001017ef OutIO fffffffffffffffd
        abort 0000018a noxri 00000000 nondlp 0000012e qdepth 00000000 wqerr 00000004 err 00000000
FCP CMPL: xb 0000018a Err 000005ca
----
=====


--
.Marvell/QLogic
--
Configuration du NVMe/FC pour un adaptateur Marvell/QLogic

.Étapes
. Vérifiez que vous exécutez les versions du pilote de carte et du micrologiciel prises en charge :
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
L'exemple suivant montre les versions du pilote et du micrologiciel :

+
[listing]
----
QLE2742 FW:v9.14.00 DVR:v10.02.09.400-k-debug
QLE2742 FW:v9.14.00 DVR:v10.02.09.400-k-debug
----
. Vérifiez-le `ql2xnvmeenable` est défini. L'adaptateur Marvell peut ainsi fonctionner en tant qu'initiateur NVMe/FC :
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
La sortie attendue est 1.



--
====


== Étape 4 : Activez éventuellement 1 Mo d'E/S

ONTAP signale une taille de transfert de données maximale (MDTS) de 8 dans les données du contrôleur d'identification.  Cela signifie que la taille maximale de la demande d'E/S peut atteindre 1 Mo.  Pour émettre des requêtes d'E/S d'une taille de 1 Mo pour un hôte Broadcom NVMe/FC, vous devez augmenter la `lpfc` valeur de la `lpfc_sg_seg_cnt` paramètre à 256 à partir de la valeur par défaut de 64.


NOTE: Ces étapes ne s'appliquent pas aux hôtes NVMe/FC Qlogic.

.Étapes
. Réglez le `lpfc_sg_seg_cnt` paramètre sur 256 :
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
Vous devriez voir une sortie similaire à l’exemple suivant :

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Exécutez `dracut -f` la commande et redémarrez l'hôte.
. Vérifier que la valeur de `lpfc_sg_seg_cnt` est 256 :
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== Étape 5 : Vérifier les services de démarrage NVMe

Avec SLES 15 SP7, le  `nvmefc-boot-connections.service` et  `nvmf-autoconnect.service` services de démarrage inclus dans NVMe/FC  `nvme-cli` les packages sont automatiquement activés pour démarrer lors du démarrage du système. Une fois le démarrage terminé, vérifiez que les services de démarrage sont activés.

.Étapes
. Vérifiez que `nvmf-autoconnect.service` est activé :
+
[source, cli]
----
systemctl status nvmf-autoconnect.service
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot
  Loaded: loaded (/usr/lib/systemd/system/nvmf-autoconnect.service; enabled; preset: enabled)
  Active: inactive (dead) since Fri 2025-07-04 23:56:38 IST; 4 days ago
  Main PID: 12208 (code=exited, status=0/SUCCESS)
    CPU: 62ms

Jul 04 23:56:26 localhost systemd[1]: Starting Connect NVMe-oF subsystems automatically during boot...
Jul 04 23:56:38 localhost systemd[1]: nvmf-autoconnect.service: Deactivated successfully.
Jul 04 23:56:38 localhost systemd[1]: Finished Connect NVMe-oF subsystems automatically during boot.
----
====
. Vérifiez que `nvmefc-boot-connections.service` est activé :
+
[source, cli]
----
systemctl status nvmefc-boot-connections.service
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot
    Loaded: loaded (/usr/lib/systemd/system/nvmefc-boot-connections.service; enabled; preset: enabled)
    Active: inactive (dead) since Mon 2025-07-07 19:52:30 IST; 1 day 4h ago
  Main PID: 2945 (code=exited, status=0/SUCCESS)
      CPU: 14ms

Jul 07 19:52:30 HP-DL360-14-168 systemd[1]: Starting Auto-connect to subsystems on FC-NVME devices found during boot...
Jul 07 19:52:30 HP-DL360-14-168 systemd[1]: nvmefc-boot-connections.service: Deactivated successfully.
Jul 07 19:52:30 HP-DL360-14-168 systemd[1]: Finished Auto-connect to subsystems on FC-NVME devices found during boot.
----
====




== Étape 6 : Configurer NVMe/TCP

Le protocole NVMe/TCP ne prend pas en charge `auto-connect` l'opération. Vous pouvez à la place détecter les sous-systèmes et les espaces de noms NVMe/TCP en exécutant manuellement les opérations NVMe/TCP `connect` ou `connect-all`.

.Étapes
. Vérifiez que le port initiateur peut récupérer les données de la page de journal de découverte sur les LIF NVMe/TCP prises en charge :
+
[listing]
----
nvme discover -t tcp -w <host-traddr> -a <traddr>
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.111.80 -a 192.168.111.70
Discovery Log Number of Records 8, Generation counter 42
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  4
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:discovery
traddr:  192.168.211.71
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  3
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:discovery
traddr:  192.168.111.71
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  2
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:discovery
traddr:  192.168.211.70
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:discovery
traddr:  192.168.111.70
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 4======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  4
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:subsystem.sample_tcp_sub
traddr:  192.168.211.71
eflags:  none
sectype: none
=====Discovery Log Entry 5======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  3
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:subsystem.sample_tcp_sub
traddr:  192.168.111.71
eflags:  none
sectype: none
=====Discovery Log Entry 6======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  2
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:subsystem.sample_tcp_sub
traddr:  192.168.211.70
eflags:  none
sectype: none
=====Discovery Log Entry 7======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:subsystem.sample_tcp_sub
traddr:  192.168.111.70
eflags:  none
sectype: none
localhost:~ #
----
====
. Vérifier que toutes les autres combinaisons de LIF NVMe/TCP initiator-target peuvent récupérer les données de la page du journal de découverte :
+
[listing]
----
nvme discover -t tcp -w <host-traddr> -a <traddr>
----
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.111.80 -a 192.168.111.66
nvme discover -t tcp -w 192.168.111.80 -a 192.168.111.67
nvme discover -t tcp -w 192.168.211.80 -a 192.168.211.66
nvme discover -t tcp -w 192.168.211.80 -a 192.168.211.67
----
====
. Exécutez le `nvme connect-all` Commande sur toutes les LIF cible-initiateur NVMe/TCP prises en charge sur l'ensemble des nœuds :
+
[listing]
----
nvme connect-all -t tcp -w <host-traddr> -a <traddr>
----
+
.Montrer l'exemple
[%collapsible]
====
[listing, subs="+quotes"]
----
nvme	connect-all	-t	tcp	-w	192.168.111.80	-a	192.168.111.66
nvme	connect-all	-t	tcp	-w	192.168.111.80	-a	192.168.111.67
nvme	connect-all	-t	tcp	-w	192.168.211.80	-a	192.168.211.66
nvme	connect-all	-t	tcp	-w	192.168.211.80	-a	192.168.211.67
----
====



NOTE: À partir de SLES 15 SP6, le paramètre par défaut pour NVMe/TCP  `ctrl-loss-tmo` Le délai d'expiration est désactivé. Cela signifie qu'il n'y a pas de limite au nombre de tentatives (répétitions indéfinies) et qu'il n'est pas nécessaire de configurer manuellement un délai spécifique.  `ctrl-loss-tmo` durée du délai d'attente lors de l'utilisation du  `nvme connect` ou  `nvme connect-all` commandes (option  `-l` ). Par ailleurs, les contrôleurs NVMe/TCP ne connaissent pas de délais d'expiration en cas de défaillance de chemin et restent connectés indéfiniment.



== Étape 7 : Valider NVMe-oF

Vérifiez que l'état des chemins d'accès multiples NVMe in-kernel, l'état ANA et les namespaces ONTAP sont corrects pour la configuration NVMe-of.

.Étapes
. Vérifiez que le chemin d'accès multiples NVMe intégré au noyau est activé :
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
Y
----
. Vérifiez que les paramètres NVMe-of appropriés (par exemple, modèle défini sur contrôleur NetApp ONTAP et iopole d'équilibrage de la charge sur round-Robin) pour les espaces de noms ONTAP respectifs reflètent correctement l'hôte :
+
.. Afficher les sous-systèmes :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. Afficher la politique :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
round-robin
round-robin
----


. Vérifiez que les espaces de noms sont créés et correctement découverts sur l'hôte :
+
[source, cli]
----
nvme list
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme4n1 81Ix2BVuekWcAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
====
. Vérifiez que l'état du contrôleur de chaque chemin est actif et que l'état ANA est correct :
+
[role="tabbed-block"]
====
.NVMe/FC
--
[listing]
----
nvme list-subsys /dev/nvme4n5
----
.Affiche un exemple de résultat
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys114 - NQN=nqn.1992-08.com.netapp:sn.9e30b9760a4911f08c87d039eab67a95:subsystem.sles_161_27
                 hostnqn=nqn.2014-08.org.nvmexpress:uuid:f6517cae-3133-11e8-bbff-7ed30aef123f
iopolicy=round-robin\
+- nvme114 *fc* traddr=nn-0x234ed039ea359e4a:pn-0x2360d039ea359e4a,host_traddr=nn-0x20000090fae0ec88:pn-0x10000090fae0ec88 *live optimized*
+- nvme115 *fc* traddr=nn-0x234ed039ea359e4a:pn-0x2362d039ea359e4a,host_traddr=nn-0x20000090fae0ec88:pn-0x10000090fae0ec88 *live non-optimized*
+- nvme116 *fc* traddr=nn-0x234ed039ea359e4a:pn-0x2361d039ea359e4a,host_traddr=nn-0x20000090fae0ec89:pn-0x10000090fae0ec89 *live optimized*
+- nvme117 *fc* traddr=nn-0x234ed039ea359e4a:pn-0x2363d039ea359e4a,host_traddr=nn-0x20000090fae0ec89:pn-0x10000090fae0ec89 *live non-optimized*
----
=====
--
.NVMe/TCP
--
[listing]
----
nvme list-subsys /dev/nvme9n1
----
.Affiche un exemple de résultat
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys9 - NQN=nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:subsystem.with_inband_with_json hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-b2c04f444d33
iopolicy=round-robin
\
+- nvme10 *tcp* traddr=192.168.111.71,trsvcid=4420,src_addr=192.168.111.80 *live non-optimized*
 +- nvme11 *tcp* traddr=192.168.211.70,trsvcid=4420,src_addr=192.168.211.80 *live optimized*
 +- nvme12 *tcp* traddr=192.168.111.70,trsvcid=4420,src_addr=192.168.111.80 *live optimized*
 +- nvme9 *tcp* traddr=192.168.211.71,trsvcid=4420,src_addr=192.168.211.80 *live non-optimized*
----
=====
--
====
. Vérifier que le plug-in NetApp affiche les valeurs correctes pour chaque périphérique d'espace de noms ONTAP :


[role="tabbed-block"]
====
.Colonne
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.Montrer l'exemple
[%collapsible]
=====
[listing, subs="+quotes"]
----
Device           Vserver                   Namespace Path                                     NSID UUID                                   Size
---------------- ------------------------- -------------------------------------------------- ---- -------------------------------------- ---------
/dev/nvme0n1     vs_161                    /vol/fc_nvme_vol1/fc_nvme_ns1                      1    32fd92c7-0797-428e-a577-fdb3f14d0dc3   5.37GB
----
=====
--
.JSON
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.Montrer l'exemple
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
      "Device":"/dev/nvme98n2",
      "Vserver":"vs_161",
      "Namespace_Path":"/vol/fc_nvme_vol71/fc_nvme_ns71",
      "NSID":2,
      "UUID":"39d634c4-a75e-4fbd-ab00-3f9355a26e43",
      "LBA_Size":4096,
      "Namespace_Size":5368709120,
      "UsedBytes":430649344,
    }
  ]
}
----
=====
--
====


== Étape 8 : Créer un contrôleur de découverte persistant

À partir d' ONTAP 9.11.1, vous pouvez créer un contrôleur de découverte persistante (PDC) pour un hôte SLES 15 SP7. Un PDC est nécessaire pour détecter automatiquement une opération d'ajout ou de suppression d'un sous-système NVMe et les modifications apportées aux données de la page du journal de découverte.

.Étapes
. Vérifier que les données de la page du journal de découverte sont disponibles et peuvent être récupérées via la combinaison port initiateur et LIF cible :
+
[source, cli]
----
nvme discover -t <trtype> -w <host-traddr> -a <traddr>
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing, subs="+quotes"]
----
Discovery Log Number of Records 8, Generation counter 18
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  4
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:discovery
traddr:  192.168.111.66
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  2
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:discovery
traddr:  192.168.211.66
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  3
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:discovery
traddr:  192.168.111.67
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:discovery
traddr:  192.168.211.67
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: *none*
=====Discovery Log Entry 4======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  4
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.pdc
traddr:  192.168.111.66
eflags:  none
sectype: none
=====Discovery Log Entry 5======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  2
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.pdc
traddr:  192.168.211.66
eflags:  none
sectype: none
=====Discovery Log Entry 6======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  3
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.pdc
traddr:  192.168.111.67
eflags:  none
sectype: none
=====Discovery Log Entry 7======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.pdc
traddr:  192.168.211.67
eflags:  none
sectype: none
----
====
. Créer un PDC pour le sous-système de découverte :
+
[source, cli]
----
nvme discover -t <trtype> -w <host-traddr> -a <traddr> -p
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
nvme discover -t tcp -w 192.168.111.80 -a 192.168.111.66 -p
----
. À partir du contrôleur ONTAP, vérifier que le PDC a été créé :
+
[source, cli]
----
vserver nvme show-discovery-controller -instance -vserver <vserver_name>
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing, subs="+quotes"]
----
vserver nvme show-discovery-controller -instance -vserver vs_pdc

           Vserver Name: vs_pdc
               Controller ID: 0101h
     Discovery Subsystem NQN: nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:discovery
           Logical Interface: lif2
                        Node: A400-12-181
                    Host NQN: nqn.2014-08.org.nvmexpress:uuid:9796c1ec-0d34-11eb-b6b2-3a68dd3bab57
          Transport Protocol: nvme-tcp
 Initiator Transport Address: 192.168.111.80
Transport Service Identifier: 8009
             Host Identifier: 9796c1ec0d3411ebb6b23a68dd3bab57
           Admin Queue Depth: 32
       Header Digest Enabled: false
         Data Digest Enabled: false
   Keep-Alive Timeout (msec): 30000
----
====




== Étape 9 : Configurer une authentification sécurisée en bande

À partir d'ONTAP 9.12.1, l'authentification sécurisée en bande est prise en charge via NVMe/TCP et NVMe/FC entre l'hôte et le contrôleur ONTAP.

Pour configurer l'authentification sécurisée, chaque hôte ou contrôleur doit être associé à un `DH-HMAC-CHAP` Clé, qui combine le NQN de l'hôte ou du contrôleur NVMe et un code d'authentification configuré par l'administrateur. Pour authentifier son homologue, un hôte ou un contrôleur NVMe doit reconnaître la clé associée à cet homologue.

Vous pouvez configurer l'authentification intrabande sécurisée à l'aide de l'interface de ligne de commande ou d'un fichier JSON de configuration. Si vous devez spécifier différentes clés dhchap pour différents sous-systèmes, vous devez utiliser un fichier JSON de configuration.

[role="tabbed-block"]
====
.CLI
--
Configurez l'authentification intrabande sécurisée à l'aide de l'interface de ligne de commande.

.Étapes
. Obtenir le NQN hôte :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
. Générer la clé dhchap pour l'hôte.
+
Le résultat suivant décrit les `gen-dhchap-key` paramètres de commande :

+
[listing]
----
nvme gen-dhchap-key -s optional_secret -l key_length {32|48|64} -m HMAC_function {0|1|2|3} -n host_nqn
•	-s secret key in hexadecimal characters to be used to initialize the host key
•	-l length of the resulting key in bytes
•	-m HMAC function to use for key transformation
0 = none, 1- SHA-256, 2 = SHA-384, 3=SHA-512
•	-n host NQN to use for key transformation
----
+
Dans l'exemple suivant, une clé dhchap aléatoire avec HMAC définie sur 3 (SHA-512) est générée.

+
[listing]
----
nvme gen-dhchap-key -m 3 -n nqn.2014-08.org.nvmexpress:uuid:e6dade64-216d-11ec-b7bb-7ed30a5482c3
DHHC-1:03:1CFivw9ccz58gAcOUJrM7Vs98hd2ZHSr+iw+Amg6xZPl5D2Yk+HDTZiUAg1iGgxTYqnxukqvYedA55Bw3wtz6sJNpR4=:
----
. Sur le contrôleur ONTAP, ajoutez l'hôte et spécifiez les deux clés dhchap :
+
[listing]
----
vserver nvme subsystem host add -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn> -dhchap-host-secret <authentication_host_secret> -dhchap-controller-secret <authentication_controller_secret> -dhchap-hash-function {sha-256|sha-512} -dhchap-group {none|2048-bit|3072-bit|4096-bit|6144-bit|8192-bit}
----
. Un hôte prend en charge deux types de méthodes d'authentification, unidirectionnelles et bidirectionnelles. Sur l'hôte, connectez-vous au contrôleur ONTAP et spécifiez des clés dhchap en fonction de la méthode d'authentification choisie :
+
[listing]
----
nvme connect -t tcp -w <host-traddr> -a <tr-addr> -n <host_nqn> -S <authentication_host_secret> -C <authentication_controller_secret>
----
. Valider le `nvme connect authentication` en vérifiant les clés dhchap de l'hôte et du contrôleur :
+
.. Vérifiez les clés dhchap hôte :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_secret
----
+
.Affiche un exemple de sortie pour une configuration unidirectionnelle
[%collapsible]
=====
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys1/nvme*/dhchap_secret
DHHC-1:01:iM63E6cX7G5SOKKOju8gmzM53qywsy+C/YwtzxhIt9ZRz+ky:
DHHC-1:01:iM63E6cX7G5SOKKOju8gmzM53qywsy+C/YwtzxhIt9ZRz+ky:
DHHC-1:01:iM63E6cX7G5SOKKOju8gmzM53qywsy+C/YwtzxhIt9ZRz+ky:
DHHC-1:01:iM63E6cX7G5SOKKOju8gmzM53qywsy+C/YwtzxhIt9ZRz+ky:
----
=====
.. Vérifiez les clés dhchap du contrôleur :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_ctrl_secret
----
+
.Affiche un exemple de sortie pour une configuration bidirectionnelle
[%collapsible]
=====
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys6/nvme*/dhchap_ctrl_secret
DHHC-1:03:1CFivw9ccz58gAcOUJrM7Vs98hd2ZHSr+iw+Amg6xZPl5D2Yk+HDTZiUAg1iGgxTYqnxukqvYedA55Bw3wtz6sJNpR4=:
DHHC-1:03:1CFivw9ccz58gAcOUJrM7Vs98hd2ZHSr+iw+Amg6xZPl5D2Yk+HDTZiUAg1iGgxTYqnxukqvYedA55Bw3wtz6sJNpR4=:
DHHC-1:03:1CFivw9ccz58gAcOUJrM7Vs98hd2ZHSr+iw+Amg6xZPl5D2Yk+HDTZiUAg1iGgxTYqnxukqvYedA55Bw3wtz6sJNpR4=:
DHHC-1:03:1CFivw9ccz58gAcOUJrM7Vs98hd2ZHSr+iw+Amg6xZPl5D2Yk+HDTZiUAg1iGgxTYqnxukqvYedA55Bw3wtz6sJNpR4=:
----
=====




--
.Fichier JSON
--
Lorsque plusieurs sous-systèmes NVMe sont disponibles dans la configuration du contrôleur ONTAP, vous pouvez utiliser le `/etc/nvme/config.json` fichier avec la `nvme connect-all` commande.

Pour générer le fichier JSON, vous pouvez utiliser l' `-o`option. Pour plus d'options de syntaxe, reportez-vous aux pages de manuel de NVMe Connect-all.

.Étapes
. Configurez le fichier JSON :
+
.Affiche un exemple de résultat
[%collapsible]
=====
[listing]
----
# cat /etc/nvme/config.json
[
 {
    "hostnqn":"nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-b2c04f444d33",
    "hostid":"4c4c4544-0035-5910-804b-b2c04f444d33",
    "dhchap_key":"DHHC-1:01:i4i789R11sMuHLCY27RVI8XloC\/GzjRwyhxip5hmIELsHrBq:",
    "subsystems":[
      {
        "nqn":"nqn.1992-08.com.netapp:sn.f8e2af201b7211f0ac2bd039eab67a95:subsystem.sample_tcp_sub",
        "ports":[
          {
            "transport":"tcp",
            "traddr":"192.168.111.70",
            "host_traddr":"192.168.111.80",
            "trsvcid":"4420"
            "dhchap_ctrl_key":"DHHC-1:03:jqgYcJSKp73+XqAf2X6twr9ngBpr2n0MGWbmZIZq4PieKZCoilKGef8lAvhYS0PNK7T+04YD5CRPjh+m3qjJU++yR8s=:"
          },
               {
                    "transport":"tcp",
                    "traddr":"192.168.111.71",
                    "host_traddr":"192.168.111.80",
                    "trsvcid":"4420",
                    "dhchap_ctrl_key":"DHHC-1:03:jqgYcJSKp73+XqAf2X6twr9ngBpr2n0MGWbmZIZq4PieKZCoilKGef8lAvhYS0PNK7T+04YD5CRPjh+m3qjJU++yR8s=:"
               },
               {
                    "transport":"tcp",
                    "traddr":"192.168.211.70",
                    "host_traddr":"192.168.211.80",
                    "trsvcid":"4420",
                    "dhchap_ctrl_key":"DHHC-1:03:jqgYcJSKp73+XqAf2X6twr9ngBpr2n0MGWbmZIZq4PieKZCoilKGef8lAvhYS0PNK7T+04YD5CRPjh+m3qjJU++yR8s=:"
               },
               {
                    "transport":"tcp",
                    "traddr":"192.168.211.71",
                    "host_traddr":"192.168.211.80",
                    "trsvcid":"4420",
                    "dhchap_ctrl_key":"DHHC-1:03:jqgYcJSKp73+XqAf2X6twr9ngBpr2n0MGWbmZIZq4PieKZCoilKGef8lAvhYS0PNK7T+04YD5CRPjh+m3qjJU++yR8s=:"
               }
           ]
       }
   ]
 }
]
----
=====
+

NOTE: Dans l'exemple précédent, `dhchap_key` correspond à `dhchap_secret` et `dhchap_ctrl_key` correspond à `dhchap_ctrl_secret`.

. Connectez-vous au contrôleur ONTAP à l'aide du fichier JSON de configuration :
+
[source, cli]
----
nvme connect-all -J /etc/nvme/config.json
----
+
.Affiche un exemple de résultat
[%collapsible]
=====
[listing]
----
traddr=192.168.211.70 is already connected
traddr=192.168.111.71 is already connected
traddr=192.168.211.71 is already connected
traddr=192.168.111.70 is already connected
traddr=192.168.211.70 is already connected
traddr=192.168.111.70 is already connected
traddr=192.168.211.71 is already connected
traddr=192.168.111.71 is already connected
traddr=192.168.211.70 is already connected
traddr=192.168.111.71 is already connected
traddr=192.168.211.71 is already connected
traddr=192.168.111.70 is already connected
----
=====
. Vérifiez que les secrets dhchap ont été activés pour les contrôleurs respectifs de chaque sous-système :
+
.. Vérifiez les clés dhchap hôte :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys0/nvme0/dhchap_secret
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
DHHC-1:01:i4i789R11sMuHLCY27RVI8XloC/GzjRwyhxip5hmIELsHrBq:
----
.. Vérifiez les clés dhchap du contrôleur :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys0/nvme0/dhchap_ctrl_secret
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
DHHC-1:03:jqgYcJSKp73+XqAf2X6twr9ngBpr2n0MGWbmZIZq4PieKZCoilKGef8lAvhYS0PNK7T+04YD5CRPjh+m3qjJU++yR8s=:
----




--
====


== Étape 10 : Configurer la sécurité de la couche de transport

TLS (transport Layer Security) assure le chiffrement sécurisé de bout en bout des connexions NVMe entre des hôtes NVMe-of et une baie ONTAP. À partir de ONTAP 9.16.1, vous pouvez configurer TLS 1.3 à l'aide de l'interface de ligne de commande et d'une clé pré-partagée (PSK) configurée.

.Description de la tâche
Vous effectuez les étapes de cette procédure sur l'hôte SUSE Linux Enterprise Server, sauf lorsqu'il est spécifié que vous effectuez une étape sur le contrôleur ONTAP.

.Étapes
. Vérifiez que vous disposez des éléments suivants  `ktls-utils` ,  `openssl` , et  `libopenssl` paquets installés sur l'hôte :
+
.. Vérifiez le  `ktls-utils` :
+
[source, cli]
----
rpm -qa | grep ktls
----
+
Vous devriez voir la sortie suivante affichée :

+
[listing]
----
ktls-utils-0.10+33.g311d943-150700.1.5.x86_64
----
.. Vérifiez les packages SSL :
+
[source, cli]
----
rpm -qa | grep ssl
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
libopenssl3-3.2.3-150700.3.20.x86_64
openssl-3-3.2.3-150700.3.20.x86_64
libopenssl1_1-1.1.1w-150700.9.37.x86_64
----
====


. Vérifiez que vous disposez de la configuration correcte pour `/etc/tlshd.conf`:
+
[source, cli]
----
cat /etc/tlshd.conf
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing, subs="+quotes"]
----
[debug]
loglevel=0
tls=0
nl=0
[authenticate]
*keyrings=.nvme*
[authenticate.client]
#x509.truststore= <pathname>
#x509.certificate= <pathname>
#x509.private_key= <pathname>
[authenticate.server]
#x509.truststore= <pathname>
#x509.certificate= <pathname>
#x509.private_key= <pathname>
----
====
. Activer `tlshd` pour démarrer au démarrage du système :
+
[source, cli]
----
systemctl enable tlshd
----
. Vérifiez que le `tlshd` démon est en cours d'exécution :
+
[source, cli]
----
systemctl status tlshd
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
tlshd.service - Handshake service for kernel TLS consumers
   Loaded: loaded (/usr/lib/systemd/system/tlshd.service; enabled; preset: disabled)
   Active: active (running) since Wed 2024-08-21 15:46:53 IST; 4h 57min ago
     Docs: man:tlshd(8)
Main PID: 961 (tlshd)
   Tasks: 1
     CPU: 46ms
   CGroup: /system.slice/tlshd.service
       └─961 /usr/sbin/tlshd
Aug 21 15:46:54 RX2530-M4-17-153 tlshd[961]: Built from ktls-utils 0.11-dev on Mar 21 2024 12:00:00
----
====
. Générez le TLS PSK en utilisant `nvme gen-tls-key` :
+
.. Vérifiez l'hôte :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-b2c04f444d33
----
.. Vérifiez la clé :
+
[source, cli]
----
nvme gen-tls-key --hmac=1 --identity=1 --subsysnqn= nqn.1992-08.com.netapp:sn.a2d41235b78211efb57dd039eab67a95:subsystem.nvme1
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
NVMeTLSkey-1:01:C50EsaGtuOp8n5fGE9EuWjbBCtshmfoHx4XTqTJUmydf0gIj:
----


. Sur le contrôleur ONTAP, ajoutez le protocole TLS PSK au sous-système ONTAP :
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
nvme subsystem host add -vserver vs_iscsi_tcp -subsystem nvme1 -host-nqn nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-b2c04f444d33 -tls-configured-psk NVMeTLSkey-1:01:C50EsaGtuOp8n5fGE9EuWjbBCtshmfoHx4XTqTJUmydf0gIj:
----
====
. Insérez le TLS PSK dans le porte-clés du noyau hôte :
+
[source, cli]
----
nvme check-tls-key --identity=1 --subsysnqn=nqn.1992-08.com.netapp:sn.a2d41235b78211efb57dd039eab67a95:subsystem.nvme1 --keydata=NVMeTLSkey-1:01:C50EsaGtuOp8n5fGE9EuWjbBCtshmfoHx4XTqTJUmydf0gIj: --insert
----
+
Vous devriez voir la clé TLS suivante :

+
[listing]
----
Inserted TLS key 22152a7e
----
+

NOTE: Le PSK montre comme  `NVMe1R01` parce qu'il utilise  `identity v1` à partir de l'algorithme de négociation TLS. Identity v1 est la seule version prise en charge par ONTAP.

. Vérifiez que TLS PSK est correctement inséré :
+
[source, cli]
----
cat /proc/keys | grep NVMe
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
069f56bb I--Q---     5 perm 3b010000     0     0 psk       NVMe1R01 nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-b2c04f444d33 nqn.1992-08.com.netapp:sn.a2d41235b78211efb57dd039eab67a95:subsystem.nvme1 oYVLelmiOwnvDjXKBmrnIgGVpFIBDJtc4hmQXE/36Sw=: 32
----
====
. Connectez-vous au sous-système ONTAP à l'aide du protocole TLS PSK inséré :
+
.. Vérifiez le TLS PSK :
+
[source, cli]
----
nvme connect -t tcp -w 192.168.111.80 -a 192.168.111.66  -n nqn.1992-08.com.netapp:sn.a2d41235b78211efb57dd039eab67a95:subsystem.nvme1 --tls_key=0x069f56bb –tls
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
connecting to device: nvme0
----
.. Vérifiez la liste-sous-système :
+
[source, cli]
----
nvme list-subsys
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.a2d41235b78211efb57dd039eab67a95:subsystem.nvme1
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-b2c04f444d33
\
 +- nvme0 tcp traddr=192.168.111.66,trsvcid=4420,host_traddr=192.168.111.80,src_addr=192.168.111.80 live
----
====


. Ajoutez la cible et vérifiez la connexion TLS au sous-système ONTAP spécifié :
+
[source, cli]
----
nvme subsystem controller show -vserver sles15_tls -subsystem sles15 -instance
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
(vserver nvme subsystem controller show)
                          Vserver Name: vs_iscsi_tcp
                          Subsystem: nvme1
                      Controller ID: 0040h
                  Logical Interface: tcpnvme_lif1_1
                               Node: A400-12-181
                           Host NQN: nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-b2c04f444d33
                 Transport Protocol: nvme-tcp
        Initiator Transport Address: 192.168.111.80
                    Host Identifier: 4c4c454400355910804bb2c04f444d33
               Number of I/O Queues: 2
                   I/O Queue Depths: 128, 128
                  Admin Queue Depth: 32
              Max I/O Size in Bytes: 1048576
          Keep-Alive Timeout (msec): 5000
                     Subsystem UUID: 8bbfb403-1602-11f0-ac2b-d039eab67a95
              Header Digest Enabled: false
                Data Digest Enabled: false
       Authentication Hash Function: sha-256
Authentication Diffie-Hellman Group: 3072-bit
                Authentication Mode: unidirectional
       Transport Service Identifier: 4420
                       TLS Key Type: configured
                   TLS PSK Identity: NVMe1R01 nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-b2c04f444d33 nqn.1992-08.com.netapp:sn.a2d41235b78211efb57dd039eab67a95:subsystem.nvme1 oYVLelmiOwnvDjXKBmrnIgGVpFIBDJtc4hmQXE/36Sw=
                         TLS Cipher: TLS-AES-128-GCM-SHA256
----
====




== Étape 11 : passez en revue les problèmes connus

Il n'y a pas de problème connu.
