---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: Comment configurer un hôte NVMe/FC pour AIX avec ONTAP 
---
= Configuration d'hôte NVMe/FC pour AIX avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez activer NVMe over Fibre Channel (NVMe/FC) sur des hôtes IBM AIX et VIOS/PowerVM en utilisant le stockage ONTAP comme cible. Pour plus de détails sur les configurations prises en charge, consultez le link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].

La prise en charge suivante est disponible pour la configuration hôte NVMe/FC pour un hôte AIX avec ONTAP :

* À partir de ONTAP 9.13.1, la prise en charge de NVMe/FC est ajoutée pour les versions IBM AIX 7.2 TL5 SP6, AIX 7.3 TL1 SP2 et VIOS 3.1.4.21 avec prise en charge du démarrage SAN pour les piles physiques et virtuelles. Pour plus d'informations sur la configuration de la prise en charge de l'amorçage SAN, reportez-vous à la documentation IBM.
* NVMe/FC est pris en charge par les serveurs IBM Power9 et Power10.
* Pour les périphériques NVMe, aucun module de contrôle des chemins d'accès (PCM) distinct, tel que la prise en charge MPIO (Host Utilities for AIX SCSI Multipath I/O) n'est requis.
* La prise en charge de la virtualisation avec NetApp (VIOS/PowerVM) est introduite avec le logiciel VIOS 3.1.4.21. Ceci est _uniquement_ pris en charge via le mode de virtualisation du stockage NPIV (N_portID Virtualization) à l'aide du serveur IBM Power10.


.Ce dont vous avez besoin
* Vérifiez que vous disposez d'adaptateurs Emulex FC 32 Gb (EN1A, EN1B, EN1L, EN1M) ou d'adaptateurs FC 64 Go (EN1N, EN1P) avec micrologiciel d'adaptateur 12.4.257.30 et versions ultérieures.
* Si vous disposez d'une configuration MetroCluster, NetApp recommande de modifier le délai d'interruption par défaut (All Path Down) pour la prise en charge des événements de basculement non planifiés MetroCluster afin d'éviter que le système d'exploitation AIX n'applique un délai d'expiration d'E/S plus court. Pour plus d'informations et pour connaître les modifications recommandées des paramètres par défaut, reportez-vous à la section Bugs NetApp en ligne - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249"^].
* Par défaut, la valeur Asymmetric Namespace Access transition Timeout (ANATT) du système d'exploitation hôte AIX est de 30 secondes. IBM fournit un correctif provisoire (ifix) qui limite la valeur de l'ANATT à 60 secondes ; vous devez installer un ifix à partir du site Web d'IBM pour vous assurer que tous les flux de travail ONTAP sont sans interruption.
+

NOTE: Pour la prise en charge de NVMe/FC AIX, vous devez installer un ifix sur les versions GA du système d'exploitation AIX. Ceci n'est pas nécessaire pour le système d'exploitation VIOS/PowerVM.

+
Les détails ifix sont les suivants :

+
** Pour AIX niveau 72-TL5-SP6-2320, installez `IJ46710s6a.230509.epkg.Z` création de package.
** Pour AIX niveau 73-TL1-SP2-2320, installez `IJ46711s2a.230509.epkg.Z` création de package.
+
Pour plus d'informations sur la gestion des ifexes, reportez-vous à la section link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["Gestion des correctifs provisoires sous AIX"^].

+

NOTE: Vous devez installer les ifix sur une version AIX sans aucun ifix précédemment installé associé à `devices.pciex.pciexclass.010802.rte` sur le système. Si ces ifexes sont présents, ils entrent en conflit avec la nouvelle installation.

+
Le tableau suivant présente les HBA attribués à la partition logique AIX (AIX Logical partition) ou à la pile physique :

+
[cols="10,10,10,10,10"]
|===
| Système d'exploitation hôte | Power Arch | Version Power FW | Mode | Commentaires 


.2+| AIX 7.2 TL5 SP6 | Puissance 9 | FW 950 ou version ultérieure | Pile physique | ifix est disponible via TS012877410. 


| Puissance 10 | FW 1010 ou version ultérieure | Pile physique | Le démarrage SAN est pris en charge. ifix est disponible via TS012877410. 


.2+| AIX 7.3 TL1 SP2 | Puissance 9 | FW 950 ou version ultérieure | Pile physique | ifix est disponible via TS012877410. 


| Puissance 10 | FW 1010 ou version ultérieure | Pile physique et virtuelle | ifix est disponible via TS012877410. 
|===
+
Le tableau suivant présente les HBA attribués au VIOS avec prise en charge NPIV en mode virtualisé :

+
[cols="10,10,10,10,10"]
|===
| Système d'exploitation hôte | Power Arch | Version Power FW | Mode | Commentaires 


| VIOS/PowerVM 3.1.4.21 | Puissance 10 | FW 1010 ou version ultérieure | Pile virtuelle | Prise en charge à partir de AIX 7.3 TL1 SP2 pour VIOC 
|===






== Limites connues

Les limitations connues de la configuration hôte NVMe/FC pour AIX avec ONTAP sont les suivantes :

* Les HBA FC QLogic/Marvel 32G sur un hôte AIX ne prennent pas en charge NVMe/FC.
* Le démarrage SAN n'est pas pris en charge pour les périphériques NVMe/FC utilisant le serveur IBM Power9.




== Chemins d'accès multiples

IBM MPIO (Multi Path I/O), utilisé pour les chemins d'accès multiples NVMe, est fourni par défaut lors de l'installation du système d'exploitation AIX.

Vous pouvez vérifier que les chemins d'accès multiples NVMe sont activés pour un hôte AIX à l'aide du `lsmpio` commande :

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*Exemple de sortie*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----


== Configurez NVMe/FC

Vous pouvez utiliser la procédure suivante pour configurer NVMe/FC pour des cartes Broadcom/Emulex.

.Étapes
. Vérifiez que vous utilisez la carte prise en charge. Pour consulter la liste la plus récente des cartes prises en charge, reportez-vous à la section link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^].
. Par défaut, la prise en charge du protocole NVMe/FC est activée dans le FC physique. Toutefois, la prise en charge du protocole NVMe/FC est désactivée dans le VFC (Virtual Fibre Channel) sur le serveur d'E/S virtuel (VIOS).
+
Récupérer une liste d'adaptateurs virtuels :

+
[listing]
----
$ lsmap -all -npiv
----
+
*Exemple de sortie*

+
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
. Activez la prise en charge du protocole NVMe/FC sur un adaptateur en exécutant `ioscli vfcctrl` Commande sur le VIOS :
+
[listing]
----
$  vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
*Exemple de sortie*

+
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. Vérifiez que la prise en charge a été activée sur la carte :
+
[listing]
----
# lsattr -El vfchost0
----
+
*Exemple de sortie*

+
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
. Activez le protocole NVMe/FC pour tous les adaptateurs actuels ou sélectionnés :
+
.. Activez le protocole NVMe/FC pour tous les adaptateurs :
+
... Modifiez le `dflt_enabl_nvme` valeur d'attribut de `viosnpiv0` pseudo-périphérique vers `yes`.
... Réglez le `enable_nvme` valeur d'attribut vers `yes` Pour tous les périphériques hôtes VFC.
+
[listing]
----
# chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[listing]
----
# lsattr -El viosnpiv0
----
+
*Exemple de sortie*

+
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----


.. Activez le protocole NVMe/FC pour certains adaptateurs en modifiant le `enable_nvme` Valeur de l'attribut de périphérique hôte VFC à `yes`.


. Vérifiez-le `FC-NVMe Protocol Device` a été créé sur le serveur :
+
[listing]
----
# [root@aix_server /]: lsdev |grep fcnvme
----
+
*Sortie Exerable*

+
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. Enregistrez le NQN hôte à partir du serveur :
+
[listing]
----
# [root@aix_server /]: lsattr -El fcnvme0
----
+
*Exemple de sortie*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
[listing]
----
[root@aix_server /]: lsattr -El fcnvme1
----
+
*Exemple de sortie*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
. Vérifiez le NQN hôte et assurez-vous qu'il correspond à la chaîne NQN hôte du sous-système correspondant sur la matrice ONTAP :
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
*Exemple de sortie*

+
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. Vérifiez que les ports initiateurs sont opérationnels et que les LIF cibles s'affichent.




== Validation de la spécification NVMe/FC

Vous devez vérifier que les espaces de noms ONTAP reflètent correctement sur l'hôte. Exécutez la commande suivante pour ce faire :

[listing]
----
# [root@aix_server /]: lsdev -Cc disk |grep NVMe
----
*Exemple de sortie*

[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
Vous pouvez vérifier l'état des chemins d'accès multiples :

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*Exemple de sortie*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----


== Problèmes connus

La configuration hôte NVMe/FC pour AIX avec ONTAP présente les problèmes connus suivants :

[cols="10,30,30"]
|===
| ID de Burt | Titre | Description 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249"^] | Temps APD par défaut AIX NVMe/FC à modifier pour la prise en charge des événements de basculement MCC non planifiés | Par défaut, les systèmes d'exploitation AIX utilisent une valeur de délai d'expiration All path down (APD) de 20 secondes pour NVMe/FC.  Cependant, ONTAP MetroCluster les flux de travail de basculement automatique non planifié (AUSO) et initié par Tiebreaker peuvent prendre un peu plus de temps que la fenêtre APD timeout, ce qui provoque des erreurs d'E/S. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017"^] | La connectivité NVMe/FC AIX plafonne à 60 s, au lieu de 120 s comme annoncé par ONTAP | ONTAP annonce le délai d'expiration de la transition ANA (Asymmetric Namespace Access) dans l'identification du contrôleur à 120 s. Actuellement, avec ifix, AIX lit le délai d'expiration de la transition ANA à partir du contrôleur Identify, mais le fixe à 60 s s'il dépasse cette limite. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386"^] | AIX NVMe/FC frappe EIO après expiration ANATT | Pour tout événement de basculement du stockage (SFO), si la transition ANA (Asymmetric Namespace Access) dépasse le délai maximal de transition ANA sur un chemin donné, l'hôte NVMe/FC AIX échoue et affiche une erreur d'E/S alors que d'autres chemins sains sont disponibles pour le namespace. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380"^] | AIX NVMe/FC attend l'expiration de l'ANATT demi-complet avant de reprendre les E/S après ANA AEN | IBM AIX NVMe/FC ne prend pas en charge certaines notifications asynchrones (AENs) publiées par ONTAP. Cette manipulation non optimale de l'ANA se traduira par des performances sous-optimales pendant les opérations SFO. 
|===


== Résoudre les problèmes

Avant de dépanner toute défaillance NVMe/FC, vérifiez que vous exécutez une configuration conforme aux spécifications de l'outil de matrice d'interopérabilité (IMT). Si les problèmes persistent, contactez link:https://mysupport.netapp.com["Support NetApp"^] pour un triage plus poussé.
