---
sidebar: sidebar 
permalink: nvme_rhel_83.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: 'Comment configurer l"hôte NVMe/FC pour RHEL 8.3 avec ONTAP' 
---
= Configuration hôte NVMe/FC pour RHEL 8.3 avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depuis la version ONTAP 9.6, NVMe/FC est pris en charge pour Red Hat Enterprise Linux (RHEL) 8.3. L'hôte RHEL 8.3 exécute le trafic NVMe et SCSI via les mêmes ports d'adaptateur FC initiator. Consultez la link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] pour obtenir la liste des adaptateurs et contrôleurs FC pris en charge.

Pour obtenir la liste actuelle des configurations prises en charge, reportez-vous aulink:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].



== Caractéristiques

Cette version ne contient aucune nouvelle fonctionnalité.



== Limites connues

* Pour RHEL 8.3, le protocole NVMe multivoie intégré au noyau est désactivé par défaut. Vous pouvez l'activer manuellement.
* Le démarrage SAN à l'aide du protocole NVMe-of n'est pas pris en charge pour le moment.




== Activez le démarrage SAN

Vous pouvez configurer votre hôte pour qu'il utilise le démarrage SAN afin de simplifier le déploiement et d'améliorer l'évolutivité.

.Avant de commencer
Utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.

.Étapes
. Créez un espace de noms de démarrage SAN et mappez-le à l'hôte.
+
Voir https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["Provisionner le stockage NVMe"^].

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Vérifiez que la configuration a réussi en redémarrant l'hôte et en vérifiant que le système d'exploitation est opérationnel.




== Activez NVMe/FC sur RHEL 8.3

Vous pouvez utiliser la procédure suivante pour activer NVMe/FC.

.Étapes
. Installez Red Hat Enterprise Linux 8.3 GA sur le serveur.
. Si vous effectuez une mise à niveau de RHEL 8.2 vers RHEL 8.3 à l'aide de `yum update/upgrade` commande, votre `/etc/nvme/host*` il se peut que des fichiers soient perdus. Pour éviter toute perte de fichier, procédez comme suit :
+
.Affiche un exemple de résultat
[%collapsible]
====
.. Sauvegardez votre `/etc/nvme/host*` fichiers.
.. Si vous avez un modifié manuellement `udev` règle, supprimer :
+
[listing]
----
/lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules
----
.. Effectuez la mise à niveau.
.. Une fois la mise à niveau terminée, exécutez la commande suivante :
+
[listing]
----
yum remove nvme-cli
----
.. Restaurez les fichiers hôte à `/etc/nvme/`.
+
[listing]
----
yum install nvmecli
----
.. Copiez l'original `/etc/nvme/host*` contenu de la sauvegarde vers les fichiers hôtes réels à `/etc/nvme/`.


====
. Une fois l'installation terminée, vérifiez que vous exécutez le noyau RHEL spécifié :
+
[listing]
----
# uname -r
4.18.0-240.el8.x86_64
----
+
Voir link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^]pour la liste actuelle des versions prises en charge.

. Installez le package nvme-cli :
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.12-2.el8.x86_64
----
. Activez le chemins d'accès multiples NVMe dans le noyau.
+
[listing]
----
# grubby --args=nvme_core.multipath=Y --update-kernel /boot/vmlinuz-4.18.0-240.el8.x86_64
----
. Sur l'hôte RHEL 8.3, vérifiez la chaîne NQN de l'hôte à l'adresse `/etc/nvme/hostnqn`  Vérifiez qu'il correspond à la chaîne NQN hôte du sous-système correspondant sur la baie ONTAP :
+
[listing]
----
# cat /etc/nvme/hostnqn
----
+
*Exemple de sortie* :

+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
. Vérifiez que le `hostnqn` String correspond à la chaîne hostnqn du sous-système correspondant sur la baie ONTAP :
+
[listing]
----
vserver nvme subsystem host show -vserver vs_fcnvme_141
----
+
*Exemple de sortie*

+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_fcnvme_141
Vserver         Subsystem        Host           NQN
-----------     --------------- ----------- ---------------
vs_fcnvme_141    nvme_141_1                 nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+

TIP: Si les chaînes NQN hôte ne correspondent pas, utilisez le `vserver modify` Commande permettant de mettre à jour la chaîne NQN hôte sur le sous-système de matrice ONTAP correspondant pour qu'elle corresponde à la chaîne NQN hôte à partir de `/etc/nvme/hostnqn` sur l'hôte.

. Redémarrez l'hôte.
. Si vous le souhaitez, mettez à jour le `enable_foreign` réglage.
+
[NOTE]
====
Si vous avez l'intention d'exécuter à la fois le trafic NVMe et SCSI sur le même hôte RHEL 8.3, NetApp vous recommande d'utiliser respectivement les chemins d'accès multiples NVMe in-kernel pour les namespaces ONTAP et dm-multipath pour les LUN ONTAP. Vous devez également répertorier les espaces de noms ONTAP dans dm-multipath pour empêcher dm-multipath de réclamer ces périphériques d'espace de noms. Pour ce faire, vous pouvez ajouter le `enable_foreign` paramètre au fichier /etc/multipath.conf, comme indiqué ci-dessous :

[listing]
----
# cat /etc/multipath.conf
defaults {
   enable_foreign NONE
}
----
Redémarrez le démon multipathd en exécutant un `systemctl restart multipathd`.

====




== Validation de la spécification NVMe/FC

La procédure suivante permet de valider NVMe/FC.

.Étapes
. Vérifiez les paramètres NVMe/FC suivants :
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. Vérifier que les espaces de noms sont créés et détectés correctement sur l'hôte.
+
[listing]
----
/dev/nvme0n1     814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller                1                  85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
/dev/nvme0n2     814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller                2                  85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
/dev/nvme0n3     814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller                3                  85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
----
. Vérifiez le statut des chemins ANA.
+
[listing]
----
# nvme list-subsys /dev/nvme0n1
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.5f5f2c4aa73b11e9967e00a098df41bd:subsystem.nvme_141_1
\
+- nvme0 fc traddr=nn-0x203700a098dfdd91:pn-0x203800a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme1 fc traddr=nn-0x203700a098dfdd91:pn-0x203900a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x203700a098dfdd91:pn-0x203a00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x203700a098dfdd91:pn-0x203d00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
----
. Vérifiez le plug-in NetApp pour les périphériques ONTAP :
+
[role="tabbed-block"]
====
.Colonne
--
[listing]
----
# nvme netapp ontapdevices -o column
----
*Exemple de sortie*

[listing]
----
Device               Vserver            Namespace Path                           NSID                      UUID                     Size
--------------- --------------- ---------------------------------------------  -------- --------------------------------------  ---------
/dev/nvme0n1      vs_fcnvme_141     /vol/fcnvme_141_vol_1_1_0/fcnvme_141_ns        1      72b887b1-5fb6-47b8-be0b-33326e2542e2    85.90GB
/dev/nvme0n2      vs_fcnvme_141     /vol/fcnvme_141_vol_1_0_0/fcnvme_141_ns        2      04bf9f6e-9031-40ea-99c7-a1a61b2d7d08    85.90GB
/dev/nvme0n3      vs_fcnvme_141     /vol/fcnvme_141_vol_1_1_1/fcnvme_141_ns        3      264823b1-8e03-4155-80dd-e904237014a4    85.90GB
----
--
.JSON
--
[listing]
----
# nvme netapp ontapdevices -o json
----
*Exemple de sortie*

[listing]
----
{
"ONTAPdevices" : [
    {
        "Device" : "/dev/nvme0n1",
        "Vserver" : "vs_fcnvme_141",
        "Namespace_Path" : "/vol/fcnvme_141_vol_1_1_0/fcnvme_141_ns",
        "NSID" : 1,
        "UUID" : "72b887b1-5fb6-47b8-be0b-33326e2542e2",
        "Size" : "85.90GB",
        "LBA_Data_Size" : 4096,
        "Namespace_Size" : 20971520
    },
    {
        "Device" : "/dev/nvme0n2",
        "Vserver" : "vs_fcnvme_141",
        "Namespace_Path" : "/vol/fcnvme_141_vol_1_0_0/fcnvme_141_ns",
        "NSID" : 2,
        "UUID" : "04bf9f6e-9031-40ea-99c7-a1a61b2d7d08",
        "Size" : "85.90GB",
        "LBA_Data_Size" : 4096,
        "Namespace_Size" : 20971520
      },
      {
         "Device" : "/dev/nvme0n3",
         "Vserver" : "vs_fcnvme_141",
         "Namespace_Path" : "/vol/fcnvme_141_vol_1_1_1/fcnvme_141_ns",
         "NSID" : 3,
         "UUID" : "264823b1-8e03-4155-80dd-e904237014a4",
         "Size" : "85.90GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 20971520
       },
  ]
----
--
====




== Configurez la carte FC Broadcom pour NVMe/FC

Vous pouvez utiliser la procédure suivante pour configurer une carte FC Broadcom.

Pour obtenir la liste actuelle des cartes prises en charge, reportez-vous au link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].

.Étapes
. Vérifiez que vous utilisez la carte prise en charge.
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. Vérifiez-le `lpfc_enable_fc4_type` est défini sur "*3*".
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Vérifier que les ports initiateurs sont opérationnels et que les LIFs cibles sont bien voir.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b1c1204
0x100000109b1c1205
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 ONLINE
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 ONLINE
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----
. Activez la taille d'E/S de 1 Mo _ (facultatif)_.
+
Le `lpfc_sg_seg_cnt` paramètre doit être défini sur 256 pour que le pilote lpfc puisse émettre des demandes d'E/S d'une taille maximale de 1 Mo.

+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. Exécutez `dracut -f` la commande, puis redémarrez l'hôte.
. Après le démarrage de l'hôte, vérifiez que lpfc_sg_seg_CNT est défini sur 256.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----
. Vérifiez que vous utilisez le micrologiciel Broadcom lpfc recommandé ainsi que le pilote de boîte de réception :
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
12.8.340.8, sli-4:2:c
12.8.340.8, sli-4:2:c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:12.8.0.1
----

