---
sidebar: sidebar 
permalink: nvme_rhel_82.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: 'Comment configurer l"hôte NVMe/FC pour RHEL 8.2 avec ONTAP' 
---
= Configuration hôte NVMe/FC pour RHEL 8.2 avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depuis la version ONTAP 9.6, NVMe/FC est pris en charge pour Red Hat Enterprise Linux (RHEL) 8.2. L'hôte RHEL 8.2 exécute le trafic NVMe et SCSI via les mêmes ports d'adaptateur Fibre Channel (FC). Consultez la link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] pour obtenir la liste des adaptateurs et contrôleurs FC pris en charge.

Pour obtenir la liste actuelle des configurations prises en charge, reportez-vous aulink:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].



== Caractéristiques

* À partir de RHEL 8.2, `nvme-fc auto-connect` les scripts sont inclus dans le package natif `nvme-cli`. Vous pouvez utiliser ces scripts de connexion automatique natifs au lieu d'installer les scripts de connexion automatique fournis par le fournisseur externe.
* À partir de RHEL 8.2, une version native `udev` la règle est déjà fournie dans le cadre du `nvme-cli` Une solution qui permet l'équilibrage de la charge Round-Robin pour les chemins d'accès multiples NVMe. Vous n'avez plus besoin de créer cette règle manuellement (comme cela a été fait dans RHEL 8.1).
* À partir de RHEL 8.2, le trafic NVMe et SCSI peut être exécuté sur le même hôte. En fait, il s'agit de la configuration d'hôte déployée prévue. Par conséquent, pour SCSI, vous pouvez configurer `dm-multipath` comme d'habitude pour les LUN SCSI aboutissant à `mpath` des périphériques, tandis que les chemins d'accès multiples NVMe permettent de configurer des périphériques multivoies NVMe-of sur l'hôte.
* À partir de RHEL 8.2, le plug-in NetApp dans le natif `nvme-cli` Le package peut afficher les détails ONTAP pour les espaces de noms ONTAP.




== Limites connues

* Pour RHEL 8.2, le protocole NVMe multivoie intégré au noyau est désactivé par défaut. Par conséquent, vous devez l'activer manuellement.
* Le démarrage SAN à l'aide du protocole NVMe-of n'est pas pris en charge pour le moment.




== Activez le démarrage SAN

Vous pouvez configurer votre hôte pour qu'il utilise le démarrage SAN afin de simplifier le déploiement et d'améliorer l'évolutivité.

.Avant de commencer
Utilisez le link:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.

.Étapes
. Créez un espace de noms de démarrage SAN et mappez-le à l'hôte.
+
Voir https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["Provisionner le stockage NVMe"^].

. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Vérifiez que la configuration a réussi en redémarrant l'hôte et en vérifiant que le système d'exploitation est opérationnel.




== Activation de NVMe/FC

Vous pouvez utiliser la procédure suivante pour activer NVMe/FC.

.Étapes
. Installez Red Hat Enterprise Linux 8.2 GA sur le serveur.
. Si vous effectuez une mise à niveau de RHEL 8.1 vers RHEL 8.2 à l'aide de `yum update/upgrade`, votre `/etc/nvme/host*` il se peut que des fichiers soient perdus. Pour éviter la perte de fichier, procédez comme suit :
+
.. Sauvegardez votre `/etc/nvme/host*` fichiers.
.. Si vous avez un modifié manuellement `udev` règle, supprimer :
+
[listing]
----
/lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules
----
.. Effectuez la mise à niveau.
.. Une fois la mise à niveau terminée, exécutez la commande suivante :
+
[listing]
----
yum remove nvme-cli
----
.. Restaurez les fichiers hôte à `/etc/nvme/`.
+
[listing]
----
yum install nvmecli
----
.. Copiez l'original `/etc/nvme/host*` contenu de la sauvegarde vers les fichiers hôtes réels à `/etc/nvme/`.


. Une fois l'installation terminée, vérifiez que vous exécutez le noyau Red Hat Enterprise Linux spécifié.
+
[listing]
----
# uname -r
4.18.0-193.el8.x86_64
----
+
Voir link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^]pour la liste actuelle des versions prises en charge.

. Installez le pack nvme-cli.
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.9.5.el8.x86_64
----
. Activez le chemins d'accès multiples NVMe dans le noyau.
+
[listing]
----
# grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-193.el8.x86_64
----
. Sur l'hôte RHEL 8.2, vérifiez la chaîne NQN de l'hôte à l'adresse `/etc/nvme/hostnqn` Et vérifiez qu'il correspond à la chaîne NQN hôte pour le sous-système correspondant de la matrice ONTAP.
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1


::> vserver nvme subsystem host show -vserver vs_fcnvme_141
Vserver      Subsystem        Host           NQN
----------- --------------- ----------- ---------------
  vs_fcnvme_141
    nvme_141_1
        nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+
Si les chaînes NQN hôte ne correspondent pas, utilisez le `vserver modify` Commande permettant de mettre à jour la chaîne NQN hôte sur le sous-système de matrice ONTAP correspondant pour qu'elle corresponde à la chaîne NQN hôte à partir de `/etc/nvme/hostnqn` sur l'hôte.

. Redémarrez l'hôte.
. Mettez à jour le `enable_foreign` réglage _ (facultatif)_.
+
Si vous avez l'intention d'exécuter à la fois le trafic NVMe et SCSI sur le même hôte RHEL 8.2, NetApp vous recommande d'utiliser respectivement le protocole NVMe multipath in-kernel pour les namespaces ONTAP et dm-multipath pour les LUN ONTAP. Vous devez également répertorier les espaces de noms ONTAP dans dm-multipath pour empêcher dm-multipath de réclamer ces périphériques d'espace de noms. Pour ce faire, vous pouvez ajouter le `enable_foreign` paramètre au `/etc/multipath.conf`, comme indiqué ci-dessous.

+
[listing]
----
# cat /etc/multipath.conf
defaults {
   enable_foreign NONE
}
----
. Redémarrez le démon multipathd en exécutant un `systemctl restart multipathd`.




== Configurez la carte FC Broadcom pour NVMe/FC

Vous pouvez utiliser la procédure suivante pour configurer une carte FC Broadcom.

Pour obtenir la liste actuelle des cartes prises en charge, reportez-vous au link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].

.Étapes
. Vérifiez que vous utilisez la carte prise en charge.
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. Vérifiez-le `lpfc_enable_fc4_type` est défini sur "*3*".
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Vérifier que les ports initiateurs sont opérationnels et que les LIFs cibles sont bien voir.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b1c1204
0x100000109b1c1205
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 ONLINE
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 ONLINE
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----
. Activez la taille d'E/S de 1 Mo _ (facultatif)_.
+
Le `lpfc_sg_seg_cnt` paramètre doit être défini sur 256 pour que le pilote lpfc puisse émettre des demandes d'E/S d'une taille maximale de 1 Mo.

+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. Exécutez `dracut -f` la commande, puis redémarrez l'hôte.
. Après le démarrage de l'hôte, vérifiez que lpfc_sg_seg_CNT est défini sur 256.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----
. Vérifiez que vous utilisez le micrologiciel lpfc Broadcom recommandé ainsi que le pilote de la boîte de réception.
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
12.6.182.8, sli-4:2:c
12.6.182.8, sli-4:2:c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:12.6.0.2
----
. Vérifiez-le `lpfc_enable_fc4_type` est défini sur "*3*".
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Vérifier que les ports initiateurs sont opérationnels et que les LIFs cibles sont bien voir.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b1c1204
0x100000109b1c1205
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 ONLINE
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 ONLINE
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----
. Activez la taille d'E/S de 1 Mo _ (facultatif)_.
+
Le `lpfc_sg_seg_cnt` paramètre doit être défini sur 256 pour que le pilote lpfc puisse émettre des demandes d'E/S d'une taille maximale de 1 Mo.

+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. Exécutez `dracut -f` la commande, puis redémarrez l'hôte.
. Après le démarrage de l'hôte, vérifiez que lpfc_sg_seg_CNT est défini sur 256.
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----




== Validation de la spécification NVMe/FC

La procédure suivante permet de valider NVMe/FC.

.Étapes
. Vérifiez les paramètres NVMe/FC suivants.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. Vérifier que les espaces de noms sont créés.
+
[listing]
----
# nvme list
Node SN Model Namespace Usage Format FW Rev
---------------- -------------------- -----------------------
/dev/nvme0n1 80BADBKnB/JvAAAAAAAC NetApp ONTAP Controller 1 53.69 GB / 53.69 GB 4 KiB + 0 B FFFFFFFF
----
. Vérifiez le statut des chemins ANA.
+
[listing]
----
# nvme list-subsys/dev/nvme0n1
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.rhel_141_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 live optimized
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live inaccessible
----
. Vérifier le plug-in NetApp pour les systèmes ONTAP.
+
[listing]
----

# nvme netapp ontapdevices -o column
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/rhel_141_vol_10_0/rhel_141_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB

# nvme netapp ontapdevices -o json
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/rhel_141_vol_10_0/rhel_141_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----

