---
sidebar: sidebar 
permalink: nvme-rhel-9x.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: Comment configurer un hôte NVMe-oF pour RHEL 9.x avec ONTAP 
---
= Configurer RHEL 9.x pour NVMe-oF avec stockage ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les hôtes Red Hat Enterprise Linux (RHEL) prennent en charge les protocoles NVMe over Fibre Channel (NVMe/FC) et NVMe over TCP (NVMe/TCP) avec Asymmetric Namespace Access (ANA).  ANA fournit une fonctionnalité de multi-accès équivalente à l'accès aux unités logiques asymétriques (ALUA) dans les environnements iSCSI et FCP.

Apprenez à configurer les hôtes NVMe over Fabrics (NVMe-oF) pour RHEL 9.x. Pour plus d'assistance et d'informations sur les fonctionnalités, consultez link:nvme-rhel-supported-features.html["Prise en charge et fonctionnalités de RHEL ONTAP"].

NVMe-oF avec RHEL 9.x présente les limitations connues suivantes :

* Le `nvme disconnect-all` Cette commande déconnecte les systèmes de fichiers racine et de données et peut entraîner une instabilité du système.  Ne pas utiliser cette commande sur des systèmes démarrant à partir d'un SAN via des espaces de noms NVMe-TCP ou NVMe-FC.




[[step-1-optionally-enable-san-booting]]
== Étape 1 : activez éventuellement le démarrage SAN

Vous pouvez configurer votre hôte pour utiliser le démarrage SAN afin de simplifier le déploiement et d’améliorer l’évolutivité. Utilisez lelink:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Linux, votre adaptateur de bus hôte (HBA), votre micrologiciel HBA, votre BIOS de démarrage HBA et votre version ONTAP prennent en charge le démarrage SAN.

.Étapes
. https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["Créez un espace de noms NVMe et mappez-le à l'hôte"^] .
. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels l'espace de noms de démarrage SAN est mappé.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Redémarrez l’hôte et vérifiez que le système d’exploitation est opérationnel.




[[step-2-install-rhel-and-nvme-software-and-verify-your-configuration]]
== Étape 2 : Installez RHEL et le logiciel NVMe, puis vérifiez votre configuration.

Pour configurer votre hôte pour NVMe-oF, vous devez installer les packages logiciels hôte et NVMe, activer le multipathing et vérifier la configuration NQN de votre hôte.

.Étapes
. Installez RHEL 9.x sur le serveur. Une fois l'installation terminée, vérifiez que vous utilisez bien le noyau RHEL 9.x requis :
+
[source, cli]
----
uname -r
----
+
Exemple de version du noyau RHEL :

+
[listing]
----
5.14.0-687.5.3.el9_8.x86_64
----
. Installer le `nvme-cli` groupe :
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
L'exemple suivant montre un  `nvme-cli` version du paquet :

+
[listing]
----
nvme-cli-2.16-1.el9.x86_64
----
. Installer le `libnvme` groupe :
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
L'exemple suivant illustre une  `libnvme` version de package :

+
[listing]
----
libnvme-1.16.1-3.el9_8.x86_64
----
. Sur l'hôte, vérifiez la chaîne hostnqn à  `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
L'exemple suivant montre un  `hostnqn` version:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0056-xxxx-8048-b9cxxxx25633
----
. Sur le système ONTAP , vérifiez que le `hostnqn` La chaîne correspond à `hostnqn` chaîne de caractères pour le sous-système correspondant sur le système de stockage ONTAP :
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_188
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ------------------------------------------------
vs_188  Nvme1
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0056-xxxx-8048-b9cxxxx25633
        Nvme10
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0056-xxxx-8048-b9cxxxx25633
        Nvme11
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0056-xxxx-8048-b9cxxxx25633
        Nvme12
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0056-xxxx-8048-b9cxxxx25633
48 entries were displayed.
----
====



NOTE: Si le `hostnqn` les chaînes ne correspondent pas, utilisez le `vserver modify` commande pour mettre à jour le `hostnqn` chaîne sur votre sous-système de stockage ONTAP correspondant pour correspondre à la `hostnqn` chaîne de `/etc/nvme/hostnqn` sur l'hôte.



[[step-3-configure-nvmefc-and-nvmetcp]]
== Étape 3 : Configurer NVMe/FC et NVMe/TCP

Configurez NVMe/FC avec des adaptateurs Broadcom/Emulex ou Marvell/QLogic, ou configurez NVMe/TCP à l'aide d'opérations de découverte et de connexion manuelles.

[role="tabbed-block"]
====
.NVMe/FC - Broadcom/Emulex
--
Configuration de NVMe/FC pour une carte Broadcom/Emulex

.Étapes
. Vérifiez que vous utilisez le modèle d'adaptateur pris en charge :
+
.. Afficher les noms des modèles :
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
LPe36002-M64
LPe36002-M64
----
.. Afficher les descriptions des modèles :
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Vous devriez voir une sortie similaire à l’exemple suivant :

+
[listing]
----
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
----


. Vérifiez que vous utilisez la carte Broadcom recommandée `lpfc` micrologiciel et pilote de boîte de réception :
+
.. Afficher la version du firmware :
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
La commande renvoie les versions du firmware :

+
[listing]
----
14.4.725.15, sli-4:6:d
14.4.725.15, sli-4:6:d
----
.. Afficher la version du pilote de la boîte de réception :
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
L'exemple suivant montre une version de pilote :

+
[listing]
----
0:14.4.0.12
----


+
Pour obtenir la liste actuelle des versions de pilotes et de micrologiciels de carte prises en charge, consultez le link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité"^].

. Vérifiez-le `lpfc_enable_fc4_type` est défini sur `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Vérifiez que vous pouvez afficher vos ports initiateurs :
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
L'exemple suivant montre les identités de port :

+
[listing]
----
0x100000109bf044b1
0x100000109bf044b2
----
. Vérifiez que vos ports initiateurs sont en ligne :
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
Online
Online
----
. Vérifiez que les ports initiateurs NVMe/FC sont activés et que les ports cibles sont visibles :
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Montrer l'exemple
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b954518 WWNN x200000109b954518 DID x030c00 *ONLINE*

NVME Statistics
LS: Xmt 0000000000 Cmpl 0000000000 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000000000000 Issue 0000000000000000 OutIO 0000000000000000
        abort 00000000 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000000 Err 00000000

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b954519 WWNN x200000109b954519 DID x081600 ONLINE

NVME Statistics
LS: Xmt 0000000000 Cmpl 0000000000 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000000000000 Issue 0000000000000000 OutIO 0000000000000000
        abort 00000000 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000000 Err 00000000

NVME Initiator Enabled
XRI Dist lpfc2 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc2 WWPN x100000109bf044b1 WWNN x200000109bf044b1 DID x081700 *ONLINE*
NVME RPORT       WWPN x2004d039eab6cb6c WWNN x2000d039eab6cb6c DID x062d01 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x203cd039eab6cb6c WWNN x2038d039eab6cb6c DID x062d02 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2003d039eab6cb6c WWNN x2000d039eab6cb6c DID x060501 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x203bd039eab6cb6c WWNN x2038d039eab6cb6c DID x060502 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000002866 Cmpl 0000002866 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000024c23f76 Issue 0000000024be06af OutIO fffffffffffbc739
        abort 00002809 noxri 00000af5 nondlp 0000001f qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00002a0c Err 0008b360

NVME Initiator Enabled
XRI Dist lpfc3 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc3 WWPN x100000109bf044b2 WWNN x200000109bf044b2 DID x030300 *ONLINE*
NVME RPORT       WWPN x2001d039eab6cb6c WWNN x2000d039eab6cb6c DID x021301 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2039d039eab6cb6c WWNN x2038d039eab6cb6c DID x021302 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2002d039eab6cb6c WWNN x2000d039eab6cb6c DID x020b01 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x203ad039eab6cb6c WWNN x2038d039eab6cb6c DID x020b02 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000002850 Cmpl 0000002850 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000028cfb367 Issue 0000000028ca59c5 OutIO fffffffffffaa65e
        abort 00002928 noxri 00000b66 nondlp 00000035 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00002db8 Err 0008b4d9

----
=====


--
.NVMe/FC - Marvell/QLogic
--
Configuration du NVMe/FC pour un adaptateur Marvell/QLogic

.Étapes
. Vérifiez que vous utilisez les versions de pilote d'adaptateur et de micrologiciel prises en charge :
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
L'exemple suivant montre les versions du pilote et du micrologiciel :

+
[listing]
----
QLE2872 FW:v9.15.17 DVR:v10.02.10.100-k
QLE2872 FW:v9.15.17 DVR:v10.02.10.100-k
----
. Vérifiez-le `ql2xnvmeenable` est défini. L'adaptateur Marvell peut ainsi fonctionner en tant qu'initiateur NVMe/FC :
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
La sortie attendue est 1.



--
.NVMe/TCP
--
Le protocole NVMe/TCP ne prend pas en charge l'opération de connexion automatique.  Au lieu de cela, vous pouvez découvrir les sous-systèmes et espaces de noms NVMe/TCP en exécutant l'opération NVMe/TCP. `connect` ou `connect-all` opérations manuellement.

.Étapes
. Vérifiez que le port initiateur peut obtenir les données de la page du journal de découverte sur les LIF NVMe/TCP pris en charge :
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.Montrer l'exemple
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.30.15 -a 192.168.30.48

Discovery Log Number of Records 8, Generation counter 18
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  8
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.51a3c9846e0c11f08f5dd039eaa7dfc9:discovery
traddr:  192.168.31.49
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  7
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.51a3c9846e0c11f08f5dd039eaa7dfc9:discovery
traddr:  192.168.31.48
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  6
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.51a3c9846e0c11f08f5dd039eaa7dfc9:discovery
traddr:  192.168.30.49
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  5
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.51a3c9846e0c11f08f5dd039eaa7dfc9:discovery
traddr:  192.168.30.48
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 4======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  8
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.51a3c9846e0c11f08f5dd039eaa7dfc9:subsystem.Nvme38
traddr:  192.168.31.49
eflags:  none
sectype: none
=====Discovery Log Entry 5======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  7
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.51a3c9846e0c11f08f5dd039eaa7dfc9:subsystem.Nvme38
traddr:  192.168.31.48
eflags:  none
sectype: none
=====Discovery Log Entry 6======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  6
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.51a3c9846e0c11f08f5dd039eaa7dfc9:subsystem.Nvme38
traddr:  192.168.30.49
eflags:  none
sectype: none
=====Discovery Log Entry 7======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  5
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.51a3c9846e0c11f08f5dd039eaa7dfc9:subsystem.Nvme38
traddr:  192.168.30.48
eflags:  none
sectype: none
----
=====
. Vérifiez que les autres combinaisons LIF initiateur-cible NVMe/TCP peuvent récupérer avec succès les données de la page du journal de découverte :
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.Montrer l'exemple
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.30.15 -a 192.168.30.48
nvme discover -t tcp -w 192.168.30.15 -a 192.168.30.49
nvme discover -t tcp -w 192.168.31.15 -a 192.168.31.48
nvme discover -t tcp -w 192.168.31.15 -a 192.168.31.49
----
=====
. Exécutez le `nvme connect-all` Commande sur toutes les LIF cible-initiateur NVMe/TCP prises en charge sur l'ensemble des nœuds :
+
[source, cli]
----
nvme connect-all -t tcp -w host-traddr -a traddr
----
+
.Montrer l'exemple
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme  connect-all -t  tcp -w  192.168.30.15 -a	192.168.30.48
nvme	connect-all	-t	tcp	-w	192.168.30.15	-a	192.168.30.49
nvme	connect-all	-t	tcp	-w	192.168.31.15	-a	192.168.31.48
nvme	connect-all	-t	tcp	-w	192.168.31.15	-a	192.168.31.49
----
=====


[NOTE]
====
À partir de RHEL 9.4, le paramètre NVMe/TCP  `ctrl_loss_tmo timeout` est automatiquement réglé sur « off ». Par conséquent :

* Il n'y a pas de limite au nombre de tentatives (nouvelle tentative indéfinie).
* Vous n'avez pas besoin de configurer manuellement un élément spécifique  `ctrl_loss_tmo timeout` durée lors de l'utilisation du  `nvme connect` ou  `nvme connect-all` commandes (option -l ).
* Les contrôleurs NVMe/TCP ne subissent pas de dépassement de délai en cas de défaillance d'un chemin et restent connectés indéfiniment.


====
--
====


[[step-4-optionally-modify-the-iopolicy-in-the-udev-rules]]
== Étape 4 : Vous pouvez éventuellement modifier la politique d’E/S dans les règles udev.

.Modifications apportées à la politique d'E/S pour les versions RHEL 9.x
* À partir de RHEL 9.7, la iopolicy par défaut est queue-depth.
* Dans RHEL 9.6, round-robin est la stratégie d'E/S par défaut, mais queue-depth est disponible en tant qu'option configurable.
* Avant RHEL 9.6, round-robin est la seule stratégie d'E/S NVMe-oF prise en charge.


Si vous utilisez RHEL 9.6 et souhaitez changer la iopolicy `queue-depth`, modifiez le fichier de règles udev comme suit :

.Étapes
. Ouvrez le fichier de règles udev dans un éditeur de texte avec des privilèges root :
+
[source, cli]
----
/usr/lib/udev/rules.d/71-nvmf-netapp.rules
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
vi /usr/lib/udev/rules.d/71-nvmf-netapp.rules
----
. Recherchez la ligne qui définit la politique d'E/S pour le contrôleur NetApp ONTAP , comme indiqué dans l'exemple de règle suivant :
+
[listing]
----
ACTION=="add", SUBSYSTEM=="nvme-subsystem", ATTR{subsystype}=="nvm", ATTR{model}=="NetApp ONTAP Controller", ATTR{iopolicy}="round-robin"
----
. Modifier la règle afin que `round-robin` devient `queue-depth` :
+
[source, cli]
----
ACTION=="add", SUBSYSTEM=="nvme-subsystem", ATTR{subsystype}=="nvm", ATTR{model}=="NetApp ONTAP Controller", ATTR{iopolicy}="queue-depth"
----
. Rechargez les règles udev et appliquez les modifications :
+
[source, cli]
----
udevadm control --reload
udevadm trigger --subsystem-match=nvme-subsystem
----
. Vérifiez la politique d'E/S actuelle de votre sous-système.  Remplacez <subsystem>, par exemple, `nvme-subsys0` .
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<subsystem>/iopolicy
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
queue-depth
----



NOTE: La nouvelle politique d'E/S s'applique automatiquement aux périphériques NetApp ONTAP Controller correspondants. Vous n'avez pas besoin de redémarrer.



[[step-5-optionally-enable-1mb-io-for-nvmefc]]
== Étape 5 : Vous pouvez activer l’E/S à 1 Mo pour NVMe/FC (optionnel).

ONTAP signale une taille de transfert de données maximale (MDTS) de 8 dans les données du contrôleur d'identification.  Cela signifie que la taille maximale de la demande d'E/S peut atteindre 1 Mo.  Pour émettre des requêtes d'E/S d'une taille de 1 Mo pour un hôte Broadcom NVMe/FC, vous devez augmenter la `lpfc` valeur de la `lpfc_sg_seg_cnt` paramètre à 256 à partir de la valeur par défaut de 64.


NOTE: Ces étapes ne s'appliquent pas aux hôtes NVMe/FC Qlogic.

.Étapes
. Réglez le `lpfc_sg_seg_cnt` paramètre sur 256 :
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
Vous devriez voir une sortie similaire à l’exemple suivant :

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Exécutez `dracut -f` la commande et redémarrez l'hôte.
. Vérifier que la valeur de `lpfc_sg_seg_cnt` est 256 :
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




[[step-6-verify-nvme-boot-services]]
== Étape 6 : Vérifier les services de démarrage NVMe

Le `nvmefc-boot-connections.service` et `nvmf-autoconnect.service` services de démarrage inclus dans NVMe/FC `nvme-cli` les packages sont automatiquement activés au démarrage du système.

Une fois le démarrage terminé, vérifiez que le  `nvmefc-boot-connections.service` et  `nvmf-autoconnect.service` les services de démarrage sont activés.

.Étapes
. Vérifiez que `nvmf-autoconnect.service` est activé :
+
[source, cli]
----
systemctl status nvmf-autoconnect.service
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
○ nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmf-autoconnect.service; enabled; preset: disabled)
     Active: inactive (dead) since Thu 2026-05-21 10:20:23 EDT; 10min ago
    Process: 7484 ExecStart=/usr/sbin/nvme connect-all --context=autoconnect (code=exited, status=0/SUCCESS)
   Main PID: 7484 (code=exited, status=0/SUCCESS)
        CPU: 30ms

May 21 10:20:23 SR650-N-13-89 systemd[1]: Starting Connect NVMe-oF subsystems automatically during boot...
May 21 10:20:23 SR650-N-13-89 systemd[1]: nvmf-autoconnect.service: Deactivated successfully.
May 21 10:20:23 SR650-N-13-89 systemd[1]: Finished Connect NVMe-oF subsystems automatically during boot.
----
====
. Vérifiez que `nvmefc-boot-connections.service` est activé :
+
[source, cli]
----
systemctl status nvmefc-boot-connections.service
----
+
.Affiche un exemple de résultat
[%collapsible]
====
[listing]
----
nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmefc-boot-connections.service; enabled; preset: enabled)
     Active: inactive (dead) since Thu 2026-05-21 10:20:04 EDT; 16min ago
    Process: 3427 ExecStart=/bin/sh -c echo add > /sys/class/fc/fc_udev_device/nvme_discovery (code=exited, status=0/SUCCESS)
   Main PID: 3427 (code=exited, status=0/SUCCESS)
        CPU: 18ms

May 21 10:20:04 SR650-N-13-89 systemd[1]: Starting Auto-connect to subsystems on FC-NVME devices found during boot...
May 21 10:20:04 SR650-N-13-89 systemd[1]: nvmefc-boot-connections.service: Deactivated successfully.
May 21 10:20:04 SR650-N-13-89 systemd[1]: Finished Auto-connect to subsystems on FC-NVME devices found during boot.
----
====




[[step-7-verify-the-multipathing-configuration]]
== Étape 7 : Vérifier la configuration du multipathing

Vérifiez que l'état des chemins d'accès multiples NVMe in-kernel, l'état ANA et les namespaces ONTAP sont corrects pour la configuration NVMe-of.

.Étapes
. Vérifiez que le chemin d'accès multiples NVMe intégré au noyau est activé :
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
Y
----
. Vérifiez que les paramètres NVMe-oF appropriés (tels que le modèle défini sur NetApp ONTAP Controller et la stratégie d'E/S d'équilibrage de charge définie sur round-robin) pour les espaces de noms ONTAP respectifs s'affichent correctement sur l'hôte :
+
.. Afficher les sous-systèmes :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. Afficher la politique :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
Vous devriez voir le résultat suivant :

+
[listing]
----
queue-depth
queue-depth
----


. Vérifiez que les espaces de noms sont créés et correctement découverts sur l'hôte :
+
[source, cli]
----
nvme list
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
Node                               Generic             SN                   Model
--------------------------------------------------------------------------------------
/dev/nvme100n1  /dev/ng100n1  81LJCJYaKOHhAAAAAAAf   NetApp ONTAP Controller
Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
0x1                 1.19  GB /   5.37  GB   4 KiB + 0 B   9.18.1
----
====
. Vérifiez que l'état du contrôleur de chaque chemin est actif et que l'état ANA est correct :
+
[source, cli]
----
nvme list-subsys /dev/<controller_ID>
----
+

NOTE: À partir d'ONTAP 9.16.1, NVMe/FC et NVMe/TCP signalent tous les chemins optimisés sur les systèmes ASA r2.

+
[role="tabbed-block"]
====
.NVMe/FC
--
L'exemple suivant montre les résultats pour un espace de noms hébergé sur un contrôleur ONTAP à deux nœuds pour les systèmes AFF, FAS et ASA ainsi que le système ASA r2 avec NVMe/FC.

.Afficher un exemple de sortie AFF, FAS et ASA
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys5 - NQN=nqn.1992-08.com.netapp:sn.f7565b15a66911ef9668d039ea951c46:subsystem.nvme1
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-c7c04f425633
\
+- nvme126 fc traddr=nn-0x2036d039ea951c45:pn-0x2038d039ea951c45,host_traddr=nn-0x2000f4c7aa0cd7c3:pn-0x2100f4c7aa0cd7c3 *live optimized*
+- nvme176 fc traddr=nn-0x2036d039ea951c45:pn-0x2037d039ea951c45,host_traddr=nn-0x2000f4c7aa0cd7c2:pn-0x2100f4c7aa0cd7c2 *live optimized*
+- nvme5 fc traddr=nn-0x2036d039ea951c45:pn-0x2039d039ea951c45,host_traddr=nn-0x2000f4c7aa0cd7c2:pn-0x2100f4c7aa0cd7c2 *live non-optimized*
+- nvme71 fc traddr=nn-0x2036d039ea951c45:pn-0x203ad039ea951c45,host_traddr=nn-0x2000f4c7aa0cd7c3:pn-0x2100f4c7aa0cd7c3 *live non-optimized*
----
=====
.Afficher un exemple de sortie ASA r2
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys96 - NQN=nqn.1992-08.om.netapp:sn.b351b2b6777b11f0b3c2d039ea5cfc91:subsystem.nvme24
                hostnqn=nqn.2014-08.org.nvmexpress:uuid:d3b581b4-c975-11e6-8425-0894ef31a074
\
 +- nvme203 *fc* traddr=nn-0x2011d039ea5cfc90:pn-0x2015d039ea5cfc90,host_traddr=nn-0x200000109bdacc76:pn-0x100000109bdacc76 *live optimized*
 +- nvme25 *fc* traddr=nn-0x2011d039ea5cfc90:pn-0x2014d039ea5cfc90,host_traddr=nn-0x200000109bdacc75:pn-0x100000109bdacc75 *live optimized*
 +- nvme30 *fc* traddr=nn-0x2011d039ea5cfc90:pn-0x2012d039ea5cfc90,host_traddr=nn-0x200000109bdacc75:pn-0x100000109bdacc75 *live optimized*
 +- nvme32 *fc* traddr=nn-0x2011d039ea5cfc90:pn-0x2013d039ea5cfc90,host_traddr=nn-0x200000109bdacc76:pn-0x100000109bdacc76 *live optimized*
----
=====
--
.NVMe/TCP
--
L'exemple suivant montre des sorties affichant un espace de noms hébergé sur un contrôleur ONTAP à deux nœuds pour les systèmes AFF, FAS et ASA ainsi que les systèmes ASA r2 avec NVMe/TCP.

.Afficher un exemple de sortie AFF, FAS et ASA
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys4 - NQN=nqn.1992-08.com.netapp:sn.64e65e6caae711ef9668d039ea951c46:subsystem.nvme4
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0035-5910-804b-c2c04f444d33
\
 +- nvme102 tcp traddr=192.168.21.20,trsvcid=4420,host_traddr=192.168.21.1,src_addr=192.168.21.1 *live non-optimized*
 +- nvme151 tcp traddr=192.168.21.21,trsvcid=4420,host_traddr=192.168.21.1,src_addr=192.168.21.1 *live optimized*
 +- nvme4 tcp traddr=192.168.20.20,trsvcid=4420,host_traddr=192.168.20.1,src_addr=192.168.20.1 *live non-optimized*
 +- nvme53 tcp traddr=192.168.20.21,trsvcid=4420,host_traddr=192.168.20.1,src_addr=192.168.20.1 *live optimized*
----
=====
.Afficher un exemple de sortie ASA r2
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys4 - NQN=nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:subsystem.Bidirectional_DHCP_1_0
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0054-5110-8039-c3c04f523034
\                                                                                                                                                                               +- nvme4 *tcp* traddr=192.168.20.28,trsvcid=4420,host_traddr=192.168.20.21,src_addr=192.168.20.21 *live optimized*
+- nvme5 *tcp* traddr=192.168.20.29,trsvcid=4420,host_traddr=192.168.20.21,src_addr=192.168.20.21 *live optimized*
+- nvme6 *tcp* traddr=192.168.21.28,trsvcid=4420,host_traddr=192.168.21.21,src_addr=192.168.21.21 *live optimized*
+- nvme7 *tcp* traddr=192.168.21.29,trsvcid=4420,host_traddr=192.168.21.21,src_addr=192.168.21.21 *live optimized*
----
=====
--
====
. Vérifier que le plug-in NetApp affiche les valeurs correctes pour chaque périphérique d'espace de noms ONTAP :
+
[role="tabbed-block"]
====
.Colonne
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.Montrer l'exemple
[%collapsible]
=====
[listing, subs="+quotes"]
----
Device          Vserver         Subsystem   Namespace Path      NSID
------------    --------        ----------- -----------------   ----
/dev/nvme0n1    vs_iscsi_tcp    Nvme1       /vol/Nvmevol1/ns1   1
UUID                                    Size
-------------------------------------   -----
d8efef7d-4dde-447f-b50e-b2c009298c66    26.84GB

----
=====
--
.JSON
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.Montrer l'exemple
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
  "ONTAPdevices":[
    {
      "Device":"/dev/nvme0n1",
      "Vserver":"vs_iscsi_tcp",
      " Subsystem":"Nvme1",
      "Namespace_Path":"/vol/Nvmevol1/ns1",
      "NSID":1,
      "UUID":"d8efef7d-4dde-447f-b50e-b2c009298c66",
      "LBA_Size":4096,
      "UsedBytes":832835584,
      "Namespace_Size":26843545600,
      "Version":"9.18.1"
    },
]
}
----
=====
--
====




[[step-8-set-up-secure-in-band-authentication]]
== Étape 8 : Configurer une authentification sécurisée en bande

L'authentification sécurisée en bande est prise en charge via NVMe/TCP entre un hôte RHEL 9.x et un contrôleur ONTAP .

Chaque hôte ou contrôleur doit être associé à un  `DH-HMAC-CHAP` clé pour configurer l'authentification sécurisée. A  `DH-HMAC-CHAP` la clé est une combinaison du NQN de l'hôte ou du contrôleur NVMe et d'un secret d'authentification configuré par l'administrateur. Pour authentifier son homologue, un hôte ou un contrôleur NVMe doit reconnaître la clé associée à cet homologue.

.Étapes
Configurez une authentification intrabande sécurisée à l’aide de l’interface de ligne de commande ou d’un fichier de configuration JSON. Si vous devez spécifier différentes clés dhchap pour différents sous-systèmes, vous devez utiliser un fichier JSON de configuration.

[role="tabbed-block"]
====
.CLI
--
Configurez l'authentification intrabande sécurisée à l'aide de l'interface de ligne de commande.

. Obtenir le NQN hôte :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
. Générez la clé dhchap pour l'hôte RHEL 9.x.
+
La sortie suivante décrit le `gen-dhchap-key` paramètres de commande :

+
[listing]
----
nvme gen-dhchap-key -s optional_secret -l key_length {32|48|64} -m HMAC_function {0|1|2|3} -n host_nqn
•	-s secret key in hexadecimal characters to be used to initialize the host key
•	-l length of the resulting key in bytes
•	-m HMAC function to use for key transformation
0 = none, 1- SHA-256, 2 = SHA-384, 3=SHA-512
•	-n host NQN to use for key transformation
----
+
Dans l'exemple suivant, une clé dhchap aléatoire avec HMAC définie sur 3 (SHA-512) est générée.

+
[listing]
----
nvme gen-dhchap-key -m 3 -n nqn.2014-
08.org.nvmexpress:uuid:e6daxxxx-216d-xxxx-b7bb-7edxxxx482c3
DHHC-1:03:wSpuuKbBHTzC0W9JZxMBsYd9JFV8Si9aDh22k2BR/4m852vH7KGlrJeMpzhmyjDWOo0PJJM6yZsTeEpGkDHMHQ255+g=:
----
. Sur le contrôleur ONTAP, ajoutez l'hôte et spécifiez les deux clés dhchap :
+
[source, cli]
----
vserver nvme subsystem host add -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn> -dhchap-host-secret <authentication_host_secret> -dhchap-controller-secret <authentication_controller_secret> -dhchap-hash-function {sha-256|sha-512} -dhchap-group {none|2048-bit|3072-bit|4096-bit|6144-bit|8192-bit}
----
. Un hôte prend en charge deux types de méthodes d'authentification, unidirectionnelles et bidirectionnelles. Sur l'hôte, connectez-vous au contrôleur ONTAP et spécifiez des clés dhchap en fonction de la méthode d'authentification choisie :
+
[source, cli]
----
nvme connect -t tcp -w <host-traddr> -a <tr-addr> -n <host_nqn> -S <authentication_host_secret> -C <authentication_controller_secret>
----
. Valider le `nvme connect authentication` en vérifiant les clés dhchap de l'hôte et du contrôleur :
+
.. Vérifiez les clés dhchap hôte :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_secret
----
+
.Affiche un exemple de sortie pour une configuration unidirectionnelle
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys1/nvme*/dhchap_secret
DHHC-1:01:hhdIYK7rGxHiNYS4d421GxHeDRUAuY0vmdqCp/NOaYND2PSc:
DHHC-1:01:hhdIYK7rGxHiNYS4d421GxHeDRUAuY0vmdqCp/NOaYND2PSc:
DHHC-1:01:hhdIYK7rGxHiNYS4d421GxHeDRUAuY0vmdqCp/NOaYND2PSc:
DHHC-1:01:hhdIYK7rGxHiNYS4d421GxHeDRUAuY0vmdqCp/NOaYND2PSc:
----
=====
.. Vérifiez les clés dhchap du contrôleur :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_ctrl_secret
----
+
.Affiche un exemple de sortie pour une configuration bidirectionnelle
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme-
subsys*/nvme*/dhchap_ctrl_secret

DHHC-1:03:ZCRrP9MQOeXhFitT7Fvvf/3P6K/qY1HfSmSfM8nLjESJdOjbjK/J6m00ygJgjm0VrRlrgrnHzjtWJmsnoVBO3rPDGEk=:
DHHC-1:03:ZCRrP9MQOeXhFitT7Fvvf/3P6K/qY1HfSmSfM8nLjESJdOjbjK/J6m00ygJgjm0VrRlrgrnHzjtWJmsnoVBO3rPDGEk=:
DHHC-1:03:ZCRrP9MQOeXhFitT7Fvvf/3P6K/qY1HfSmSfM8nLjESJdOjbjK/J6m00ygJgjm0VrRlrgrnHzjtWJmsnoVBO3rPDGEk=:
DHHC-1:03:ZCRrP9MQOeXhFitT7Fvvf/3P6K/qY1HfSmSfM8nLjESJdOjbjK/J6m00ygJgjm0VrRlrgrnHzjtWJmsnoVBO3rPDGEk=:
----
=====




--
.JSON
--
Lorsque plusieurs sous-systèmes NVMe sont disponibles sur le contrôleur ONTAP , vous pouvez utiliser le `/etc/nvme/config.json` fichier avec le `nvme connect-all` commande.

Utilisez le `-o` option pour générer le fichier JSON.  Reportez-vous aux pages de manuel NVMe connect-all pour plus d'options de syntaxe.

. Configurer le fichier JSON.
+

NOTE: Dans l'exemple suivant,  `dhchap_key` correspond à  `dhchap_secret` et  `dhchap_ctrl_key` correspond à  `dhchap_ctrl_secret` .

+
.Montrer l'exemple
[%collapsible]
=====
[listing]
----
cat /etc/nvme/config.json
[
{
  "hostnqn":"nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0035-xxxx-804b-b5cxxxx44d33",
  "hostid":"4c4cxxxx-0035-xxxx-804b-b5cxxxx44d33",
  "dhchap_key":"DHHC-1:01:GhgaLS+0h0W/IxKhSa0iaMHg17SOHRTzBduPzoJ6LKEJs3/f:",
  "subsystems":[
        {
          "nqn":"nqn.1992-08.com.netapp:sn.2c0c80d9873a11f0bc60d039eab6cb6d:subsystem.istpMNTC_subsys",
          "ports":[
              {
                  "transport":"tcp",
                    "traddr":"192.168.30.44",
                  "host_traddr":"192.168.30.15",
                  "trsvcid":"4420",
                  "dhchap_ctrl_key":"DHHC-1:03:GaraCO84o/uM0jF4rKJlgTy22bVoV0dRn1M+9QDfQRNVwJDHfPu2LrK5Y+/XG8iGcRtBCdm3
fYm3ZmO6NiepCORoY5Q=:"
              },
              {
                  "transport":"tcp",
                  "traddr":"192.168.30.45"
                  "host_traddr":"192.168.30.15",
                  "trsvcid":"4420",
                  "dhchap_ctrl_key":"DHHC-1:03:GaraCO84o/uM0jF4rKJlgTy22bVoV0dRn1M+9QDfQRNVwJDHfPu2LrK5Y+/XG8iGcRtBCdm3
fYm3ZmO6NiepCORoY5Q=:"
              },
              {
                  "transport":"tcp",
                 "traddr":"192.168.31.44",
                  "host_traddr":"192.168.31.15",
                  "trsvcid":"4420",
                  "dhchap_ctrl_key":"DHHC-
                  1:03:
GaraCO84o/uM0jF4rKJlgTy22bVoV0dRn1M+9QDfQRNVwJDHfPu2LrK5Y+/XG8iGc
RtBCdm3fYm3ZmO6NiepCORoY5Q=:"                               },
 {
                  "transport":"tcp",
                  "traddr":"192.168.31.45",
                  "host_traddr":"192.168.31.15",
                  "trsvcid":"4420",
                  "dhchap_ctrl_key":"DHHC-
                  1:03:                                    GaraCO84o/uM0jF4rKJlgTy22bVoV0dRn1M+9QDfQRNVwJDHfPu2LrK5Y+/XG8iGcRtBCdm3fYm3ZmO6NiepCORoY5Q=:"
              }
        ]
  ]
}
]
----
=====
. Connectez-vous au contrôleur ONTAP à l'aide du fichier JSON de configuration :
+
[source, cli]
----
nvme connect-all -J /etc/nvme/config.json
----
+
.Montrer l'exemple
[%collapsible]
=====
[listing]
----
already connected to hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0035-xxxx-804b-b5cxxxx44d33,nqn=nqn.1992-08.com.netapp:sn.2c0c80d9873a11f0bc60d039eab6cb6d:subsystem.istpMNTC_subsys,transport=tcp,traddr=192.168.30.44,trsvcid=4420
already connected to hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0035-xxxx-804b-b5cxxxx44d33,nqn=nqn.1992-08.com.netapp:sn.2c0c80d9873a11f0bc60d039eab6cb6d:subsystem.istpMNTC_subsys,transport=tcp,traddr=192.168.31.44,trsvcid=4420
already connected to hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0035-xxxx-804b-b5cxxxx44d33,nqn=nqn.1992-08.com.netapp:sn.2c0c80d9873a11f0bc60d039eab6cb6d:subsystem.istpMNTC_subsys,transport=tcp,traddr=192.168.30.45,trsvcid=4420
already connected to hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4cxxxx-0035-xxxx-804b-b5cxxxx44d33,nqn=nqn.1992-08.com.netapp:sn.2c0c80d9873a11f0bc60d039eab6cb6d:subsystem.istpMNTC_subsys,transport=tcp,traddr=192.168.31.45,trsvcid=4420
----
=====
. Vérifiez que les secrets dhchap ont été activés pour les contrôleurs respectifs de chaque sous-système :
+
.. Vérifiez les clés dhchap hôte :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys96/nvme96/dhchap_secret
----
+
L'exemple suivant montre une clé dhchap :

+
[listing]
----
DHHC-1:01:hhdIYK7rGxHiNYS4d421GxHeDRUAuY0vmdqCp/NOaYND2PSc:
----
.. Vérifiez les clés dhchap du contrôleur :
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys96/nvme96/dhchap_ctrl_secret
----
+
Vous devriez voir une sortie similaire à l’exemple suivant :

+
[listing]
----
DHHC-1:03:ZCRrP9MQOeXhFitT7Fvvf/3P6K/qY1HfSmSfM8nLjESJdOjbjK/J6m00ygJgjm0VrRlrgrnHzjtWJmsnoVBO3rPDGEk=:
----




--
====


[[step-9-review-the-known-issues]]
== Étape 9 : passez en revue les problèmes connus

Il n'y a pas de problème connu.
