---
sidebar: sidebar 
permalink: nvme_rhel_89.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: 'Comment configurer l"hôte NVMe-of pour RHEL 8.9 avec ONTAP' 
---
= Configuration hôte NVMe-of pour RHEL 8.9 avec ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NVMe over Fabrics (NVMe-of), y compris NVMe over Fibre Channel (NVMe/FC) et d'autres moyens de transport, est pris en charge par Red Hat Enterprise Linux (RHEL) 8.9 avec ANA (Asymmetric Namespace Access). Dans les environnements NVMe-of, ANA est l'équivalent des chemins d'accès multiples ALUA dans les environnements iSCSI et FC. Il est implémenté avec les chemins d'accès multiples NVMe intégrés au noyau.

La prise en charge suivante est disponible pour la configuration hôte NVMe-of pour RHEL 8.9 avec ONTAP :

* Prise en charge de NVMe over TCP (NVMe/TCP) en plus de NVMe/FC. Le plug-in NetApp du package nvme-cli natif affiche les détails des ONTAP pour les namespaces NVMe/FC et NVMe/TCP.


Pour plus d'informations sur les configurations prises en charge, reportez-vous au link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^].



== Limites connues

* Les chemins d'accès multiples NVMe dans le noyau sont désactivés par défaut pour les hôtes RHEL 8.9 NVMe-of. Par conséquent, vous devez l'activer manuellement.
* Sur les hôtes RHEL 8.9, NVMe/TCP est une fonctionnalité de prévisualisation technologique en raison de problèmes ouverts.
* Le démarrage SAN à l'aide du protocole NVMe-of n'est pas pris en charge pour le moment.




== Activer le multipathing in-kernel

Vous pouvez utiliser la procédure suivante pour activer les chemins d'accès multiples dans le noyau.

.Étapes
. Installez RHEL 8.9 sur le serveur hôte.
. Une fois l'installation terminée, vérifiez que vous exécutez le noyau RHEL 8.9 spécifié :
+
[listing]
----
# uname -r
----
+
*Exemple de sortie*

+
[listing]
----
4.18.0-513.5.1.el8_9.x86_64
----
. Installez le package nvme-cli :
+
[listing]
----
rpm -qa|grep nvme-cli
----
+
*Exemple de sortie*

+
[listing]
----
nvme-cli-1.16-9.el8.x86_64
----
. Activer les chemins d'accès multiples NVMe dans -kernel :
+
[listing]
----
# grubby --args=nvme_core.multipath=Y --update-kernel /boot/vmlinuz-4.18.0-513.5.1.el8_9.x86_64
----
. Sur l'hôte, vérifiez la chaîne NQN hôte à `/etc/nvme/hostnqn`:
+
[listing]
----
# cat /etc/nvme/hostnqn
----
+
*Exemple de sortie*

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0032-3410-8035-b8c04f4c5132
----
. Vérifiez que le `hostnqn` la chaîne correspond au `hostnqn` Chaîne du sous-système correspondant sur la baie ONTAP :
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_fcnvme_141
----
+
*Exemple de sortie*

+
[listing]
----
Vserver     Subsystem       Host NQN
----------- --------------- ----------------------------------------------------------
vs_nvme101 rhel_101_QLe2772    nqn.2014-08.org.nvmexpress: uuid:4c4c4544-0032-3410-8035-b8c04f4c5132
----
+

NOTE: Si les chaînes NQN hôte ne correspondent pas, vous pouvez utiliser le `vserver modify` Commande pour mettre à jour la chaîne NQN hôte sur le sous-système NVMe ONTAP correspondant afin qu'elle corresponde à la chaîne NQN hôte `/etc/nvme/hostnqn` sur l'hôte.

. Redémarrez l'hôte.


[NOTE]
====
Si vous avez l'intention d'exécuter à la fois le trafic existant NVMe et SCSI sur le même hôte, NetApp vous recommande d'utiliser respectivement le chemin d'accès multiples NVMe intégré au noyau pour les namespaces ONTAP et le chemin d'accès multiples dm-multipath pour les LUN ONTAP. Cela doit exclure les espaces de noms ONTAP de dm-multipath et empêcher dm-multipath de réclamer ces périphériques d'espace de noms. Pour ce faire, ajoutez la `enable_foreign` réglage sur `/etc/multipath.conf` fichier :

[listing]
----
# cat /etc/multipath.conf
defaults {
  enable_foreign  NONE
}
----
====


== Configurez NVMe/FC

Vous pouvez configurer NVMe/FC pour les cartes Broadcom/Emulex ou Marvell/Qlogic.

[role="tabbed-block"]
====
.Broadcom/Emulex
--
.Étapes
. Vérifiez que vous utilisez le modèle d'adaptateur pris en charge :
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
----
+
*Exemple de sortie :*

+
[listing]
----
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
----
+
*Exemple de sortie :*

+
[listing]
----
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. Vérifiez que vous utilisez la carte Broadcom recommandée `lpfc` micrologiciel et pilote de boîte de réception :
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
14.2.539.16, sli-4:2:c
14.2.539.16, sli-4:2:c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:14.0.0.21
----
+
Pour obtenir la liste la plus récente des versions de pilote de carte et de micrologiciel prises en charge, reportez-vous à la section link:https://mysupport.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^].

. Vérifiez-le `lpfc_enable_fc4_type` est défini sur `3`:
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Vérifier que les ports initiateurs sont opérationnels et que les LIFs cibles sont visibles :
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x10000090fae0ec88
0x10000090fae0ec89
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
[listing, subs="+quotes"]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec88 WWNN x20000090fae0ec88 DID x0a1300 *ONLINE*
NVME RPORT       WWPN x2049d039ea36a105 WWNN x2048d039ea36a105 DID x0a0c0a *TARGET DISCSRVC ONLINE*
NVME Statistics
LS: Xmt 0000000024 Cmpl 0000000024 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 00000000000001aa Issue 00000000000001ab OutIO 0000000000000001
        abort 00000002 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000002 Err 00000003
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x10000090fae0ec89 WWNN x20000090fae0ec89 DID x0a1200 *ONLINE*
NVME RPORT       WWPN x204ad039ea36a105 WWNN x2048d039ea36a105 DID x0a080a *TARGET DISCSRVC ONLINE*
NVME Statistics
LS: Xmt 0000000024 Cmpl 0000000024 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 00000000000001ac Issue 00000000000001ad OutIO 0000000000000001
        abort 00000002 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000002 Err 00000003



----


--
.Adaptateur FC Marvell/QLogic pour NVMe/FC
--
Le pilote natif qla2xxx inclus dans le noyau RHEL 8.9 GA possède les derniers correctifs en amont. Ces correctifs sont essentiels à la prise en charge de ONTAP.

.Étapes
. Vérifiez que vous exécutez les versions du pilote de carte et du micrologiciel prises en charge :
+
[listing]
----
# cat /sys/class/fc_host/host*/symbolic_name
----
+
*Exemple de sortie*

+
[listing]
----
QLE2742 FW: v9.10.11 DVR: v10.02.08.200-k
QLE2742 FW: v9.10.11 DVR: v10.02.08.200-k
----
. Vérifiez-le `ql2xnvmeenable` est défini. L'adaptateur Marvell peut ainsi fonctionner en tant qu'initiateur NVMe/FC :
+
[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----


--
====


=== Activer les E/S de 1 Mo (en option)

ONTAP signale une taille de transfert MAX Data (MDT) de 8 dans les données Identify Controller. La taille maximale des demandes d'E/S peut donc atteindre 1 Mo. Pour émettre des demandes d'E/S d'une taille de 1 Mo pour un hôte Broadcom NVMe/FC, vous devez augmenter la `lpfc` valeur du `lpfc_sg_seg_cnt` paramètre à 256 par rapport à la valeur par défaut 64.


NOTE: Les étapes suivantes ne s'appliquent pas aux hôtes NVMe/FC Qlogic.

.Étapes
. Réglez le `lpfc_sg_seg_cnt` paramètre sur 256 :
+
[listing]
----
cat /etc/modprobe.d/lpfc.conf
----
+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Lancer `dracut -f` la commande et redémarrer l'hôte :
. Vérifiez que `lpfc_sg_seg_cnt` est 256 :
+
[listing]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----
+
La valeur attendue est 256.





== Configurez NVMe/TCP

NVMe/TCP ne dispose pas de la fonctionnalité de connexion automatique. Par conséquent, si un chemin tombe en panne et n'est pas rétabli dans le délai par défaut de 10 minutes, NVMe/TCP ne peut pas se reconnecter automatiquement. Pour éviter une temporisation, vous devez définir la période de nouvelle tentative pour les événements de basculement sur incident à au moins 30 minutes.

.Étapes
. Vérifiez que le port initiateur peut récupérer les données de la page de journal de découverte sur les LIF NVMe/TCP prises en charge :
+
[listing]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
*Exemple de sortie :*

+
[listing]
----
# nvme discover -t tcp -w 192.168.111.79 -a 192.168.111.14 -l 1800

Discovery Log Number of Records 8, Generation counter 18
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified.
portid:  0
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b: discovery
traddr:  192.168.211.15
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified.
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b: discovery
traddr:  192.168.111.15
sectype: none ..........


----
. Vérifier que les autres combinaisons de LIF cible-initiateur NVMe/TCP peuvent récupérer les données de la page du journal de détection :
+
[listing]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
*Exemple de sortie :*

+
[listing]
----
# nvme	discover	-t   tcp    -w	192.168.111.79   -a	192.168.111.14
# nvme	discover	-t   tcp    -w	192.168.111.79   -a	192.168.111.15
# nvme	discover	-t   tcp    -w	192.168.211.79   -a	192.168.211.14
# nvme	discover	-t   tcp    -w	192.168.211.79   -a	192.168.211.15


----
. Exécutez le `nvme connect-all` Commande sur toutes les LIFs initiator-target-target NVMe/TCP prises en charge sur les nœuds et définissez le délai de perte du contrôleur pendant au moins 30 minutes ou 1800 secondes :
+
[listing]
----
nvme connect-all -t tcp -w host-traddr -a traddr -l 1800
----
+
*Exemple de sortie :*

+
[listing]
----
# nvme	connect-all	-t	tcp	-w	192.168.111.79	-a	192.168.111.14	-l	1800
# nvme	connect-all	-t	tcp	-w	192.168.111.79	-a	192.168.111.15	-l	1800
# nvme	connect-all	-t	tcp	-w	192.168.211.79	-a	192.168.211.14	-l	1800
# nvme	connect-all	-t	tcp	-w	192.168.211.79	-a	192.168.211.15	-l	1800


----




== Validez la spécification NVMe-of

La procédure suivante permet de valider NVMe-of.

.Étapes
. Vérifiez que le chemin d'accès multiples NVMe intégré au noyau est activé :
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
. Vérifiez que les paramètres NVMe-of appropriés (par exemple, `model` réglez sur `NetApp ONTAP Controller` et équilibrage de la charge `iopolicy` réglez sur `round-robin`) Pour les espaces de noms ONTAP respectifs reflètent correctement sur l'hôte :
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. Vérifiez que les espaces de noms sont créés et correctement découverts sur l'hôte :
+
[listing]
----
# nvme list
----
+
*Exemple de sortie :*

+
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme0n1 81Gx7NSiKSQqAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
. Vérifiez que l'état du contrôleur de chaque chemin est actif et que l'état ANA est correct :
+
[role="tabbed-block"]
====
.NVMe/FC
--
[listing]
----
# nvme list-subsys /dev/nvme3n1
----
*Exemple de sortie :*

[listing, subs="+quotes"]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.8e501f8ebafa11ec9b99d039ea359e4b:subsystem.rhel_163_Qle2742
+- nvme0 *fc* traddr=nn-0x204dd039ea36a105:pn-0x2050d039ea36a105 host_traddr=nn-0x20000024ff7f4994:pn-0x21000024ff7f4994 *live non-optimized*
+- nvme1 *fc* traddr=nn-0x204dd039ea36a105:pn-0x2050d039ea36a105 host_traddr=nn-0x20000024ff7f4994:pn-0x21000024ff7f4994 *live non-optimized*
+- nvme2 *fc* traddr=nn-0x204dd039ea36a105:pn-0x204fd039ea36a105 host_traddr=nn-0x20000024ff7f4995:pn-0x21000024ff7f4995 *live optimized*
+- nvme3 *fc* traddr=nn-0x204dd039ea36a105:pn-0x204ed039ea36a105 host_traddr=nn-0x20000024ff7f4994:pn-0x21000024ff7f4994 *live optimized*

----
--
.NVMe/TCP
--
[listing]
----
# nvme list-subsys /dev/nvme0n1
----
*Exemple de sortie :*

[listing, subs="+quotes"]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:subsystem.rhel_tcp_165\
+- nvme0 *tcp* traddr=192.168.111.15 trsvcid=4420 host_traddr=192.168.111.79 *live non-optimized*
+- nvme1 *tcp* traddr=192.168.111.14 trsvcid=4420 host_traddr=192.168.111.79 *live optimized*
+- nvme2 *tcp* traddr=192.168.211.15 trsvcid=4420 host_traddr=192.168.211.79 *live non-optimized*
+- nvme3 *tcp* traddr=192.168.211.14 trsvcid=4420 host_traddr=192.168.211.79 *live optimized*

----
--
====
. Vérifier que le plug-in NetApp affiche les valeurs correctes pour chaque périphérique d'espace de noms ONTAP :
+
[role="tabbed-block"]
====
.Colonne
--
[listing]
----
# nvme netapp ontapdevices -o column
----
*Exemple de sortie :*

[listing]
----
Device        Vserver   Namespace Path
----------------------- ------------------------------
/dev/nvme0n1 vs_tcp79           /vol/vol1/ns


NSID       UUID                                   Size
------------------------------------------------------------
1          aa197984-3f62-4a80-97de-e89436360cec	21.47GB
----
--
.JSON
--
[listing]
----
# nvme netapp ontapdevices -o json
----
*Exemple de sortie*

[listing]
----
{
  "ONTAPdevices”: [
    {
      "Device”: "/dev/nvme0n1",
      "Vserver”: "vs_tcp79",
      "Namespace Path”: "/vol/vol1/ns",
      "NSID”: 1,
      "UUID”: "aa197984-3f62-4a80-97de-e89436360cec",
      "Size”: "21.47GB",
      "LBA_Data_Size”: 4096,
      "Namespace Size" : 5242880
    },
]

}


----
--
====




== Problèmes connus

La configuration hôte NVMe-of pour RHEL 8.9 avec ONTAP version présente le problème connu suivant :

[cols="20,40,40"]
|===
| ID de bug NetApp | Titre | Description 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1479047["1479047"^] | Les hôtes RHEL 8.9 NVMe-of créent des contrôleurs de détection persistants dupliqués | Sur les hôtes NVMe over Fabrics (NVMe-of), vous pouvez utiliser la commande nvme Discover -p pour créer des contrôleurs de découverte persistants (CDP). Lorsque cette commande est utilisée, un seul PDC doit être créé par combinaison initiateur-cible.  Toutefois, si vous exécutez Red Hat Enterprise Linux (RHEL) 8.9 sur un hôte NVMe-of, un PDC dupliqué est créé chaque fois que « nvme Discover -p » est exécuté. Cela entraîne une utilisation inutile des ressources sur l'hôte et la cible. 
|===