---
sidebar: sidebar 
permalink: overview.html 
keywords: ontap, san, host, rhel, red, hat, linux, sles, suse, esxi, nvme, oracle, linux, windows, enterprise, fc, fcp, isci, aix, powervm, vios, centos, citrix, hp-ux, solaris, veritas, cvo, cloud, volume, ontap, clients, configuration, FSx, instance, netapp 
summary: Ce contenu fournit des recommandations spécifiques à une distribution sur la façon de configurer les clients cloud connectés à Cloud Volumes ONTAP et Amazon FSX pour les hôtes ONTAP et SAN connectés au stockage ONTAP sur site. 
---
= Présentation de la configuration hôte SAN
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


Ce contenu fournit des meilleures pratiques propres à l'hôte et à la version pour configurer rapidement les hôtes SAN connectés au stockage ONTAP.

Vos hôtes SAN et votre stockage ONTAP peuvent résider sur votre site, dans le cloud, ou les deux.


NOTE: Dans un environnement cloud, les hôtes sont généralement appelés clients. Toutes les informations spécifiques à l'hôte de ce contenu s'appliquent également aux clients cloud.

Par exemple, vous pouvez configurer le stockage ONTAP sur site pour la connexion à des hôtes SAN sur site ou pour la connexion à des clients cloud SAN. Vous pouvez également configurer link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] ou link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX pour ONTAP"^] Pour se connecter à des hôtes SAN sur site ou pour se connecter aux clients cloud SAN.

Une configuration correcte est importante pour de meilleures performances et un basculement réussi.

.Informations associées
* Le link:https://docs.netapp.com/us-en/ontap/san-config/index.html["Configuration SAN ONTAP"^] Pour votre version de ONTAP
* Le link:https://docs.netapp.com/us-en/ontap/san-management/index.html["Guide d'administration du SAN ONTAP"^] Pour votre version de ONTAP
* Le link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de version de ONTAP"^] Pour votre version de ONTAP
* Le link:https://docs.netapp.com/us-en/e-series/index.html["Documentation E-Series"^] Pour accéder à la documentation relative à SANtricity.

