= Étape 1 : activez éventuellement le démarrage SAN
:allow-uri-read: 




== Étape 1 : activez éventuellement le démarrage SAN

Vous pouvez configurer votre hôte pour utiliser le démarrage SAN afin de simplifier le déploiement et d’améliorer l’évolutivité.  Si votre configuration ne prend pas en charge le démarrage SAN, vous pouvez utiliser un démarrage local.

[role="tabbed-block"]
====
.Démarrage SAN
--
Le démarrage SAN est le processus de configuration d'un disque connecté au SAN (un LUN) en tant que périphérique de démarrage pour un hôte AIX/PowerVM.  Vous pouvez configurer un LUN de démarrage SAN pour qu'il fonctionne dans un environnement AIX Multipath I/O (MPIO) qui utilise le protocole FC et exécute AIX Host Utilities avec le protocole FC ou FCoE.  La méthode que vous utilisez pour créer un LUN de démarrage SAN et installer une nouvelle image de système d'exploitation dans un environnement AIX MPIO dépend du protocole que vous utilisez.

.Étapes
. Utilisez lelink:https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation AIX, votre protocole et votre version ONTAP prennent en charge le démarrage SAN.
. Suivez les meilleures pratiques pour configurer un démarrage SAN dans la documentation du fournisseur.


--
.Démarrage local
--
Effectuez un démarrage local en installant le système d'exploitation AIX sur le disque dur local, par exemple sur un SSD, SATA ou RAID.

--
====