= 
:allow-uri-read: 


. Si votre configuration de stockage inclut la synchronisation active MetroCluster ou SnapMirror , modifiez les paramètres par défaut :
+
[role="tabbed-block"]
====
.MetroCluster
--
Par défaut, le système d'exploitation AIX applique un délai d'expiration d'E/S plus court lorsqu'il n'y a aucun chemin disponible vers un LUN.  Cela peut se produire dans les configurations qui incluent une structure SAN à commutateur unique et dans les configurations MetroCluster qui subissent des basculements imprévus.  Pour plus d'informations et les modifications recommandées aux paramètres par défaut, consultez l'article de la base de connaissanceslink:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["Quelles sont les considérations relatives à la prise en charge de l’hôte AIX dans une configuration MetroCluster ?"^] .

--
.Synchronisation active de SnapMirror
--
SnapMirror active sync est prise en charge pour un hôte AIX. Le comportement de prise en charge diffère selon la version d'ONTAP :

** À partir de ONTAP 9.19.1, la synchronisation active SnapMirror est prise en charge dans la configuration Active/Active, permettant des opérations de synchronisation active SnapMirror non perturbatrices. Consultez l’article de la base de connaissances link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/SnapMirror_active_sync_support_for_AIX%3A_behavior_by_ONTAP_release_and_migration_guidance["SnapMirror active sync prise en charge pour AIX : comportement selon la version d'ONTAP et guide de migration"^].
** Pour ONTAP 9.11.1 à 9.18.1, la synchronisation active SnapMirror est prise en charge en configuration actif/passif. Consultez l'article de la base de connaissances link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["Comment configurer un hôte AIX pour la synchronisation active SnapMirror dans ONTAP 9.11.1 à 9.18.1"^].


--
====

