= 
:allow-uri-read: 


.Étapes
Selon votre configuration, sélectionnez l'onglet UEK 3 ou UEK 4.

[role="tabbed-block"]
====
.UEK 3
--
Les paramètres d'Oracle Linux UEK 3 avec et sans ALUA se mettent à jour automatiquement. Après la mise à jour, vous devez activer le gestionnaire ALUA :

. Créez une sauvegarde de l'image initrd.
. Ajoutez la valeur de paramètre suivante au noyau pour ALUA et non-ALUA à fonctionner :
+
[source, cli]
----
rdloaddriver=scsi_dh_alua
----
+
.Exemple de sortie
[listing]
----
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
----
. Recréer l'image initrd :
+
[source, cli]
----
dracut -f
----
. Redémarrez l'hôte.
. Examiner la sortie de la  `cat /proc/cmdline` commande pour vérifier que le réglage est terminé.


--
.UEK 4
--
Pour Oracle Linux UEK 4, vérifiez que le  `/etc/multipath.conf` le fichier est défini et que les paramètres recommandés par NetApp sont configurés pour vos LUN ONTAP.

. Vérifiez que le `/etc/multipath.conf` fichier se ferme. Si le fichier n'existe pas, créez un fichier vide à zéro octet :
+
[source, cli]
----
touch /etc/multipath.conf
----
. Lors de la première `multipath.conf` création du fichier, vous devrez peut-être activer et démarrer les services multivoies pour charger les paramètres recommandés :
+
[source, cli]
----
chkconfig multipathd on
----
+
[source, cli]
----
/etc/init.d/multipathd start
----
. Chaque fois que vous démarrez l'hôte, le fichier vide `/etc/multipath.conf` à zéro octet charge automatiquement les paramètres de chemins d'accès multiples recommandés par NetApp comme paramètres par défaut. Vous ne devriez pas avoir besoin d'apporter de modifications au `/etc/multipath.conf` fichier de votre hôte car le système d'exploitation est compilé avec les paramètres multivoies qui reconnaissent et gèrent correctement les LUN ONTAP.
+
.Affiche les paramètres
[%collapsible]
=====
[cols="2"]
|===
| Paramètre | Réglage 


| détecter_prio | oui 


| dev_loss_tmo | « infini » 


| du rétablissement | immédiate 


| fast_io_fail_tmo | 5 


| caractéristiques | « 2 pg_init_retries 50 » 


| flush_on_last_del | « oui » 


| gestionnaire_matériel | « 0 » 


| no_path_réessayer | file d'attente 


| path_checker | « tur » 


| path_groupage_policy | « group_by_prio » 


| sélecteur de chemin | « temps-service 0 » 


| intervalle_interrogation | 5 


| prio | « ONTAP » 


| solution netapp | LUN 


| conservez_attaed_hw_handler | oui 


| rr_weight | « uniforme » 


| noms_conviviaux_conviviaux | non 


| fournisseur | NETAPP 
|===
=====
. Vérifiez les paramètres et l'état du chemin de vos LUN ONTAP :
+
[source, cli]
----
multipath -ll
----
+
Les paramètres multi-trajets par défaut prennent en charge les configurations AFF et FAS. Dans ces configurations, une seule LUN ONTAP ne doit pas nécessiter plus de quatre chemins. S'il y a plus de quatre chemins, cela peut causer des problèmes avec les chemins en cas de panne de stockage.

+
Une configuration AFF ou FAS doit comporter deux groupes de chemins ayant des priorités plus élevées et moins élevées. Les chemins actifs/optimisés à priorité supérieure sont servis par le contrôleur où se trouve l'agrégat. Les chemins de priorité inférieure sont actifs mais non optimisés, car ils sont gérés par un autre contrôleur. Les chemins non optimisés ne sont utilisés que lorsque des chemins optimisés ne sont pas disponibles.

+
Les exemples de sortie suivants montrent les paramètres corrects et l'état du chemin pour les LUN ONTAP dans une configuration AFF ou FAS avec deux chemins actifs/optimisés et deux chemins actifs/non optimisés :

+
.Montrer l'exemple
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
=====


--
====