= 
:allow-uri-read: 


Assurez-vous que iSCSI est correctement configuré pour votre hôte.

.Description de la tâche
Vous effectuez les étapes suivantes sur l'hôte iSCSI.

.Étapes
. Vérifiez que le package initiateur iSCSI (open-iscsi) est installé :
+
[source, cli]
----
$apt list |grep open-iscsi
----
+
Vous devriez voir une sortie similaire à l’exemple suivant :

+
[listing]
----
open-iscsi/stable,now 2.1.11-1+deb13u1 amd64
----
. Vérifiez le nom du nœud initiateur iSCSI, qui se trouve dans le fichier  `/etc/iscsi/initiatorname.iscsi` :
+
[source, cli]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Configurez le paramètre de délai d'expiration de la session iSCSI situé dans le fichier  `/etc/iscsi/iscsid.conf` :
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
Le paramètre iSCSI `replacement_timeout` contrôle la durée pendant laquelle la couche iSCSI doit attendre qu’un chemin ou une session ayant expiré se rétablisse avant d’échouer toute commande qui lui est adressée. Vous devez définir la valeur de `replacement_timeout` sur 5 dans le fichier de configuration iSCSI.

. Activez le service iSCSI :
+
[source, cli]
----
$systemctl enable iscsid
----
. Démarrez le service iSCSI :
+
[source, cli]
----
$systemctl start iscsid
----
. Vérifiez que le service iSCSI est en cours d'exécution :
+
[source, cli]
----
$systemctl status iscsid
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
● iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; disabled; preset: enabled)
     Active: active (running) since Fri 2026-02-20 22:14:34 IST; 2 days ago
 Invocation: 37a44a6ebd3a4e3898dcc6c408b85bec
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
    Process: 4985 ExecStartPre=/usr/lib/open-iscsi/startup-checks.sh (code=exited, status=0/SUCCESS)
    Process: 4988 ExecStart=/usr/sbin/iscsid (code=exited, status=0/SUCCESS)
   Main PID: 4991 (iscsid)
      Tasks: 2 (limit: 151112)
     Memory: 12.5M (peak: 15.5M)
        CPU: 2.438s
     CGroup: /system.slice/iscsid.service
             ├─4990 /usr/sbin/iscsid
             └─4991 /usr/sbin/iscsid

----
====
. Découvrez les cibles iSCSI :
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.afficher exemple
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal
192.168.166.70
192.168.166.70:3260,1042 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.165.71:3260,1045 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.165.70:3260,1044 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.166.71:3260,1043 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
----
====
. Connectez-vous aux cibles :
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Configurer iSCSI pour qu'il se connecte automatiquement au démarrage de l'hôte :
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Remplacez  `<target_name>` par le nom de la cible à laquelle vous souhaitez vous connecter automatiquement au démarrage de l’hôte. Remplacez  `<ip:port>` par l’adresse IP et le numéro de port de la cible. Par exemple :

+
[source, cli]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 -p 192.168.166.70:3260 -o update -n node.startup -v automatic
----
. Vérifiez les sessions iSCSI :
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.166.71:3260,1043 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [2] 192.168.165.71:3260,1045 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [3] 192.168.165.70:3260,1044 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [4] 192.168.166.70:3260,1042 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
----
====

