= 
:allow-uri-read: 


Assurez-vous que iSCSI est correctement configuré pour votre hôte.

.Description de la tâche
Vous effectuez les étapes suivantes sur l'hôte iSCSI.

.Étapes
. Vérifiez que le package initiateur iSCSI (open-iscsi) est installé :
+
[source, cli]
----
$apt list |grep open-iscsi
----
+
Vous devriez voir une sortie similaire à l’exemple suivant :

+
[listing]
----
open-iscsi/noble-updates,noble-updates,now 2.1.9-3ubuntu5.4 amd64
----
. Vérifiez le nom du nœud initiateur iSCSI, qui se trouve dans le fichier  `/etc/iscsi/initiatorname.iscsi` :
+
[source, cli]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Configurez le paramètre de délai d'expiration de la session iSCSI situé dans le fichier  `/etc/iscsi/iscsid.conf` :
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
Le paramètre iSCSI `replacement_timeout` contrôle la durée pendant laquelle la couche iSCSI doit attendre qu’un chemin ou une session ayant expiré se rétablisse avant d’échouer toute commande qui lui est adressée. Vous devez définir la valeur de `replacement_timeout` sur 5 dans le fichier de configuration iSCSI.

. Activez le service iSCSI :
+
[source, cli]
----
$systemctl enable iscsid
----
. Démarrez le service iSCSI :
+
[source, cli]
----
$systemctl start iscsid
----
. Vérifiez que le service iSCSI est en cours d'exécution :
+
[source, cli]
----
$systemctl status iscsid
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
●iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; enabled; preset: disabled)
     Active: active (running) since Mon 2026-01-12 12:53:18 IST; 2 days ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
   Main PID: 1127419 (iscsid)
      Tasks: 2 (limit: 76557)
     Memory: 4.3M (peak: 8.8M)
        CPU: 1.657s
     CGroup: /system.slice/iscsid.service
             ├─1127418 /usr/sbin/iscsid
             └─1127419 /usr/sbin/iscsid
----
====
. Découvrez les cibles iSCSI :
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.afficher exemple
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal  192.168.100.197
192.168.100.197:3260,1046 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
192.168.200.199:3260,1049 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
192.168.100.199:3260,1048 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
192.168.200.197:3260,1047 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
----
====
. Connectez-vous aux cibles :
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Configurer iSCSI pour qu'il se connecte automatiquement au démarrage de l'hôte :
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Vous devriez voir une sortie similaire à l’exemple suivant :

+
[listing]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 -p 192.168.100.197:3260 -o update -n node.startup -v automatic
----
. Vérifiez les sessions iSCSI :
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Montrer l'exemple
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.200.197:3260,1047 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
tcp: [2] 192.168.100.197:3260,1046 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
tcp: [3] 192.168.100.199:3260,1048 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
tcp: [4] 192.168.200.199:3260,1049 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
----
====

