= Étape 1 : activez éventuellement le démarrage SAN
:allow-uri-read: 




== Étape 1 : activez éventuellement le démarrage SAN

Vous pouvez démarrer le système d'exploitation Windows en utilisant un démarrage local ou un démarrage SAN.  NetApp recommande l'utilisation d'un démarrage SAN pour simplifier le déploiement et améliorer l'évolutivité.

[role="tabbed-block"]
====
.Démarrage SAN
--
Si vous choisissez d'utiliser le démarrage SAN, il doit être pris en charge par votre configuration.

.Avant de commencer
Utilisez le https://mysupport.netapp.com/matrix/#welcome["Matrice d'interopérabilité"^] pour vérifier que votre système d'exploitation Windows, votre adaptateur de bus hôte (HBA), le micrologiciel HBA, le BIOS de démarrage HBA et la version ONTAP prennent en charge le démarrage SAN.

.Étapes
. link:https://docs.netapp.com/us-en/ontap/san-management/index.html["Créez un LUN de démarrage SAN et mappez-le à l'hôte"^].
. Activez le démarrage SAN dans le BIOS du serveur pour les ports auxquels la LUN de démarrage SAN est mappée.
+
Pour plus d'informations sur l'activation du BIOS HBA, reportez-vous à la documentation spécifique au fournisseur.

. Vérifiez que la configuration a réussi en redémarrant l'hôte et en vérifiant que le système d'exploitation est opérationnel.


--
.Démarrage local
--
Effectuez un démarrage local en installant le système d'exploitation Windows sur le disque dur local, par exemple sur un SSD, un disque SATA ou un RAID.

--
====